package compatibilities

var Aquariuspisces = Compatibility{
	Name: Aquarius + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "40%",
		Traits:  []string{Stormy},
		Summary: "Cuando Acuario y Piscis coinciden en el terreno de la amistad, comprobarán que son más parecidos de lo que pensaban y que pueden ser buenos amigos.\n \nAcuario posee una mentalidad abierta que le permite socializar con facilidad.\n \nTienen también una escala de valores que comparten y cualidades complementarias.\n \nAcuario es muy ingenioso y Piscis se prestará de mil amores a secundarle para desarrollar sus ideas.\n \nEn el ámbito amistoso, Acuario y Piscis sabrán respetar los tiempos y los papeles de cada uno y no perderán su tiempo ni su energía en determinar quién va a llevar la voz cantante en sus iniciativas.\n \nLa relación entre Acuario y Piscis se estrechará con el paso del tiempo.\n \nSus similitudes en este terreno son abundantes y por eso tienen tanta empatía entre ellos, algo que sin duda les haría falta también en otros ámbitos.\n \nAmbos necesitan también mucho espacio individual, Acuario para atender a sus incontables amigos y Piscis para hacer su habitual introspección personal en soledad.\n \nEsto no supondrá nunca un problema, ambos lo aceptarán y será un punto más que les una.\n \nEl deseo de Piscis de querer siempre hacer la vida más fácil a los demás, tendrá en Acuario terreno abonado.\n \nPodrá beneficiarle mucho.",
	},
	Love: Love{
		Match:  "38%",
		Traits: []string{NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "Como todos los signos vecinos, Acuario y Piscis no tienen necesariamente la mejor comprensión de la personalidad del otro.\n \nSin embargo, el signo de Acuario exalta a Neptuno, el regente de Piscis, y esto les proporciona un fuerte vínculo a través del planeta de toda magia.\n \nNo es fácil crear la versión de cuento de hadas de este contacto, pero una vez que encuentren el equilibrio emocional y la verdad fundamental el uno para el otro, no tendrán ningún problema para mantener vivo su cuento de hadas, día tras día.",
			Match: "38%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "El signo de Acuario exalta a Neptuno, el regente de Piscis.\n \nExiste un fuerte vínculo entre estos dos signos y, en su relación sexual, las cosas nunca serán aburridas.\n \nA primera vista, no se llevan muy bien, ya que uno de ellos es romántico y busca el amor perfecto, mientras que el otro es distante y busca la forma de liberarse de toda emoción.\n \nAun así, su vida sexual puede ser bastante sorprendente si los Piscis no se apegan demasiado y encuentran la forma de mantener las distancias hasta que su pareja muestre emoción.\n \nComo signo mutable, Piscis comprende el cambio constante y el regocijo y la excitación del acto sexual.\n \nAcuario le seguirá felizmente, con un poco menos de entusiasmo porque, al fin y al cabo, son racionales.\n \nLa belleza de su vida sexual podría estar en la creatividad, un juego de emociones y el cuestionamiento eterno que traerá aún más excitación y emoción a toda la relación.\n \nPor desgracia, en muchos casos Piscis sólo quieren que sus emociones fluyan y terminarán la relación, antes que lidiar con constantes decepciones.\n \nLa mejor oportunidad para una vida sexual satisfactoria entre un Acuario y una pareja Piscis es en un escenario en el que Acuario ya tenía algunas emociones para compartir, antes de su relación incluso comenzó.",
			Match: "50%"},
		Trust: SummaryPercentage{
			Text:  "La confianza es la cuestión más importante para esta pareja y puede ir de un extremo a otro.\n \nDependiendo del estado de su intimidad, podrían acabar cubiertos de mentiras o completamente libres de ellas.\n \nLa naturaleza de Acuario puede ser un poco agresiva de vez en cuando y sus necesidades personales de rebeldía no ayudan realmente a Piscis a sentirse lo suficientemente seguro como para compartir pensamientos íntimos.\n \nLa potencial dependencia emocional de Piscis puede hacer que la pareja de Acuario ceda a sus perfectas habilidades para mentir con el fin de sentirse más libre.\n \nLa única manera en que pueden construir una confianza incondicional es utilizar su capacidad para sentir el verdadero núcleo del otro.\n \nSi Piscis entiende el lado suave de Acuario, el que se encuentra muy por debajo de la superficie, no huirá de decir la verdad.\n \nCuando se encuentre la intimidad, Acuario podrá por fin dejar de huir del compromiso y el problema de la falta de libertad se resolverá automáticamente.",
			Match: "50%"},
		Communication: SummaryPercentage{
			Text:  "Pueden soñar bien juntos, pero por desgracia difícilmente harán realidad ningún sueño.\n \nLa falta de realidad en su relación podría perjudicarlos a ambos y es posible que ni siquiera sepan dónde se esconde el problema, mientras se sienten frustrados por su relación.\n \nEl signo de Piscis debería ser capaz de aterrizar las ideas de la pareja de Acuario porque su elemento está más cerca de la tierra.\n \nSin embargo, a menudo se pierden en el camino de hacer algo real, especialmente cuando no sienten que esté en el camino de su propia misión.\n \nEl entendimiento entre ellos no siempre es muy profundo y, aunque pueden divertirse mucho juntos, tendrán enfoques diferentes sobre las mismas cosas que les interesan.\n \nPor ejemplo, si empiezan a hablar de religión, acabarán en una batalla filosófica que no tiene ningún valor real.\n \nAl final, Piscis se sentirá mal por haber intentado siquiera racionalizar su fe, y Acuario tendrá la sensación de haber estado hablando con una imagen borrosa de algo parecido a una opinión.",
			Match: "35%"},
		Emotions: SummaryPercentage{
			Text:  "Acuario es distante e impersonal, mientras que Piscis no puede esperar a atarse a alguien de su amor de cuento de hadas.\n \nSu relación podría ser agotador para Piscis pareja si se esfuerzan demasiado para encontrar la respuesta para los sentimientos que puedan tener.\n \nLa distancia de su pareja seguramente los exaltará y creará una montaña rusa emocional especial para Piscis que podría llevarlos directamente a la decepción.\n \nEllos podrían hacer un ambiente emocional seguro para el otro sólo si la iniciativa proviene de la pareja Acuario solo.\n \nPiscis tendría que ser completamente silencioso, no implicado, femenino y reactivo.\n \nEn cuanto aparezca la idealización, el fino equilibrio se verá sacudido y la sensación de libertad de Acuario se verá perturbada.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "El vínculo entre estos signos simplemente no les permite alejarse demasiado el uno del otro y sus valores serán en su mayoría los mismos, pero totalmente diferentes en su realización.\n \nAmbos valorarán la libertad de cualquier tipo, el amor por la humanidad, la emoción, el cambio, la inspiración y sus ideas y sueños.\n \nPara Acuario, este amor por la humanidad significará justicia absoluta, igualdad y libertad de expresión.\n \nPara Piscis, significaría el sonido eterno del océano como una bendición que nos trae aquí.\n \nSi aplicamos esta importante diferencia de carácter a todas las demás cosas que valoran juntos, veremos que necesitarán mucha comprensión profunda para enmendar sus diferencias.",
			Match: "50%"},
		SharedActivities: SummaryPercentage{
			Text:  "Es bueno que el signo de Piscis esté siempre abierto a los cambios, porque Acuario se los proporcionará con mucho gusto.\n \nSus intereses pueden ser bastante similares y con ciertos compromisos podrían encontrar mucho que hacer juntos.\n \nPiscis visitará con gusto una exposición de arte, pero ¿por qué no hacer que sea moderna para que Acuario se interese también? Su problema está en la percepción del romanticismo y en los desacuerdos sobre las cosas que las parejas deberían hacer juntas.\n \nLa pareja Piscis querrá cosas inusuales, sorprendentes y excitantes, pero seguidas de romanticismo, placer físico y profunda comprensión emocional.\n \nLa pareja de Acuario, en cambio, querrá conversaciones inspiradoras, estimulación intelectual y, preferiblemente, algunas actividades extremas incluidas.",
			Match: "40%"},
	},
}
