package compatibilities

var Aquariusaquarius = Compatibility{
	Name: Aquarius + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "55%",
		Traits:  []string{AlmostNothingReally},
		Summary: "Es en el campo de la amistad donde la compatibilidad de Acuario y Acuario se muestra en todo su esplendor.\n \nAmbos están en la misma onda, sabrán aprovechar todos los momentos de diversión y esta relación puede funcionar muy bien.\n \nEsto no significa, sin embargo, que vaya a ser perfecta, porque en la vida todo tiene su parte gris y entre Acuario y Acuario también existirán algunos problemas, aunque serán de muy fácil solución.\n \nSi surgen las diferencias, cualquiera de los dos Acuario ambos han de procurar no ser tan tercos y admitir que se están peleando por una tontería.\n \nQuien lleve la razón es lo de menos, lo importante es lo que pueden perder.\n \nEn la base de esta amistad de Acuario y Acuario late una profunda admiración de uno hacia el otro.\n \nEstán encantados de poder contar con alguien que tiene su misma visión de la vida.\n \nSu amistad puede durar para siempre porque juntos nunca se aburrirán ni se cansarán.\n \nAdemás, no son nada egoístas ni celosos.\n \nSi uno de los Acuario amplía aún más su círculo social, el otro sabe que el nuevo amigo acabará siendo también el suyo.\n \nAcuario y Acuario jamás dejarán de planear cosas nuevas con las que pasarlo bien y divertirse.",
	},
	Love: Love{
		Match:  "74%",
		Traits: []string{Volatile},
		Summary: SummaryPercentage{
			Text:  "Puede resultar extraño imaginar a un Acuario enamorado de otro Acuario.\n \nCuando estudias Astrología, una de las primeras cosas que aprenderás es que Acuario es el signo de los divorcios, las rupturas y la liberación de regímenes y relaciones.\n \nComo signo que lleva la oposición en su interior, no suele ser fácil estar con ellos para ningún signo del zodiaco, pero esto es precisamente algo que ambos podrían entender el uno en el otro.\n \nSi se respetan de verdad, hay muchas posibilidades de que aprendan a entender también otras cosas de la vida del otro.\n \nAunque parezca una locura, estos dos miembros de la pareja tienen muchas posibilidades de permanecer juntos porque se conocerán mejor que nadie.\n \nSin embargo, rara vez se sienten tan atraídos el uno por el otro, e incluso cuando lo están, es muy difícil que formen un vínculo emocional profundo.\n \nCuando lo hacen, bueno...\n \nel cielo no es el límite.",
			Match: "74%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Dos Acuario pueden tener una relación sexual muy interesante, llena de excitaciones y experimentación.\n \nCumplirán las fantasías del otro sin ningún tipo de represión y encontrarán fácilmente un lenguaje en el que conectar sus extrañas sexualidades.\n \nAmbos miembros de la pareja tendrán problemas para encajar en los estereotipos habituales de la sexualidad y rara vez entenderán los tabúes y restricciones habituales que otras personas tienden a imponer.\n \nAún así, podrían encontrar un obstáculo en la vinculación emocional que podría presentarse a través de una falta general de intimidad en su vida sexual.\n \nEsto no apagará el deseo que sentirán cuando se sientan verdaderamente atraídos el uno por el otro, pero podrían estar demasiado distanciados como para que cualquiera de los miembros de la pareja pueda dar suficiente calor o enfoque a su relación.\n \nPor eso, en cuanto la excitación y la atracción iniciales empiecen a desvanecerse y surja la necesidad de un verdadero contacto emocional, podrían tener problemas para seguir juntos.\n \nSin embargo, si ambos buscan una aventura ocasional, éste podría ser el mejor contacto de los signos de todo el zodíaco para tenerla.",
			Match: "50%"},
		Trust: SummaryPercentage{
			Text:  "Siempre existe un vínculo interesante entre dos representantes del signo de Acuario.\n \nComprenden en silencio los pensamientos del otro a un nivel mental que ningún otro signo puede alcanzar.\n \nCuando comiencen su relación, su confianza se construirá sobre una base de libertad, por lo que realmente no habrá razón para que ninguno de los dos mienta.\n \nSi alguno de estos miembros de la pareja se vuelve posesivo, ambos irán en contra de sus creencias si deciden permanecer en este tipo de relación.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Vaya.\n \nEsta es una conversación de la que a todos nos gustaría formar parte.\n \nAcuario es un signo de la voz de Dios y la imagen de los pensamientos y razonamientos de nuestro yo superior.\n \nLo que un Acuario le dice a otro puede ser algo que sólo ellos dos entiendan.\n \nCualquiera que sea su relación, cuando hablan, lo más seguro es que tengan una conexión eléctrica y las ideas vuelen de un lado a otro como si la conversación fuera su patio de recreo.\n \nEl problema en su contacto intelectual puede aparecer debido a sus problemas de ego y esto es casi inevitable con dos individuos tan fuertes.\n \nEl Sol representa nuestra autoestima, el respeto y la individualidad, y está en detrimento en el signo de Acuario.\n \nEste podría ser el motivo de un conflicto muy desagradable entre sus personalidades, ya que ambos miembros de la pareja tienen la necesidad de establecer fuertes límites y se pierden fácilmente en sus individualidades extremas.\n \nLa mejor cura para esta situación es que cada uno de ellos frene, respire y se pregunte: ¿se dan realmente suficiente libertad para ser quienes son?",
			Match: "75%"},
		Emotions: SummaryPercentage{
			Text:  "Acuario no es tan emocional en un sentido típico, pero esto no significa que no son emocionales en absoluto.\n \nSu amor es de una manera compartida en un grupo de personas y aunque no es tan romántico, es muy importante para ellos como la base de todo su sistema de creencias.\n \nCuando se trata de una relación romántica, dos Acuario podrían sentir mucho el uno por el otro, pero es más probable que se perciban como amigos.\n \nSi se enamoran, como representantes de un signo fijo, permanecerán juntos durante mucho tiempo, aunque a ninguno de los dos le importe realmente cuánto durará la relación.\n \nLa belleza de su amor reside en su desapego, por extraño que pueda parecer.\n \nComo saben que nunca lo encontrarán con otra pareja, sólo se acercarán más en cuanto empiecen a manifestarse las verdaderas emociones.",
			Match: "40%"},
		Values: SummaryPercentage{
			Text:  "Sería curioso suponer que dos miembros del mismo signo tienen valores diferentes.\n \nPero cuando nos fijamos en el signo de Acuario vemos que lo que valoran está estrechamente relacionado con su hogar y la forma en que fueron criados.\n \nComo dos personas rebeldes y obstinadas, necesitan una educación similar si quieren entenderse.\n \nLo bueno es que ambos valoran su libertad hasta el extremo y esto les unirá incluso cuando haya muchas otras cosas en las que no estén de acuerdo.",
			Match: "80%"},
		SharedActivities: SummaryPercentage{
			Text:  "Quizá sean un poco egoístas a los ojos de los demás, pero no piensan en ello cuando están juntos.\n \nPodrían ir a cualquier parte y hacer cualquier cosa, siempre que sea lo suficientemente interesante, educativa o excitante.\n \nLo mejor de una relación entre dos Acuario es que pueden compartir actividades extremas que otras personas no entienden.\n \nAsí, si a uno le gusta el parapente y al otro escalar el Everest, ¿por qué no van a hacer estas cosas juntos, una a una hasta que todos sus deseos se hagan realidad?",
			Match: "99%"},
	},
}
