package compatibilities

var Ariespisces = Compatibility{
	Name: Aries + " - " + Pisces,
	Friendship: Friendship{
		Match:   "67%",
		Traits:  []string{NothingReally},
		Summary: "Sus opuestas personalidades y gustos no son un impedimento para que Aries y Piscis acaben convirtiéndose en amigos inseparables.\n \nA los Piscis les gusta seguir la corriente y Aries se lo pone más que fácil.\n \nTambién el sensible Piscis necesita sentir un poco más de agresividad porque en algunas ocasiones experimenta con dolor que le están tomando el pelo a manos llenas y no sabe cómo afrontar este tipo de situación.\n \nEn cambio, si tiene a un Aries al lado, se apoyará en él para defenderse o incluso puede que su amigo acabe sacándole las castañas del fuego.\n \nAries y Piscis se prestarán siempre ayuda mutua y tanto en los temas serios como a la hora de la diversión, cada uno encontrará en el otro el aliado más adecuado.\n \nEn su relación de amistad, Aries y Piscis unas veces actuarán como detonantes y otras como freno en situaciones complicadas.\n \nPiscis también encontrará en Aries el aliado más necesario en los temas económicos.\n \nLa amistad entre Aries y Piscis puede beneficiar extraordinariamente a ambos en el aspecto más material.\n \nSimplemente por influencia astral.\n \nPor eso es positivo que además de la amistad compartan proyectos productivos o compren juntos la lotería de Navidad.",
	},
	Love: Love{
		Match:  "29%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "Se trata de una relación perturbada sobre todo por la falta de confianza y la capacidad de ambas partes para abrirse a su pareja.\n \nAries está regido por Marte, el planeta que rige nuestro primer chakra, responsable de nuestra capacidad para establecer buenos límites.\n \nPiscis está regido por Neptuno, responsable de toda nuestra aura y de nuestra permeabilidad a los estímulos externos.\n \nPuesto que ambos son responsables de nuestra frontera con el mundo exterior, es difícil decir qué pareja debe aflojar y hacer posible su acercamiento.\n \nSu única posibilidad de un final feliz es que la pareja Aries se sumerja y su pareja Piscis despierte.",
			Match: "29%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Aries y Piscis son dos signos a los que realmente les cuesta conectar.\n \nEl principio de todas las cosas se encuentra a 0° de Aries y su final a 29° de Piscis.\n \nSu conexión es como una 'pequeña muerte' que deja sitio a todo lo nuevo, indómito e inexperto.\n \nEs difícil para ellos unirse, tanto como lo es para todos nosotros trascender, ir más allá de nuestro cuerpo físico y ser uno con el Universo.\n \nDicho esto, es comprensible lo difícil que resulta para sus naturalezas sexuales aceptarse mutuamente.\n \nAries representa el sexo instintivo.\n \nEl signo de Piscis representa el orgasmo.\n \nPiscis prefiere satisfacerse a sí mismo que estar con alguien que no entiende el arte de los orgasmos.\n \nAries podría incluso tener cierto éxito en la comprensión de la necesidad de ternura y contacto físico, pero lo que Piscis quiere es como un país de las maravillas inalcanzable que nadie necesita.\n \nDe hecho, simplemente no entienden qué es lo que necesitan.\n \nAries parece un niño inexperto para su pareja Piscis, y aunque esto puede abrir la puerta para que Piscis entre en esta relación, no se siente tan bien cuando se dan cuenta de que esto no va a cambiar.",
			Match: "20%"},
		Trust: SummaryPercentage{
			Text:  "Con Aries con la cabeza bien alta, su actitud atractiva y directa y su libido, no es fácil para el sensible Piscis no captar esas señales emitidas a su alrededor.\n \nEsto repercutirá inmediatamente en su grado de confianza.\n \nEs difícil abrirse cuando no se confía en la pareja, así que Piscis permanecerá en su pequeño mundo todo el tiempo que pueda, sólo para evitar que le hagan daño y le mientan.\n \nAries verá el mundo de su pareja como una imagen falsa y poco clara que no necesita, y considerará a su pareja Piscis sospechosa e indigna de su confianza.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Aries y Piscis podrían encontrar muchas cosas de las que hablar si se abren mutuamente en busca de apoyo y consejo.\n \nAunque la mayor parte del tiempo se interesan por cosas totalmente distintas, siguen conectados como signos vecinos y tienen una forma de apoyarse el uno en el otro.\n \nA través de su relación, necesitan aprender sobre sus propias debilidades y cómo repararlas para estar completos.\n \nNo es exactamente como se completan el uno al otro, pero el efecto que tienen el uno sobre el otro puede ser como la medicina correcta.\n \nAries tiene tendencia a no mirar atrás, a cuestionarse el pasado o a ser demasiado agudo y rápido para sus relaciones.\n \nTambién podrían tener un ego con una escopeta, a la espera de cualquier socio potencial para pasar y matar su deseo de siquiera pensar en salir con un Aries, y mucho menos ser serio acerca de una relación con ellos.\n \nPiscis son lo suficientemente sensibles como para explicar a Aries cómo deben suavizar pero mantener sus límites fuertes.\n \nPiscis representan una tierra de ensueño de Aries y que son capaces de mostrar que en realidad podría tener una misión y un propósito más elevado, en lugar de simplemente persiguiendo por la vida.",
			Match: "70%"},
		Emotions: SummaryPercentage{
			Text:  "Sus mundos emocionales son como dos planetas diferentes que rigen sus signos: Marte y Neptuno.\n \nMientras que Marte, el regente de Aries, está cubierto de óxido, es un desierto de color rojo con volcanes, cañones y clima, Neptuno es un gigante de gas azul, frío, azotado por los vientos y mucho más alejado del Sol.\n \nPrecisamente en esto difieren sus emociones.\n \nLas que más aprecian los Aries están bien definidas, son fuertes, están protegidas y se tiñen de un color de pasión.\n \nLos Piscis, en cambio, tienen un mundo emocional ventoso y cambiante, teñido de azul como el color de la tristeza y la visión, y se enfrían fácilmente en cuanto sienten una decepción.",
			Match: "5%"},
		Values: SummaryPercentage{
			Text:  "Es curioso cómo ambos valoran la honestidad y tienen tantas barreras de confianza cuando se juntan.\n \nCuando se involucran, la confianza se convierte en algo así como el único objetivo de toda su relación.\n \nA los dos también les gustan los héroes de cuento de hadas y valoran el escenario habitual de orgullo, castidad y valentía.\n \nSin embargo, el núcleo de estos valores es diferente para los dos.\n \nLos representantes de Aries los valorarán por esa sensación de fuerza, poder y por el papel de héroe único, más listo y valiente que los demás.\n \nLos Piscis las valoran por sus ideales, sus finales felices y esas relaciones utópicas entre esos pocos hombres y mujeres dignos.",
			Match: "35%"},
		SharedActivities: SummaryPercentage{
			Text:  "Podrían compartir un paseo por el bosque o practicar deportes acuáticos.\n \nOtras actividades que Aries realizaría con gusto no son lo bastante 'espirituales' para Piscis.\n \nPiscis siempre necesita tener 'una segunda perspectiva' y esto puede parecerle una locura a su pareja Aries.Sí, la pareja de Piscis sabe que los deportes son saludables, pero necesita vincularlos a algo de su mundo infinito.\n \nAsí que los deportes acuáticos están bien, por todos los secretos del agua, la vista del océano, estar bajo el agua y contemplar el propósito de la vida, o una zambullida en la piscina.\n \nPasear por el bosque puede ser hermoso porque pueden oír a los pájaros, a los árboles decir 'hola' y esperar a que dos búhos se posen sobre sus hombros.\n \nEn el mundo de Aries, las cosas son realmente mucho más sencillas y si quieren disfrutar de algo, simplemente irán y disfrutarán.\n \nDel mismo modo, correrán cuando corran, practicarán cuando practiquen y contemplarán el océano cuando lo contemplen.",
			Match: "40%"},
	},
}
