package compatibilities

var Ariescapricorn = Compatibility{
	Name: Aries + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "45%",
		Traits:  []string{MutualRespect, PoorAdvisors},
		Summary: "Aries y Capricornio en el terreno de la amistad son la viva representación de aquello que dice “ni contigo ni sin ti”.\n \nSus distintos puntos de vista en múltiples cuestiones les lleva a estar constantemente en un tira y afloja que casi siempre acaba en tablas.\n \nAries es más espontáneo pero Capricornio siempre calcula la parte negativa de las cosas, pero sólo para prevenir situaciones desagradables.\n \nSiempre tienen un plan B y esto alucina bastante a Aries que suele seguir sus impulsos sin pararse a pensar en los contras.\n \nLa mente fría y organizadora de Capricornio, supone un alivio para Aries, que ciertas responsabilidades que implica la amistad, como decidir a donde se va el fin de semana o en que restaurante se reserva mesa para cenar, lo deja tranquilamente en manos de Capricornio, con la seguridad de que el plan no fallará.\n \nAries y Capricornio saben como hacer que los demás les sigan, para eso tienen vocación líder.\n \nSu amistad quizá tenga altibajos, pero los demás los percibirán como un binomio perfecto para conseguir que el grupo se divierta.\n \nSus dotes de poder y de mando son muy necesarias para dirigir a los demás hacia buen puerto y en esto ellos son realmente los reyes.",
	},
	Love: Love{
		Match:  "38%",
		Traits: []string{Volatile, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "No es una relación fácil.\n \nNinguno de los miembros de la pareja tiene ni rastro de ligereza ni de feliz ignorancia.\n \nPor eso su relación puede parecer una competición para arruinar la relación de la mejor manera posible.\n \nEs difícil saber quién saldrá ganando, ya que ambos se sentirán fatal la mayor parte del tiempo y se sentirán aliviados por haberse separado finalmente.\n \nSi deciden obstinadamente que se quieren demasiado como para dejarse ir, probablemente ambos se golpearán la cabeza contra la pared durante años.\n \nSu única posibilidad de éxito es el respeto incondicional y la amplitud de miras y expectativas.\n \nPodrían complementarse de verdad, pero sólo en un escenario en el que buscaran lo bueno en el otro y destacaran sus cualidades.\n \nPor desgracia, la naturaleza maléfica de sus regentes rara vez les permite ser tan positivos y estar tan orientados a la aceptación.\n \nSi se juntan, y sea cual sea su historia, deberían pensar en las cosas que podrían aprender el uno del otro en lugar de buscar los defectos del otro, y mantenerse siempre al margen de los asuntos del otro.",
			Match: "38%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Se trata de una combinación de signos muy difícil en lo que a compatibilidad sexual se refiere.\n \nLos regentes de Aries y Capricornio son Marte y Saturno.\n \nEstos planetas se consideran enemigos arquetípicos o kármicos.\n \nEn lo que se refiere a la sexualidad, Marte es el signo principal y su contacto con Saturno puede provocar todo tipo de obstáculos físicos y objetivos en el camino hacia una vida sexual sana.\n \nSaturno ejerce demasiada presión sobre Marte y le quita mucha de su energía.\n \nSu relación dará lugar a la falta de deseo sexual, al sentimiento mutuo de incompetencia o incluso a la impotencia de una o ambas partes incluidas.\n \nCuando se da este tipo de relación, en la mayoría de los casos está provocada por alguna profunda necesidad inconsciente de ser contenido y restringido en lo que se refiere a la sexualidad.\n \nAl igual que con todo lo que viene a través del signo de Capricornio, con el tiempo Aries pareja podría alcanzar algún tipo de estado de equilibrio en el que están satisfechos sexualmente y sus necesidades instintivas se cumplen.\n \nLamentablemente, la pareja de Capricornio perderá su energía y la necesidad de participar en este tipo de comportamiento sexual para entonces.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "Como ambos son extremos y del tipo 'todo o nada', les resultará fácil confiar el uno en el otro.\n \nAunque tengan profundos malentendidos en otras áreas de su relación, rara vez traicionarán la confianza del otro.\n \nSin embargo, esto es algo que fácilmente darán por sentado, ya que cuando están juntos parecen perder la conciencia de las cosas que hay entre ellos y que deberían atesorar.\n \nUno de los dos debería tener la sensatez de recordarle al otro de vez en cuando las cualidades que incluye su vínculo.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Rara vez una pareja Capricornio permitirá que su impulsiva y, desde su perspectiva, incluso estúpida pareja Aries tenga sus propias opiniones y las valore como útiles o prácticas.\n \nAunque ciertamente respetarán su iniciativa y nivel de energía, el resto del comportamiento de Aries es simplemente inaceptable en la mayoría de los asuntos.\n \nComo Capricornio tiene los pies en la tierra y es capaz de medir la situación racionalmente, se aferrará a su opinión tranquila sobre la falta de tacto y resistencia de su pareja o incluso de su idiotismo.\n \nPuedes imaginarte lo molesto que puede resultar esto para un Aries, sobre todo si tienes en cuenta su apasionada necesidad de establecer límites firmes y de ser respetado de todas las formas posibles.\n \nPor otra parte, Aries simplemente no tendrá paciencia con su pareja Capricornio.\n \nParecerán aburridos y como si sólo quisieran personas útiles en su vida.\n \nEsto se atribuirá a su egoísmo y falta de emoción y corazón.\n \nAmbos estarán equivocados en cierto modo, ya que necesitarán comprender lo que ambos podrían llegar a ser si apareciera la persona o el motivador adecuados.",
			Match: "20%"},
		Emotions: SummaryPercentage{
			Text:  "En este caso especial sería mejor no llamar a este apartado 'emociones', sino 'comprensión'.\n \nSu problema radica en la forma en que se entienden, para empezar.\n \nAl principio de su relación, es probable que ambos tengan una imagen de la otra persona como alguien en quien podrían convertirse después de poner algo de esfuerzo en su crecimiento.\n \nEl problema es que aquí nadie quiere cambiar.\n \nSus emociones podrían estar fácilmente conectadas a esta primera imagen que han tenido, por poco realista que sea.Así que esto es exactamente lo que llamaríamos falta de comprensión, porque estos dos podrían estar locamente enamorados de la falsa imagen del otro y locamente empeñados en cambiarse mutuamente.\n \nSu problema realmente no es la falta de emoción hacia el otro (aunque se podría atribuir fácilmente sus problemas a la incapacidad emocional teniendo en cuenta su naturaleza Marte/Saturno), sino la falta de comprensión y aceptación del otro.\n \nA menudo son demasiado testarudos y estrechos de miras para ver que hay algo diferente de lo que encaja en sus límites de posibles características personales.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Ambos valoran la independencia, la claridad y la honestidad, y en general su sistema de valores no es lo que trae problemas a su relación.\n \nEn general están en sintonía cuando se trata de ver con seriedad a las personas de las que se rodean.\n \nEl problema que tienen está en sus expectativas poco realistas basadas en el hecho de que comparten algunos valores.\n \nSi Aries valora la capacidad de alguien para aguantar y superar todas las barreras personales posibles, eso no significa que esté preparado para convertirse en esa persona, o que tenga el control para serlo.\n \nDel mismo modo, Capricornio puede valorar la velocidad y la concentración de algunas personas, pero eso no significa que vayan a poner en peligro su profundidad o su atención a los detalles sólo para ser más rápidos, o que dejen desatendidas necesidades psicológicas profundas sólo para mantenerse centrados en algún objetivo.",
			Match: "60%"},
		SharedActivities: SummaryPercentage{
			Text:  "Capricornio a veces no entiende por qué Aries quiere correr a las 6 de la mañana.\n \nAries no entiende por qué Capricornio pasaría toda la noche haciendo algo extremadamente aburrido, sólo para ser minucioso cuando no tiene ningún valor en este asunto en particular.\n \nLo que Aries no entiende es que ser estudioso siempre tiene su valor, tanto como Capricornio no entiende la necesidad física de su cuerpo de descansar y actuar por impulso de vez en cuando.\n \nAmbos pueden encontrar fácilmente actividades que les gusten si incluyen movimiento físico.Ambos necesitan prestar atención a su cuerpo y a sus hábitos cotidianos, por lo que sería bueno que realizaran juntos la misma actividad física todos los días a la misma hora.\n \nDe este modo se motivarían mutuamente: Aries levantaría la energía de Capricornio y Capricornio daría resistencia a sus esfuerzos compartidos.\n \nEsto podría hacer maravillas para toda su relación, ya que podrían comprender mucho mejor la naturaleza del otro a través de este tipo de actividad básica.",
			Match: "40%"},
	},
}
