package compatibilities

var Ariessagittarius = Compatibility{
	Name: Aries + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "98%",
		Traits:  []string{DeepMutualUnderstanding, FunEnjoyable},
		Summary: "Los Sagitario, al igual que los Aries, tienden a ser egocéntricos en su forma de relacionarse pero al ser un rasgo común ambos lo toleran o por lo menos no le conceden importancia.\n \nPara que todo funcionara mejor entre ellos, Aries y Sagitario deberían entrenarse para adquirir la capacidad de comprender el punto de vista de otra persona.\n \nEs ahí donde pueden surgir diferencias considerables que minen su amistad. Sin embargo, Aries y Sagitario comparten algo en común que más que una afición es una pasión.\n \nSe trata de viajar, ambos viven siempre con la maleta a punto, dispuestos a coger el primer tren, barco o avión que se les pase por la cabeza.\n \nEsta inclinación es tan fuerte que puede dejar en la sombra los pequeños inconvenientes que puedan existir.\n \nAries y Sagitario, cuando descubran estas características que les unen, pondrán toda la carne en el asador para tener como amigo y compañero de aventuras al otro signo.\n \nA ambos les fastidia fracasar en cualquier cometido y les amargaría bastante acabar prescindiendo del otro por causa menor.\n \nHan de evitar los reproches mutuos y todo ira como una seda.",
	},
	Love: Love{
		Match:  "87%",
		Traits: []string{Harmonious, GreatSexualChemistry, LowCommitment},
		Summary: SummaryPercentage{
			Text:  "Sin duda, se trata de una pareja con mucho potencial.\n \nPuede que tengan que enfrentarse a su entorno y defender sus sentimientos ante los demás, pero esto no les hará tambalearse demasiado, ya que a ninguno de los dos le importa demasiado la opinión de los demás.\n \nSi consiguen limar sus diferencias filosóficas y respetar las distintas opiniones del otro, podrían convertirse en una de las relaciones más cálidas del zodíaco.\n \nSu principal consejo para la relación sería decirse siempre la verdad y no volverse locos por sus sanas diferencias.\n \nSus diferencias son precisamente lo que podría hacer más excitante su vida sexual.",
			Match: "87%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando Aries y Sagitario mantener relaciones sexuales puede ser bastante divertido.\n \n Son dos signos de Fuego, ambos muy apasionados, cada uno a su manera.\n \nAries es apasionado cuando se trata de acción, cosas nuevas y, por supuesto, personas desnudas y posiciones sexuales específicas.\n \nSagitario es un apasionado de su personalidad alegre.\n \nSin embargo, Sagitario realmente sólo se preocupa por sus opiniones, convicciones y valor moral.\n \nPueden pasarse toda la vida analizándolas para ver si están equivocados o en lo cierto y buscar la verdad universal.\n \nCuando se trata de su optimismo y buen humor, los protegen apasionadamente de cualquier cosa demasiado seria o dura.\n \nSi dejaran que alguien los empañara, se tambalearía su convicción de que siempre deben sonreír y encontrar un motivo para ser felices.\n \nAunque Aries puede ser un poco vanidoso en cuanto a sus habilidades y rendimiento sexuales, en la mayoría de los casos Sagitario es capaz de romper este muro de estricta tensión sexual y llevarlos a una zona más relajada donde puedan distenderse y experimentar.",
			Match: "95%"},
		Trust: SummaryPercentage{
			Text:  "Tanto Aries como Sagitario son conscientes de la excesiva necesidad de honestidad en su vida.\n \n Normalmente no tienen que hablar mucho para entenderse y pueden detectar fácilmente cuando el otro está mintiendo.\n \nEsto hace que sea extremadamente difícil crear una situación de desconfianza, sobre todo por la sensación de seguridad que la pareja Sagitario da a Aries, al tomarse todo con dignidad y serenidad.\n \nEn la mayoría de las situaciones Aries siente que puede compartir cualquier cosa con su pareja Sagitario.\n \nEl problema puede surgir si tienen opiniones diferentes sobre la seriedad y profundidad de su relación.\n \nSi este es el caso, por lo general la pareja Sagitario ve a Aries como una pareja a corto plazo y no tan importante.\n \nEsta es la razón por la que podrían engañarlos fácilmente y probablemente ni siquiera lo llamarían engaño.\n \nA cambio, Aries pareja que valora su relación más, saltaría en su naturaleza posesiva con aún más facilidad y nunca confiar en su pareja Sagitario de nuevo.",
			Match: "70%"},
		Communication: SummaryPercentage{
			Text:  "Se trata de un vínculo maravilloso que a menudo se observa en amistades que duran años.\n \n Su comprensión mutua puede ser tan profunda que, aunque carezcan de atracción física, la sustituirían gustosamente por una vida dedicada a este tipo de relación intelectual.\n \nSe motivan y empujan mutuamente hacia donde quieran ir.\n \nCuando están juntos, se hacen sentir como si nada fuera imposible.\n \nMientras que Aries aporta iniciativa y concentración, Sagitario aporta visión y fe.\n \nEstos signos están regidos por Marte y Júpiter, lo que significa que podrían tener algunos desacuerdos sobre sus convicciones.\n \nEn caso de que no sean convicciones que consideren los cimientos de su personalidad, esto no debería suponer un gran problema.\n \nAun así, es posible que su conjunto de creencias difiera demasiado como para que lleguen a entenderse.\n \nCuando esto ocurre, se pelean cuando y donde pueden, ya que ninguno de ellos tiene la capacidad de dejar de lado sus convicciones.\n \nAries porque quiere ganar, y Sagitario porque las convicciones son su fuerte y algo en lo que seguramente han pensado mucho.",
			Match: "90%"},
		Emotions: SummaryPercentage{
			Text:  "Cuando se enamoran el uno del otro, profunda y sinceramente, es casi posible que sus transeúntes entren en calor en pleno invierno.\n \n Son signos extremadamente cálidos, debido a su correspondiente elemento Fuego, abiertos a cualquier tipo de actividad con tal de compartir tiempo juntos y sentir esa maravillosa emoción en el estómago.\n \nEs un amor que puede durar mucho tiempo, siempre y cuando respeten sus necesidades personales, su individualidad y la distancia que puedan necesitar de vez en cuando.\n \nAunque no se les considera muy emotivos, es un error atribuir la emotividad únicamente al elemento Agua.\n \nSe trata de un elemento que actúa desde el corazón y se siente en el pecho.\n \nEn busca de una explicación de la naturaleza emocional de los signos de Fuego, basta con imaginar esa sensación de calor en el vientre y ésa sería la mejor descripción posible.Sus emociones son activas, cálidas y están en movimiento.\n \nSiempre cambiantes pero creativas y ahí para moverlas a donde quieran ir.",
			Match: "%"},
		Values: SummaryPercentage{
			Text:  "La pareja Aries valora las cosas que son llevadas a un nivel superior por su Sagitario.\n \n Con el tiempo, ambos comprenderán que Aries crece a través de esta relación y amplía todo su sistema de valores.\n \nCuando empezaron a salir, Aries probablemente tenía esta idea del honor y la lógica heroica de 'arrasar'.\n \nCon el tiempo, ambos deben haberse dado cuenta de que Sagitario da a esta idea un nuevo paso adelante y la lleva a un mundo de realeza.Sagitario no sólo valora a las personas honorables y heroicas, sino que también valora a las personas honorables con sangre azul que dan dinero y comida a los pobres, todos los días.\n \nSu principal diferencia radica en el hecho de que Aries valora las cosas concisas y claras, mientras que Sagitario se dispersará fácilmente y dará vueltas al asunto durante días.\n \nEsto se puede resolver a través de su valor mutuo de la verdad, por lo que la honestidad puede ser su cura para cualquier cosa.",
			Match: "70%"},
		SharedActivities: SummaryPercentage{
			Text:  "Aries es un signo en el que cae Saturno.\n \n Esto significa que se cansan fácilmente o simplemente se aburren y siempre necesitan estímulos nuevos y excitantes.\n \nSagitario es un signo mutable, dispuesto a cambiar lo que haga falta para sentirse bien.\n \nCuando se reúnen, sus actividades pueden ser compartidas y divertidas sean cuales sean.\n \n Esto no tiene nada que ver con sus necesidades y tendencias, sino con el potencial de toda su relación.\n \nPueden ir a tomar un café y se lo pasarían bien, pero también podrían hacer puenting juntos y divertirse aún más.\n \nPara ellos es lo mismo.\n \nSon totalmente capaces de respetar la personalidad del otro, así que incluso si sus deseos para ciertas actividades difieren, esto se solucionaría fácilmente.",
			Match: "99%"},
	},
}
