package compatibilities

var Arieslibra = Compatibility{
	Name: Aries + " - " + Libra,
	Friendship: Friendship{
		Match:   "70%",
		Traits:  []string{GoodRomancePotential},
		Summary: "Pueden convertirse en compañeros inseparables por su inclinación a la actividad.\n \nSon dos signos muy sociales a quienes entusiasma la idea de tener un amigo con quien compartir experiencias emocionantes.\n \nSin embargo, del dicho al hecho hay un trecho, porque también en la amistad surgirán ciertos inconvenientes cuando sus opiniones difieran.\n \nEsto, sin embargo, no romperá los vínculos, pero podría resquebrajar su relación.\n \nLibra es alguien generoso, dando siempre de más, y éste es un aspecto que cautivará a Aries.\n \nEl mayor problema entre Aries y Libra es que ambos desearán con frecuencia llevar la voz cantante.\n \nAries está tan seguro de sí mismo que le resulta casi imposible comprender que otro tenga distinta opinión y además lo manifiesta de forma muy expresiva.\n \nLibra, en cambio, quiere hacer prevalecer su criterio pero de una forma mucho más sutil, lo cual le coloca en cierta desventaja.\n \nAries es quien suele dar el primer paso, mientras que Libra acompaña y mejora cada acción.\n \nSi evitan invadir el territorio del otro signo, serán amigos fieles y su relación eterna.",
	},
	Love: Love{
		Match:  "62%",
		Traits: []string{NaturalPartners},
		Summary: SummaryPercentage{
			Text:  "Por difícil que resulte conciliar estas dos naturalezas, recuerda que se trata de una oposición primigenia que representa a las parejas por significación.\n \nAries y Libra son la pareja del zodíaco, tanto como cualquier otro signo opuesto, ya que se corresponden mutuamente en la séptima casa, la casa de las relaciones.\n \nMás aún si tenemos en cuenta que Libra es el signo de las relaciones en general.\n \nCualquier problema que puedan tener entre ellos es algo a trabajar, porque muestra cuál es su problema personal con cualquier relación.\n \nCuando se sienten locamente atraídos el uno por el otro y se enamoran, no hay casi nada que pueda separarlos, sin importar las diferencias.\n \n¿No nos gustaría a todos encontrar el punto medio con nuestro ser querido? Necesitan trabajar en su vínculo, eso es un hecho, pero su relación es una promesa de encaje perfecto de dos almas destinadas a estar juntas.",
			Match: "62%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Aunque Aries y Libra son signos de naturaleza masculina, constituyen una oposición primigenia del zodíaco y presentan una relación entre Marte y Venus, planetas encargados de nuestra vida sexual.\n \nCuando entablan relaciones íntimas, es de esperar que aflore toda su libido y sus posibles problemas de expresión sexual.\n \nLa atracción que sienten el uno por el otro es grande, pero sus signos combinados presentan un comportamiento pasivo-agresivo en general y como pareja podrían tener tendencia a hacerse daño en las relaciones íntimas.\n \nRegido por Marte, Aries es un signo de debilitación de Saturno y Libra lo exalta, por lo que su principal problema es la falta de emoción y los límites deficientes en lo que respecta al sexo.\n \nSaturno puede enfriar demasiado las cosas y ser un reto a superar en sus intentos de acercarse sinceramente.\n \nCuando conectan a través de la emoción real y respetan los límites del otro, tienen potencial para una muy buena vida sexual, ya que Aries da iniciativa y energía al indeciso Libra, elevando su libido, y Libra despierta la finura de Aries, enseñándoles a ser amantes desinteresados y a disfrutar pensando en la satisfacción de su pareja.",
			Match: "80%"},
		Trust: SummaryPercentage{
			Text:  "La confianza no es su fuerte y los problemas con ella podrían torturarles durante años.\n \nLa pareja Libra tiene un problema de inseguridad en general y necesita demostrar su valía a través de las relaciones con diferentes personas.\n \nLes encanta ser amados y parecen hambrientos de la aprobación de quienes les rodean.\n \n A Aries esto le parece estúpido, pero se pone celoso con facilidad y amenaza su mutuo sentido de la estabilidad y la creencia en las decisiones de la otra persona.\n \nDebido a la falta de confianza de Libra, también es posible que dude de todo lo que hace su pareja.\n \nDado que Aries no pone mucho tiempo o pensamiento en sus acciones, la falta de conversación sobre cada detalle de su vida personal podría fácilmente surgir sospechas en la mente de un Libra.\n \nLo más importante aquí es que Libra trabaje en su autoestima y se centre en su propia vida en lugar de tratar de mezclarse en la vida de su pareja.",
			Match: "40%"},
		Communication: SummaryPercentage{
			Text:  "Aparte de los posibles conflictos de los que Libra intenta huir la mayoría de las veces, su comunicación suele servir para alimentar al hambriento Sol de Libra, o al hambriento Saturno de Aries.\n \nAries necesita levantar el ánimo de su pareja Libra todo el tiempo, mostrándole lo capaz y valiente que puede llegar a ser, mientras que Libra asume las responsabilidades de su pareja Aries y le muestra cómo alcanzar un determinado objetivo.\n \n Todo esto puede resultar bastante pesado a veces, sobre todo si uno de los dos tiene algún problema con este juego de roles incondicional, o no reconoce el esfuerzo de su pareja.\n \nLa mayoría de las veces hablarán de sus actividades y acontecimientos cotidianos, ya que no comparten muchos intereses.\n \nAl hablar de diferentes actividades y personas, encuentran un lenguaje común, ya que Aries ayuda a Libra a no obsesionarse con los demás y Libra ayuda a Aries a comprender puntos de vista diferentes a los suyos.\n \nSu comunicación podría ser estupenda si ejercieran la misma profesión o al menos compartieran lugar de trabajo, porque eso cubriría los intereses básicos que comparten y les daría más espacio para encontrar el punto medio entre sus opiniones.",
			Match: "55%"},
		Emotions: SummaryPercentage{
			Text:  "Por disparatado que pueda parecer con la falta de cualidades que puede sufrir su relación, se trata de una pareja que se entiende muy bien en lo que a emociones se refiere.\n \nAries puede despertar la capacidad de Libra para mostrarlas debido a su propia franqueza.\n \nEsto es algo que todo Libra necesita, ya que les cuesta bajar la guardia.\n \n Libra, por otra parte, tiene la profundidad suficiente para mirar dentro de la personalidad de Aries en lugar de examinar superficialmente su comportamiento.\n \nDe todos los signos del zodiaco, Libra es probablemente uno de los pocos que comprenden bien la naturaleza de Aries.\n \nEllos no entienden sus acciones y su forma de mostrar la emoción, pero el núcleo de la emoción y la personalidad sensible es fácil de alcanzar desde su perspectiva.\n \nEs seguro decir que esta es una pareja que podría resolver cualquier problema con el amor que sienten el uno por el otro y aunque sus problemas podrían ser grandes, esto es posiblemente una conexión emocional tan profunda que todos los problemas se desvanecen a su lado.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Nuestros valores marcan la dirección que nos lleva a nuestra meta de desarrollo personal.\n \nAries tiene una meta en el signo de Capricornio, ya que éste es el signo de su décima casa.\n \nCapricornio está regido por Saturno que exalta en Libra.\n \n En el sentido práctico, esto significa que Libra ayuda a Aries a alcanzar sus metas, mientras sigue los valores necesarios.\n \nSe trata de una observación interesante porque el signo de Aries es el signo de la debilitación de Saturno y no parece comprender el conjunto de valores o los pasos exactos que le llevarían a su meta.\n \nEs casi como si Libra conociera el camino para que Aries alcance sus objetivos descubriendo nuevos valores en relación con ellos.\n \nEn general, sus valores individuales son diferentes en muchos aspectos, pero precisamente el propósito de su relación es cuestionarlos y enderezarlos.\n \nAries valora el enfoque directo, enérgico y las personas francas.\n \nLibra valora el tacto, la delicadeza y el prestigio.\n \nMientras Aries da lo mejor de sí para vivir el ahora, Libra examina el pasado para fijar objetivos lejanos en el futuro.\n \nTienen mucho que aprender el uno del otro, pero si lo hacen, podrían situar sus valores mutuos en algún punto intermedio.",
			Match: "70%"},
		SharedActivities: SummaryPercentage{
			Text:  "Esta es la pareja a la que le resulta muy difícil coordinar sus actividades.\n \nQuieren hacer cosas opuestas la mayor parte del tiempo, y la única actividad que siempre están de acuerdo en compartir es la sexual.\n \nAunque ésta sea un pilar para una buena relación y todo lo demás que no puedan compartir les parezca irrelevante durante algún tiempo, tienen que encontrar la manera de hacer algo más que les guste a los dos.\n \n Incluso si no lo hacen, su relación podría funcionar, pero sólo si la pareja de Libra abandona su idea de que necesita incluir a su pareja en todo lo que hacen.\n \nAries podría ayudar a Libra apoyando su independencia de cualquier forma posible, al tiempo que acepta participar en una parte de las actividades que le interesan a Libra.",
			Match: "30%"},
	},
}
