package compatibilities

var Ariesaquarius = Compatibility{
	Name: Aries + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "100%",
		Traits:  []string{ExcellentAdvisors, FunEnjoyable},
		Summary: "La amistad entre Aries y Acuario funciona de maravilla.\n \nLa aparente frialdad que Acuario puede demostrar al principio de un amor, desaparece si de lo que se trata es de afianzar una amistad.\n \nAries con su carácter intrépido le atrae enormemente y hará todo lo posible por tenerlo como amigo.\n \nEn realidad, aunque como pareja Aries y Acuario pueden llegar a funcionar muy bien, lo superan en el plano de la amistad.\n \nA veces parece que están más y mejor unidos por una amistad de lo que demuestran estarlo en una relación sentimental.\n \nLa objetividad de Acuario atrae irresistiblemente a Aries, que de alguna forma sabe que ésta cualidad no la posee pero le hace mucha falta.\n \nEste contraste entre el impulso ariano y la sosegada frialdad de Acuario es una de las razones principales por las que Aries y Acuario se atraen y se necesitan.\n \nAl lado de Acuario, Aries aprenderá a ser mejor administrador y adquirirá habilidades que no posee por naturaleza, entre ellas a entender mejor la forma de ser y expresarse de los demás.\n \nLos lazos de amistad entre Aries y Acuario siempre dan sus frutos.\n \nAmbos demostrarán lealtad y serán capaces de defender a la otra persona en cualquier situación que se encuentre.",
	},
	Love: Love{
		Match:  "68%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "Esta es una pareja a la que le falta ternura.\n \nNo son dos brutos que dejan que su relación se desvanezca tan pronto como lo hace su pasión, pero la mirada examinadora distante de Acuario puede quitarle emoción.\n \nAries pareja necesita ser relajado por su pareja, para que puedan derretirse y mostrar su verdadera naturaleza emocional, caliente.\n \nEn esta relación, tendrían una pareja distante que básicamente apoya su naturaleza primitiva e instintiva.\n \nAunque es agradable pensar que el objetivo de cada relación es que la pareja se acepte tal como es, en este caso eso le quitaría a un Aries toda oportunidad de crecer a través de la unión y de aprender sobre su naturaleza emocional.Esto es algo con lo que nunca estarán satisfechos.\n \nAún así, toda relación con Acuario puede sorprendernos tanto como podría hacerlo cualquier Acuario individual.\n \nCon ellos como pareja, siempre hay lugar para un escenario esclarecedor que deja todas las cosas al libre albedrío.\n \nEn caso de que decidan compartir sus vidas juntos, deberían tener una habitación para gritar que pudieran visitar individualmente de vez en cuando.\n \nEsto probablemente funcionaría.\n \nY sobre esa falta de emoción, podrían poner mucha ternura física para empezar y dejar que las cosas vayan a partir de ahí.",
			Match: "68%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "El contacto sexual entre los signos de Aries y Acuario puede ser realmente estresante o extremadamente excitante.\n \nNormalmente es ambas cosas.\n \nSus signos van bien juntos en general y se apoyan mutuamente con facilidad, ya que ambos tienen mucha energía para seguirse.\n \nSin embargo, cuando se trata de sus relaciones sexuales e íntimas, podrían carecer de emoción.\n \nAries es un signo apasionado con muchas emociones cálidas y creativas.\n \nEsta es una relación que podría sacar a relucir su peor naturaleza y simplemente enfatizar que son un signo regido por Marte, un cazador sexual frío y carente de emociones.\n \nAunque esto puede ser realmente excitante para ambos, no será muy satisfactorio, porque ambos necesitan sentirse amados.\n \nHay un exceso de masculinidad y energía que podría llevar a relaciones muy turbulentas.\n \nSus papeles son fáciles de entender, con Aries dando energía y resistencia a su pareja Acuario, y Acuario dando ideas locas y ampliando los horizontes de su Aries.\n \nEsto es muy divertido al principio de la relación, pero al cabo de un tiempo puede resultar agotador, ya que no hay suficientes ideas para cubrir el vacío emocional que pueden encontrar.",
			Match: "65%"},
		Trust: SummaryPercentage{
			Text:  "La confianza es un tema importante para Aries y Acuario puede entenderlo.\n \nEsto no quiere decir que vayan a ser fieles a su pareja Aries para siempre, pero se podría pensar que es justo para mantener una relación abierta y decirle acerca de sus indiscreciones.\n \nPor desgracia, Aries está regido por Marte y necesita ser el único en el mundo al que su pareja ponga los ojos.\n \nEsto podría convertirle en una persona posesiva y enfadada que se obsesiona con los movimientos de su pareja.\n \nCuando se trata de cuestiones de confianza entre ellos que no incluyen a otras personas, se puede decir que no tienen ningún problema.\n \nAmbos simplemente no entienden por qué mentirían cuando hay tantas verdades interesantes por descubrir.\n \nNecesitan ser libres para decir lo que piensan y aceptar que nunca evitarán el conflicto, pero que éste puede utilizarse de forma constructiva para comprenderse mejor y fortalecer su relación.",
			Match: "85%"},
		Communication: SummaryPercentage{
			Text:  "Sus conversaciones pueden ser tan apasionantes que a muchos les gustaría meterse en ellas.\n \nAries suele ser algo serio y pide que se respeten sus límites.\n \nLa pareja de Acuario reconocerá esto, se reirá y sacudirá todo su mundo.\n \nEs inimaginable para Aries, siempre en movimiento recto, que alguien tenga una mente tan abierta, yendo hacia atrás y hacia delante, teniendo nuevas revelaciones cada día y nunca perdiendo la energía para temas nuevos y diferentes.\n \nAries podría encontrar un ídolo en su pareja Acuario y entrar de lleno en cualquier diálogo porque le entusiasma lo que podría descubrir y cómo cambiaría su perspectiva.Por otro lado, Acuario disfruta de este papel en la vida de su pareja debido a sus problemas de ego con el Sol posicionado en este signo.\n \nCompartirán sus pensamientos con su pareja, intentando ser lo más interesantes posible.\n \nAcuario se siente motivado por su pareja Aries y disfruta haciendo pequeñas bromas a su costa.\n \nEs importante que Aries no se tome las cosas como algo personal cuando se trata del humor de Acuario y podrían divertirse mucho juntos.",
			Match: "90%"},
		Emotions: SummaryPercentage{
			Text:  "Para que Acuario despierte su naturaleza emocional, suele ser necesaria una pareja con la suficiente flexibilidad y paciencia para conseguirlo.\n \nNo diríamos exactamente que Aries sea paciente, así que puedes imaginarte el problema que podría aparecer.\n \nDesde la perspectiva de un Aries, su pareja es fría, distante y no tiene intención de abrirle su corazón.\n \nAcuario ve las cosas de otra manera e intenta ser racional en todo momento.\n \nCuando Aries comienza a pedir la muestra de emoción, el verdadero problema sale a la superficie, ya que Acuario podría haber mostrado cómo se sienten todo el tiempo, pero nadie adivinaría lo que estaban mostrando.",
			Match: "40%"},
		Values: SummaryPercentage{
			Text:  "Aunque pueden compartir una gran conversación, sus valores van por caminos distintos en cuanto tocan el tema de la libertad.\n \nAmbos valoran la libertad por primer impulso.\n \nPero con el tiempo, Aries se da cuenta de que en realidad no valoran tanto la libertad cuando la ven en el trabajo.\n \nDe hecho, a menudo cambiarían todo en sus vidas sólo para quitarle la libertad a su pareja Acuario.\n \nEsto no es una necesidad consciente, pero Aries puede ser como un niño mimado que quiere las cosas (y las personas) todo para sí mismo.\n \nAsí que con Acuario cambiando de dirección como el viento y nunca cambiando su naturaleza, Aries puede encontrarse verdaderamente infeliz porque quiere a alguien con quien compartirlo todo, no sólo lo que el viento lleva dentro.",
			Match: "30%"},
		SharedActivities: SummaryPercentage{
			Text:  "A menos que Acuario sugiera algo realmente inaceptable a su pareja Aries, tendrán abundantes posibilidades en lo que se refiere a sus actividades compartidas.\n \n \nCon tanta energía, su único error sería quedarse en casa y no compartir una oportunidad para sacar toda esa energía de sus sistemas.",
			Match: "99%"},
	},
}
