package compatibilities

var Cancerleo = Compatibility{
	Name: Cancer + " - " + Leo,
	Friendship: Friendship{
		Match:   "45%",
		Traits:  []string{NothingInCommon},
		Summary: "En una relación de amistad, Cáncer y Leo suelen ser amigos leales aunque quizá demasiado posesivos, cada uno en su estilo de relacionarse con los demás.\n \nLeo valorará las atenciones y la deferencia de Cáncer, que siempre accede a sus acciones, mientras que Cáncer dará importancia a la estabilidad emocional que le proporciona su amistad con Leo, así como el agradable trato que éste le proporciona.\n \nAmbos valoran la comodidad y la seguridad en no pocos aspectos y suelen compartir sus preferencias por relacionarse con un grupo de amigos no muy numeroso y muy bien elegidos.\n \nLeo está regido por el Sol, que le otorga energía masculina, mientras que Cáncer está regido por la Luna, que le impregna de energía femenina.\n \nCáncer y Leo se complementan por oposición, se apoyan y admiran mutuamente.\n \nDesde sus diferentes perspectivas, a ambos les gusta controlar la situación y creen saber qué es lo mejor para su amistad.\n \nSiempre se cuidaran y valorarán mutuamente, por esto lograrán subsanar sus diferencias.\n \nSu determinación de que la relación de amistad sea profunda y sincera, es uno de los aspectos más favorables y lo que contribuirá a que ambos deseen mantenerla toda la vida, cediendo terreno a veces para conseguir un buen entendimiento.",
	},
	Love: Love{
		Match:  "29%",
		Traits: []string{PoorAdvisors},
		Summary: SummaryPercentage{
			Text:  "Aunque la Luna refleja la luz del Sol, el signo de Cáncer no ve realmente a Leo como la fuente de toda su alegría.\n \nLeo es un signo que debe difundir la alegría y el amor con un enfoque activo en cada una de sus relaciones.\n \n¿Cómo es posible que Cáncer sea inmune? Pues probablemente porque la Luna gira alrededor de la Tierra, no del Sol.\n \nSon especiales, eso está claro.\n \nAmbos son individuos fuertes, cada uno en su propio plano.\n \nSu falta de comprensión y tacto emocional se explica por el hecho de que ambos tienen la misión de difundir el amor entre los signos menos afortunados del zodíaco.\n \nNo todo el mundo nace con un caudal emocional como Cáncer y un corazón enorme y cálido como Leo.\n \nSi se guardaran todo ese amor para ellos, probablemente algunas almas desafortunadas los buscarían sin rumbo y el mundo sería un lugar mucho más triste.",
			Match: "29%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cáncer y Leo forman una pareja muy interesante porque son los únicos signos del zodíaco regidos por el Sol y la Luna.\n \nAunque no tienen mucho en común, en astrología representan al rey y la reina del zodíaco.\n \nPor desgracia, sabemos lo frustrante que puede ser el sexo entre un rey y una reina.\n \nEl aspecto sexual de su relación depende de la profundidad de sus emociones.\n \nComo signos muy emocionales, tienden a demostrar su amor de formas diferentes y esto puede ser un poco difícil de conciliar en su vida sexual.\n \nComo signo de Fuego, Leo es mucho más abiertamente apasionado y esto podría ahuyentar a su Cáncer.\n \nCáncer es lo suficientemente tierno y sensible como para hacer que su pareja Leo se sienta culpable debido a su naturaleza, o Leo podría simplemente tener dificultades para ser tierno de la manera que Cáncer necesita.\n \nEs como si un león y un corzo iniciaran una relación sexual y, aunque no quieren hacerse daño, su comportamiento primario parece tirar de ellos en esa dirección.\n \nAún así, debido a sus reglas, pueden acercarse bastante y compartir emociones bonitas en sus encuentros sexuales.\n \nAunque no habrá mucha excitación en ellos, podrían ser lo suficientemente satisfactorios para ambos miembros de la pareja si no esperan una vida sexual salvaje.",
			Match: "30%"},
		Trust: SummaryPercentage{
			Text:  "Se dice que a Leo le gusta ser el centro de atención de todos.\n \nEsto es algo cierto y Leo es un artista nato, más o menos apoyado para llegar a serlo.\n \nSin embargo, su necesidad de lucirse es algo que a Cáncer puede resultarle irritante, pero no algo por lo que deba perder su confianza.\n \nSi Cáncer se siente querido, no tiene motivos para dudar de su pareja sólo por su naturaleza.\n \nAun así, las diferencias entre ellos pueden llevarles a buscar en secreto parejas más compatibles, algo que ambos perciben fácilmente.",
			Match: "50%"},
		Communication: SummaryPercentage{
			Text:  "Cáncer y Leo, regidos por la Luna y el Sol, representan un subconsciente y una mente consciente.\n \nAunque compartan intereses, a menudo tendrán un punto de vista extrañamente diferente sobre la misma cosa.\n \nA menudo se distanciarán a medida que avance la conversación.\n \nLa Luna refleja la luz del Sol, pero gira alrededor de la Tierra.\n \nEsto estaría bien si el Sol no estuviera tan acostumbrado a que todo el mundo gire a su alrededor.\n \nEsto explica lo que ocurre en su relación una vez que Leo empieza a hablar.\n \nAunque brillan, Cáncer presta mucha más atención a otra persona o a la idea de cosas terrenales que podrían tener juntos, que a su pareja Leo.\n \nLa base de su comunicación debe estar en las cosas que aún están por descubrir.\n \nTodos los misterios que hay por resolver podrían ser un buen punto de partida porque ambos necesitan entender cosas, cada uno en su área de dominio.\n \nLa mejor posibilidad que tienen está en las cosas que necesitan que se arroje luz sobre ellas desde dos ángulos diferentes.\n \nSi se respetan lo suficiente, podrían aprender mucho del enfoque pasivo y activo que cada uno tiene de la vida.",
			Match: "10%"},
		Emotions: SummaryPercentage{
			Text:  "Podemos decir con certeza que sus emociones son algo realmente hermoso.\n \nAmbos signos representan el amor y aunque no es el mismo tipo de amor, es una emoción, pura y simple.\n \nCáncer es un signo de Agua que representa el amor maternal y todas las emociones en la propia familia.\n \nAunque no siempre es una promesa de felicidad, la profundidad de todo el amor que se esconde en su interior es mágica.\n \nPor otro lado, Leo es un signo de Fuego de la alegría, los primeros amores, la diversión y el sexo.\n \nSu corazón es cálido y grande, pues Leo representa a nuestro niño interior, y su lealtad es inalterable cuando deciden entregársela a alguien.\n \nEl principal problema aquí es su conexión, ya que Cáncer necesita mirar a alguien a los ojos y sentir el amor, mientras que Leo quiere gritarlo a los cuatro vientos.\n \nAmbos tienen signos opuestos regidos tradicionalmente por Saturno y es exactamente por esto que podrían reconocer la verdadera calidad en su relación, ya que cada uno de ellos toma su rol opuesto para aprender algo.\n \nPor lo general, esto no es algo que pueda durar mucho tiempo y probablemente ambos seguirán adelante para encontrar a alguien que sea más una imagen de su séptima casa.",
			Match: "45%"},
		Values: SummaryPercentage{
			Text:  "Sencillamente, no valoran las mismas cosas. Aunque éste es el punto en el que separan sus caminos, suelen tardar mucho en darse cuenta de este hecho. Cáncer valora la ternura, las emociones, la familia y una vida estable con alguien, mientras que Leo valora la iniciativa, la pasión, la energía y la concentración. Rara vez hay algo que ambos valoren de la misma manera, o que pongan en el mismo lugar en sus listas de prioridades.",
			Match: "1%"},
		SharedActivities: SummaryPercentage{
			Text:  "Ayuda que Leo duerma con gusto 20 horas al día.\n \nAsí estarán disponibles en casa.\n \nTambién estarán encantados de que les sirvan el desayuno, la comida y la cena, y quién mejor para preparárselos que un Cáncer cariñoso.\n \nSin embargo, cuando salgan de casa, querrán visitar lugares diferentes.\n \nCáncer querrá visitar a sus amigos íntimos, sobre todo si tienen bebés, dar un paseo por el lago o pasar una velada romántica en el cine.\n \nHagan lo que hagan, les gusta que haya un poco de intimidad.\n \nComo si se opusiera a esto, Leo querrá pasar tiempo en lugares donde puedan ser vistos.\n \nSu pareja necesita brillar ante los demás y llevarles de la mano mientras todos los demás aplauden a los suyos.\n \nEsto no suele ser algo que Cáncer esté dispuesto a hacer, ya que en realidad no le gusta ser el centro de atención.\n \nPor otro lado, Leo podría transigir, pero al final no serían felices si no se satisfacen sus necesidades sociales.",
			Match: "36%"},
	},
}
