package compatibilities

var Cancersagittarius = Compatibility{
	Name: Cancer + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "65%",
		Traits:  []string{CautionRomance},
		Summary: "En este terreno Cáncer y Sagitario pueden llegar a tener una larga y fructífera amistad si descubren a tiempo las cosas que les unen y también procuran evitar o suavizar todas aquellas que les separan por razones de carácter.\n \nA Cáncer le enamoran las posibles aventuras y los proyectos de los que siempre habla Sagitario.\n \nSin embargo, pronto se cansará de tanta movida y mostrará temor a correr riesgos innecesarios que le hagan perder su valorada estabilidad.\n \nA Sagitario, por su parte, le atrae la calidez y la ternura que halla en Cáncer, pero percibe muy pronto que no será fácil convencerle para que venza sus temores y hacerle ver que su resistencia al cambio le perjudica.\n \nA Sagitario le gusta introducir cambios en sus relaciones y en su vida en general y esto es quizá lo que más teme el cangrejo, que detesta cualquier cambio.\n \nCáncer y Sagitario lograrán estabilidad en su relación de amistad casi siempre, aunque no compartirán demasiados proyectos, viajes, vacaciones, aventuras… Sin embargo, tanto Cáncer como Sagitario sabrán que tienen ahí a alguien en quien confiar plenamente en cualquier situación.\n \nLa lealtad presidirá esta relación un tanto dispar pero que puede perdurar a través del tiempo.",
	},
	Love: Love{
		Match:  "27%",
		Traits: []string{DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "Cáncer y Sagitario suelen ser signos que no se atraen en absoluto. Si la atracción y el amor nacen entre ellos, rara vez tendrán una relación perjudicial para alguno de los dos, porque sus signos están regidos por la Luna y el benéfico Júpiter. Es seguro suponer que serán buenos el uno para el otro, mientras dure su relación, pero es raro que tengan éxito a largo plazo si no cuentan con un fuerte apoyo de posiciones en sus horóscopos personales. Así como Cáncer puede llegar a la profundidad de la fe de su pareja, Sagitario puede ampliar los horizontes de su pareja y hacerla mucho más feliz en su acercamiento al mundo. Si sienten algo el uno por el otro, sería una pena no actuar en consecuencia y perder la oportunidad de crecer pacíficamente.",
			Match: "27%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La naturaleza cambiante de Sagitario puede ser algo difícil de entender para Cáncer debido a su opuesta necesidad de seguridad emocional.\n \nSi la confianza entre ellos se alcanza de cualquier manera posible y se comparten emociones verdaderas, esta característica de una pareja Sagitario se convertirá en un condimento para su vida sexual, en lugar de su fuerza destructiva.\n \nSi tienen suficiente seguridad emocional el uno con el otro, su vida sexual podría ser muy divertida.\n \nCáncer es un signo que exalta a Júpiter, y probablemente hará que su pareja se sienta especial.\n \nPor otro lado, Sagitario hará que las cosas sean ligeras, divertidas, y la pasión y calidez que aportan a su vida sexual podrían ser suficientes para compensar.\n \nAunque pueden parecer apacibles la mayor parte del tiempo, tienen tendencia a aferrarse a patrones seguros cuando se trata de cosas que pueden hacerles sentir vergüenza o inseguridad.\n \nA cambio, Sagitario tendrá que rebajar sus expectativas sobre la propia capacidad de cambio y creatividad sexual de Cáncer, y conformarse con hacer el amor en lugar de una aventura sexual.",
			Match: "40%"},
		Trust: SummaryPercentage{
			Text:  "Sagitario es un signo regido por Júpiter.\n \nLas deidades asociadas a este planeta eran consideradas grandes amantes, siempre a la caza de diferentes mujeres, diosas, ninfas y cualquiera que pareciera lo bastante atractivo.\n \nLa mayoría de las veces, los representantes de Sagitario tienen la necesidad de mostrar sus dotes de seducción a todos los que les rodean y podríamos llamarlo 'complejo de Zeus'.\n \nAunque el signo de Cáncer ama mucho a Júpiter, las emociones le impiden comprender esta necesidad coqueta de su pareja de ganarse el corazón de todos los que le rodean.\n \nEsto no sólo perturbará la confianza de Cáncer, sino que también afectará a la confianza que Sagitario tiene en la comprensión que obtendrá de su pareja.\n \nEsto podría ser la fuente de muchos conflictos y malentendidos, y finalmente podría llevar al punto en que su relación no tenga ningún propósito o futuro.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Ambos signos aspiran al conocimiento puro y duro.\n \nSu amor mutuo por él les dará mucho de qué hablar y una profunda comprensión del razonamiento del otro.\n \nSus mentes necesitan encontrar la síntesis de las cosas que les rodean y sus sistemas de creencias pueden ser bastante similares.\n \nLo maravilloso de su amor mutuo por Júpiter está precisamente en las similitudes entre sus mentes y sus formas de pensar.\n \nCáncer puede parecer un poco lento desde la perspectiva de Sagitario, tanto como Sagitario puede parecer superficial o demasiado 'filosófico' para Cáncer.\n \nEllos pueden superar fácilmente estos problemas si encuentran una pasión que comparten y por lo general si estos dos eligen la misma profesión, tienen muchas cosas de que hablar.\n \nComprenden la mente del otro y el funcionamiento de su cerebro, incluso cuando existe una gran diferencia intelectual entre ellos.\n \nSi por casualidad se enamoran, la comunicación es algo que siempre pueden utilizar como medio para resolver cualquier otro problema que aparezca en el transcurso de su relación.",
			Match: "60%"},
		Emotions: SummaryPercentage{
			Text:  "Como elementos de Agua y Fuego, no encienden realmente la pasión del otro y el amor entre ellos casi nunca será de la misma intensidad, al mismo tiempo o al mismo ritmo.\n \nSagitario es un signo de Fuego mutable y suelen enamorarse rápida y apasionadamente.\n \nPara que su amor dure, su pareja debe sorprenderle e impresionarle a menudo, haciendo que la relación sea emocionante e imprevisible.\n \nCáncer, por su parte, es un signo de Agua, y puede hacer giros bruscos y grandes cambios.\n \nLos Cáncer siguen su percepción de las situaciones y las personas, y necesitan tiempo para construir una relación en la que se sientan lo bastante seguros como para compartir emociones.\n \nCuando el amor sucede entre ellos, generalmente Sagitario lo siente primero, quiere entrar y salir y entrar y salir suficientes veces para que Cáncer se dé cuenta de que no pueden construir esta sensación de seguridad para siquiera considerar su relación un amor verdadero.\n \nSi quieren construir un amor que dure, la pareja de Sagitario tendrá que ir más despacio y esperar a que su pareja decida cómo se siente.\n \nA cambio, Cáncer tendrá que dar un salto de fe y lanzarse a una relación que no ofrece ninguna seguridad, para ver si se puede encontrar suficiente amor entre ellos para que puedan permanecer juntos.",
			Match: "10%"},
		Values: SummaryPercentage{
			Text:  "Aunque valoran cosas distintas y características diferentes en las personas que les rodean, tienen un fuerte vínculo en la forma en que valoran el conocimiento.\n \nCáncer valorará la honestidad de Sagitario y su capacidad para actuar por impulso emocional, aunque no entienda la emoción que hay detrás del acto.\n \nSagitario valorará la dedicación de Cáncer a las cosas que ama y su increíble capacidad para la compasión.",
			Match: "45%"},
		SharedActivities: SummaryPercentage{
			Text:  "Podrían estudiar juntos, pero probablemente sería una tortura para Cáncer ver a su pareja pasar de un párrafo a otro, sólo para encontrar lo que realmente buscaba al final de algún libro viejo y luego perder el interés por todo el tema.\n \nSagitario mirará a su pareja como si toda la persona acabara de convertirse en una larga e irritante pausa.\n \nLa forma en que estos signos utilizan su energía es tan diferente que no sólo es difícil encontrar actividades que harán juntos, sino que, lo que es más importante, es difícil que hagan las cosas de forma similar.\n \nEsto podría hacer imposible lo posible y podrían quedar separados para siempre por una simple diferencia en su velocidad.",
			Match: "5%"},
	},
}
