package compatibilities

var Cancerlibra = Compatibility{
	Name: Cancer + " - " + Libra,
	Friendship: Friendship{
		Match:   "40%",
		Traits:  []string{Stormy, PoorAdvisors},
		Summary: "Las diferencias en este ámbito entre Cáncer y Libra son también muy notables por las diferentes maneras de enfocar las relaciones sociales que tienen ambos signos.\n \nMientras que a Cáncer le atrae cultivar la amistad con la gente más variopinta, Libra se muestra mucho más selectivo a la hora de relacionarse socialmente.\n \nTiene que estar seguro de que cada persona es merecedora de su amistad, por ello, aunque las relaciones personales entre Cáncer y Libra pueden ser positivas, el cangrejo no tolerará que Libra quiera inmiscuirse con el resto de gente que considera sus amigos o que éstos queden excluidos de ciertos encuentros.\n \nSi Cáncer hace prevalecer su deseo, Libra se sentirá decepcionado, puede considerarlo una traición y una vez puestas así las cosas serán muy difíciles de arreglar.\n \nPara evitar llegar a estos extremos y conociendo este punto débil de la compatibilidad de Cáncer y Libra en el ámbito de la amistad, será mejor prevenir que curar.\n \nSi ambos consideran que su relación lo vale, las concesiones por ambas partes serán imprescindibles.\n \nSólo si hay voluntad por ambas partes para preservar la amistad, ésta se convertirá en un vínculo sólido, aunque cualquier error por ambas partes puede hacer que salte todo por los aires.",
	},
	Love: Love{
		Match:  "28%",
		Traits: []string{GreatSexualChemistry, Volatile},
		Summary: SummaryPercentage{
			Text:  "Probablemente la mayor restricción en la relación entre Cáncer y Libra está en las cosas que quieren de su pareja.\n \nCáncer quiere a alguien responsable, que le lleve de la mano si es necesario y complemente su naturaleza emocional con el sentido práctico.\n \nLibra quiere a alguien lleno de vida, enérgico, fuerte y con iniciativa para seguir sus ideas.\n \nPueden decepcionarse mutuamente si se crean expectativas equivocadas al principio de la relación.\n \nLa mejor forma de construir un amor duradero es que ambos se aferren a su independencia pase lo que pase.\n \nSi se centran en el amor y se preocupan de las cosas terrenales cada uno por su lado, Cáncer podría 'comprometer' el amor celestial, por mucho que a Libra le gustaría tener una familia.",
			Match: "28%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Ambos signos tienen problemas para aceptar a Marte y esto conduce a una falta de pasión e iniciativa en su vida sexual.\n \nSin embargo, el tacto y el cuidado de Libra pueden calmar a Cáncer.\n \nEsto se debe principalmente al hecho de que Saturno, el regente del signo opuesto de Cáncer, está exaltado en Libra.\n \nAunque puede faltar algo de iniciativa, existe la posibilidad de que Cáncer y Libra funcionen muy bien en su vida sexual si pasan suficiente tiempo juntos.\n \nSin embargo, Cáncer pertenece al elemento Agua y Libra es un signo de Aire.\n \nAunque la pareja de Libra sea extremadamente paciente y agradable, el elemento Aire tiene una velocidad a la que Cáncer puede tener problemas para adaptarse.\n \nLas cosas que les gustaría probar diferirán mucho, ya que Cáncer necesita conexión emocional y Libra necesita contacto, tacto y experiencia antes de emocionarse demasiado.\n \nLibra no suele sentirse inspirado por la naturaleza de Cáncer y normalmente no se enamorará de ellos a primera vista.\n \nSu vida sexual puede ser muy buena si ya comparten emociones profundas, así que lo mejor sería que iniciaran una relación desde la amistad, conociéndose ya hasta cierto punto y compartiendo algunos sentimientos además de la posible atracción.",
			Match: "40%"},
		Trust: SummaryPercentage{
			Text:  "Cáncer puede ser uno de los signos del zodíaco más confiados, pero hay un lado irritante en la naturaleza de Libra al que rara vez permanecen inmunes.\n \nMientras que Cáncer desea una vida familiar tranquila sin interferencias de otras personas, Libra parece no poder mantenerse alejado de otras personas, buscando su afecto y aprobación día tras día.\n \nEn algún momento, su pareja Cáncer tiene que preguntarse si éste es el tipo de pareja con el que quiere tener hijos.\n \nPor otra parte, Libra considera poco realista todo el enfoque que Cáncer da a una relación romántica.\n \nEsto puede conducir fácilmente a una falta de confianza en Libra, especialmente si el Sol está en los grados finales del signo.",
			Match: "30%"},
		Communication: SummaryPercentage{
			Text:  "Como signos regidos por Venus y la Luna, cabe suponer que su relación es, en cierto modo, muy importante.\n \nAunque Libra está a cargo de la naturaleza superior y espiritual de Venus, sigue siendo un signo de relaciones y la Luna sólo enfatizará la necesidad de cercanía y armonía.\n \nSu comunicación no será demasiado difícil, pero existe la posibilidad de que no compartan muchos intereses ni se respeten lo suficiente como para que tenga verdadera calidad.\n \nSu principal problema podría surgir si empiezan a hacer planes poco realistas juntos.\n \nLibra exalta a Saturno, pero no es un signo de Tierra, y por lo general se quedan en el campo de las ideas en lugar de un enfoque práctico de la materialización.\n \nCáncer no entiende cómo alguien puede estar tan alejado de la realidad y esto podría desembocar en un extraño conflicto pasivo que podría poner en peligro toda su relación.\n \nEs importante recordar que Libra tiene un Sol problemático y suele buscar una pareja con más fuego y energía pasional de la que normalmente tiene Cáncer.\n \nPor feo que pueda sonar, necesitan a alguien de quien alimentarse, y normalmente tienen relaciones sólidas con signos de fuego que producen suficiente energía incluso para sus seres queridos, o signos de Aire a los que realmente no les importa.\n \n",
			Match: "50%"},
		Emotions: SummaryPercentage{
			Text:  "Tanto Luna como Venus representan las emociones, y ambos son signos muy emocionales.\n \nSin embargo, su contexto emocional es muy diferente, ya que Cáncer busca un amor en la Tierra y Libra busca a alguien a quien llevar al cielo.\n \nAquí es exactamente donde el lado espiritual de Venus de Libra les quita la verdadera oportunidad de compartir una vida juntos.\n \nEs un Venus que no necesita comer ni dormir, mientras sienta el amor único y equilibrado.\n \nCáncer entenderá esta idea hasta cierto punto, pero probablemente busque una pareja con los pies en la tierra cuando se dé cuenta de que éste es un patrón que no va a cambiar.\n \nComo dos signos cardinales, podrían tener una relación larga e insatisfactoria porque ambos están esperando un momento decisivo que los libere.\n \nEn algunos casos habría que aconsejarles que hagan un cambio si no están satisfechos, y que busquen a alguien que pueda hacerles más felices.",
			Match: "15%"},
		Values: SummaryPercentage{
			Text:  "Como ambos son signos de relaciones -familiares o de pareja-, valorarán una conexión agradable y alegre entre dos personas.\n \nSi la encuentran el uno con el otro, sin duda les costará dejarla ir, comprendiendo ambos que no es tan fácil de encontrar.\n \nSin embargo, todo su sistema de valores difiere mucho más allá del punto de las relaciones, y mientras Cáncer valorará la ternura y el cuidado, Libra valorará la responsabilidad y el amor platónico.\n \nNo suena muy prometedor, ¿verdad?",
			Match: "20%"},
		SharedActivities: SummaryPercentage{
			Text:  "Cáncer y Libra podrían hacer muchas cosas juntos, pero es dudoso que quieran hacerlo.\n \nCáncer es un signo que exalta a Júpiter y, aunque pueden ser perfectamente felices con una pareja gruñona, agradecerían que no tuvieran la necesidad de imponerles su malhumor.\n \nHay un deseo secreto en todo Cáncer de viajar por el mundo, teniendo al mismo tiempo la base segura a la que volver a casa, pero Libra podría desestructurar sus creencias y llevarles a dudas con las que simplemente no quieren lidiar.\n \nCon el temperamento suave y apacible de Cáncer, Libra probablemente se sentirá aún más inadecuado y gruñón, pues necesita que alguien sea su oposición y lo desafíe para tener respeto y carga sexual.",
			Match: "10%"},
	},
}
