package compatibilities

var Cancerscorpio = Compatibility{
	Name: Cancer + " - " + Scorpio,
	Friendship: Friendship{
		Match:   "95%",
		Traits:  []string{GoodRomancePotential, DeepMutualUnderstanding},
		Summary: "Es en terreno donde quizá surjan más diferencias entre Cáncer y Escorpio.\n \nA Cáncer le costará bastante averiguar cómo es Escorpio.\n \nLa amistad es un factor muy importante en la vida de los nativos del cangrejo y tal como les sucede en el amor, tampoco quieren correr riesgos con sus supuestos amigos.\n \nEscorpio, en cambio, se acercará de inmediato a Cáncer, porque ambos comparten una sensibilidad que no es común en otros signos.\n \nPero también muy pronto pondrá de relieve su carácter posesivo y su deseo de ser el centro de atención en la vida de sus amigos.\n \nEste descubrimiento retrasará el inicio de la verdadera amistad entre Cáncer y Escorpio, aunque llegará a producirse.\n \nCáncer necesitará descubrir que los aspectos que les unen son más que los que les separan.\n \nAfortunadamente, la intuición de Cáncer le señalará que no ha de alejarse de Escorpio.\n \nUna vez establecida la amistad, ambos tendrán que hacer concesiones para mantenerla.\n \nEn ocasiones les parecerá demasiado esfuerzo seguir controlando su propia esencia por no perder a un amigo.\n \nEntre Cáncer y Escorpio debería haber mejor comunicación, pero ambos signos guardan muchas cosas dentro que casi nunca asoman a la luz y de este modo resulta difícil establecer la confianza necesaria.",
	},
	Love: Love{
		Match:  "79%",
		Traits: []string{Harmonious, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Una relación entre un Cáncer y un Escorpio puede ir de un extremo a otro, y aunque la pareja Cáncer se esforzará por estabilizarla, podría ser demasiado difícil si Escorpio no tiene suficiente respeto por sus propias emociones.\n \nCuando encuentran un vínculo emocional, pueden profundizar mucho en busca del amor verdadero, y unirse a un nivel inalcanzable para otros signos del zodíaco.\n \nEsto puede hacer que hablen sin palabras, que entiendan los pensamientos del otro con sólo una mirada compartida y que estén sincronizados en su enfoque de su futuro juntos.\n \nSi sus emociones no se comparten en el nivel más profundo posible, o la pareja Escorpio se niega a lidiar con ellas, podría ser demasiado difícil para Cáncer manejar la naturaleza autodestructiva de su pareja.\n \nSu conexión debe ser sincera y pura, para que ambos estén dispuestos a entregarse a este intenso contacto emocional.",
			Match: "79%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "El signo de Escorpio se asocia con la muerte y todo tipo de cosas malas, pero toda su malicia proviene de su represión emocional y sexual. Por lo general, Cáncer puede comprender la necesidad de su pareja Escorpio de expresar sus emociones más profundas y oscuras en su vida sexual. Si la pareja Cáncer no se asusta ni se ve demasiado forzada a hacer algo para lo que no está preparada, una relación sexual entre Cáncer y Escorpio puede ser profundamente satisfactoria para ambos. Esta es una relación de dos signos de Agua y debido a esto su vida sexual necesita reflejar toda su conexión emocional o la falta de ella si la hay. Cuando se enamoran, ambos necesitan expresar sus sentimientos y la intimidad que pueden compartir es increíble. Sin embargo, Escorpio es un signo en el que cae la Luna y ésta es la regente del signo de Cáncer. Si la necesidad de Escorpio de enterrar sus emociones es demasiado intensa, existe una gran posibilidad de que sea demasiado brusco o insensible con su pareja. Esto es algo con lo que Cáncer tendrá dificultades para lidiar y podría llevar a Cáncer a la necesidad de separarse porque podría simplemente cansarse de todos los requerimientos sexuales especiales o agresivos que tiene su pareja Escorpio.",
			Match: "90%"},
		Trust: SummaryPercentage{
			Text:  "Cuando Escorpio se enamora, la confianza es una de las cosas más importantes que busca.\n \nSi se sienten traicionados de alguna manera, pueden empezar a mostrar todos esos lados maléficos de su naturaleza y volverse verdaderamente posesivos y celosos.\n \nLa pareja de Cáncer suele querer a alguien con quien compartir la vida y no tendrá motivos para engañar o mentir a su pareja.\n \nComo todos los signos de agua, ambos podrían temer decir la verdad hasta cierto punto, pero esto no necesariamente tiene que hablar de su infidelidad o del principio del fin de su relación.Por lo general, ambos serán capaces de darse la seguridad suficiente para sentirse seguros y generar la confianza que ambos necesitan para no sentirse heridos o traicionados.",
			Match: "95%"},
		Communication: SummaryPercentage{
			Text:  "Cáncer y Escorpio suelen entenderse sin palabras.\n \nEsto puede influir en su vida sexual y hacerla mucho mejor, o mucho peor, dependiendo de cómo se exprese su necesidad de misterio.\n \nSu comunicación es muy buena, siempre que las emociones no sean el tema principal de la conversación.\n \nPueden terminar las frases del otro si tienen necesidad de hablar.\n \nLa profundidad que ambos tienen, aunque no sea visible al principio en la pareja Cáncer, hace que puedan hablar de cualquier cosa.\n \nEn el caso de que Cáncer quiera huir de las experiencias negativas y Escorpio de sus emociones, podrían tener problemas para formar una relación.\n \nAún así, se trata de una situación muy poco frecuente e incluso si tienen estas tendencias, probablemente se ayudarán mutuamente a lidiar con ellas y se proporcionarán la estimulación mental que ambos necesitan.",
			Match: "99%"},
		Emotions: SummaryPercentage{
			Text:  "Este es un territorio delicado para una pareja como ésta.\n \nCáncer vive enterrado en sus emociones, positivas o negativas, capaz de utilizarlas en su rutina diaria como parte incorporada de su vida.\n \nEscorpio puede tener problemas para entender cómo funciona esto exactamente, porque tienen tendencia a desestimar las emociones, pensando que es la única forma de alcanzar un determinado objetivo.\n \nEl término medio que necesitan encontrar es un lugar en el que ambos sean libres de seguir estas necesidades.\n \nLas emociones tienen que ser una forma de vida, por mucho que puedan interferir en nuestros objetivos.\n \nAmbos deben aprender a perder el control y a recuperarlo para poder dejar que las cosas fluyan y cambien como deben.",
			Match: "70%"},
		Values: SummaryPercentage{
			Text:  "Cáncer valora su paz interior y desea una vida estable con una familia en la que pueda confiar.\n \nEscorpio representa el cambio y lo valora por encima de todo, aunque no sea plenamente consciente de ello.\n \nPuede ser difícil para estos miembros de la pareja coordinar sus personalidades si ambos no son lo suficientemente flexibles para comprender sus diferencias y la profundidad que cada uno de ellos tiene detrás de esas necesidades superficiales.\n \nEscorpio puede temer las emociones hasta la agonía y si Cáncer reconoce esto, podrá acercarse a ellas de la mejor manera posible y descubrir su verdadera necesidad de seguridad y equilibrio emocional.",
			Match: "25%"},
		SharedActivities: SummaryPercentage{
			Text:  "En realidad, no importa lo que hagan Cáncer y Escorpio si ambos se sienten bien el uno con el otro.\n \nTienen que compartir emociones y proteger a sus seres queridos: Cáncer debido a su necesidad maternal de proteger a las personas que aman, y Escorpio para establecer buenos límites sobre lo que creen que es correcto.\n \nSi crean su propio pequeño mundo, pueden encontrarse en cualquier situación juntos, afrontando las cosas como un solo ser.\n \nA Escorpio le suelen gustar algunas actividades peligrosas y a Cáncer le costará adaptarse a ellas, pero si su núcleo emocional es bueno, comprenderán tranquilamente las necesidades del otro, por muy destructivas que puedan llegar a ser.",
			Match: "95%"},
	},
}
