package compatibilities

var Cancercancer = Compatibility{
	Name: Cancer + " - " + Cancer,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{AlmostNothingReally},
		Summary: "La capacidad de este signo de comprender a los demás, garantiza en la amistad de Cáncer y Cáncer un vínculo como el que todo el mundo sueña cuando busca o encuentra a un amigo.\n \nTambién en este terreno su compatibilidad es de las más altas de la rueda zodiacal.\n \nLos nativos y nativas de Cáncer sienten antes de experimentar un pensamiento razonable.\n \nSu sexto sentido les mueve a acercarse a personas afines, por eso comprenderán que comparten su forma de ver la vida, sus aficiones y también sus deseos, aunque por su naturaleza reservada les lleve un tiempo tomar la confianza necesaria para iniciar su amistad.\n \nTambién es cierto que Cáncer y Cáncer compartirán igualmente sus rasgos negativos, aunque no sean demasiado ni muy notables.\n \nCáncer no suele comunicar lo que piensa o lo que quiere a la primera de cambio y esto puede inducir a error a la otra persona, a pesar de que pertenezca al mismo signo zodiacal.\n \nEsto puede crear cierta confusión y a la vez algún reproche porque Cáncer supone que un amigo ha de leer en su mente como en un libro abierto.\n \nEs difícil llegar a esta perfección, aunque entre Cáncer y Cáncer es posible, pero si no sucede, tendrán que aprender a disculparlo.",
	},
	Love: Love{
		Match:  "85%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "Cáncer es un signo de herencia genética y a veces resulta difícil conciliar las predisposiciones genéticas de dos cónyuges Cáncer.\n \nSin embargo, su naturaleza apacible, su capacidad para sentir y tener suficiente compasión el uno por el otro, les convierte en grandes candidatos para el matrimonio, los hijos y todo el escenario de la valla.\n \nSu vida sexual y sus actividades en común podrían sufrir una falta general de iniciativa, energía y movimiento.\n \nPor eso, ambos deberían intentar no caer en una rutina diaria aburrida en la que sólo comen y se sientan frente al televisor nada más llegar a casa del trabajo.\n \nEs importante que tengan suficientes sorpresas tiernas y actividades que construyan su relación física, o podrían acabar insatisfechos y sin entender muy bien por qué.\n \nSi les preocupa este posible defecto de su relación, como dos personas tiernas que son, se las arreglarán para hacer que el otro se sienta de maravilla, aunque eso signifique romper.",
			Match: "85%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando se trata de intimidad, Cáncer es un maestro en conseguirla con la persona adecuada.\n \nSi dos Cáncer se encuentran de verdad, llegarán al núcleo emocional más profundo del otro dentro de su vida sexual.\n \nAun así, Cáncer es un signo en el que Marte cae y no les resulta fácil tener iniciativa.\n \nPara una vida sexual sana, Marte necesita ser fuerte y estos dos no muestran necesariamente esta fuerza.\n \nEs bueno que ambos no necesiten mucha experiencia o conocimientos técnicos en sus encuentros sexuales, porque esto les da la oportunidad de basar su vida sexual exclusivamente en las emociones que sienten el uno por el otro.\n \nPodría ser aburrido desde la perspectiva de algunos otros signos del zodíaco, pero a ellos realmente no les importará si reciben la confirmación de que son amados a través de su contacto físico.\n \nNingún Cáncer se conformará con una vida sentimental aburrida, aunque pueda parecerlo.\n \nLucharán por su familia, por su intimidad y su seguridad, pero no se conformarán con algo que no les entusiasme en absoluto.\n \nPara que la relación de dos de ellos tenga éxito, sería buena idea experimentar un poco y mostrar iniciativa en cualquier momento en que se sientan mínimamente sexuales.",
			Match: "65%"},
		Trust: SummaryPercentage{
			Text:  "Por qué no confiar el uno en el otro cuando a ambos no les importa que les levanten el ego con un adulterio, una pareja más joven o la búsqueda de una historia de amor imposible.\n \nCáncer es un signo bien cimentado, pues su regente está exaltado en Tauro.\n \nQuieren una estabilidad emocional que pueda sentirse en el mundo material y comprenden que la perfección no existe.\n \nCuando encuentren a una persona con la que puedan verse en los años venideros, aceptarán sus defectos y harán los compromisos necesarios para construir una familia amorosa y un hogar para ellos.\n \nSi dos Cáncer se ven así, no tienen motivos para no confiar plenamente el uno en el otro.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Si buscas a un fanático de la comunicación no verbal, busca a Cáncer.\n \nCuando son dos, sobre todo si están en una relación íntima, pueden estar callados durante días mientras su sentimiento interior sea bueno.\n \nAunque disfrutan de la rutina de compartir algunos detalles de la vida con su pareja, su momento favorito del día será probablemente esa taza de café matutina en la que no tienen que hablar en absoluto.\n \nAlgunos de los signos más racionales podrían tener una opinión baja sobre la fuerza intelectual de estos compañeros y podría parecer que no tienen nada que decir.\n \nPero cualquiera que sea un poco más sensible sentirá que se miran con atención indivisa y que siguen los movimientos y las sonrisas del otro.\n \nNo necesitan palabras cuando pueden sonreírse el uno al otro.\n \n¿A quién le importa realmente la comunicación? Puede ser tan obsoleta...",
			Match: "90%"},
		Emotions: SummaryPercentage{
			Text:  "A Cáncer se le suele considerar el signo más emocional del zodíaco.\n \nEn cierto modo es cierto, aunque el protagonismo se lo reparten todos los signos de Agua.\n \nCáncer es el signo del amor familiar y la cercanía, no tanto del amor sensual y sexual que se presenta a través de Venus.\n \nCuando dos representantes de Cáncer inician una relación, comprenderán perfectamente los estados emocionales del otro.\n \nEn sus familias primarias hay un asunto casi inevitable que necesita resolverse, y normalmente se utilizarán el uno al otro para hacerlo.\n \nComo ambos están regidos por la Luna, sus cambios de humor probablemente coincidirán, pero el alcance de las emociones que representa la Luna es mucho mayor de lo que la mayoría de nosotros suponemos.\n \nSon portadores del estado emocional de sus antepasados y no basta con etiquetarlos como simplemente 'emocionales'.\n \nLa mejor relación para dos Cáncer significa formar una familia, pero sólo en el caso de que tengan una buena vida sexual.\n \nTodas sus emociones se comparten, comprenden y tratan mejor cuando comparten un hogar y su vida juntos.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Compartirán los mismos valores y se entenderán perfectamente en este segmento de su relación.\n \nSu similitud sale a relucir justo aquí, donde son libres de valorar la claridad emocional, la paz y una vida tranquila y familiar que alguien es capaz de crear.\n \nEsto podría mantenerlos unidos en una relación amorosa, incluso aunque en un principio no parecieran perfectos el uno para el otro.",
			Match: "99%"},
		SharedActivities: SummaryPercentage{
			Text:  "Como dos compañeros de Cáncer no tienen ningún problema para compartir cualquier actividad, pero podrían darse cuenta de que tienen un problema para empezar una.\n \nMientras su relación es nueva y todo es excitante, ambos compartirán sus ideas sobre cosas que podrían hacer juntos, probablemente cosas de sus rutinas individuales.\n \nCuando la relación se asiente, podrían encontrarse estancados, sin moverse en absoluto, sólo por su naturaleza pasiva que tiene tendencia a pasar una velada acogedora en casa.",
			Match: "55%"},
	},
}
