package compatibilities

var Canceraquarius = Compatibility{
	Name: Cancer + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "25%",
		Traits:  []string{NothingInCommon},
		Summary: "A pesar de sus muy diferentes personalidades, Cáncer y Acuario, cuya tenacidad y perseverancia queda fuera de toda duda, pueden llegar a forjar una sólida amistad que sin ningún género de duda estará plagada de momentos difíciles, incluso de enfados.\n \nSin embargo, ninguno de los dos estará dispuesto a renunciar al verdadero amigo que han descubierto en el otro.\n \nPor su naturaleza, Cáncer intentará llevar a su terreno a Acuario, que siempre se evade de compromisos y proyectos a largo plazo.\n \nSi Cáncer sabe utilizar bien sus armas a la vez que corregir esta tendencia al control y al conservadurismo, a querer que las cosas se hagan según desea, puede conseguir una amistad con Acuario de la más sólidas y duraderas.\n \nAcuario, por su parte, no estará en ningún momento ceder terreno ni libertad, pero puede mostrarle a Cáncer las ventajas que tiene su forma de vivir la vida.\n \nEl intelectual Cáncer, que las caza al vuelo, tomará buena nota y él si que es capaz de mantener su propia esencia pero asumir algunos rasgos ajenos si el resultado es positivo.\n \nCáncer y Acuario podrán tener relaciones de amistad largas o cortas pero siempre súper intensas y gratificantes para ambos, mientras duren.",
	},
	Love: Love{
		Match:  "31%",
		Traits: []string{PoorAdvisors},
		Summary: SummaryPercentage{
			Text:  "Podríamos decir que Cáncer y Acuario no son la típica pareja feliz en la mayoría de los casos.\n \nSu relación puede ser demasiado estresante para la pareja de Cáncer y la falta de intimidad probablemente los separe.\n \nSin embargo, el vínculo entre ellos puede ser realmente maravilloso cuando se encuentra, y podrían abrir nuevas perspectivas tan interesantes el uno para el otro si esto sucede.\n \nAmbos desean aprender cosas nuevas y podrían viajar lejos si se establece una base sólida en casa, para que Cáncer pueda permanecer en paz.\n \nPara que esta pareja avance en una dirección positiva, Acuario tiene que comprender lo inusual que es su pareja, y tratar de experimentar en ser hogareños mientras se divierten.\n \nCáncer tendrá que asumir el grueso de las responsabilidades para aferrarse a la idea de su hogar como base desde la que pueden moverse a donde quieran.\n \nAl final, Cáncer podría descubrir una increíble alegría de la libertad y Acuario podría desarrollar la cercanía.\n \nSi estos miembros de la pareja pueden estar juntos en silencio, saboreando su café matutino, en la mayoría de los casos éste es el primer paso hacia el éxito.",
			Match: "31%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Una relación sexual entre Cáncer y Acuario puede ser estresante para ambos miembros de la pareja.\n \nAunque Cáncer es considerado el signo más sensible del zodíaco, regido por la Luna, pueden ser bastante bruscos y distantes cuando sienten la necesidad de establecer límites fuertes.\n \nAcuario, por su parte, tiene fama de innovador, de hacer el cambio, pero en realidad es un signo fijo, bastante arraigado a sus costumbres y, paradójicamente, inmutable.\n \nCuando se involucran en la actividad sexual, Cáncer podría estar tan estresado que tendrá que establecer esos límites y Acuario no será capaz de hacer el cambio necesario para ser más suave con su pareja Cáncer.\n \nHay demasiada energía en Acuario que necesita ser conectada a tierra a través de su actividad física y esto incluye el sexo.\n \n Si Acuario encuentra la forma de bajar el ritmo y no forzar nada en su pareja, y si Cáncer permite que su mente racional tome el control durante parte del tiempo que pasan juntos, podrían compartir una experiencia sexual excitante.\n \nCáncer aportará emociones y ternura a su vida sexual y Acuario nunca dejará que la aburrida rutina se apodere de ellos.\n \nSi se comprometen a experimentar y a intercambiar emociones, podrían incluso empezar a divertirse.",
			Match: "1%"},
		Trust: SummaryPercentage{
			Text:  "Cáncer suele ser leal y honesto, excepto en situaciones en las que teme la reacción agresiva de la persona amada o hacerle mucho daño.\n \nCon Acuario, podrían sentirse estresados para compartir cosas y esto podría presentar un problema en ambos sentidos cuando se trata de la confianza.\n \nLa naturaleza liberal de Acuario podría parecer una locura para un Cáncer, y la sinceridad de su pareja acerca de sus locuras no ayudará al sentimiento interno de desconfianza por sus posibles acciones.\n \nEs algo complicado para ellos, porque ninguno quiere mentir, pero aun así no parecen confiar en el futuro que podrían compartir.",
			Match: "35%"},
		Communication: SummaryPercentage{
			Text:  "Cáncer y Acuario son capaces de unir sus fuerzas en la actividad intelectual.\n \nLa mente de un Cáncer es lo bastante sensible como para prestar atención a los detalles y a las relaciones interpersonales cuando Acuario no lo hace.\n \nPodrían hacer realidad grandes ideas, especialmente aquellas que necesitan de mucha gente involucrada en su camino para convertirse en realidad.\n \nSin embargo, podrían tener problemas para hablarse en el mismo tono o para entenderse en primer lugar.\n \nCáncer está regido por la Luna, el cuerpo celeste más rápido del cielo, pero no son rápidos para reconocer lo que se esconde tras las palabras de Acuario.\n \nA Acuario le cuesta expresar su estado interior y esto es algo que a Cáncer le cuesta entender.\n \nEl mejor comienzo de su relación está garantizado si Acuario ve a su pareja Cáncer como un ser humano extraño que necesita ser examinado.\n \nEsto les permitirá a ambos el espacio suficiente para conocerse bien, y esto podría influir en todas las demás áreas de su relación.\n \nSi esto sucede, Acuario se acercará a esas actividades extrañas que Cáncer necesita como si no fueran ordinarias en absoluto.\n \nAl fin y al cabo, no todo el mundo puede tomarse un café matutino en total silencio con su pareja y disfrutar de ese silencio tanto como estos dos.",
			Match: "55%"},
		Emotions: SummaryPercentage{
			Text:  "La naturaleza poco convencional de Acuario interfiere con la necesidad de Cáncer de permanecer en un entorno tranquilo, y esto es algo que les resultará difícil de conciliar.\n \nEsa sensación hogareña y acogedora que Cáncer necesita puede verse profundamente perturbada por el rebelde signo de Aire de Acuario.\n \nTraerán estrés y demasiada información a su vida, y velocidad que no puede ser manejada por un sutil estado de profunda empatía con el que Cáncer tiene que vivir a diario.\n \nLa forma en que muestran el amor es muy diferente, pero puede estar maravillosamente centrada en sus hijos y en la familia que construyen si llegan a este punto.\n \nNo hay ningún signo del zodíaco predestinado a una vida familiar como Cáncer.\n \nEn una relación con Acuario, ellos asumirían la mayor parte de las actividades y responsabilidades cotidianas.\n \nCuando se enamoren, no se apresurarán a poner fin a su relación.\n \nAcuario lo afrontará como una especie de reto y comprenderá la estabilidad y el amor que obtiene de esta pareja.\n \nCáncer se dará cuenta de que nunca ha sido tan libre de ser él mismo, en lugar de vivir en una relación simbiótica en la que se ve absorbido con facilidad.\n \nUna vez que formen un vínculo fuerte, será muy difícil para ambos dejarlo ir.",
			Match: "50%"},
		Values: SummaryPercentage{
			Text:  "Cáncer valora el conocimiento casi tanto como Acuario la información.\n \nSe trata de una fina conexión entre sus mundos y, si se cultiva, podría ser suficiente para que no se distancien por otros valores a los que se aferran.\n \nCáncer valora la estabilidad, la intimidad y la familia, mientras que Acuario valora su libertad, el intelecto y las nuevas tecnologías.\n \nHay una diferencia entre sus mundos que podría parecer imposible de superar, pero si se aferran a su amor por las distancias y los viajes o si aprenden juntos, podrían superar fácilmente el hecho de que sus valores en otras cosas difieran tanto.",
			Match: "10%"},
		SharedActivities: SummaryPercentage{
			Text:  "Mientras Cáncer querrá quedarse en casa, ir de picnic al parque o a una tienda de muebles, Acuario buscará el rascacielos más alto, deseará un portátil nuevo y leerá cualquier cosa que caiga en sus manos.\n \nLa actividad clave que podría conectarles de verdad es viajar.\n \nAunque Cáncer parece hogareño e inamovible, esto no es exactamente cierto.\n \nAl ser un signo de exaltación de Júpiter, querrán viajar lejos.\n \nAcuario siempre querrá subirse a un avión y sería perfecto si pudieran saltar en paracaídas hasta un lugar donde Cáncer aterrizara a salvo en un Boeing 747.",
			Match: "25%"},
	},
}
