package compatibilities

var Cancerpisces = Compatibility{
	Name: Cancer + " - " + Pisces,
	Friendship: Friendship{
		Match:   "100%",
		Traits:  []string{GoodRomancePotential, DeepMutualUnderstanding},
		Summary: "La relación de amistad entre Cáncer y Piscis durará toda la vida, incluso sin que se lo propongan.\n \nSi en algún ámbito pueden superar a la cuestión sentimental, es en de la amistad, intensa y profunda hasta límites insospechados.\n \nDe todas formas, que nadie espere ver a Cáncer y Piscis pegados como si fueran siameses, no, lo suyo trasciende al aspecto físico y se adentra en el mundo espiritual.\n \nTanto Cáncer como Piscis se considerarán como hermanos y no les hará falta verse cada día ni estar en contacto continuamente para mantener esta sólida unión.\n \nConecta muy bien por su disposición a aprender del otro y apoyarle en todo.\n \nCáncer aporta seguridad a la relación, mientras que Piscis es el generador de ideas, es innovador y se siente libre en la toma de decisiones.\n \nCáncer, en cambio es más meticuloso y necesita seguridad antes de lanzarse al ruedo.\n \nSe escucharán siempre el uno al otro y esto revertirá en una relación con pocos fracasos y muchos aciertos.\n \nSólo discreparán en la forma de divertirse porque Cáncer es mucho más conservador que Piscis en este terreno, pero dejará que su amigo le convenza de que de vez en cuando es positivo romper las reglas.",
	},
	Love: Love{
		Match:  "72%",
		Traits: []string{Harmonious, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Como dos signos de Agua, Cáncer y Piscis conectan a través de las emociones, normalmente en cuanto se miran.\n \nSe trata de una de las combinaciones de signos del zodiaco típicas del amor a primera vista.\n \nSu principal reto se esconde en la naturaleza cambiante del signo de Piscis, no porque esté ahí, sino porque pueden temer mostrarla.\n \nSu mayor problema radica en el hecho de que dan prioridad a diferentes tipos de amor en su vida.\n \nSi la pasión y el amor sensual y sexual no están presentes, Piscis rara vez se sentirá satisfecho con el amor que recibe de su familia, y Cáncer encontraría muy deprimente una vida sin nido familiar.\n \nHay que lograr un delicado equilibrio entre entusiasmo y estabilidad, y podrían ser una de las parejas más maravillosas del zodíaco: Cáncer inspirado y Piscis con aire de hogar.",
			Match: "72%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cáncer y Piscis casi siempre están unidos por un amor romántico.\n \nSu conexión sexual suele ser principalmente emocional.\n \nPiscis puede parecerle un poco raro y pervertido a Cáncer, pero deben tener un sentimiento mutuo lo suficientemente fuerte como para que ambos enriquezcan su relación sexual con su propia calidad.\n \nCáncer aportará intimidad a su vida sexual y el significado que hay detrás del acto.\n \nCuidará a su pareja y se preocupará por su placer, ofreciéndole un enfoque estable y seguro para una vida sexual sana.\n \nPiscis aportará cambio, creatividad, inspiración y probablemente mucha sensualidad debido a que es el signo que exalta a Venus.\n \nLa belleza de esta conexión reside en la emoción que comparten y en la forma en que se aprecian y respetan mutuamente su sensibilidad.\n \nSu principal problema puede surgir porque Cáncer puede ser un tanto tradicional en lo que respecta al sexo y Piscis no lo entiende muy bien.\n \nLa necesidad de Piscis de conectar y sentir amor es mayor que cualquier tipo de regla que la humanidad pueda haber establecido para el amor.\n \nSin embargo, en la mayoría de los casos serán lo suficientemente tiernos como para inspirar a su pareja Cáncer a dejar de lado sus actitudes rígidas y su vergüenza.",
			Match: "85%"},
		Trust: SummaryPercentage{
			Text:  "Menos mal que Cáncer no suele ser agresivo ni prepotente, o podría conseguir fácilmente la deshonestidad de Piscis como respuesta a su tendencia a crear intimidad y un hogar feliz a cualquier precio.\n \nLos Piscis no entienden realmente el matrimonio excepto como parte de un final de cuento de hadas o por todo ese encaje, y Cáncer normalmente querrá una boda como coronación de una relación amorosa.\n \nEsto podría ser reconocido como presión hasta cierto punto y esto podría llevar a que la pareja Piscis se asuste.\n \nCuando Piscis se asustan, que de alguna manera no decir la verdad, incluso en cosas tontas en su vida, porque sienten la necesidad de distanciarse de cualquier presión que puedan sentir.\n \nEs bueno que Cáncer entienda esto y separe fácilmente las mentiras de la intimidad.\n \nSea cual sea la situación, probablemente ambos tendrán la paciencia suficiente para confiar el uno en el otro lo suficiente como para que su relación funcione.",
			Match: "70%"},
		Communication: SummaryPercentage{
			Text:  "Tan cambiantes como son los Piscis, siempre tienen algo de qué hablar.\n \nEsto puede resultar inspirador o irritante para Cáncer, que tal vez preferiría tratar con 'información real'.\n \nNormalmente se comunican bien, pero hay situaciones en las que podrían flotar en una idea hecha de palabras.\n \nCáncer busca a alguien con claridad sobre la utilidad y el sentido práctico de todo lo que menciona.\n \nPiscis es todo menos centrado en la practicidad en la mayoría de las situaciones cotidianas.\n \nSi la pareja de Piscis aprende a ser más silenciosa, confiando en sus sentimientos, y empieza a luchar por lo que desea, podría arrasar con Cáncer.\n \nDesgraciadamente, su relación no durará mucho si se limitan a hablar pero no siguen los hechos.\n \nDespués de todo, el signo opuesto de Cáncer es Capricornio, y necesita una pareja capaz de utilizar las cosas, las situaciones y las emociones de forma constructiva.",
			Match: "85%"},
		Emotions: SummaryPercentage{
			Text:  "Cáncer puede comprender mejor que nadie la naturaleza sensible de su pareja Piscis.\n \nTodo lo que parece fácil y positivo puede tener una nota negativa oculta en el mundo de Piscis, y Cáncer siente más que escucha, lo que le convierte en un compañero perfecto para alguien como Piscis.\n \nCuando perciban esta profunda comprensión, la pareja Piscis devolverá el favor con una ternura absoluta y finalmente se abrirá a su pareja Cáncer.\n \nCuando encuentren este punto compartido de intimidad en el que se comparten las emociones verdaderas, esto afectará a todos los demás segmentos de su relación y será un combustible para que tenga un final de cuento de hadas.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Aquí es donde las diferencias de carácter se hacen realmente patentes.\n \nPor mucho que ambos valoren ser amados y cuidados, Cáncer valorará una situación emocional estable y un hogar acogedor al que acudir, mientras que Piscis probablemente valorará más cualquier posibilidad de una montaña rusa emocional.\n \nSuele decirse que los Piscis idealizan a sus parejas y las distintas cosas de la vida, pero en realidad se deprimen cuando no hay magia y belleza perfecta a su alrededor.\n \nSi su día a día con una pareja Cáncer se convierte en algo parecido a una rutina aburrida, encontrarán la forma de huir, encontrar un amante o crear cualquier tipo de circunstancias verdaderamente excitantes.",
			Match: "25%"},
		SharedActivities: SummaryPercentage{
			Text:  "Cuando se conozcan y comiencen su relación, probablemente tendrán muchas cosas que hacer juntos.\n \nUna relación con una pareja Piscis siempre es excitante e inspiradora, y Cáncer le dará fuerza, estabilidad y raíces.\n \nAl principio, esto puede parecer un gran arreglo, pero con el tiempo, Piscis podría querer demasiada actividad para lo que la pareja de Cáncer realmente necesita.\n \nEsto no sería un gran problema si se lo dijeran a su pareja sin temor a que alguno de los dos salga herido.\n \nSi comienzan a torcer la verdad, Cáncer sentirá que su confianza comienza a desvanecerse y esto podría comenzar una serie de problemas entre ellos, que podrían haber sido fácilmente evitados.",
			Match: "70%"},
	},
}
