package compatibilities

var Cancervirgo = Compatibility{
	Name: Cancer + " - " + Virgo,
	Friendship: Friendship{
		Match:   "98%",
		Traits:  []string{DeepMutualUnderstanding, GoodRomancePotential, ExcellentAdvisors},
		Summary: "Cáncer y Virgo tendrán que hacer complementarias sus diferencias para conseguir que una relación de amistad entre ellos funcione.\n \nSin embargo, lo conseguirán en numerosas ocasiones con una facilidad pasmosa.\n \nVirgo es una de las mejores personas con quien se puede cruzar Cáncer.\n \nEl carácter altruista del primero y su deseo de comprender a los demás será crucial para que el nativo o nativa de Cáncer salga de su caparazón y le entregue su amistad.\n \nClaro que esto no sucederá a la primera de cambio.\n \nComo tampoco Virgo podrá apreciar de entrada el carácter bondadoso y alegre de Cáncer.\n \nAmbos necesitarán tiempo para forjar los cimientos de su amistad, pero una vez establecida será indestructible.\n \nCáncer y Virgo serán de la clase de amigos que quedan y se llaman con frecuencia.\n \nSi alguna vez surge entre ambos una discusión, ambos harán lo posible para que las cosas vuelvan a su sitio y su amistad no se resienta.\n \nLa reconocida paciencia de Virgo y su deseo de escuchar el punto de vista de los demás será clave para que la reconciliación se produzca, ya que Cáncer, más retraído, no lo haría con la suficiente rapidez para que la relación no sufra consecuencias.",
	},
	Love: Love{
		Match:  "77%",
		Traits: []string{Harmonious},
		Summary: SummaryPercentage{
			Text:  "Cáncer y Virgo pueden tener una conexión maravillosa y suelen estar unidos por el entendimiento sexual.\n \nEl principal problema de su relación está en el posible conflicto entre el emocional Cáncer y el razonable Virgo.\n \nSi consiguen superarlo, aceptando los defectos del otro y aprendiendo a incorporar algo de racionalidad o de emoción a sus vidas, podrían acabar en una relación inspiradora que durará mucho tiempo.\n \nEn cierto modo, se complementan tanto como el corazón complementa a la mente.\n \nSi comparten una chispa de amor, sería una pena perder la oportunidad de ser felices sólo por las expectativas irracionales o el corazón cerrado de alguien.",
			Match: "77%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando Cáncer y Virgo se juntan, hay potencial para un gran amor eterno.\n \nTienen la posibilidad de convertirse en un contacto inspirador de corazón y mente, si tan sólo se dan la oportunidad de entrar en el mundo del otro.\n \nSu relación sexual parece ser una conferencia sobre la emoción.\n \nEl signo de Virgo lleva a Venus a su caída y sufre de una falta general de emoción.\n \nEs un signo racional con mucho que analizar, que rara vez cede al primer impulso o a su frágil estado emocional.\n \nDeben aprender a sentirse lo suficientemente seguros como para bajar la guardia y cerrar su mente para sentir y disfrutar del sexo.\n \nCáncer no comprende realmente cómo alguien puede tener problemas para entrar en contacto con sus emociones y puede tener expectativas poco realistas por este motivo.\n \nAprenderán a comprender mejor a su pareja y a establecer un vínculo sexual más fuerte, dándose cuenta de lo diferentes que pueden ser las personas.",
			Match: "95%"},
		Trust: SummaryPercentage{
			Text:  "Si alguien puede ayudar a Virgo a fomentar su confianza, es su pareja Cáncer.\n \nAunque Cáncer es un signo cardinal, son estables por naturaleza, especialmente cuando se trata de decisiones emocionales que han tomado.\n \nSi han elegido a Virgo para ser su pareja amorosa, no tendrán motivos para mentir o engañar.\n \nEste comportamiento sólo pondría en peligro su visión de una vida compartida y una familia amorosa que desean con la pareja que eligieron.\n \nEsta es también una razón por la que Cáncer no tendrá un problema inicial para confiar en Virgo.\n \nSus convicciones son más fuertes que sus dudas.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Esta es una faceta delicada de una relación para una pareja de Cáncer y Virgo.\n \nLa falta de palabras de Cáncer ciertamente deja espacio para todo lo que Virgo quiere decir, pero como signos regidos por la Luna y Mercurio, tienen un simple conflicto de emoción versus lógica.\n \nAunque Virgo representa el lado con los pies en la tierra de Mercurio y eso le facilita mucho la comunicación con alguien como Cáncer, sigue apoyándose demasiado en su racionalidad y no en su corazón.\n \nSin embargo, ambos planetas rigen el cerebro humano: Mercurio representa el núcleo y la Luna rige el resto.\n \nPor eso, cuando sus temas y sus fortalezas intelectuales se combinan de forma correcta, y con sus emociones para seguirles, encuentran un territorio inexplorado y nuevo en el que ninguno de ellos ha estado nunca.\n \nSu comunicación puede llegar a ser realmente inspiradora y mágica si aceptan plenamente el carácter del otro.",
			Match: "60%"},
		Emotions: SummaryPercentage{
			Text:  "El lado racional de Virgo podría mantener muy bajo su estado emocional general.\n \nSi Cáncer empieza a mostrar sus emociones abiertamente y sin restricciones, Virgo podría asustarse y empezar a analizar cada pequeña cosa para determinar si realmente existe alguna emoción.\n \nProbablemente no haya mayor rechazo para un Cáncer que alguien que racionaliza sus propias emociones.\n \nComo si la lucha por mantenerse a flote entre la raza humana no fuera suficiente, ahora tienen que lidiar con una pareja neurótica que los descarta.\n \nEl lado emocional de Virgo es un lado profundamente femenino, que suele avergonzarse de mostrar su rostro, especialmente si la pareja de Virgo es masculina.\n \nLes resulta casi imposible sentir algo si se sienten presionados de algún modo o sienten desconfianza con su pareja.\n \nVirgo prefiere estar solo, con un libro correcto, que con la persona equivocada, y hace falta mucha paciencia y racionalidad por parte de su pareja si quiere comprender y esperar a que se derrita el hielo.\n \nSi Cáncer consigue hacerlo, no hay razón para que ambos no resuelvan juntos cualquier otro asunto emocional que necesiten resolver, mutuo o individual.",
			Match: "65%"},
		Values: SummaryPercentage{
			Text:  "Si forman una relación verdaderamente funcional y hermosa, se valorarán mutuamente.\n \nA Virgo, su pareja Cáncer le parecerá mucho más realista y racional que ellos, y para Cáncer, su pareja Virgo tendrá una reconocida debilidad en su corazón.\n \nLas otras cosas no importarán mucho cuando se encuentren, porque no hay compromiso que ambos no harían para mantener este amor.\n \nSin embargo, sus diferentes valores podrían representar un obstáculo para que lleguen a este punto en una relación.\n \nComo signo profundamente emocional y el más inteligente del zodíaco, uno de ellos valora la familia, el amor y la comprensión, y el otro el intelecto, la atención a los detalles y su salud.\n \nNo es que no tengan un punto de encuentro, pero no será fácil encontrarlo si ambos se aferran obstinadamente a sus costumbres y opiniones.",
			Match: "50%"},
		SharedActivities: SummaryPercentage{
			Text:  "Aunque Virgo es un signo mutable y pueden ser bastante difíciles de seguir, pertenecen al elemento Tierra y serán capaces de esperar a que su pareja Cáncer decida si quiere unirse a ellos o no.\n \nMuy a menudo se trata de una relación de dos personas que pueden arreglárselas sin el otro, por lo que no estarán tan atados por las actividades compartidas como podrían estarlo otros signos.\n \nSi uno de ellos quiere hacer algo, a menos que se sienta realmente inseguro, no se tomará como un insulto personal que su pareja no quiera hacer lo mismo.\n \nAquí es donde su compatibilidad racional será realmente útil, ya que organizan su tiempo juntos.\n \nPor lo general, habrá suficiente movimiento y romanticismo para que ambos se sientan especiales y, desde luego, ésta no es la principal preocupación de su relación.\n \nAl fin y al cabo, ambos irían encantados al cine y comerían palomitas, así que siempre hay algo que pueden hacer juntos, aunque sus necesidades sean muy diferentes.",
			Match: "90%"},
	},
}
