package compatibilities

var Cancercapricorn = Compatibility{
	Name: Cancer + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{GoodRomancePotential},
		Summary: "Tanto Cáncer como Capricornio perciben la amistad como algo profundo e intenso, o por lo menos es lo que buscan ambos.\n \nPrincipalmente por este motivo es por lo que Cáncer y Capricornio están destinados a ser grandes amigos.\n \nCáncer valora mucho la franqueza, que no le oculten nada y esto lo encontrará en Capricornio, a quienes les interesan las cualidades que se mantienen a lo largo del tiempo y también se resiste como Cáncer a los cambios.\n \nSi entablan una relación de amistad será para vivirla sin sombras ni amenazas, seguros de que en el otro tienen un buen amigo.\n \nCáncer busca apoyos de las más variadas índoles en sus amigos y el signo que mejor responde a esta necesidad es Capricornio.\n \nLa idea de Cáncer y Capricornio de que las relaciones que valen la pena se cultivan con paciencia y tiempo, será un punto de partida para alcanzar esta amistad casi perfecta y en la que ambos encontrarán en el otro un puntal para cualquier asunto que cause su preocupación.\n \nPor otra parte, el inseguro Cáncer encontrará en Capricornio un soporte inigualable para cualquier contingencia porque el carnero siempre tiene un plan para los peligros o los malentendidos.\n \nSu amistad será firme y sincera.",
	},
	Love: Love{
		Match:  "84%",
		Traits: []string{NaturalPartners, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Cáncer y Capricornio suelen estar destinados a revivir la historia de amor de alguien que vivió antes de su tiempo.\n \nEsta necesidad profundamente sembrada de reparar lo que está roto en nuestro árbol genealógico es algo que todos llevamos dentro, pero estos signos solares están predestinados a manejar deudas kármicas y emociones residuales de sus familias.\n \nTendrán que ocuparse primero de los problemas si quieren liberarse del pasado, y sólo después de haber reparado lo que había que reparar, podrán elegirse de verdad el uno al otro.\n \nEn la mayoría de los casos se trata de un amor único en la vida para ambos miembros de la pareja, y probablemente se elegirán el uno al otro sin ninguna duda.",
			Match: "84%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cáncer y Capricornio son signos opuestos y existe una fuerte atracción entre ellos. Cuando se juntan, se despierta la pasión y ambos se convierten en amantes perfectos el uno para el otro. La paciencia que Capricornio tiene con su pareja es algo que Cáncer realmente necesita para relajarse y empezar a sentirse sexual. Capricornio necesita a alguien que actúe con verdadera emoción, pero también a alguien que no se tome el sexo a la ligera. Hay representantes de Capricornio que han cambiado muchos socios, pero probablemente nunca se quedará con el que no está orientado a la familia y emocional cuando se trata de relaciones físicas. Intimidad Cáncer puede crear es exactamente compatible con lo que Capricornio carece. Hay una falta de amor, hogar y calidez en el signo de Capricornio, y la pareja de Cáncer puede curar esto con su enfoque altamente compasivo. Esto podría conducir a la descongelación del estado emocional de Capricornio y elevar el estado de su vida sexual de manera significativa.",
			Match: "99%"},
		Trust: SummaryPercentage{
			Text:  "Aunque Capricornio pueda parecer confiado, probablemente sea uno de los signos menos confiados del zodíaco.\n \nNo sólo el signo de Piscis en su tercera casa representa su forma de pensar, sino que también suelen dejarse llevar por el pánico en sus relaciones íntimas.\n \nCuando un representante de Capricornio se enamora, comprenderá que su pareja necesita ver confianza y eso es lo que demostrará.\n \nSin embargo, podrían tener problemas para creer cualquier cosa que diga su pareja hasta que se demuestre cierta coherencia o se comprueben sus historias con otras personas.\n \nPor suerte, en el mundo de Cáncer no suele haber nada tan feo y reservado que encontrar, pues sus valores morales son tan altos como la exaltación de Júpiter en su signo.\n \nMientras Cáncer sienta la devoción de Capricornio, no cuestionará sus actos.\n \nPor eso Cáncer podría percibir fácilmente la falta de confianza de su pareja, fingir que no se ha dado cuenta y encontrarlo entrañable en lugar de repulsivo.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Se trata de una pareja que tiene lo más extraño en común: la genética.\n \nNo literalmente, claro, pero a menudo comparten la imagen de una relación que tuvieron sus parientes lejanos, quizá hace siglos.\n \nHay información en nuestro cuerpo emocional, sobre cada emoción que nuestros antepasados han sentido y no supieron cómo tratar o cómo utilizar.\n \nAquí es donde Cáncer y Capricornio conectan, como signos de la familia de la que venimos y de la familia que crearemos.\n \nEstos signos podrían sentir que se conocen desde antes de conocerse.\n \nSu afecto mutuo les resultará familiar y cálido, como si hubieran crecido en la misma casa, aunque sus circunstancias sean completamente distintas.\n \nEsto podría hacerles capaces de hablar de cualquier cosa, ya que existe una cercanía en la relación de estos dos signos que resulta inexplicable para todos los demás.\n \nSin embargo, si este vínculo emocional no se produce al primer impulso, Capricornio podría ser muy difícil de hablar desde la perspectiva de Cáncer.\n \nNecesitan conectar a un nivel muy profundo, o tendrán objetivos opuestos.\n \nAmbos deberían recordar que si se ven el uno al otro bajo esta luz negativa, probablemente sólo se estén escondiendo de su propio lado opuesto interior, desechando la oportunidad de ser completos.",
			Match: "70%"},
		Emotions: SummaryPercentage{
			Text:  "Cáncer y Capricornio son una historia de amor que tuvieron sus antepasados, a la espera de ser resuelta.\n \nAunque esto podría sonar como un sueño hecho realidad y de hecho podría crear emociones muy fuertes en ambos miembros de la pareja, casi siempre hay una deuda kármica que saldar antes de que puedan decir que son verdaderamente felices juntos.\n \nEstos signos representan el eje de exaltación y caída de Júpiter y es importante comprender que sus estados emocionales están estrechamente ligados a las expectativas que tienen el uno del otro y de su relación.\n \nEstos dos son considerados uno de los signos más y uno de los menos emocionales del zodíaco.\n \nUno de ellos debe orientarse a la familia y el otro a su carrera profesional.\n \nAun así, sus emociones suelen desbocarse en cuanto se miran.\n \nLa profundidad emocional de Capricornio es realmente difícil de alcanzar, pero la pareja de Cáncer puede abordar esto como su desafío en la vida.\n \nCuando se atan el uno al otro, es casi imposible para ellos no casarse, tener hijos y todo el paquete de amor terrenal.\n \nSin embargo, si intentaran cambiarse el uno al otro, podrían absorber mucha de su energía.\n \nLo mejor para ellos es aceptar la personalidad del otro como algo inevitable e imposible de cambiar.\n \n",
			Match: "75%"},
		Values: SummaryPercentage{
			Text:  "Ambos valoran la estabilidad y el sentido práctico.\n \nComo signos opuestos, puede parecer que tienen valores opuestos, pero en realidad no es así.\n \nAmbos necesitan estabilidad en sus vidas y valorarán a las personas que les den esa sensación de seguridad.\n \nEsto es probablemente lo que más valorarán el uno en el otro, la capacidad de ambos para no rendirse ni abandonar, por muy difíciles que se pongan las cosas.",
			Match: "70%"},
		SharedActivities: SummaryPercentage{
			Text:  "Cáncer no es muy exigente en lo que se refiere a las opciones de actividad de su pareja, siempre y cuando no se las impongan o sean demasiado agresivas para su gusto.\n \nCapricornio es cuidadoso y planificará sus actividades con mucha antelación, así ambos tendrán tiempo de adaptarse a la idea o cambiar de opinión si se dan cuenta de que no es lo que quieren.\n \nLes será muy fácil ponerse de acuerdo sobre lo que quieren hacer juntos y encontrar esas actividades, sólo si respetan la personalidad del otro.\n \nCapricornio no querrá ir de compras para decorar la casa, como tampoco Cáncer querrá pasar tres noches sin dormir sólo por un proyecto de trabajo.\n \nSi respetan los límites del otro, el tiempo que pasen juntos será realmente satisfactorio para ambos.",
			Match: "90%"},
	},
}
