package compatibilities

var Capricorncapricorn = Compatibility{
	Name: Capricorn + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{AlmostNothingReally},
		Summary: "Entre dos Capricornio que se hagan amigos, se establecerá una relación no sólo agradable sino también fraterna.\n \nSi consolidan su amistad Capricornio y Capricornio serán casi como hermanos.\n \nTambién en el terreno de la amistad, Capricornio necesitará ir despacio, conociendo al otro poco a poco.\n \nNecesitará la seguridad de que no se equivoca, aunque se trate de otro Capricornio.\n \nCuando se dé cuenta de que su posible amigo tiene tan claras las ideas como él mismo, bajará todas las barreras y le permitirá entrar en su intimidad.\n \nEl agudo sentido del humor de este signo será otra de las características que les unirá y que además les hará sentir mucha complicidad.\n \nCuando Capricornio y Capricornio deciden entregarse mutuamente su amistad, ambos sabrán que cuentan con un amigo incondicional y leal como nadie.\n \nLo único que deben tener en cuenta es que ninguno de los dos toleraría una traición, o lo que puedan considerar como tal, en este caso liberarse del resentimiento y recuperar la confianza sería una tarea muy complicada.\n \nPor eso Capricornio y Capricornio han de cuidar que entre ellos no existan malentendidos y que la sinceridad sea total, callar por omisión para no causar daño no es nada aconsejable.",
	},
	Love: Love{
		Match:  "62%",
		Traits: []string{DeepMutualUnderstanding, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "La relación de dos socios Capricornio no es realmente ideal.\n \nUn menos puede dar un más con el otro menos, pero estos dos se convierten en todo lo contrario de funcionales en cuanto otro compañero dominante (Capricornio) entra en su vida.\n \nEl juego de superioridad que les costará contener puede convertirse en la corriente principal de su relación, llevándoles hacia un final inevitable.\n \nPara permanecer juntos, necesitan apuntar sus cuernos hacia alguien o algo más, y hacer sitio a la emoción que ambos necesitan para encontrar el equilibrio.",
			Match: "62%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Es difícil decir algo sobre esta pareja, y mucho menos imaginar su vida sexual.\n \nPodemos ver a dos parejas que exaltan a Marte, lo que significa que su libido es fuerte y que tienen la necesidad de seguir sus instintos.\n \nPero también podemos ver a dos personas que se aferran a sus restricciones, que se niegan el derecho a la satisfacción y optan por tomar decisiones racionales cada día.\n \nLa practicidad no va bien con la sexualidad, y mientras que otras parejas pueden despertar su creatividad sexual y formar un vínculo íntimo con ellos, dos parejas Capricornio rara vez se satisfarán mutuamente en un sentido sexual y emocional combinados.\n \nAdemás, su signo es el regente del tiempo, y lo más probable es que su contacto termine en una espera interminable.\n \nA ninguno de los dos les falta iniciativa, ya que ambos exaltan a Marte, pero cuando se trata de tabúes y asuntos carnales, parece que dos Capricornio no pueden llegar al punto en el que realmente se quiten la ropa.\n \nCuando inicien una relación sexual, podrían llegar a uno de los dos extremos.\n \nO bien comprenderán perfectamente las necesidades del otro con muy pocas palabras, o bien se darán de bruces contra la pared cada vez que alguno de los miembros de la pareja desee crear una atmósfera más íntima.",
			Match: "40%"},
		Trust: SummaryPercentage{
			Text:  "¿Por qué no confiarías en un Capricornio si tú eres Capricornio?\n \nProbablemente porque sabes que eres una versión mejor y más honesta de un Capricornio.\n \nExiste una extraña necesidad de competencia entre estas parejas, y esto no les ayudará precisamente a creerse mutuamente ni a confiar del todo en su futuro.\n \nEl problema aquí no se reduce a las mentiras, sino a los silencios que deciden crear.\n \nSi crean ese aire tranquilo pero tenso a su alrededor cuando intentan comunicarse, ambos se cuestionarán hasta el punto de perder de vista quién es realmente su pareja.",
			Match: "80%"},
		Communication: SummaryPercentage{
			Text:  "Hay tanto que discutir entre dos Capricornio.\n \nDurante cinco minutos.\n \nSí, su relación intelectual puede convertirse en una arena de debate, pero lo más probable es que se trate de un torneo silencioso en el que ninguno de los dos pueda ganar nunca.\n \nSi no dicen lo que piensan, analizándose mutuamente como cobayas, no llegarán muy lejos, y su respeto se hará añicos en cuanto esto quede claro para ambos.\n \nEn muchos casos, dos Capricornio ni siquiera sentirán la necesidad de hablarse tanto.\n \nTendrían mucho que decirse, ambos interesados en la vida y la historia del otro, pero con una valla delante que no les da la oportunidad de compartir de verdad.\n \nSi trabajan en el mismo proyecto y se encuentran en una situación en la que tienen que hablar, descubrirán muchas cosas en las que están de acuerdo.\n \nPara construir una relación con la cantidad adecuada de conversaciones significativas, lo mejor es que trabajen juntos y resuelvan las mismas situaciones con una mente compartida.\n \nA medida que vayan resolviendo ecuaciones de la vida el uno con el otro, es posible que empiecen a disfrutar mucho de su comunicación.",
			Match: "65%"},
		Emotions: SummaryPercentage{
			Text:  "El contacto emocional entre dos Capricornio puede ser algo muy interesante.\n \nSon parejas que se apoyan en su falta de emociones la mayor parte del tiempo, tratando siempre de ser fríos, controladores y racionales.\n \nCuando se junten, lo más probable es que reconozcan estas características, pero eso no hará que les moleste menos quién es su pareja.\n \nEs bueno que compartan el mismo enfoque en todas las relaciones, siendo incapaces de abrirse hasta que alguien deje caer la presión y les haga sentir seguros y protegidos para expresar lo que sienten.\n \nSi se enamoran de verdad, necesitarán mucho tiempo para decirlo en voz alta, ya que ambos temen cualquier muestra pública de emoción y tampoco se sienten lo suficientemente seguros para hacerlo en privado.\n \nLes puede salvar una simple palabra de confianza, y su comprensión de la profundidad emocional del otro, que no es fácil de alcanzar.\n \nEl respeto, sin embargo, no les bastará para compartir los sentimientos que necesitan compartirse, y tienden a dejarse estar, en cierto silencio, por esa comprensión que tienen de las similitudes de sus naturalezas.\n \nDesgraciadamente, esto los aleja aún más, ya que luchan por mantenerse en una conexión emocional utilizando sólo sus cerebros.",
			Match: "30%"},
		Values: SummaryPercentage{
			Text:  "Aunque pertenezcan al mismo signo solar, cada Capricornio es un individuo específico con su propio conjunto de valores que deben ser grabados en piedra.\n \nNo es fácil para un Capricornio encontrar a otro Capricornio que los comparta.\n \nLa naturaleza rígida de Capricornio no permite mucha comprensión cuando se trata de comportamientos que 'no están aprobados' y ser Capricornio no excluye a nadie de las ecuaciones primarias que cada uno de ellos establece.\n \nDeberían atenerse a los valores que comparten en lugar de cuestionar los que no.",
			Match: "80%"},
		SharedActivities: SummaryPercentage{
			Text:  "Dos socios Capricornio podría compartir cualquier actividad posible que viene a la mente, pero uno de ellos, o ambos, simplemente no lo hará.\n \nEs difícil determinar por qué cuando tienen el tiempo y la energía, y la única explicación lógica parece ser - por despecho.\n \n¿Quién diría que el leal y responsable Capricornio tiene esta necesidad dentro de su mente y su corazón? Cuando se relajen y se den cuenta de que su pareja no les amenaza, ambos encontrarán muchas cosas que hacer juntos.\n \nAun así, es posible que no comprendan dónde tienen que aparecer y qué es lo verdaderamente importante para su pareja.\n \nSi pierden la cercanía lo suficiente como para perder la comprensión de las necesidades y deseos del otro, es muy probable que tengan que poner fin a su relación y encontrar a alguien un poco más compasivo y apacible.",
			Match: "65%"},
	},
}
