package compatibilities

var Capricornaquarius = Compatibility{
	Name: Capricorn + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "70%",
		Traits:  []string{CautionRomance, MutualRespect},
		Summary: "En el ámbito de la amistad, Capricornio y Acuario muestran algunas semejanzas aunque también alguna diferencia, ya que socializan de forma distinta.\n \nEntre ellos tendrán que llegar a ciertos acuerdos para mantener una relación fructífera y agradable para ambos.\n \nCapricornio tiende a querer mantener el control y la toma de decisiones.\n \nEn este aspecto no encontrará oposición por parte de Acuario, que con un carácter más flexible estará encantado de formar parte de los proyectos de su amigo, se sentirá útil.\n \nCapricornio estará encantado de tener a Acuario, tan emotivo y soñador, como fiel amigo.\n \nCapricornio y Acuario tienen además en común la virtud de resaltar lo mejor de su amigo y saben como motivarse recíprocamente para avanzar.\n \nSe admiran porque cada uno tiene la capacidad natural de hacer cosas que el otro no puede o no se atreve.\n \nUna diferencia que deben pulir Capricornio y Acuario es que el primero sólo está cómodo cuando no tiene demasiada gente cerca, mientras que el segundo necesita relacionarse con cuanta más gente mejor.\n \nSin embargo, Capricornio y Acuario darán a la privacidad de su amistad el valor que merece.\n \nEn esta relación se establecerán estrechos lazos que les harán mostrarse el uno al otro tal cual son, algo que no permiten a todo el mundo.",
	},
	Love: Love{
		Match:  "37%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "Puede que Capricornio y Acuario no se encuentren tan interesantes el uno al otro, para empezar.\n \nAmbos están regidos tradicionalmente por Saturno, pero sus papeles en el zodíaco son totalmente distintos.\n \nSu punto más conflictivo en una relación es el contacto emocional.\n \nSi quieren permanecer juntos, la pareja de Capricornio tendrá que separarse del suelo, sólo un poco, y Acuario tendrá que acercarse un poco más a la Tierra.\n \nNecesitan encontrarse en el medio para que Capricornio pueda ayudar a Acuario a materializar sus ideas, y para que Acuario pueda ayudar a Capricornio a hacer el cambio necesario en su vida y orientarse hacia algo nuevo.",
			Match: "37%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Sería fácil suponer que Capricornio es tradicional y restrictivo, mientras que Acuario es todo lo contrario, pero ambos están regidos tradicionalmente por el mismo planeta y sería absurdo no entender sus similitudes.\n \nEl principal problema en su vida sexual será su ritmo diferente, y esto es causado principalmente por la diferencia en sus elementos.\n \nComo signo de Tierra, Capricornio es lento y minucioso.\n \nUn representante de este signo rara vez se lanzará a una relación sexual sin sentir atracción y respeto por la otra persona, y querrá dar lo mejor de sí mismo cuando finalmente haya sexo.\n \nAcuario es un signo de Aire y esto los hace algo escamosos y poco fiables, aunque están regidos por Saturno, el maestro de la fiabilidad.\n \nQuerrán que las cosas sean espontáneas y rápidas, sin pensar mucho y lo más relajadas posible.\n \nAmbos pueden ser muy apasionados con la pareja adecuada, pero el punto de partida de sus enfoques suele ser demasiado diferente como para que funcione.\n \nAfortunadamente, el respeto que se tienen mutuamente puede hacer que se conviertan en muy buenos amigos y, si consiguen encontrar la forma adecuada de comunicarse, puede que incluso construyan una relación sexual de calidad sobre la base de la amistad.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "¿Por qué no iban a confiar el uno en el otro?\n \nUno de ellos tiene convicciones inquebrantables y la necesidad de no equivocarse nunca ni cometer errores de ningún tipo, mientras que el otro no teme la confrontación y valora demasiado la imagen de la verdad entre la raza humana como para tener el deseo de mentir.\n \nSin embargo, sus ideas sobre la confianza son diferentes, y a ambos les costará aceptar la naturaleza del otro tal y como debe ser.\n \nLa falta de confianza entre ellos no es realmente la falta de confianza que tienen el uno en el otro, sino en la posibilidad de que este tipo de relación funcione.",
			Match: "80%"},
		Communication: SummaryPercentage{
			Text:  "Una relación intelectual entre un Capricornio y un Acuario puede ser algo doloroso de ver cuando eres, por ejemplo, un Tauro o un Cáncer.\n \nTienen este acuerdo distante, frío y silencioso de que ambos son dignos del respeto del otro y esto puede parecer aterrador a veces, ya que se distancian el uno del otro con el fin de permanecer en este acuerdo.\n \nPreferirían no tener ninguna relación antes que mirarse el uno al otro de otra manera, y por ello podrían formar una hermosa y duradera amistad.\n \nAun así, es importante recordar lo diferentes que son.\n \nAunque para Acuario no hay verdadera libertad si no se siguen las reglas de su signo precedente, no les resulta fácil comprender la forma de vivir del otro.\n \nMientras se aferren a los intereses compartidos y a su amor mutuo por la seriedad de su vínculo, podrán mantener la imagen de un fuerte lazo intelectual que los satisfaga a ambos.",
			Match: "65%"},
		Emotions: SummaryPercentage{
			Text:  "El aspecto emocional de una relación entre un Capricornio y un Acuario es algo realmente extraño.\n \nEn las interpretaciones generales se supone que ambos son poco emocionales, distantes y cerrados a la interacción emocional con otras personas.\n \nSin embargo, esta no es exactamente la raíz de su falta de conexión emocional.\n \nComo signo de Tierra, Capricornio necesita que las emociones se muestren de forma física y práctica.\n \nPrecisamente por eso se les describe a menudo como egoístas, que sólo se preocupan de sus propias necesidades.\n \nLos signos más espirituales no aceptan fácilmente que alguien preste tanta atención a las cosas terrenales, como el dinero, o a cualquier valor material u orientado a la carrera profesional.\n \nAcuario pertenece al elemento Aire y es un signo de fe global definitiva, diferente a cualquier religión o regla que un humano pueda haber creado.\n \nNecesitan amor celestial, alguien con quien compartir todas sus ideas, para poder flotar juntos en una nube hacia el País de Nunca Jamás.\n \nNo les importará mucho el dinero, la comida o incluso el sexo, si su elevado espíritu consigue alas y tienen otra oportunidad de soñar.\n \nPara formar un vínculo emocional, tanto Capricornio como Acuario tendrán que aceptar la otra cara de la realidad.",
			Match: "5%"},
		Values: SummaryPercentage{
			Text:  "Capricornio valora los límites y Acuario la libertad.\n \nEntonces, ¿cómo podrían tener una relación amorosa? A veces es fácil olvidar que el signo de Capricornio precede a Acuario y que no habría sensación de liberación sin la suficiente presión.\n \nSus papeles están entrelazados de un modo extraño y podrían descubrir que valoran exactamente las mismas cosas si indagan un poco más en sus personalidades.\n \nPara empezar, ambos valoran la coherencia y la lealtad, y ambos considerarán necesarias todas las evaluaciones humanas estándar de las personas.\n \nCuando se trata de compromisos a largo plazo, eligen sus relaciones sobre las mismas bases y rara vez permiten que otros les controlen.",
			Match: "40%"},
		SharedActivities: SummaryPercentage{
			Text:  "A ninguno de estos signos le falta energía.\n \nCapricornio exalta a Marte y sabe exactamente dónde drenarla, y Acuario no sabe muy bien qué hacer con ella.\n \nAunque no elegirán a menudo las mismas actividades, esto debería ayudarles a seguirse el uno al otro durante el tiempo suficiente para determinar lo que podría gustarles a ambos.\n \nSólo es necesario que la pareja de Acuario no fuerce, insista y acelere, y que Capricornio no inhiba, restrinja y niegue.",
			Match: "25%"},
	},
}
