package compatibilities

var Capricornpisces = Compatibility{
	Name: Capricorn + " - " + Pisces,
	Friendship: Friendship{
		Match:   "100%",
		Traits:  []string{ExcellentAdvisors, GoodRomancePotential},
		Summary: "También en el terreno de las relaciones amistosas Capricornio y Piscis se llevan la palma en cuanto a complementariedad se refiere.\n \nEl temperamental Capricornio se sentirá a gusto desde el minuto cero con el sensible y perceptivo Piscis, que asombrosamente para él sabe captar sus emociones y sus deseos sin necesidad de que se los explique.\n \nPiscis tiene la habilidad de introducirse en la mente y el corazón de Capricornio sin que éste se sienta incómodo.\n \nCon esto ya hay mucho terreno ganado porque precisamente Capricornio pocas veces permite que nadie se inmiscuya en su intimidad, en su Yo más profundo.\n \nPiscis, a su vez, se siente protegido y amparado por Capricornio.\n \nLa firmeza y estabilidad del carnero le dan a Piscis la sensación de seguridad de la que carece y esto le reconforta.\n \nCapricornio y Piscis se sentirán acogidos recíprocamente y no desearán por nada del mundo perder esa amistad que tan bien les hace sentir.\n \nSólo en contadas ocasiones, Capricornio puede cansarse de la sensibilidad de Piscis y considerarlo algo infantil.\n \nPiscis, por su parte, también puede llegar a detestar la inflexibilidad y frialdad de Capricornio en determinados momentos.\n \nNo obstante, esto no será lo habitual ni mucho menos.\n \nEn general el panorama para Capricornio y Piscis es mucho más alentador.",
	},
	Love: Love{
		Match:  "76%",
		Traits: []string{GoodWorkCombination, GreatSexualChemistry, Harmonious},
		Summary: SummaryPercentage{
			Text:  "Una relación entre Capricornio y Piscis cuenta una historia sobre las posibilidades de inspiración.\n \nSi alguien como Capricornio puede dejarse arrastrar a una historia de amor loca, excitante e imprevisible, Piscis deberá hacerlo.\n \nA cambio, Capricornio ofrecerá a su pareja Piscis estabilidad, paz y cierto descanso de sus habituales tornados emocionales.\n \nCapricornio puede ayudar a Piscis a ser más realista y práctico, a la vez que él mismo se siente más alegre y optimista.\n \nAun así, su contacto plantea algunos retos, representados principalmente por su amor a Júpiter.\n \nPuede resultarles difícil conciliar sus diferentes enfoques de la religión, la fe y sus distintos sistemas de creencias.\n \nPara superarlo, lo mejor es que ambos se pregunten: ¿funciona su sistema de creencias? ¿Y funciona también el de su pareja? Si entienden las respuestas a estas preguntas, puede que encuentren el respeto suficiente para dejar intacto el Júpiter del otro.",
			Match: "76%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Probablemente no haya mejor forma de relajarse para un Capricornio que entablar una relación con una pareja Piscis.\n \nSu relación sexual es el contacto de dos individuos poderosos, uno de ellos extremadamente estricto y racional, y otro flexible y emocional, pero seguro de sus creencias.\n \nLas diferencias entre ellos crearán una fuerte atracción, casi como si fueran signos opuestos.\n \nLa vida sexual que pueden compartir estas parejas es inexplicable cuando se observan superficialmente sus caracteres.\n \nPero de una manera diferente a la de Cáncer, Piscis puede llegar a la profundidad emocional de Capricornio por un simple tacto.\n \nNo se trata de compasión, sino de sus profundas verdades interiores.\n \nCapricornio no es impasible, por evidente que sea su frialdad, y Piscis puede ser bastante racional, aunque parezca perdido en la emoción.\n \nSu vida sexual será extrañamente espontánea.\n \nCapricornio se sentirá inspirado para dejarse llevar y abrirse a su pareja, mientras que Piscis aterrizará fácilmente sus afectos y encontrará la forma de mostrarlos a través del contacto físico.\n \nCapricornio se sentirá más despreocupado y Piscis empezará a recogerse.\n \nSi permanecen juntos el tiempo suficiente, podrían formar una mezcla perfecta de estabilidad, confianza y excitación emocional.",
			Match: "99%"},
		Trust: SummaryPercentage{
			Text:  "A menudo se entenderán lo suficientemente bien como para respetar su relación y mantenerla alejada de la deshonestidad.\n \nNo siempre es así, y la posible aspereza de Capricornio puede inducir a Piscis a decir alguna que otra mentira.\n \nPor otro lado, si Capricornio se muestra cerrado e inalcanzable, la confianza se verá perturbada por el simple hecho de que no se conocen del todo bien.\n \nLa belleza de su relación radica en su acercamiento a la confianza cuando se dan cuenta de con quién están tratando.\n \nComo ambos no confían en que el mundo se abra fácilmente, tendrán que ganársela, día a día, el uno al otro.\n \nEsto puede parecer un juego o una competición para ganarse la confianza de su pareja.",
			Match: "85%"},
		Communication: SummaryPercentage{
			Text:  "Si alguien puede inspirar a un Capricornio, es su pareja Piscis.\n \nAmbos pueden preocuparse mucho por la comunicación en su relación, pero su vínculo les permitirá dejar de hablar y empezar a escuchar.\n \nEn cierto modo, ambos son tímidos y, para conocerse, tendrán que prestar mucha atención el uno al otro.\n \nLo bueno es que ambos querrán hacerlo, intrigados por la naturaleza de su pareja, entusiasmados por conocerse en profundidad.\n \nEl problema en su comunicación puede surgir cuando Capricornio cede a sus rígidas opiniones y creencias.\n \nEl signo de Capricornio lleva a Júpiter a su caída, y Júpiter es tradicionalmente el regente de Piscis.\n \nEsto podría poner realmente en peligro toda su relación, ya que la naturaleza estricta y racional de Capricornio puede dañar la fe y las convicciones de Piscis por simple incredulidad.\n \nLa pareja de Piscis rara vez renunciará a su sistema de creencias, ya que es para lo que vive, pero podría cuestionarlo y sentirse sola por la falta de comprensión de su pareja.\n \nEl 'lo que tenga que ser, será' podría convertirse en 'yo decido lo que tendrá que ser' y esto puede sofocar la espontaneidad y la inspiración que la pareja Piscis lleva dentro.",
			Match: "65%"},
		Emotions: SummaryPercentage{
			Text:  "Estas parejas comparten un profundo vínculo emocional que puede construirse durante años hasta que florece de verdad.\n \nEl lado más maravilloso de su relación está en la expectación ante las emociones, el crecimiento constante y su capacidad para sacar lo mejor el uno del otro.\n \nSin embargo, esto no significa que ninguno de los dos vaya a cambiar su forma de ser, aunque serán lo mejor que puedan.\n \nCapricornio podría seguir siendo gruñón, mientras que Piscis podría seguir siendo escamoso y poco fiable.\n \nCuando se aferran demasiado a sus costumbres, pueden acabar molestándose mutuamente, ya que Capricornio apaga las creencias y la magia de Piscis, y Piscis decepciona al fiable y terrenal Capricornio.",
			Match: "90%"},
		Values: SummaryPercentage{
			Text:  "Hay cierta coherencia en su forma de enfocar sus valores.\n \nEs extraño cómo alguien como Piscis puede valorar tanto las emociones estables, pero éstas le ayudan a descansar por fin su mente y su corazón cuando se encuentra en una relación emocional estable.\n \nCapricornio valorará sorprendentemente la capacidad de alguien para estar en contacto con sus emociones y tener una visión clara de un resultado positivo.\n \nDesgraciadamente, tendrán un verdadero problema a la hora de abordar el uso de las creencias y las emociones en la vida cotidiana, y mientras Capricornio valorará el pensamiento frío y la capacidad de ser racional, Piscis valorará todo lo contrario.\n \nA veces serán demasiado diferentes, Piscis soñando con un amor perfecto, Capricornio sabiendo que es imposible, Piscis imaginando un Dios con barba dorada, Capricornio creyendo en este momento, o visitando una iglesia por tradición más que por creencia.\n \nNo será fácil, pero puede que se valoren lo suficiente como para superar sus diferencias.",
			Match: "45%"},
		SharedActivities: SummaryPercentage{
			Text:  "Cuando comiencen su relación, querrán hacer todo juntos.\n \nAunque sus intereses suelen ser muy diferentes, Capricornio se sentirá inspirado para adentrarse en el mundo de Piscis, tanto como Piscis querrá resolver la ecuación dentro de su pareja Capricornio.\n \nCon el tiempo, sus actividades se separarán, a medida que se den cuenta de que las cosas que Capricornio quiere hacer son aburridas para Piscis, mientras que las cosas que a Piscis le gusta hacer, vuelven loco a Capricornio - sin plan, sin intención o cualquier tipo de utilidad aparente.\n \nAún así, ambos tendrán la necesidad de aferrarse a la tradición, Capricornio por respeto a la tradición misma, y Piscis por razones románticas, y esto debería ayudarles a construir suficientes actividades compartidas a medida que pase el tiempo.",
			Match: "70%"},
	},
}
