package compatibilities

var Geminilibra = Compatibility{
	Name: Gemini + " - " + Libra,
	Friendship: Friendship{
		Match:   "95%",
		Traits:  []string{GoodRomancePotential, ExcellentAdvisors, DeepMutualUnderstanding},
		Summary: "Entre las numerosas cualidades que poseen conjuntamente Géminis y Libra está que ambos son ocurrentes, les divierte y estimula compartir ámbitos intelectuales donde interactuar con otros amigos.\n \nEl equilibrio de Libra atrae a Géminis, cuya dualidad le hace ser más inconstante.\n \nPor otra parte, el sentido del humor de Géminis, a veces un tanto rebuscado, gusta muchísimo a Libra porque sabe captar su esencia y nunca lo malinterpreta.\n \nGéminis y Libra en realidad no cuentan con demasiados amigos entre nativos de otros signos, sobre todo porque son muy exigentes a la hora de seleccionar con quién quieren compartir sus ideas o sus ratos de ocio.\n \nSi llegan a entregar su amistad a alguien y esta persona les defrauda, le cerrarán sus puertas a cal y canto.\n \nSin embargo, esto no sucederá nunca entre Géminis y Libra, desde el primer momento ambos tendrán la seguridad de que pueden tener plena confianza en su amigo, a quien confiarán su intimidad como si se tratara de un hermano.\n \nGéminis sentirá que Libra le proporciona cuanto necesita para transitar en paz por la vida y viceversa.\n \nPor eso, la relación de amistad entre ellos surgirá desde los primeros encuentros y tendrá categoría de amistad íntima, de las que son para siempre.",
	},
	Love: Love{
		Match:  "78%",
		Traits: []string{Harmonious, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Géminis y Libra no siempre forman una pareja perfecta, aunque sus signos se apoyan mutuamente.\n \nSi la pareja de Libra tiene problemas para estar sola y hacer cosas por sí misma, esto no es algo que Géminis comprenda fácilmente.\n \nDebido a su falta de límites personales, los representantes de Libra a menudo dejarán que sus socios de Géminis lleven la voz cantante hasta que toda su energía se agote, sientan que sólo deben acostarse y apagar su cerebro.\n \nSi quieren trabajar en su relación y ser felices, Libra necesita respetar a su pareja Géminis lo suficiente como para dejarle ser su maestro, amante y amigo.\n \nA cambio, Géminis tendrá que cuidar de su pareja Libra, respetando sus límites y su necesidad de estar juntos.",
			Match: "78%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Géminis y Libra se guían ambos por el elemento Aire y esto debería darles un buen comienzo para su conexión mental y entendimiento verbal.\n \nCuando se trata de sexo, esto es una ventaja, ya que ambos serán libres de comunicar cualquier cosa que les moleste o les satisfaga.\n \nEl frágil ego de Libra puede ser levantado por el encanto de Géminis y su acercamiento al sexo.\n \nParecen saber cómo hacer que todo sea un poco menos serio y esto ayudará a su pareja Libra abrirse y compartir sus emociones a través del sexo, también.\n \nEl objetivo principal en su vida sexual es, de hecho, equilibrar estas emociones.\n \nLibra es un signo regido por Venus, sexual, sensual y seductor, mientras que Géminis está regido por Mercurio, sin sabiduría sexual ni emocional.\n \nLa base de una buena vida sexual entre ellos es su curiosidad, ya que Libra siempre siente curiosidad por su pareja, tanto como Géminis por todo lo demás.\n \nAunque Libra puede ser indeciso, Géminis no tendrá problemas en pensar en un enfoque diferente y encontrar nuevas técnicas, palabras y aventuras para condimentar sus encuentros sexuales.",
			Match: "80%"},
		Trust: SummaryPercentage{
			Text:  "Cuando Libra decide estar con alguien, aunque sea después de una larga y dura batalla interior, probablemente creerá en sus palabras y en sus actos.\n \nCuando elige a su pareja, lo hace por su carácter y su franqueza.\n \nLibra no tiene motivos para dudar de su propio juicio y probablemente creerá a su Géminis en todos los casos, excepto cuando su falta de honradez sea demasiado evidente.\n \nA cambio, Géminis respetará la necesidad de Libra de coquetear para ser aceptado y querido por otras personas.\n \nNo sólo no lo encontrará amenazador, sino que disfrutará de una consecuencia de este comportamiento: su propia libertad.",
			Match: "95%"},
		Communication: SummaryPercentage{
			Text:  "Géminis es muy obstinado y Libra tiene tendencia a tomarse muchas de las cosas que dice su pareja como un insulto personal.\n \nAunque Géminis, en la mayoría de los casos, seguirá su naturaleza racional y comentará las cosas simplemente porque quiere hablar, a Libra le resultará difícil superar algunas de las cosas que pueda decir.\n \nLibra es muy sensible a cualquier tipo de imposición de voluntad o crítica y la reconocerá incluso cuando Géminis no tenga ni idea de lo que su pareja está imaginando.\n \nComo no hay dos personas que puedan estar de acuerdo en todo cada vez que cada una de ellas abre la boca para hablar, Géminis y Libra pueden tener una comunicación muy hiriente y dura debido a la mutua falta de tolerancia.\n \nUn Géminis preferiría quedarse ciega antes que aceptar que tiene falta de tolerancia.\n \nLa cuestión principal aquí está en el hecho de que Géminis vive para aprender y enseñar lo que ha aprendido.\n \nA menudo se presenta como alguien que sabe cosas, y Libra puede ver esto como su necesidad de demostrar su dominio intelectual.\n \nAunque esta no sea su intención en la mayoría de los casos, a veces una sola frase dicha por Géminis puede ser algo por lo que Libra se sienta herido durante años.\n \n",
			Match: "60%"},
		Emotions: SummaryPercentage{
			Text:  "La forma en que se desarrollan las emociones de Libra es algo realmente adecuado para Géminis.\n \nParecen estar sincronizados mientras la pareja de Libra busca profundidad y Géminis vuela de un lado a otro en busca de un nuevo descubrimiento.\n \nNi siquiera se darán cuenta de cómo empieza a surgir el amor entre ellos, uno corriendo de un lado para otro y el otro pensando en las razones por las que no serían perfectos juntos.\n \nPodríamos decir que ninguno de los dos es muy emocional, pero Libra está regido por Venus, así que aquí hay un fuerte vínculo con una llanura emocional.\n \nEl problema surge cuando ambos hablan demasiado de sus emociones, mientras que ninguno se detiene a sentir realmente.\n \nPueden permanecer distantes y distanciados, a menos que Libra se enamore lo bastante profundamente como para seguir a su pareja Géminis dondequiera que vaya, y Géminis se enamore lo bastante profundamente como para que todas las palabras pierdan significado.",
			Match: "90%"},
		Values: SummaryPercentage{
			Text:  "Mientras que Libra valorará la coherencia y que alguien sea responsable y fiable, Géminis será muy diferente a esto, con valores opuestos también.\n \nGéminis valorará la creatividad y la fuerza intelectual de alguien y esto es algo a lo que Libra no puede responder si su Sol está en su estado más bajo.\n \nSu punto de encuentro está en el valor del intelecto, por extraño que parezca.\n \nAmbos son signos de Aire y prestan mucha atención a la personalidad mental de su pareja y a su forma de pensar.\n \nPodrían encontrar la forma de burlarse el uno del otro con palabras, seducirse y, al final, encontrar la forma de comunicar todo lo demás, en caso de que ambos se preocupen lo suficiente.",
			Match: "55%"},
		SharedActivities: SummaryPercentage{
			Text:  "Libra es el típico camaleón de actividades cuando se enamora.\n \nQuieren examinar el mundo de su pareja, de principio a fin, y le seguirán con gusto en todas sus actividades esperando lo mismo a cambio.\n \nSin embargo, esto puede acabar de forma desafortunada, dejando a Libra con su energía agotada y sus deseos sin cumplir.\n \nA Géminis no le importa seguir a su pareja sólo porque quiere ser seguido.\n \nAmbos deben mantener bajas sus expectativas y dejar que su pareja les sorprenda con algo nuevo y excitante.\n \nDisfrutarán juntos de diversas actividades, pero para ello necesitan, para empezar, respetar los límites y deseos del otro.",
			Match: "85%"},
	},
}
