package compatibilities

var Geminivirgo = Compatibility{
	Name: Gemini + " - " + Virgo,
	Friendship: Friendship{
		Match:   "70%",
		Traits:  []string{AlmostNothingReally},
		Summary: "Géminis y Virgo son dos de los signos más compatibles del zodíaco porque ambos poseen cualidades comunes pero también algunas otras muy complementarias.\n \nCuando saben compartir y coinciden en el punto de equilibrio perfecto, forman una de las amistades más sólidas del zodíaco.\n \nTanto Géminis como Virgo tienen un gran sentido del humor y lo pondrán en práctica ante las dificultades.\n \nEsto quitará importancia a los problemas o por lo menos no los hará parecer insalvables.\n \nGéminis podrá mostrar con Virgo todo su ingenio, con las seguridad de que éste captará todas sus ironías y frases de doble sentido.\n \nEntre Géminis y Virgo en el terreno de la amistad no habrá nunca aburrimiento.\n \nLa capacidad verbal de ambos será también un punto de admiración mutua, ante su inteligencia compartidas.\n \nGéminis y Virgo encajarán ya en el primer contacto y pueden llegar a mantener una amistad muy estrecha, tanto por los rasgos anteriormente descritos como porque se toman los compromisos en serio, y la amistad es uno de ellos.\n \nSi Géminis acepta a Virgo en su vida o viceversa, lo hará de un modo consciente y con la idea de que perdure en el tiempo.\n \nFormarán una amistad sólida que difícilmente se resquebrajará.",
	},
	Love: Love{
		Match:  "40%",
		Traits: []string{Volatile, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "La relación de Géminis y Virgo puede cambiar como el viento, mientras ambos se pierden y se encuentran a diario.\n \nSu amor mutuo por Mercurio es lo que les une y lo que les separa, porque ambos tienden a pensar demasiado las cosas en lugar de seguir a su corazón.\n \nLos dos están sobre todo en sus cabales, cada uno a su manera, y necesitan respetarse hasta el punto de no juzgar la inteligencia de nadie a nivel superficial.\n \nSi se enamoran, se convertirán en una unificación de Mercurio de Aire y Mercurio de Tierra: el cielo en la Tierra.",
			Match: "40%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Géminis y Virgo están regidos por Mercurio, un planeta poco sexual a primera vista.\n \nSin embargo, esto les afecta de forma diferente, ya que Géminis es un signo masculino, siempre dispuesto a explorar, mientras que Virgo es un signo femenino, tímido y sensible.\n \nSu relación sexual es poco prometedora, pero ambos tienen la necesidad de comunicarse.\n \nSi encuentran un lenguaje que ambos entiendan, puede que se pongan de acuerdo sobre la forma en que debe progresar su vida sexual.\n \nSin embargo, existe una gran probabilidad de que las interminables discusiones no lleven a un entendimiento mutuo, dejándoles distantes y sin interés por compartir experiencias sexuales.\n \nSi se enamoran, utilizarán la ternura y el respeto suficientes para que su vida sexual funcione, pero rara vez será satisfactoria para ambos.\n \nAmbos son curiosos, pero no de la misma manera, y tienen un conflicto extrovertido vs.\n \nintrovertido.\n \nMientras que a Géminis le gustaría ser libre para desnudarse y correr por las calles, Virgo preferiría que todo el mundo guardara sus fluidos corporales para sí mismo.\n \nPor si fuera poco, ambos necesitan estimulación verbal, pero las palabras que a cada uno le gustaría oír a menudo no son las que la otra persona sabe decir.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "¡Qué combinación! Con los problemas de confianza de Virgo y la naturaleza embaucadora de Géminis, ambos están a punto de volverse locos.\n \nLo bueno es que no son propensos a los celos, o probablemente se matarían el uno al otro al cabo de un par de semanas.\n \nGéminis no es alguien en quien Virgo pueda confiar.\n \nCuando Virgo empiece a dudar y a analizarlo todo, Géminis simplemente saldrá volando, en el mejor de los casos.\n \nSi se tocan a través de planetas maléficos, como Marte, esto no terminará ahí, sino en peleas interminables y conflictos sobre la confianza y la fidelidad.\n \nLa clave aquí es que Géminis vuelva al planeta Tierra y respete la naturaleza sensible de su pareja.\n \nPueden construir su seguridad y ser libres de ser quienes son al mismo tiempo.\n \nAdemás, Virgo tendrá que abrirse o nunca encontrarán la forma de seguir juntos.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Están regidos por el mismo planeta, maestro de la comunicación, Mercurio.\n \nPueden tener sus diferencias, pero no diríamos que su comunicación es mala.\n \nAunque se peleen, seguirán hablando bien.\n \nSin embargo, su visión del intelecto podría ser un poco diferente.\n \nLa naturaleza superficial de Géminis podría parecerle extremadamente estúpida a su pareja de Virgo.\n \nEsto hará que Géminis sea aún más irritante a propósito, porque son todo menos estúpidos.\n \nA cambio, Géminis verá la obsesión de Virgo por los detalles y pensará que está loco.\n \nNecesitan encontrar la forma de reconocer los 'defectos' del otro como buenas cualidades y lo conseguirán si cada uno de ellos se deja ayudar por su pareja.\n \nCuando estas mentes se juntan, no hay problema que se quede sin resolver, porque juntos son Mercurio en todo su esplendor.\n \nEstos signos tienen la misión de unirse y transformar las ideas celestiales en vida real, y elevar el conocimiento humano paso a paso, hacia la divinidad.\n \nSe trata de una relación del lado Aire de Mercurio y su lado Tierra, fundamentada y bien pensada.\n \nNo hay que olvidar que el signo de Virgo exalta a Mercurio, por lo que Virgo puede exaltar a su pareja de Géminis, si tan sólo quisiera aterrizar.",
			Match: "80%"},
		Emotions: SummaryPercentage{
			Text:  "Se considera que Géminis no es tan emocional.\n \nVirgo lleva a Venus a su caída y lo racionaliza todo.\n \nAun así, ambos tienen un lado emocional interesante.\n \nGéminis está situado entre Tauro y Cáncer, dos signos fuertes, femeninos y maternales.\n \nEsto significa que el signo de Géminis se forma a partir de Tauro y es una base para Cáncer.\n \n¿Cómo puede faltar emoción entonces? Virgo tiene un problema con Venus, eso es cierto, pero ¿hace esto que Virgo carezca de emociones?\n \nSus mayores problemas son la velocidad y el miedo.\n \nGéminis simplemente no permanece en un lugar el tiempo suficiente como para crear un vínculo emocional o reconocer lo que siente, mientras que Virgo se esfuerza por descartar a Venus y con él el amor y todos los placeres terrenales porque no cree merecer nada de eso.\n \nAmbos signos tienen un pequeño y veloz planeta en común, y si se tocan el corazón, comprenderán la necesidad ocasional de su pareja de huir o escaparse.",
			Match: "55%"},
		Values: SummaryPercentage{
			Text:  "A ambos les gusta la inteligencia, el ingenio y el sentido práctico.\n \nSin embargo, su enfoque de la inteligencia básica es diferente y no siempre la reconocerán de la misma manera.\n \nDe hecho, su relación puede mostrarnos lo relativa que es la inteligencia.\n \nSu punto de encuentro está en su inteligencia emocional, no en la nuestra.\n \nSin embargo, valoran la racionalidad, la capacidad de razonar y el uso práctico de las manos y el cerebro.",
			Match: "70%"},
		SharedActivities: SummaryPercentage{
			Text:  "Menos mal que a los dos les gusta leer, así que pueden visitar una biblioteca de vez en cuando.\n \nEs probable que Virgo se quede allí un rato más, sin darse cuenta de que su pareja Géminis se perdió y encontró accidentalmente una salida de emergencia que tuvo que utilizar para ver cómo funcionaba la gran manilla de la enorme puerta roja.\n \nLa falta de autoestima que sufre constantemente Virgo le hará cuestionarse cada lugar y actividad a la que su pareja Géminis quiera llevarle.\n \nAunque intenten ocultarlo, sus dudas se harán sentir y Géminis preferirá ir solo que presionar a alguien para que le acompañe.\n \nAmbos signos son mutables y, como tales, tienen tendencia a cambiar de lugar, de intereses y de relaciones.\n \nEsto puede permitirles seguir juntos en movimiento, si tan sólo Virgo estuviera lo suficientemente abierto a nuevas y excitantes experiencias y Géminis encontrara la forma de no perderse.",
			Match: "30%"},
	},
}
