package compatibilities

var Geminigemini = Compatibility{
	Name: Gemini + " - " + Gemini,
	Friendship: Friendship{
		Match:   "70%",
		Traits:  []string{CautionRomance, FunEnjoyable, PoorAdvisors},
		Summary: "A Géminis le encanta la variedad, probar cosas nuevas cada día, por esto su relación con otra persona del mismo signo, con las mismas apetencias, está encaminada a perduraren el tiempo.\n \nSe compenetrarán muy bien de entrada, sólo con oír hablar al otro sabrán que han encontrado a la persona idónea para compartir confidencias, diversión, viajes y aventuras.\n \nLos Géminis son muy perspicaces y detectan a la legua a la persona a quien pueden ofrecer y les puede proporcionar una amistad sólida.\n \nTambién se estimularán mentalmente en todo momento y pueden ser excelentes amigos.\n \nCuando uno de ellos tenga un tropiezo, el otro le ayudará a levantarse.\n \nCuando Géminis tiene ante sí a un amigo o amiga del mismo signo, le recuerda quién es, una persona inteligente y que sabe salir airosa de cualquier dificultad.\n \nGéminis y Géminis disfrutarán como niños con sus planes conjuntos para cualquier salida, organizando una fiesta, preparando el viaje de vacaciones o simplemente recomendándose un libro que leer.\n \nDada su facilidad de palabra, será importante que sepan también escuchar al otro Géminis, no dejar que se establezca una lucha verbal que supondría uno de los pocos obstáculos para que su amistad sea perfecta.",
	},
	Love: Love{
		Match:  "83%",
		Traits: []string{DeepMutualUnderstanding, LowCommitment},
		Summary: SummaryPercentage{
			Text:  "La relación entre dos Géminis dará a otros signos del zodíaco un dolor de cabeza casi seguro.\n \nIrán juntos a todas partes, lo harán todo juntos y hablarán de todo entre ellos, una y otra vez, hasta que uno de los dos pierda el interés por el otro.\n \nDebido a su enfoque posiblemente superficial, lo mejor es que ya hayan tenido algunas relaciones con profundidad antes de conocerse.\n \nEsto podría darles la calidad necesaria para durar juntos más de una o dos semanas.\n \nEn la mayoría de los casos, no es una relación en la que quieran quedarse, aunque su entendimiento mutuo sea perfecto.\n \nEs como si fueran demasiado parecidos y, al mismo tiempo, una relación con demasiadas personalidades.\n \nSi cada una de ellas no está reunida en una sola persona, necesitarán a alguien que sí lo esté, para mantener el equilibrio y no dejar que se disipen.\n \nEn caso de que hayan construido personalidades y cada uno de ellos comprenda su propio núcleo interno, probablemente puedan vivir para siempre y no consumir nunca la energía que aporta su conexión.",
			Match: "83%"},
		SexualIntimacy: SummaryPercentage{
			Text:  " Es muy raro que un Géminis, como signo de Aire, sea práctico y encuentre la forma de manifestar lo que ha leído o escuchado en el ámbito de la realidad y el cuerpo físico.\n \nSu mayor cualidad es la capacidad de aprender.\n \nCon su deseo de convertirse en grandes amantes, absorberán conocimientos a través de cada una de sus relaciones como una esponja.\n \nDos Géminis juntos compartirán información y coordinarán sus experiencias previas entre sí.\n \nSe sentirán más satisfechos cuando enseñen algo a su pareja, que por el sexo en sí.\n \nCon sus mentes abiertas y su ingenio creativo, probablemente no haya un solo lugar en el que no quisieran tener sexo, ni una postura que no quisieran probar.\n \nNo es que sean promiscuos, pero encuentran alegría y excitación en el cambio de escenario, sobre todo si también hay movimiento relativo de por medio.\n \nSin embargo, su vida sexual puede volverse vacía cuando la excitación ha pasado si ninguno de ellos tiene suficiente profundidad para aportar al acto sexual.\n \nNi siquiera son conscientes de la concentración y la conexión emocional que necesitan, hasta que encuentran a la pareja adecuada.\n \nDeberían desenterrar sus corazones y cambiar su relación con la sexualidad, antes de juntarse con uno de su especie.",
			Match: "80%"},
		Trust: SummaryPercentage{
			Text:  "Puede que no confíen el uno en el otro, pero no les importa.\n \nAmbos se conocen, así que es fácil entenderse en todos esos estados de ánimo escamosos, superficiales y cambiantes.\n \nBásicamente, uno de ellos se mudará en dos minutos y el otro en tres, así que ¿cómo pueden confiar en que el otro se quede? Si supieran cuál va a ser su próximo movimiento, podrían ser capaces de construir la confianza con alguien tan parecido a ellos.\n \nEsto no es algo que les moleste.\n \nAl contrario, les dará la libertad de ser ellos mismos, pero rara vez les mantendrá en una relación durante demasiado tiempo.",
			Match: "50%"},
		Communication: SummaryPercentage{
			Text:  "La comunicación entre un Géminis y otro Géminis nunca termina.\n \nSaltarán en las frases del otro y utilizarán todas las herramientas de comunicación posibles, empezando por las habituales conversaciones telefónicas y el chat que crecerá hasta convertirse en docenas de variaciones de chat, dependiendo del emoticono que quieran utilizar.\n \nCuando se reúnen, siempre hay algo que compartir, una idea que debatir y una distancia que recorrer a pie.\n \nEs maravilloso verles juntos cuando encuentran a alguien que les entiende y habla en su mismo idioma.\n \nMientras haya suficiente respeto y escucha entre ellos, el lado intelectual de su relación permanecerá intacto.",
			Match: "99%"},
		Emotions: SummaryPercentage{
			Text:  "Para empezar, el signo de Géminis no es muy emocional.\n \nLo bueno es que ambos lo saben y encuentran una explicación racional al beneficio de su mutua falta de emoción.\n \nAun así, existe en cada uno de ellos la necesidad de alcanzar algo que no pueden tener.\n \nEs de esperar que el Géminis más abierto establezca un vínculo emocional profundo con su pareja, aunque sus sentimientos podrían no ser correspondidos.\n \nPuesto que confían en una conexión intelectual con alguien, podrían encontrar una verdadera satisfacción emocional en su comunicación, pero ésta se rompe fácilmente debido a que la compatibilidad mental no es lo mismo que la emocional, y mucho menos la sexual.\n \nA menudo, lo niegan y se aferran a lo que tienen, hasta que uno de los dos es barrido de sus pies por alguien que despierta sus emociones con el silencio.",
			Match: "70%"},
		Values: SummaryPercentage{
			Text:  "Cuando decimos 'libertad' pensamos en Acuario, pero en realidad Géminis valora la libertad tanto o más que su amigo Acuario.\n \nEste es un valor que dos Géminis compartirán apasionadamente.\n \nNo les gusta aburrirse con detalles fastidiosos, obligaciones de una relación significativa o la necesidad de su pareja de una compasión que no hay que pedir.\n \nEl problema radica en que piensan demasiado y sienten mucho menos.\n \nSi pudieran salir de su cabeza durante un par de segundos, podrían darse cuenta de que su pecho está pidiendo a gritos intimidad, cercanía y compasión",
			Match: "99%"},
		SharedActivities: SummaryPercentage{
			Text:  "Este título lo dice todo.\n \nComparten actividades.\n \nTodas.\n \nSi uno de ellos quiere hacer...\n \nbueno, básicamente cualquier cosa, el otro le seguirá por pura curiosidad, y viceversa.\n \nIncluso si ambos no querían hacer algo, lo harán juntos por curiosidad.\n \nDespués de compartir una experiencia, la pasarán por un filtro mental, la comentarán y pasarán a la siguiente.\n \nNo hay quien pare a estos dos y nadie puede seguirles como ellos se siguen el uno al otro.",
			Match: "99%"},
	},
}
