package compatibilities

var Geminileo = Compatibility{
	Name: Gemini + " - " + Leo,
	Friendship: Friendship{
		Match:   "95%",
		Traits:  []string{GoodRomancePotential, FunEnjoyable},
		Summary: "Tanto Leo como Géminis tienen una naturaleza aventurera y procuran siempre disfrutar al máximo de la vida.\n \nEntre ambos se establecerán lazos de amistad desde el primer momento y disfrutarán al máximo de la mutua compañía.\n \nGéminis y Leo se hallan a un mismo nivel intelectual, ambos disfrutarán conversando, una de sus mayores aficiones.\n \nUno de los puntos en contra que deberán tener en cuenta, es que a Leo le gusta dominar siempre la situación, algo a lo que Géminis no siempre estará dispuestos.\n \nSin embargo, el carácter flexible de Géminis, junto con su gran capacidad de adaptación, puede resolver favorablemente este tipo de conflictos.\n \nLeo suele querer mantenerse a toda costa en lo que ha manifestado o lo que quiere hacer, es ahí donde Géminis puede conseguir cambiar las tortas con su capacidad social y sus dotes de persuasión.\n \nAmbos se manifiestan brillantes en el contexto social, donde son admirados por el resto.\n \nGéminis y Leo profesan admiración por las cualidades del otro de las que ellos carecen.\n \nGéminis respetará a Leo por su creatividad y aprenderá de ella, mientras que la calidez de Leo hará sentir a Géminis que aprecia sus talentos.\n \nSu mutua admiración también conformará la base para que ambos se conviertan en buenos amigos.",
	},
	Love: Love{
		Match:  "82%",
		Traits: []string{Harmonious},
		Summary: SummaryPercentage{
			Text:  "Géminis y Leo pueden divertirse tanto que podrían dar envidia al resto del zodíaco.\n \nAmbos consideran que su día transcurre mejor entre risas y, si comparten amigos, podrían parecer la pareja perfecta.\n \nSu principal reto es la diferencia en su enfoque del cambio y ambos necesitan hacer sitio para pequeños ajustes en su comportamiento si quieren que su relación dure.\n \nLeo tendrá que dar cabida a más movimiento y entender lo que parece ser 'flaqueza' de su cambiante pareja Géminis, mientras que Géminis tendrá que entender que Leo es en realidad mantenerlos juntos por el tiempo que están destinados a durar.\n \nPor lo general, su respeto mutuo puede superar cualquier límite, y deberán seguir divirtiéndose y construyendo su relación sobre una base sólida de alegría infantil.",
			Match: "82%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Todo lo que Leo quiera mostrar, Géminis lo examinará con gusto.\n \nEncajan muy bien en el sexo, pues Géminis aporta ideas y emoción a su relación, mientras que Leo aporta energía, creatividad y amor.\n \nSu vida sexual puede verse estimulada por su intelecto y su comunicación, ya que ambos confían en su Yo consciente y en su mente.\n \nSi Leo se siente bien en las relaciones íntimas con su Géminis, como signo fijo que es, les dará estabilidad y la posibilidad de durar juntos mucho tiempo.\n \nGéminis es infantil cuando se trata de sexo, y rara vez conecta la emoción profunda con la sexualidad.\n \nLeo podría ser la pareja adecuada para enseñarles a establecer una verdadera conexión íntima si no están preocupados por sí mismos.\n \nAmbos querrán experimentar, tener encuentros sexuales al aire libre y disfrutarán desnudos.\n \nEsta es una relación perfecta para que ambos superen la vergüenza y cualquier tipo de miedo en relación con la intimidad y la sexualidad.",
			Match: "90%"},
		Trust: SummaryPercentage{
			Text:  "Tanto Géminis como Leo pueden ser malos oyentes cuando se trata de las necesidades de los demás.\n \nUno de ellos se distrae con todo y el otro se centra sólo en sus propias necesidades.\n \nDebido a esto, podrían terminar en una situación en la que su relación carezca de confianza y podría llevarles algún tiempo darse cuenta, porque no se cuestionarán el uno al otro al principio.\n \nDebido a su naturaleza, podrían perderse, satisfaciendo cada uno sus propias necesidades.\n \nEsto les llevará a todo tipo de situaciones que no quieren compartir entre ellos, incluso al adulterio.\n \nEs de suma importancia que compartan y se escuchen desde el principio, para que ambos puedan satisfacer las necesidades de su pareja en lugar de dejarlas escapar.",
			Match: "45%"},
		Communication: SummaryPercentage{
			Text:  "Tanto Géminis como Leo son racionales y se centran en su actividad mental.\n \nLeo tiene un profundo trasfondo emocional, pero presta mucha atención a las palabras y a la fuerza intelectual de su pareja.\n \nAquí es donde Géminis interviene como fiel seguidor, para admirar a su pareja Leo y enseñarle un par de cosas.\n \nSi se encuentran en una relación emocional, probablemente hablarán de todo menos de sus sentimientos.\n \nA los dos no les sirven de mucho las zalamerías y si Géminis intenta utilizar su habilidad con las palabras, podría funcionar sólo hasta un punto en el que empiecen a sonar falsos.\n \nNo hay mucho espacio para pensar más de la cuenta y probablemente ambos digan lo primero que se les ocurra.\n \nEsta es una buena forma de crear confianza entre ellos, si no se juzgan mutuamente en el proceso y comparten algunas emociones por el camino.\n \nSin embargo, existe el problema del Sol 'perfecto' de Leo.\n \nEsta posición da tanta energía a Leo que a veces se siente obligado a quemar a todos los que le rodean imponiendo su voluntad.\n \nSuelen tener la idea de cambiar el mundo y convertirlo en un lugar mejor, y esto puede volver loca a su pareja Géminis en caso de que no tengan suficiente espacio para sus propias opiniones.",
			Match: "95%"},
		Emotions: SummaryPercentage{
			Text:  "La calidez que Leo está dispuesto a dar a su pareja Géminis difícilmente le dejará indiferente, mientras que el encanto y la naturaleza infantil de Géminis va a despertar emociones maravillosas en Leo, día tras día.\n \nAunque la cualidad mutable de la pareja de Géminis no va realmente bien con la cualidad fija de ningún signo, con Leo podría ser una pareja perfecta debido a su naturaleza cálida, solidaria y respetuosa.\n \nSi Leo tiene la paciencia suficiente para esperar a que afloren las emociones de Géminis, podría obtener más de lo que esperaba.\n \nLa belleza de su relación es la conciencia de ambos, que les lleva a mostrar verbalmente sus emociones, una vez que se sienten seguros el uno con el otro.\n \nSi ambos reconocen el amor, ésta es una maravillosa historia de amor llena de apoyo, respeto y siempre algo nuevo que discutir.",
			Match: "85%"},
		Values: SummaryPercentage{
			Text:  "Sobre todo, ambos valoran la inteligencia y la claridad.\n \nComo dos signos regidos por planetas responsables de nuestro comportamiento mental y racional, satisfarán perfectamente las necesidades del otro.\n \nGéminis valora la independencia de su pareja y su propia libertad, y esto es exactamente lo que Leo puede darle.\n \nPor otro lado, Leo siempre valora el niño interior de su pareja y esto es exactamente lo que obtendrá en su Géminis.",
			Match: "99%"},
		SharedActivities: SummaryPercentage{
			Text:  "Menos mal que Géminis quiere ir a todas partes y hacerlo todo, o estos dos podrían tener un gran problema para encontrar actividades que quieran compartir.\n \nDe este modo, Leo puede elevar sus actividades a un 'nivel superior' yendo a todos los lugares que Géminis sugeriría, pero en una versión lujosa y cara.\n \nAunque a Géminis no le gustaría gastar tanto dinero, a Leo no le importa pagar por todo, siempre y cuando no se sienta utilizado.\n \nAun así, Leo puede ser muy perezoso.\n \nGéminis siempre está en movimiento, y tiene la necesidad de hacer al menos tres actividades diferentes cada día.\n \nCuando Leo tiene tiempo para descansar, probablemente querrá ver la televisión y moverse del lado izquierdo al derecho del sofá durante todo el día.\n \nEsto es algo que podría abrir una brecha entre sus mundos, pero normalmente respetan lo suficiente las necesidades del otro como para poder separar actividades y ser muy felices juntos.\n \nNinguno de los dos está necesitado y no quieren pasar cada momento de su vida con su pareja, así que ambos tendrán suficiente libertad: Géminis para moverse y Leo para descansar.",
			Match: "80%"},
	},
}
