package compatibilities

var Geminiscorpio = Compatibility{
	Name: Gemini + " - " + Scorpio,
	Friendship: Friendship{
		Match:   "35%",
		Traits:  []string{NothingInCommon},
		Summary: "Aunque la amistad entre Géminis y Escorpio parece que siempre tiene que estar cargada de conflictos, si logran entenderse será positiva para ambos.\n \nTanto Géminis como Escorpio tienen cosas que ofrecerse en este terreno.\n \nA pesar de que de entrada no suelen congeniar en absoluto, si tienen la oportunidad de conocerse mejor empezarán a considerarse amigos.\n \nCiertos aspectos, como el relajado estilo de vida de Géminis, necesita que Escorpio ponga un poco de orden y estrategia a su vida, a sus aficiones, a sus deseos infinitos de viajar constantemente y de divertirse sin tregua.\n \nSi esta amistad se establece, Géminis se encontrará con alguien que le defiende con uñas y dientes delante de cualquier adversario o de cualquier adversidad.\n \nDelante de tamaña demostración de afecto incondicional, el quisquilloso Géminis rendirá armas y puede convertirse en incondicional de Escorpio.\n \nLa amistad entre Géminis y Escorpio sí que puede ser muy intensa y de larga duración, contrariamente a lo que ocurre con las relaciones amorosas, aunque quizá pasen largos períodos sin verse, Sin embargo, siempre sabrán que el otro está ahí para lo que haga falta.",
	},
	Love: Love{
		Match:  "15%",
		Traits: []string{Volatile, NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "Géminis y Escorpio suelen molestarse mutuamente hasta perder el sentido.\n \nNinguno de ellos entenderá a la ligera la personalidad de su pareja.\n \nA Géminis, su pareja le parecerá demasiado deprimida y oscura sin motivo aparente, y para Escorpio podría ser una experiencia sin propósito ni profundidad.\n \nSi se enamoran locamente, podrían conectar a través de su amor mutuo por el cambio y darse el uno al otro exactamente lo que les falta.\n \nGéminis obtendría una satisfacción emocional profunda que nunca ha sentido antes y Escorpio tendría por fin la oportunidad de descansar su alma atribulada, y darse cuenta de que no todo tiene que tomarse en serio.\n \nEsta es una relación de grandes lecciones y una enorme capacidad de crecimiento personal de ambos miembros de la pareja.",
			Match: "15%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Géminis está tan alejado del mundo emocional de Escorpio que el buen sexo entre ellos parece algo casi imposible de suceder.\n \nEsta pareja necesita el apoyo de otras posiciones en sus cartas natales si quieren tener alguna posibilidad de durar en una relación amorosa y sexual.\n \nGéminis puede ser superficial y no hay otro signo que lo sepa mejor que Escorpio.\n \nSu elemento Aire combinado con la regla de Mercurio y su falta de emoción se acerca a la peor pesadilla de Escorpio.\n \nEscorpio es el signo de nuestras emociones más profundas y, como tal, está vinculado al lado más íntimo de la sexualidad.\n \nSi se enamoran, ambos tendrán mucho que aprender.\n \nEscorpio da mucha importancia a su vida sexual y puede ser muy creativo cuando está relajado.\n \nAun así, tienen tendencia a crear un ambiente oscuro, sádico o masoquista del que Géminis sólo puede reírse.\n \nSi su respeto mutuo está en un punto muy alto, Géminis podría enseñar a Escorpio que no todo tiene que ser tan fatalista en su vida sexual.\n \nA cambio, Escorpio le dará a su pareja Géminis una profundidad y una vibración emocional en el sexo que nunca antes había encontrado.",
			Match: "1%"},
		Trust: SummaryPercentage{
			Text:  "Escorpio confía en todo el mundo hasta que deja de hacerlo.\n \nTienen esa naturaleza extraña y posesiva que puede dar la máxima confianza a su pareja hasta que se crea el primer gusano de sospecha, normalmente por flaqueza y falta de respeto.\n \nLes gustan las cosas limpias y sin dudas, y están dispuestos a dar una honestidad incondicional, esperando lo mismo a cambio.\n \nAquí es donde llega Géminis y plantea una pregunta sencilla: ¿cómo puedo ser honesto si, para empezar, no sé cuál es mi verdad? Es ridículo esperar una honestidad tan definida de una pareja Géminis cuando son tan propensos a cambiar y no tienen ni idea de lo que sentirán o harán mañana.\n \nAún así, tienen un don para la comunicación que puede salvar el día, pero sólo se puede utilizar si Escorpio no se siente amenazado debido a su desamor anterior del que nunca se han curado.",
			Match: "5%"},
		Communication: SummaryPercentage{
			Text:  "Es bueno que Géminis pueda comunicarse con cualquiera.\n \nSe sentirán conmovidos e intrigados por la naturaleza de Escorpio, y muy curiosos, como de costumbre.\n \nEsto se verá amplificado por la profundidad y los temas interesantes de Escorpio, hasta el punto de volverse demasiado oscuro y depresivo.\n \nEsto es algo con lo que Géminis no quiere lidiar si no es necesario.\n \nPor desgracia, Escorpio no cree que pueda aprender mucho de Géminis.\n \nAunque deseen ser más superficiales, cuando entran en contacto con alguien con menos profundidad, su ego echa chispas y se sienten dominantes por ser como son.\n \nDifícilmente respetarán a Géminis por ello, y pueden intentar nutrirse de su personalidad para añadir calidad a la suya.\n \nEn caso de que compartan intereses y tengan orientaciones profesionales o educativas similares, podrían complementarse muy bien.\n \nGéminis aportará ideas y descubrirá nueva información, mientras que Escorpio profundizará y dará verdadera esencia a todo.\n \nSu comunicación puede ser inspiradora si se ponen en este modo y empiezan a aceptar las cualidades del otro.\n \n",
			Match: "20%"},
		Emotions: SummaryPercentage{
			Text:  "La falta de compatibilidad emocional es lo que arruina su vida sexual y les da dolores de cabeza a ambos.\n \nSi uno de ellos se enamora del otro, difícilmente pasarán un buen rato si sus sentimientos no son correspondidos en la misma proporción.\n \nPodríamos decir que les cuesta sincronizarse, porque las emociones que Escorpio entregaría libremente son algo por lo que Géminis tendría que dejarse llevar.\n \nNo parecen tener la misma escala emocional y esto puede dejar a ambos insatisfechos o presionados hasta un punto de ruptura.\n \nLa mejor opción para su mundo emocional compartido sería que ambos dieran lo que pudieran y no esperaran nada a cambio.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Lo bueno de su relación es que ambos valoran la fuerza de pensamiento.\n \nAunque Escorpio valora muchas otras cosas en la personalidad de alguien, se sentirá impresionado por la inteligencia y el ingenio de alguien.\n \nGéminis se centrará en lo mismo, pero tendrá una valoración ligeramente diferente del intelecto de alguien.\n \nSin embargo, pueden estar de acuerdo en tener un punto en común del mismo valor, aunque otras cosas por las que se esfuercen diferirán mucho.",
			Match: "20%"},
		SharedActivities: SummaryPercentage{
			Text:  "Lo mejor de estos dos es su apertura al cambio.\n \nGéminis querrá cambiar de aires y Escorpio querrá cambiar de vida, dando con gusto los pequeños pasos de Géminis hacia ese objetivo.\n \nEscorpio es un signo fijo, establecido en el cambio de enormes proporciones, y la cualidad mutable de Géminis les molestará en la mayoría de los casos.\n \nAun así, pueden identificarse con su necesidad de experiencias diferentes en la vida y con la emoción que siempre buscan.\n \nAunque no les entusiasmen las mismas cosas, habrá suficiente emoción para que ambos miembros de la pareja elijan a lo largo del camino que decidan recorrer juntos.",
			Match: "40%"},
	},
}
