package compatibilities

var Geminipisces = Compatibility{
	Name: Gemini + " - " + Pisces,
	Friendship: Friendship{
		Match:   "65%",
		Traits:  []string{PoorAdvisors},
		Summary: "La compatibilidad en la amistad entre Géminis y Piscis, depende en gran medida de la fuerza de voluntad que tengan ambo para conducir esta relación por el buen camino.\n \nTanto Géminis como Piscis necesitan poner interés por su parte y mucha comprensión porque pertenecen a dos signos mutables y esto significa que comparten algunos aspectos positivos pero bastantes más de negativos.\n \nGéminis aspira a una tranquilidad que Piscis posiblemente no pueda aportarle.\n \nSin embargo, el etéreo Piscis conseguirá atraer la atención de Géminis con su peculiar forma de ver la vida.\n \nÉste podría ser el punto de partida para una amistad que se basará en el interés de Géminis por descubrir qué hay en la profundidad del espíritu de Piscis, por qué piensa de determinada manera tan opuesta a la suya.\n \nPor su parte, Piscis, se deslumbrará con la facilidad de palabra de Géminis, querrá entender en su discurso lo que quiere oír no lo que el otro está diciendo realmente.\n \nAún así, este deseo de conocer mejor al otro se prolongará en el tiempo y por mucho que Géminis y Piscis descubran sus facetas antagónicas, siempre querrán intentarlo de nuevo manteniendo una amistad que, curiosamente, les dará a ambos muchas satisfacciones.",
	},
	Love: Love{
		Match:  "10%",
		Traits: []string{LowCommitment, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Géminis y Piscis son signos en cuadratura que no suelen tener mucho en común.\n \nAmbos suelen ser lo suficientemente positivos como para tener una relación superficial agradable y llevarse bien en las grandes reuniones sociales.\n \nAmbos pueden olvidarse de llamarse cuando han quedado en hacerlo, y ambos pueden cambiar de opinión en dos segundos, pero simplemente no comparten los mismos objetivos.\n \nComo signo fuertemente mental y fuertemente emocional, su falta de entendimiento puede ser hiriente para Piscis y a veces para ambos.\n \nSi se enamoran y comienzan una relación romántica, lo más probable es que no dure mucho.\n \nSin embargo, hay una belleza en el lado creativo de esta relación y si Géminis decide escuchar de verdad a Piscis, podría ayudarle a utilizar su talento de forma constructiva.\n \nEn la mayoría de las situaciones, Piscis sólo drenará la energía de su pareja Géminis, especialmente si terminan en su modo frágil y necesitado que algunos otros signos podrían entender mucho mejor que Géminis.\n \nSi quieren tener éxito en su empeño por estar juntos, deben trabajar juntos y socializar mucho.\n \nLo más importante para ambos en esta relación es llegar a sus núcleos emocionales y entregarse a la verdadera intimidad, o nunca lograrán comunicarse.",
			Match: "10%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Menos mal que Géminis es muy creativo en sus relaciones sexuales, pues de lo contrario tendría muchas dificultades para establecer una relación íntima con Piscis.\n \nPueden sentirse atraídos el uno por el otro debido a que están regidos por Mercurio y Júpiter, los mismos planetas que rigen sus signos opuestos.\n \nAun así, es muy probable que ni siquiera se reconozcan como seres sexuales o que, si lo hacen, mantengan las distancias.\n \nGéminis tiene un gran potencial creativo, pero no está precisamente en busca de su único y verdadero amor para tener relaciones sexuales.\n \nPiscis, en cambio, exalta a Venus, y sólo quiere tener sexo con el amor de su vida, a menos que se haya decepcionado demasiadas veces.\n \nSi se encuentran después de estas numerosas decepciones, Géminis no encontrará a Piscis muy atractivo, pues ya no tendrá energía ni encanto infantil.\n \nGéminis tendrá que darse cuenta de la verdad que se esconde tras su propia naturaleza emocional y entregarse a la verdadera intimidad, mientras que Piscis tendrá que aceptar las diferencias de su pareja en lugar de buscar un alma gemela con cualidades predefinidas.",
			Match: "15%"},
		Trust: SummaryPercentage{
			Text:  "La confianza ya es un punto débil en casi todas las relaciones que estos dos puedan tener y cuando se junten, existe la posibilidad de que no tengan ni idea de cómo crear confianza entre ellos.\n \nTienen formas completamente diferentes de manejar sus relaciones emocionales y sus problemas con la autoimagen, y se les ocurrirán muchas formas diferentes de torcer la verdad cuando estén juntos.\n \nPor desgracia, cuando alguno de ellos mienta, no tendrá mucho éxito.\n \nGéminis es demasiado inteligente como para que su pareja Piscis le mienta, y Piscis percibe demasiado bien el estado de su pareja Géminis como para no darse cuenta cuando no está diciendo la verdad.\n \nBásicamente, ambos se sumergen en el inconsciente del otro y se ven como ninguno de ellos se ve a sí mismo.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Siempre hay un cuento o dos para compartir entre ellos y algo de diversión cuando salen.\n \nSe reirán juntos, pero se trata de una conexión extraña con una falta de comunicación real.\n \nGéminis puede decidir hacer una broma y Piscis se reirá sin pensarlo realmente.\n \nPiscis dirá algo para molestar a Géminis y éste se reirá sin pensarlo.\n \nEs como si nunca se escucharan realmente y se hundieran en una extraña piscina de relaciones superficiales y charlas triviales.\n \nSi empiezan a hablar de sus pensamientos y sentimientos profundos, pueden acabar en un conflicto que ninguno de los dos había previsto.\n \nPodríamos decir que se idealizan mutuamente, pero sólo hasta un punto de reconocimiento.\n \nNi Géminis ni Piscis pensarán en el otro como su único y verdadero amor, a menos que realmente sean el único y verdadero amor del otro.\n \nAsí que tendrán esta imagen del otro que se desvía de la realidad, debido al hecho de que realmente no se escuchan el uno al otro.\n \nLa única forma posible de que mantengan una conversación con profundidad es en una situación en la que tengan una intimidad emocional absoluta, como la que suelen tener los miembros de una familia.",
			Match: "20%"},
		Emotions: SummaryPercentage{
			Text:  "Géminis es uno de los signos más racionales del zodíaco y Piscis es el romántico incurable y uno de los signos más emocionales.\n \nCuando se enamoran, rara vez están en la misma frecuencia y a menudo sólo uno de ellos siente verdaderas emociones por el otro.\n \nRepresentan los candidatos ideales para un escenario de amor no correspondido y pueden ser una molestia para todos los que les rodean si acaban en una relación sin equilibrio emocional.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Ambos valoran lo que defienden y aunque Géminis valora que alguien le escuche y le ame incondicionalmente, esto no es lo mismo que el amor apasionado que desea tener la pareja de Piscis.\n \nEn general, ambos se aferrarán a lo que mejor saben hacer y Géminis valorará la fuerza intelectual y no se perturbará mucho por la deshonestidad mientras su imagen de una relación no se vea perturbada.\n \nPiscis valorará la fiabilidad de su pareja y la confianza estará muy arriba en su lista de prioridades.\n \nSin embargo, hay una cosa que compartirán, oculta en el hecho de que ambos valoran la capacidad de alguien para crear.\n \nAunque esto surja de diferentes puntos de vista sobre la creación, puede unirlos en el acto de la creatividad.\n \nPiscis aportaría talento e inspiración y Géminis su ingenio y sentido práctico.",
			Match: "5%"},
		SharedActivities: SummaryPercentage{
			Text:  "Cuando hablamos de Géminis y Piscis, tenemos que tener en cuenta que ambos signos son mutables.\n \nAunque sus intereses puedan diferir mucho, podrían encontrar actividades para compartir debido a su mutua necesidad de movimiento de cualquier tipo.\n \nPiscis normalmente soñará con el movimiento en lugar de moverse realmente y esto es exactamente lo que Géminis podría enseñarle: cómo dar el primer paso.",
			Match: "15%"},
	},
}
