package compatibilities

var Geminicapricorn = Compatibility{
	Name: Gemini + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{ExcellentAdvisors},
		Summary: "A pesar de sus muy distintos rasgos de personalidad, la amistad entre Géminis y Capricornio puede tener futuro.\n \nAmbos suelen tener un buen número de amistades que muchas veces también son sus admiradores.\n \nCapricornio valora mucho la amistad y suele tener relaciones profundas con las personas a las que integra en su vida, si no llega a ser un amigo incondicional, se le parece mucho.\n \nGéminis, por su parte, atrae a la gente por su personalidad brillante, aunque no concede tanta importancia a estas relaciones.\n \nEn este aspecto, Géminis y Capricornio se complementarán a la perfección porque Géminis le ofrece un mundo interior muy complejo y también le desvela la mejor forma de sacar todo el partido posible de la vida.\n \nCapricornio comprenderá las razones y sabrá sacar provecho de estas experiencias que, aún sin querer, le revela Géminis, quien a su vez aprenderá que la verdadera amistad hay que valorarla y potenciarla.\n \nLe seducirá poder conocer más a fondo el intrincado mundo interior de Capricornio.\n \nCon el paso del tiempo, Géminis y Capricornio comprenderán que su amistad trascenderá por encima de cualquier obstáculo y que juntos podrán vivir experiencias que por separado no podrían ni soñar.",
	},
	Love: Love{
		Match:  "15%",
		Traits: []string{MutualRespect, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "Las parejas de Géminis y Capricornio encajan de forma muy extraña.\n \nAunque ambos buscan cosas que la otra persona tiene, no parecen reconocerlas en el otro.\n \nMientras que Géminis necesita a alguien que lo enraíce y le dé profundidad, cuando mira a Capricornio, ve a alguien viejo, inamovible y aburrido.\n \nCapricornio necesita alegría y relajación en su vida, pero Géminis parece una bola de opiniones incontrolables y superficiales que no van a ninguna parte.\n \nEn realidad, podrían tener una valiosa experiencia estando juntos, compartiendo sus diferentes vidas día tras día.\n \nIncluso podrían descubrir que en realidad trabajan bien juntos y que tienen la capacidad de alcanzar cualquier meta que se les ocurra.",
			Match: "15%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Hay ciertas actividades que no requieren muchas palabras y, en la humilde opinión de Capricornio, el sexo es una de ellas.\n \nEntonces llega Géminis y empieza a explicar cada postura, el interesante repaso al Kama Sutra y la belleza del sexo al aire libre.\n \nPara que Capricornio experimente en el sexo, su pareja tiene que conseguir relajarle de verdad y abrirle la mente.\n \nCon Géminis, se sienten como si estuvieran cuidando a un niño que va camino de meterse en líos, desnudándose donde les da la gana.\n \nAunque en realidad no sea así, es lo que le puede parecer a Capricornio, dependiente de los valores tradicionales y siempre asumiendo la responsabilidad de sus actos.\n \nLo más extraño de esta combinación de signos es que probablemente ambos se consideren aburridos.\n \nSí, todo el mundo diría Capricornio puede ser aburrido y Géminis es tan interesante y divertido, pero en realidad, la falta de enfoque y sentimientos profundos Géminis pareja por lo general sufre de, es un gran apagado para Capricornio.\n \nTeniendo todo esto en cuenta, estos dos no son realmente los mejores compañeros sexuales entre los signos del zodiaco, pero podría hacer un punto de encuentro en una relación con suficientes límites y suficiente creatividad de ambos socios.",
			Match: "1%"},
		Trust: SummaryPercentage{
			Text:  "Un representante típico de Capricornio no se dejará engañar fácilmente.\n \nLa pareja de Géminis puede tener tendencia a coquetear mucho y a considerar normal el 'adulterio ligero'.\n \nEsto es pensar en un loco en opinión de un Capricornio, y no hay 'niveles' de adulterio en su mundo.\n \nLo que está claro, está claro.\n \nAún así, debido a la ecuación de confianza de Capricornio que les hace la vida fácil, tenderán a confiar en su Géminis.\n \nEn realidad, confiarán en su propia interpretación de lo que dice Géminis.\n \nCapricornio siempre va un paso más allá que los demás, y Géminis rara vez reflexiona tanto sobre sus coartadas.\n \nPor eso Capricornio las leerá con tanta facilidad, probablemente sabiendo exactamente dónde han estado y en qué son deshonestos.\n \nGéminis, en cambio, encontrará a Capricornio tan cuadrado y según las reglas, que ni siquiera dudará de su fidelidad y honestidad, aunque tenga algo que ocultar.",
			Match: "50%"},
		Communication: SummaryPercentage{
			Text:  "Es seguro decir que Géminis puede hablar con cualquiera y resolver cualquier asunto comunicándose.\n \nPor desgracia, esto no significa mucho para un Capricornio cuando reconocen la falta de esencia en las cosas que dice su pareja.\n \nSin embargo, todavía tendrán mucho de qué hablar porque siempre hay ese lado serio de Géminis en una de sus personalidades que tendrá una cosa o dos para compartir con un Capricornio estricto y a veces difícil.\n \nEs una buena cosa que Géminis están interesados en, literalmente, todo lo que existe en el mundo y fuera de él.\n \nA Capricornio le interesan las cosas que tienen un significado profundo y oculto, las ve como ecuaciones que deben resolverse y admira a los solucionadores de problemas.\n \nSi están en paz y no se miran como estúpidos, distantes o aburridos, podrían ayudarse mutuamente a construir una mejor comprensión del mundo.\n \nLa naturaleza firme y segura de Capricornio podría enseñar a Géminis a hacer horarios y a organizar sus pensamientos y sus acciones, dándoles la oportunidad de llevar cada pensamiento un paso más allá.\n \nA cambio, el enfoque infantil de la vida de Géminis puede ser algo maravilloso que Capricornio incorpore a su vida para ser más feliz.",
			Match: "25%"},
		Emotions: SummaryPercentage{
			Text:  "Regidos por Mercurio y Saturno, ambos signos no son tan emocionales, pero el verdadero problema está en el hecho de que normalmente ni siquiera despiertan algunas emociones el uno en el otro.\n \nAunque ambos pueden tener relaciones con otros signos no tan emocionales en las que se sienten despiertos con su pareja, cuando están el uno con el otro, pueden ser inmunes al encanto del otro.\n \nSimplemente no hay mucho que los conecte y la mayoría de las veces su relación emocional se reduce a los pensamientos oscuros de Géminis y la distancia emocional de Capricornio.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Géminis valora realmente la información en cualquiera de sus formas, la capacidad de alguien para hablar bonito, para utilizar sus manos de forma creativa y para poner en práctica ideas con un propósito superior.\n \nCapricornio valora la estabilidad, la puntualidad y la simple honestidad.\n \nAunque ambos se sentirán deslumbrados por la independencia de su pareja, el resto de sus mundos rara vez coinciden tanto.",
			Match: "5%"},
		SharedActivities: SummaryPercentage{
			Text:  "Ambos caminarían mucho, es cierto, pero la divergencia de sus motivos es casi increíble.\n \nCapricornio es un signo de cosas útiles, y querrán tener una actividad útil, sea cual sea.\n \nSi salen a pasear, querrán hacerlo para ir del punto A al punto B, o para tener un estilo de vida más saludable.\n \nCuando Géminis pasea, nunca sabe dónde acabará.\n \nPuede que hayan empezado su ruta de camino al supermercado, pero una llamada de teléfono más tarde, ya están en su coche, dirigiéndose a una ciudad diferente.\n \nEs bueno que Géminis siempre quiera aprender cosas nuevas y que a Capricornio le guste la rutina y la dedicación, así que tienen una base sólida para el estudio constructivo y la resolución de problemas.\n \nSin embargo, en la mayoría de los casos, sus caminos van en direcciones diferentes.",
			Match: "10%"},
	},
}
