package compatibilities

var Geminiaquarius = Compatibility{
	Name: Gemini + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "100%",
		Traits:  []string{GoodRomancePotential, DeepMutualUnderstanding, ExcellentAdvisors},
		Summary: "Es bastante frecuente que Géminis y Acuario conecten por primera vez en circunstancias poco habituales.\n \nTanto uno como el otro se sentirán inmediatamente atraídos por la personalidad del otro, que inconscientemente tanto les recuerda a la suya propia, salvando las diferencias.\n \nLa afinidad suele ser inmediata porque comparten un estilo abierto y locuaz.\n \nA Géminis le subyugará la aparente rebeldía de Acuario y sentirá que a su lado aparece la inspiración, se potencia su espíritu creativo.\n \nTambién admirará que para el signo del aguador no parece haber cosas complicadas ni difíciles.\n \nAcuario, por su parte, admirará la brillantez y la locuacidad de Géminis, también su capacidad para negociar cualquier cosa y salirse con la suya.\n \nEstos aspectos complementarios, hacen que Géminis y Acuario lleguen a consolidar una amistad.\n \nEsta relación puede ponerse en peligro sólo por las ansias de libertad de Géminis, que no considerará necesario dar explicaciones a su amigo y paradójicamente también por sus celos, ya que considerará una traición si a su vez Acuario no le hace partícipe de sus planes o de otros aspectos de su vida.\n \nSerá tarea de ambos que Géminis y Acuario puedan hacer perdurar su amistad en el tiempo.",
	},
	Love: Love{
		Match:  "85%",
		Traits: []string{Harmonious},
		Summary: SummaryPercentage{
			Text:  "Géminis necesita una pareja que no le aburra ni le cohíba.\n \nVisto así, se podría decir que no hay mejor pareja para ellos que el fabuloso Acuario.\n \nAcuario necesita a alguien que comprenda sus ideas grandiosas y discuta cada una de ellas con él, y también a alguien que no le haga sentirse cohibido.\n \n¿Quién podría hacerlo mejor que Géminis? Sin embargo, podrían encontrarse en una relación que no tenga suficiente emoción y compasión, y es seguro que esto saldrá a la superficie en cuanto ocurra la primera cosa perturbadora en la vida de uno de estos miembros de la pareja.\n \nNecesitan trabajar su base emocional y su comprensión no verbal si quieren que su relación dure.",
			Match: "85%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Géminis y Acuario probablemente podrían tener relaciones sexuales con una simple estimulación verbal.\n \nNo necesitan desnudarse para tener una experiencia sexual, aunque querrán estar desnudos todo el tiempo para liberarse de todas las restricciones humanas.\n \nSe perderán de camino a algún sitio y tendrán sexo allí.\n \nA ambos les excitará el lado intelectual de su relación y, si quieren estar satisfechos, tendrán que considerarse inteligentes el uno al otro.\n \nNi Géminis ni Acuario tendrán una relación seria con alguien que, en su opinión, sea estúpido.\n \nIncluso lo que ellos llamarían un 'encuentro sexual insignificante' tiene que ser con alguien suficientemente inteligente.\n \nGéminis es un poco infantil y puede avergonzarse en ciertas situaciones, pero cuando Acuario tome el control, Géminis se dará cuenta de que no hay límites para su libertad de expresión.\n \nEstos miembros de la pareja lo intentarán todo, se comunicarán en exceso y aprenderán rápidamente sobre el cuerpo del otro.\n \nSin embargo, su relación podría carecer de emoción y de verdadera intimidad física.\n \nEsto podría llevarles a distanciarse, a menudo sin ser conscientes de que ambos necesitan algo más en su pareja.",
			Match: "85%"},
		Trust: SummaryPercentage{
			Text:  "La confianza es algo extraño para esta pareja.\n \nDebemos hacer hincapié en que confiarán el uno en el otro.\n \nAcuario considera que mentir es ridículo y Géminis, por lo general, se sentirá lo suficientemente libre como para no mentir.\n \nPor otro lado, Acuario comprende la necesidad de intimidad, ya que es un signo en el que Neptuno está exaltado.\n \nEs probable que ambos confíen plenamente en su pareja y rara vez se dejen engañar, debido a su premisa de dar y recibir libertad como prioridad absoluta.\n \nA ninguno de ellos le satisfará contar historias o mentir cuando hay tantas cosas interesantes de las que hablar con su pareja rara, y tan poco que compartir que será juzgado.",
			Match: "90%"},
		Communication: SummaryPercentage{
			Text:  "Cuando Géminis y Acuario se enzarzan en un debate intelectual, son divertidos de ver para todos.\n \nEstimulan la mente del otro hasta tal punto que disparan argumentos que no sabían que existían en sus pensamientos.\n \nLa cualidad mutable de Géminis les permitirá adaptarse a algunas de esas actitudes y opiniones rígidas de Acuario, aunque no estén de acuerdo.\n \nGéminis tiene una naturaleza apacible que comprende el flujo del contacto social con otras personas, y rara vez luchará por sus creencias con alguien a quien se sienta realmente cercano.\n \nEsto es bueno para su vida cotidiana, pero en general, puede suponer un problema porque la auténtica personalidad de Géminis podría quedar silenciada hasta que ya no estén seguros de quiénes son, una vez más.\n \nLo mejor es que compartan la misma filosofía de vida, que es lo que suelen hacer, o podrían distanciarse y perder el interés el uno por el otro.\n \nComo dos representantes del Aire, consideran que la comunicación es la solución a cualquier problema, pero no son conscientes de lo lejos que pueden llegar de la Tierra con sus ideas sin realizar y sus objetivos sin alcanzar por culpa de demasiada palabrería y muy poca acción.",
			Match: "99%"},
		Emotions: SummaryPercentage{
			Text:  "Podríamos decir que Géminis y Acuario se entienden perfectamente cuando se trata de sus emociones.\n \nNormalmente esto es cierto, pero eso no significa que sea lo que ambos necesitan.\n \nLa naturaleza inestable de Géminis puede hacerles cambiar de opinión o de estado emocional a diario, y si no se sienten bien en una relación, se liberarán sin darle demasiadas vueltas a las razones por las que han tenido que hacerlo.\n \nAcuario siempre tiene prisa por liberarse de cualquier cosa o persona, por lo que una ruptura no sería algo extraño en su mundo.\n \nEn la mayoría de los casos, sus naturalezas racionales y mentales se complementarán de forma excitante, pero no hay mucha emoción que construir en el núcleo de su relación.\n \nParece que estos dos compañeros necesitan encontrar a alguien un poco más cálido para sentir las cosas más profundamente y encender sus apasionados corazones.\n \nEs mucho más frecuente que se conviertan en amigos que en amantes, aunque se sintieran atraídos el uno por el otro cuando se conocieron.",
			Match: "40%"},
		Values: SummaryPercentage{
			Text:  "Baste decir que ambos valoran el intelecto.\n \nEl resto es algo que preocupa a otros signos.\n \nSin embargo, Acuario puede ser muy apasionado con sus creencias humanas y a menudo las apoyará firmemente.\n \nEsto es algo que Géminis puede comprender pero que rara vez apoya.\n \nDebido al hecho de que la pareja de Acuario valora la igualdad de las personas tanto como su propia libertad, éste puede ser su punto de separación, aunque la pareja de Géminis no esté realmente en desacuerdo.",
			Match: "95%"},
		SharedActivities: SummaryPercentage{
			Text:  "Acuario es el único signo capaz de sorprender realmente a Géminis.\n \nSon tan diferentes a los demás y representan un peldaño que Géminis debe subir si quiere que su vida sea increíble.\n \nEsto no siempre es así porque algunas de las rarezas de Acuario pueden ser un alarde, diseñado por su necesidad de enmendar su turbulento Sol.\n \nAun así, es emocionante para ambos entrar en esta relación: Acuario para sorprender y Géminis para seguirles allá donde vayan.\n \nSu principal actividad compartida es el movimiento.\n \nPodrían conducir miles de kilómetros sólo para encontrar un helado específico o sin motivo alguno.\n \nEn general, pueden hacer cualquier cosa juntos, desde viajar y salir de fiesta hasta leer etiquetas e instrucciones sobre el uso de distintos utensilios de cocina.",
			Match: "99%"},
	},
}
