package compatibilities

var Geminicancer = Compatibility{
	Name: Gemini + " - " + Cancer,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{MutualRespect, CautionRomance},
		Summary: "Muchos vínculos de amistad entre Géminis y Cáncer proceden ya de las etapas más jóvenes de la vida, incluso de la infancia.\n \nA ambos les gusta tener por amigos a alguien a quien conocen en profundidad y que les conoce a ellos del mismo modo.\n \nÉste es un punto coincidente entre Géminis y Cáncer que ya en la edad adulta son mucho menos afines, aunque en el terreno de la amistad son más compatibles que en el amor.\n \nMuchas veces consiguen encontrar el equilibrio entre la personalidad cerebral e intelectual de Géminis y la sensibilidad emocional de Cáncer, que se rige por lo que siente.\n \nCuando coinciden por primera vez, Cáncer se sentirá cautivado por el espíritu emprendedor de Géminis y saldrá con más rapidez de lo habitual de su caparazón para intentar conocerle mejor.\n \nCáncer seguramente intentará enseñarle a Géminis las ventajas de ir más lento y apreciar mejor las cosas que la vida pone por delante.\n \nLe aportará equilibrio.\n \nEntre Géminis y Cáncer se establecerá una relación de protección por parte del primero, con la que el segundo se sentirá cómodo y seguro.\n \nLa capacidad instintiva de Cáncer puede ayudar también al irreflexivo Géminis, que muchas veces se lanza sin red a los retos de la vida.",
	},
	Love: Love{
		Match:  "21%",
		Traits: []string{DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "Géminis y Cáncer están uno al lado del otro en el zodíaco, y es probable que también lo estén en la amistad.\n \nCuando se trata de relaciones emocionales o sexuales, parece que hay demasiadas cosas que los separan.\n \nPara que su relación dure, ambos necesitan hacer algunos ajustes.\n \nGéminis difícilmente cambiará su rutina por alguien, especialmente cuando encuentra aburrida la forma de vida de alguien, así que lo mejor que se puede hacer aquí es darle su libertad.\n \nSi Cáncer se enamora lo suficientemente profundamente, entenderá lo que su pareja Géminis necesita, y no lo retendrá aunque deseara que fuera diferente.\n \nLa pareja Géminis tiene que abrir su corazón y escuchar esas pocas palabras que Cáncer quiere compartir.\n \nA pesar de que pueden hablar de muchas cosas, cuando se trata de discusiones de su relación, sus puntos de vista sobre ella son diferentes.\n \nGéminis necesita mantener el interés y Cáncer necesita ser escuchado, tanto como sentido.\n \nSi se dan la suficiente libertad y comprensión, podrían ser como niños enamorados por primera vez.",
			Match: "21%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Géminis saldría fuera y tendría las experiencias sexuales más extrañas, y Cáncer se quedaría en casa y esperaría a la noche para ser amado por su tierna pareja.\n \nNo siempre es así, por supuesto, pero es muy raro que una pareja Géminis consiga relajar a su Cáncer y hacer que se una a su aventura sexual.\n \nAún así, existe un vínculo entre ellos, bastante fuerte por cierto.\n \nCáncer continúa el signo de Géminis, y en cierto modo su naturaleza es consecuencia de interminables conversaciones y explicaciones racionales.\n \nSi la pareja Géminis tiene la paciencia suficiente para hablar con su pareja sobre las mismas cosas una y otra vez, con el tiempo podrían construir la intimidad suficiente para tener una buena vida sexual.\n \nPara que este escenario se desarrolle, Cáncer también necesita hablar.\n \nNo bastará con decir una o dos frases y esperar que su Géminis entienda cómo se sienten.\n \nSi logran comunicarse, Cáncer podría realmente despertar la profundidad de su Géminis, dándole el apoyo suficiente para expresar su personalidad sexual más emocional.\n \nSi quieren que su relación funcione, su vida sexual debe estar en algún punto intermedio -lo suficientemente íntima y excitante- para que ambos estén satisfechos.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "Géminis es un signo regido por Mercurio, nuestro pequeño embaucador.\n \nNo es fácil confiar en la pareja de un Géminis, sobre todo si uno intenta arrebatarle su libertad.\n \nComo signo racional, no suelen encontrar motivos para mentir o engañar a su pareja, siempre que no se sientan amenazados por una intimidad para la que no están preparados, o atados.\n \nLa principal tarea de Cáncer en una relación con Géminis es dejarles ser libres.\n \nSi empiezan a vivir juntos, Géminis tendrá que permanecer fuera de su nido de amor y Cáncer pasará mucho tiempo solo.\n \nEsto es un reto, pero ambos signos pueden tener suficiente dedicación a sus valores personales, y estos compañeros deberían saber que no deben arruinar su relación con mentiras triviales.",
			Match: "25%"},
		Communication: SummaryPercentage{
			Text:  "Probablemente no haya ningún signo del zodíaco con el que Géminis no pueda hablar, por lo que sus habilidades comunicativas marcan esta categoría un poco más alta en todos los casos.\n \nEn su relación con una pareja Cáncer, suelen sentir la necesidad de abrirse un poco más y compartir cosas que no compartirían con otras personas.\n \nHay un cierto brillo 'maternal' alrededor de Cáncer, sea hombre o mujer, que da a Géminis suficiente espacio para dejar libre a su niño interior.\n \nEn realidad, ésta puede ser una relación maravillosa que dure mucho más que otras relaciones de Géminis, porque en Cáncer suele haber suficiente comprensión para su pareja infantil.\n \nEsto es, si otros aspectos de la relación son lo suficientemente satisfactorios.\n \nEs seguro decir que Cáncer y Géminis son buenos amigos y esto podría dar un empujón en la dirección correcta hacia su comprensión emocional y sexual también.",
			Match: "70%"},
		Emotions: SummaryPercentage{
			Text:  "La principal posibilidad negativa aquí estaría en el hecho de que Géminis no siempre escucha.\n \nA menudo se dice que Géminis es un signo superficial, pero en realidad, les gusta mantenerse a flote y alejarse de las conversaciones difíciles debido a su necesidad de seguir adelante.\n \nCáncer puede intentar compartir sus emociones con demasiada frecuencia como para que Géminis tenga la paciencia suficiente para entenderlas, y esto puede ser devastador para su relación afectiva.\n \nPor otra parte, Géminis no muestra realmente sus emociones de un modo que Cáncer pueda reconocer fácilmente.\n \nEs una suerte que sean capaces de encontrar emociones en cualquier cosa y en cualquier persona, así podrían tener la oportunidad de comprender la naturaleza emocional de su Géminis infantil.",
			Match: "10%"},
		Values: SummaryPercentage{
			Text:  "Tienen sistemas completamente distintos de valorar las cosas en la vida.\n \nMientras que Géminis es un signo racional, que da valor a todo lo que sale de su mente, Cáncer es un gurú emocional, que da valor a las cosas por las que late su corazón.\n \nCuando se trata de relaciones, probablemente sean los más vulnerables a las diferencias en esta categoría, ya que las diferencias aquí hacen que sus objetivos primarios sean distintos.\n \nAunque ambos estarán motivados para encontrar el amor, la forma de actuar de su pareja en una relación podría considerarse 'errónea' debido a su naturaleza opuesta a lo que cada uno de ellos valora.",
			Match: "1%"},
		SharedActivities: SummaryPercentage{
			Text:  "Las actividades que Géminis y Cáncer podrían compartir dependen principalmente del nivel de energía de la pareja Cáncer.\n \nSi tienen suficiente de ella para seguir el horario caótico de Géminis, podrían encontrar un montón de cosas agradables que hacer juntos.\n \nCáncer es un signo que exalta a Júpiter, y a sus representantes les gusta viajar, tanto como sentirse en casa debido al propio signo.\n \nAunque la pareja de Géminis no tiene por qué ir tan lejos, podrían encontrar un término medio viajando a lugares que ambos quieran visitar.\n \nSin embargo, la principal característica de Géminis es su curiosidad.\n \nLes llevará en todas direcciones, sentirán la necesidad de probarlo todo y encontrar más experiencias nuevas y emocionantes que compartir con alguien.\n \nPor desgracia, Cáncer no disfruta tanto con esto.\n \nMientras la relación sea nueva, todo le parecerá excitante e impresionante.\n \nA medida que pase el tiempo, Cáncer querrá sentar la cabeza, imaginándose comprando muebles juntos y criando hijos.\n \nNo es fácil para ellos aceptar que esta naturaleza que tiene Géminis no es algo que será diferente mañana.\n \nNo se puede sentar la cabeza con una pareja Géminis.\n \nEsta no es su misión en la vida.",
			Match: "15%"},
	},
}
