package compatibilities

var Leoaquarius = Compatibility{
	Name: Leo + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "65%",
		Traits:  []string{Stormy},
		Summary: "Es precisamente en este terreno donde se comprenderán mejor Leo y Acuario.\n \nLa extravertida personalidad de Leo y su carácter hacen que para Acuario se convierta muy pronto en un compañero o compañera indispensable.\n \nCon su gente cercana, Leo siempre se muestra entrañable, aliado en las desdichas y dispuesto en todo momento a participar de la lucha de su amigo.\n \nAcuario reconoce desde el prime instante que no encontrará otro amigo como Leo, con tanta disposición.\n \nY éste también necesita a alguien que de vez en cuando le ponga los pies en el suelo.\n \nSe complementan maravillosamente y lo descubrirán muy pronto.\n \nCuando esto ocurra, Leo y Acuario se convertirán en inseparables.\n \nJuntos podrán divertirse, viajar, acudir a esas reuniones sociales que tanto les gustan, y se encontrarán siempre en su salsa.\n \nTanto Leo como Acuario, son personas que no suelen dar marcha atrás, gente con quien siempre se puede contar.\n \nEl único riesgo es el deseo de protagonismo de ambos.\n \nEn algunas ocasiones, Leo puede sentirse eclipsado por Acuario y esto no le va a gustar.\n \nSi acuario quiere tener la fiesta en paz, es mejor que le dé espacio para que brille.\n \nEn realidad, estas cuestión en Leo no es vanidad sino necesidad que le impregna la esencia de su signo",
	},
	Love: Love{
		Match:  "89%",
		Traits: []string{Volatile, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "Los signos de Leo y Acuario combinados representan la máxima creatividad, famosos descubrimientos científicos, el primer hombre en un avión y el primer hombre en la Luna.\n \nImagina lo que estos dos podrían hacer juntos si se dejaran llevar el uno por el otro cuando tienen ante sí el territorio de su dominio.\n \nAmbos necesitan aprender a desprenderse de la imagen que tienen de sí mismos y del otro, o no llegarán muy lejos atascados en su innecesaria batalla de egos.\n \nCálidos y fríos, con corazón e inteligentes, gravitación nuclear y vacío en el espacio, no puede ser fácil arreglar sus diferencias ni formar una relación estable y amorosa.\n \nLo mejor que podrían hacer es encontrar una causa que apoyen juntos.\n \nEsto les centraría en el mundo exterior y les permitiría profundizar en el mundo emocional interior de su relación mientras luchan fuera de él.",
			Match: "89%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La atracción siempre es grande en las relaciones de signos opuestos, y probablemente sea la mayor en una relación de Leo y Acuario.\n \nLeo es el rey de todo el zodíaco, y Acuario parece estar ahí para derribar al rey y luchar por la independencia.\n \nImagina la atracción y la pasión entre dos individuos tan fuertes, situados en el eje del dominio y el detrimento del Sol.\n \nSu vida sexual es una lucha, una pelea y una experiencia increíble para ambos.\n \nLiberadora pero cálida y apasionada, sensual pero interesante.\n \nCuando encuentran la verdadera emoción, Acuario puede acabar respetando al rey.\n \nLa belleza de su vida sexual está en las cosas que pueden aprender sobre sus cuerpos, su confianza y su forma de ver el acto sexual.\n \nA través de la lucha de inseguridades y la liberación forzada, son dos compañeros para formar una fuerte conexión por un simple acto de gravitación que el Sol tiene sobre Urano.",
			Match: "99%"},
		Trust: SummaryPercentage{
			Text:  "Todo parece claro en una relación entre Leo y Acuario cuando la miramos desde la distancia.\n \nSin embargo, estos signos representan el eje de exaltación y caída de Neptuno, y casi siempre tendrán el reto de la confianza y la búsqueda de la verdad en su relación.\n \nAunque podrían encontrar una comprensión y una libertad increíbles para ambos miembros de la pareja, normalmente cuando se separan se dan cuenta de lo poco que han sabido realmente el uno del otro y de la poca confianza que compartían en un principio.",
			Match: "75%"},
		Communication: SummaryPercentage{
			Text:  "Tanto Leo como Acuario son héroes a su manera.\n \nMientras Acuario busca el heroísmo para liberarse de la represión, Leo nació héroe y a veces ni siquiera lo sabe.\n \nSi acaban luchando por la misma causa, podrían derribar gobiernos enteros y utilizar su increíble fuerza para cambiar cualquier cosa en el mundo.\n \nPara conseguirlo, estos dos tendrían que detener la batalla que mantienen entre sí, porque la energía puede dispersarse en su innecesaria lucha por el dominio en una relación.\n \nLeo es un signo regido por el Sol y tiene la capacidad de dar claridad a cualquier situación.\n \nNo importa lo confusos que puedan estar o lo perdidos que parezcan, si analizas detenidamente el tiempo que has pasado con ellos, verás que han aportado claridad a tu vida.\n \nAcuario, por otro lado, comprende la necesidad del cambio y parecen llevar consigo una chispa para encender y excitar cualquier posible situación que les parezca digna.\n \nEsto puede resultar irritante para muchos, especialmente para Leo, pero en realidad es una necesidad de liberación que todos llevamos dentro.",
			Match: "90%"},
		Emotions: SummaryPercentage{
			Text:  "Leo es exactamente lo que Acuario necesita para encontrar el amor.\n \nEs una cosa extraña cómo se encuentran el uno al otro, sobre la base de sus relaciones anteriores, para liberar y brillar como si hubieran estado buscando el uno al otro durante muchas vidas.\n \nMientras Leo es el Sol, Acuario es un relámpago y suele salir en un día lluvioso.\n \nEsto es exactamente lo que tienen que entender: hay un momento para que ambos brillen y no ponen en peligro la oportunidad del otro de hacerlo.\n \nCuando Leo se enamora, el mundo entero puede sentirlo.\n \nLa calidez brota del centro de su ser y hay que estar ciego o insensato para no captar las señales.\n \nAcuario puede ocultar sus emociones mucho mejor y a menudo tiene problemas para expresar y reconocer lo que siente.\n \nEs una buena cosa que la cálida naturaleza emocional de Leo derretirá incluso el más frío de los corazones y no habrá lugar más seguro para Acuario para compartir su amor que en estos brazos de fuego.\n \nLo único que puede poner en peligro su relación afectiva es su eterna batalla de egos y ambos deberán prestar atención a no ser demasiado orgullosos para dejarse llevar por el amor.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "El valor más profundo que comparten es el de la individualidad.\n \nAlguien con un carácter fuerte, que sabe exactamente lo que quiere, no puede pasar desapercibido ni para Leo ni para Acuario.\n \nAunque no estarán de acuerdo en muchas otras cosas, esta es la que podría conectarlos fuertemente, porque ambos son individuos tan fuertes a los ojos del otro.",
			Match: "80%"},
		SharedActivities: SummaryPercentage{
			Text:  "Mientras Leo brilla, a Acuario le gusta todo lo brillante.\n \nLa necesidad que tiene Leo de presumir puede verse un poco perturbada por la tendencia de Acuario a mostrar lo que los demás no quieren ver.\n \nDesde otra perspectiva, esto debería ayudar a Leo a sentirse más libre y seguro de sí mismo, aunque al principio no lo parezca.\n \nA ambos les gustará mostrarse, cada uno a su manera, y sólo es importante que establezcan el territorio para que ambos se expresen.\n \nAl igual que el Sol y el rayo no van juntos, Acuario deberá tomar el mando en un día lluvioso, en una multitud depresiva o en lugares donde ambos sientan que se van a ahogar.\n \nAquí es donde Leo debe ceder y dejar que su pareja gobierne el cielo si piensa mantener la relación.\n \nHabrá suficientes oportunidades regulares y brillantes y días sin nubes para que Leo gobierne.",
			Match: "90%"},
	},
}
