package compatibilities

var Leocapricorn = Compatibility{
	Name: Leo + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "30%",
		Traits:  []string{NothingInCommon},
		Summary: "Las diferencias de objetivos y caracteres de Leo y Capricornio, se manifiestan con bastante fuerza en el terreno de la amistad.\n \nLeo busca en sus amigos que se impliquen en sus deseos y aventuras, que se conviertan de algún modo en sus cómplices.\n \nCapricornio, por su parte, ama también tener alrededor muchos amigos, igual que le sucede a Leo, pero desea elegirlos, no todo el mundo vale para tener amistad con un Capricornio.\n \nCuando Leo y Capricornio coinciden en un entorno social, el estilo desenfadado y directo de Leo, esa camaradería que siempre muestra el león, no hará mella en Capricornio.\n \nSi salvan este primer obstáculo que impediría una relación de amistad entre ellos, tendrán también que ponerse de acuerdo en temas realmente esenciales para que todo funcione.\n \nLeo y Capricornio se encontrará con posturas muy distintas ante la vida.\n \nLeo ama el compromiso y la coherencia que demuestra Capricornio, pero sufre por sus críticas y sus exigentes rutinas.\n \nY el tradicional Capricornio se siente atraído por la expresividad y creatividad de Leo pero se cansará pronto de sus impulsos y sus reacciones un tanto dramáticas.\n \nEl esfuerzo mutuo tendrá que ser importante si consideran que su amistad lo vale.",
	},
	Love: Love{
		Match:  "27%",
		Traits: []string{Volatile, NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "Si se encuentran en el momento adecuado, Leo y Capricornio pueden llevarse muy bien.\n \nEl principal problema en su relación es el conjunto de prioridades que podrían no compartir, y la pasión o determinación que ambos tienen.\n \nNo es un trabajo fácil, reconciliar a Saturno con el Sol, pero trae grandes beneficios cuando se hace.\n \nLa estructura que Leo podría obtener y la creatividad que podrían construir juntos podrían elevarlos exactamente a lo que desean, sin importar cómo termine su relación.\n \nDifieren tanto como la Tierra y el Fuego, pero cuando comparten un objetivo común, son imparables.",
			Match: "27%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Leo y Capricornio tienen una cosa en común y es la conciencia de sí mismos.\n \nSerá rara la ocasión en la que Leo se sienta atraído por un Capricornio, pero la atracción a la inversa parece más probable.\n \nSin embargo, no llegarán a menudo a la parte sexual de su relación, pues aunque ambos disfruten de la persecución, no verán su futuro juntos.\n \nLeo es un signo cálido y apasionado, y a Capricornio le gusta ser frío y práctico.\n \nEsto no quiere decir que Leo no sea práctico, ni que Capricornio no sea apasionado, pero no se verán de ninguna manera similares.\n \nEsto suele encenderse por la libertad de expresión sexual de Leo que Capricornio teme, lo que provoca inseguridad en ambos miembros de la pareja porque no son capaces de encajar en el conjunto de expectativas del otro.\n \nSu vida sexual puede volverse aburrida para ambos, y a menudo no se dan cuenta de lo parecidos que son.\n \nLa única manera de que tengan una vida sexual sana es compartir el calor y aportar siempre nuevas experiencias, condimentando las cosas.\n \nSi se encuentran en la rutina, pueden permanecer en ella durante mucho tiempo, lo que lleva a la pérdida de libido y confianza, hasta la pérdida de todo deseo sexual.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "Capricornio sabe que Neptuno cae en Leo.\n \nPor eso también sabe lo que se esconde detrás de la actuación de su pareja Leo.\n \nLa profundidad a la que Capricornio está dispuesto a llegar hace que su pareja Leo se cuestione sus propios motivos y toda su personalidad.\n \nLas mentiras parecen imposibles en esta relación, ya que cada mentira dicha, vuelve de inmediato.\n \nTanto como Capricornio ve detrás del brillo de Leo, Leo ilumina la oscuridad de Capricornio.\n \nNada permanece oculto durante mucho tiempo y en cuanto uno de los dos intenta mantenerse en secreto, se despierta la desconfianza.\n \nSin embargo, en muchas situaciones tienden a confiar el uno en el otro porque resulta tan obvio que no hay razón para no hacerlo.",
			Match: "40%"},
		Communication: SummaryPercentage{
			Text:  "Sus prioridades difieren enormemente, y ambos tienen un fuerte conjunto de prioridades personales en sus vidas.\n \nEsto es algo que no se conciliará fácilmente y estos socios podrían pasar demasiado tiempo intentando demostrarse el uno al otro por qué cada uno de ellos tiene un punto de vista sobre lo que es primero.\n \nEl problema está en la falta de comprensión de que cada uno de ellos tiene su propia misión y su propio papel.\n \nEs inútil insistir en que cambien las prioridades de alguien cuando, para empezar, deberían ser diferentes.\n \nSi se respetan lo suficiente como para aceptar algunas diferencias bastante grandes, su comunicación podría ser muy satisfactoria y plena para ambos.\n \nLeo ayudará a Capricornio a encontrar una visión más positiva y creativa de cada situación y Capricornio dará a Leo la profundidad y las intenciones serias que necesita.\n \nCuando combinan sus habilidades para organizar, cualquier plan que se haga podría ser perfecto.",
			Match: "60%"},
		Emotions: SummaryPercentage{
			Text:  "Una relación entre un Leo y un Capricornio puede ser un verdadero reto emocional, no porque no se quieran, sino porque se aman.\n \nLas emociones cálidas de Leo se enfrían y entierran con facilidad, y sin la capacidad de expresar amor, Leo puede deprimirse bastante.\n \nA cambio, el tiempo que Capricornio necesita para construir la historia emocional que necesita, se verá bruscamente interrumpido por su fogosa pareja Leo.\n \nEsto podría herirles o llevarles a la opinión de que Leo no es la persona adecuada para ellos, por muy atractiva, inteligente, capaz o guapa que sea.\n \nEl problema con esta pareja está en la forma en que construyen las emociones, y sus mejores oportunidades están en el tiempo y la paciencia, cosas que Leo rara vez posee, y Capricornio domina.\n \nNo hay otra forma de llegar al corazón de una pareja Capricornio y descubrir que también puede ser cálida.\n \nSi ha habido demasiado dolor en sus relaciones afectivas anteriores, ambos miembros de la pareja podrían ser casi demasiado tercos para llegar al punto en el que realmente podrían enamorarse.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Tanto Leo como Capricornio valoran a las personas bien organizadas, las presentaciones y los planes.\n \nLeo no es un gran hacedor de planes, prefieren ir con la corriente y mirar sólo un par de días de antelación, y respetan la capacidad de Capricornio para centrarse en el destino final y sopesar cada paso del camino.\n \nAún así, el centro sensible, tranquilo y emocional que Capricornio valora nunca se encuentra en un Leo y, a menos que se sientan realmente inspirados por su pareja Leo, podrían restarle valor sólo por sus preferencias.\n \nLeo valora a las personas directas, de corazón abierto y grandes sonrisas, y en cuanto juzgan a Capricornio por no sonreír todo el tiempo, bien podrían terminar la relación.",
			Match: "50%"},
		SharedActivities: SummaryPercentage{
			Text:  "Una vez más, las actividades que puedan compartir estas parejas dependerán en gran medida de sus prioridades.\n \nSi Leo quiere sentar la cabeza, puede que le resulte interesante pasar el tiempo a la manera habitual de Capricornio.\n \nA cambio, si Capricornio necesita un poco más de energía y vigor, estará encantado de seguir a Leo en las actividades que elija.\n \nLo más importante en su relación es el buen momento.\n \nSi no existe, simplemente se resistirán, obstinadamente, a hacer cualquier cosa que la otra persona quiera hacer.",
			Match: "5%"},
	},
}
