package compatibilities

var Leolibra = Compatibility{
	Name: Leo + " - " + Libra,
	Friendship: Friendship{
		Match:   "95%",
		Traits:  []string{GoodRomancePotential, ExcellentAdvisors, DeepMutualUnderstanding},
		Summary: "Cuando dos signos son tan complementarios como Leo y Libra, la amistad surgirá espontánea, brotará como una fuente desde el mismo momento en que ambos entren en contacto.\n \nA Leo le encantará que la creativa Libra le aporte montones de ideas y sugerencias para salir, para viajar, para quedar con otros amigos o para practicar deporte.\n \nTodo lo que diga Libra, Leo lo secundará y le aportará ese toque de seguridad que manifiesta el león en todas sus acciones.\n \nEsto supondrá para Libra una dosis extra de confianza en sí misma y de autoestima porque el signo de la balanza necesita siempre dudar menos antes de tomar sus decisiones.\n \nLeo y Libra se apreciarán y disfrutarán el uno del otro como no podrían hacerlo con ningún otro signo.\n \nSólo tienen que cuidar algún pequeño detalle, como por ejemplo que Libra en ocasiones tendrá que tener paciencia con la arrolladora personalidad de Leo, mientras que éste tendrá que moderar un poco su carácter autoritario para no hacer sentir a Libra en inferioridad de condiciones.\n \nEn realidad no lo está, simplemente es una forma de proceder o de actuar que hace pensar que Libra tiene menos autoridad que Leo en una relación de amistad.\n \nAmbos, Leo y Libra, están a la par.",
	},
	Love: Love{
		Match:  "75%",
		Traits: []string{Harmonious},
		Summary: SummaryPercentage{
			Text:  "Si quieres resumir la relación entre un Leo y un Libra, tienes que entender que su vínculo implica las bellas y desafiantes dignidades de Saturno y el Sol.\n \nTienen mucho que aprender el uno del otro, y el objetivo principal de su relación es alcanzar el punto de respeto y responsabilidad compartidos en un perfecto equilibrio de poder.\n \nA veces les resultará difícil superar la necesidad de competir, intentando determinar quién es mejor, más inteligente o más capaz.\n \nAunque no lo consigan, su relación será algo de lo que disfrutar y presumir en público.",
			Match: "75%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando un Leo y un Libra se juntan, no necesitan mucho tiempo para construir una vida sexual sana.\n \nCon la confianza de Leo y la sexualidad de Libra, tienden a inspirarse mutuamente para convertirse en grandes amantes cuando están juntos.\n \nSu vida sexual suele estar llena de respeto y se sienten libres para probar cosas nuevas el uno con el otro.\n \nSi fundan su relación en una fuerte atracción mutua, podrían disfrutar de una vida sexual satisfactoria durante mucho tiempo.\n \nA Leo no le importa ser visto y Libra es un signo que representa el ojo público.\n \nAunque esto también dice algo sobre sus preferencias sexuales, normalmente se comportarán bien en público.\n \nEn cuanto aparezca alguna restricción, tendrán que representar sus apasionados escenarios en cualquier momento y en cualquier lugar en el que tengan la oportunidad de estar solos aunque sólo sea un minuto.\n \nLibra es un signo de exaltación de Saturno y les resulta fácil esperar y ser racionales, pero con el apasionado Leo les cuesta mantener el control.",
			Match: "90%"},
		Trust: SummaryPercentage{
			Text:  "No es muy frecuente que Leo y Libra compartan una relación llena de confianza mutua.\n \nEl problema aquí surge de su comprensión del Sol, ya que rige Leo y cae en Libra.\n \nPor si fuera poco, Leo es un signo de caída de Neptuno y Libra a menudo puede percibir la falta de honestidad detrás del acto de confianza de Leo, si es que la hay.\n \nEl problema radica en que a ambos les gusta ser vistos, pero de un modo totalmente distinto.\n \nLeo quiere mostrar todo lo que tiene y Libra quiere obtener la aprobación de los demás.\n \nNinguno de los dos entiende al otro, y esto puede convertirse en motivo de celos y desconfianza.\n \nSi desean permanecer en una relación de confianza, necesitan encontrar aprobación y un público adecuado en el otro para empezar.\n \nSólo entonces podrán seguir adelante y buscar estas cosas en otras personas sin levantar sospechas.",
			Match: "40%"},
		Communication: SummaryPercentage{
			Text:  "Cuando se trata del lado racional de su relación, Leo y Libra tienen una forma muy agradable de apoyar la personalidad del otro y de comunicarse.\n \nEl sextil entre sus Soles suele hacer posible que se respeten mutuamente y se ayuden a construir personalidades más fuertes, libres de juicios de cualquier tipo.\n \nSus elementos Fuego y Aire encajan perfectamente y hay un enfoque apasionado de Leo para cada idea de Libra.\n \nSu comunicación es rápida e inspiradora, aunque a veces difícil de aterrizar a través de ideas constructivas si Libra no confía en su relación fría y racional con Saturno.\n \nEl problema surge si Libra siente algún tipo de celos de su pareja Leo por su confianza a veces infundada y esa sensación de seguridad interior.\n \nLa única manera de que Libra aprenda también a sentirse seguro de sí mismo es aceptar esta capacidad de Leo como la mejor parte de su hermoso carácter.\n \nSi Libra empieza a juzgar a Leo, a hacer suposiciones sobre cómo debería comportarse su pareja pero no lo hace, su respeto mutuo se desvanecerá y ambos perderán el sentido de su relación.",
			Match: "85%"},
		Emotions: SummaryPercentage{
			Text:  "Estos dos signos representan nuestras relaciones amorosas y el matrimonio, y cuando observes a esta pareja, verás que su amor mutuo es real, obvio, demostrado y que les lleva en una dirección determinada.\n \nNunca acabarán en una relación sin futuro, y su fe en el amor les llevará al matrimonio, a tener hijos y a envejecer juntos, si comparten la confianza y el amor suficientes.\n \nRegidos por el Sol y por Venus, estos signos representan uno de los ciclos planetarios básicos del amor, a menudo relacionado con periodos de ocho años.\n \nSi permanecen juntos más de ese tiempo, bien podrían pasar por el altar y tener un montón de hijos.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Nada tiene más valor para Leo que la fuerte personalidad de alguien y su propio orgullo y heroísmo.\n \nLibra, en cambio, valora la justicia y la capacidad de ser el héroe, algo de lo que a menudo piensan que carecen.\n \nSon finamente compatibles cuando se trata de asuntos del Sol y se complementan bien de manera que ambos aprenden a expresarse y a conocer sus habilidades y puntos fuertes.\n \nEl problema de esta pareja está en su relación hacia Saturno, y mientras Leo representa su detrimento, Libra lo exalta.\n \nAunque esto puede ser una lección que aprender, el reto de la responsabilidad que asumen de forma desigual puede separarlos.\n \nLeo necesita ponerse serio y darse cuenta de cuál es su responsabilidad para encajar en lo que Libra más valora: la fiabilidad y el tacto.",
			Match: "75%"},
		SharedActivities: SummaryPercentage{
			Text:  "Existe una extraña similitud en la velocidad de estos signos.\n \nLeo es un signo de Fuego y como tal no debería ser lento como un signo de Agua o y Tierra.\n \nLibra pertenece al elemento Aire y debería ser más rápido que cualquier otro elemento.\n \nPero cuando observes a estos dos signos, verás que a Leo le gustaría dormir 20 horas al día, y Libra necesita pensárselo todo dos veces y elegir cuidadosamente las actividades y las palabras que quiere decir.\n \nEsto no suena tan rápido, ¿verdad? Si comparten los mismos intereses, podrían tener un campo infinito de posibilidades para actividades compartidas.\n \nLo que más les gustará serán los eventos de 'alfombra roja' y las reuniones elegantes en las que ambos puedan mostrarse al mundo.\n \nEl mayor problema en la elección de sus actividades radica en la naturaleza indecisa de Libra, que Leo simplemente no entiende y con la que no suele tener paciencia.\n \nAquí es donde pueden caer en la tentación de 'ayudarles' a decidir, tomando el timón y decidiendo en su lugar.\n \nEsto puede llevar a una falta de respeto mutua, aunque parezca una minucia de la que nadie se daría cuenta.\n \nTienen que darse tiempo el uno al otro, y mantenerse lo más independientes posible.",
			Match: "60%"},
	},
}
