package compatibilities

var Leoleo = Compatibility{
	Name: Leo + " - " + Leo,
	Friendship: Friendship{
		Match:   "50%",
		Traits:  []string{PoorAdvisors},
		Summary: "El signo de Leo otorga una personalidad muy sociable a sus nativos y nativas, si esto lo multiplicamos por dos, nos encontraremos con una amistad indestructible aunque a veces surjan diferencias entre ambos.\n \nLeo y Leo formarán todo un equipo siendo únicamente dos.\n \nSu brillantes les abrirá socialmente todas las puertas y su presencia requerida en todo tipo de encuentros, reuniones y eventos.\n \nA los Leo les encanta divertirse, llamar la atención, sentirse admirados y coquetear con todo el mundo.\n \nCuando Leo y Leo entablan una relación de amistad, mostrarán todos estos rasgos pero con la curiosa particularidad de no hacerse sombra el uno al otro.\n \nBrillarán ambos con luz propia.\n \nA ambos les encantará compartirlo todo, la diversión, las aventuras, los avatares de la vida, se sentirán en su salsa si otro Leo les secunda.\n \nAdemás, tienen una cualidad especial que Leo y Leo comparten y que es su alabada creatividad.\n \nConjuntamente, saben aprovechar como nadie lo que les ofrece la vida y su amistad se prolongará sin límite en el tiempo.\n \nSólo han de controlar su carácter autoritario y aprender a ceder a las propuestas del otro Leo, porque en definitiva, sea quien sea de los dos que imponga una acción, seguro que será positiva y divertida.",
	},
	Love: Love{
		Match:  "78%",
		Traits: []string{Volatile},
		Summary: SummaryPercentage{
			Text:  "Dos Leo pueden hacer lo imposible y este hecho podría mantenerlos en una relación perfectamente satisfactoria durante mucho tiempo.\n \nSu principal objetivo es encontrar la verdadera intimidad y comprender el interior emocional del otro.\n \nLeo tiene la costumbre de exagerar y hacer drama de cosas pequeñas e irrelevantes, pero esto podría ser algo bueno para su relación debido a su estatus social y a la capacidad de apoyar las necesidades teatrales del otro.\n \nSi inician una batalla por la supremacía, podría ser una buena idea fijar el territorio del que se encarga cada uno.\n \nSi uno de ellos es el mejor en un departamento emocional, el otro puede serlo en el sexual.\n \nSi se reparten las reglas de esta manera, será mucho más fácil que ambos funcionen y se consideren dignos de la relación.\n \nLo que podría hacer imposible una relación amorosa entre ellos es la falta de respeto.\n \nSi se contagian de este mal, lo mejor será que se separen y busquen parejas diferentes.",
			Match: "78%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La combinación de dos Leos puede ser difícil cuando se trata de intimidad, pero su vida sexual puede ser excelente incluso cuando no tienen ninguna intimidad.\n \nLa naturaleza cálida y el enfoque apasionado de Leo hacia todas las cosas de la vida, incluido el sexo, los mantendrá satisfechos juntos durante mucho tiempo.\n \nSin embargo, hay una cara detrás del acto para estos dos compañeros que podrían ser demasiado orgullosos para mostrar.\n \nSuelen buscar parejas que les ayuden a mostrar su esencia para conectar de verdad en lugar de limitarse a practicar el sexo como un acto instintivo.\n \nEl principal problema que pueden tener dos parejas Leo son sus límites y la posible falta de respeto que sienten el uno por el otro.\n \nAunque a ambos les gustaría estar con alguien tan seguro de sí mismo, podrían aferrarse a esa imagen de confianza durante demasiado tiempo, hasta que afloren todo tipo de inseguridades.\n \nEs difícil desarrollar la cercanía con todo ese fuego en un mismo lugar y, si lo piensas, sólo hay un Sol en nuestro sistema solar y todo gira a su alrededor.\n \nEntonces, ¿qué opinas, puede ser posible tener a dos de ellos en una cama, dando vueltas uno alrededor del otro?",
			Match: "50%"},
		Trust: SummaryPercentage{
			Text:  "Estos dos tienen la profunda convicción de que todo está claro en sus vidas.\n \nAl fin y al cabo, están regidos por el Sol, así que ¿cómo no iba a ser así? Aunque suelen ser abiertos con otras personas, cuando se juntan es como una lucha constante por la supremacía.\n \nEsto puede dar lugar a todo tipo de historias 'infladas', de esas que no se pueden repetir y que casi siempre son producto de la ficción.\n \nLeo es un mal mentiroso, en general, y sería una pena que estos compañeros llegaran al punto de tener que demostrarse algo el uno al otro.\n \nTienen que aprender a estar juntos con absoluta concentración en la otra persona.\n \nEn cuanto se apartan y empiezan a explicar lo geniales que son, han perdido de antemano una oportunidad de confianza.",
			Match: "70%"},
		Communication: SummaryPercentage{
			Text:  "Lo maravilloso de esta relación es la capacidad de ambos para arrojar luz sobre los asuntos importantes del otro.\n \nCuando conectan a un nivel profundamente personal, pueden encontrar un lenguaje especial de aprendizaje y descubrir muchas cosas sobre sus propias situaciones y otras relaciones.\n \nEl problema surgirá cuando comiencen su batalla de egos para demostrarse mutuamente quién tiene razón y quién está equivocado.\n \nCuando dos socios Leo se encuentran en este tipo de conflicto, es imposible resolverlo porque ambos se aferran a sus puntos de vista de que ambos pueden ser correctos.\n \nEn estas situaciones deben esforzarse por encontrar el término medio o podrían acabar en una pelea seria y duradera por una cosa irrelevante.",
			Match: "65%"},
		Emotions: SummaryPercentage{
			Text:  "Leo es un signo de Fuego de cualidad fija, y son bastante difíciles de cambiar.\n \nEl Fuego de Leo crea calor, pasión y energía creativa.\n \nEsto a veces puede no ser reconocido como verdadera emoción, especialmente por los signos de Agua, y es bueno que dos Leo comprendan perfectamente la profundidad emocional del otro.\n \nLo cierto es que Leo es un signo extremadamente emocional.\n \nSe apoya en Cáncer y se desplaza hacia Virgo, por lo que se trata de un signo que tiene la tarea imposible de conectar la emoción pura con el intelecto puro.\n \nSu punto de partida, sin embargo, es la emoción.\n \nSu principal reto en este campo emocional es la forma de expresar lo que siente y cómo no quemarse.\n \nComo todos los signos de Fuego, Leo tiene una naturaleza apasionada que se mueve con fiereza y a veces puede arrepentirse de no haber seguido a su corazón.\n \nSustituyen fácilmente emoción por pasión y a menudo estallan en llamas antes de darse cuenta de lo que sienten.\n \nCuando son dos, su relación puede parecer una reacción nuclear en cadena que carece de fundamento emocional.\n \nSin embargo, hay mucha emoción bajo la superficie si deciden permanecer juntos, pues sólo un Leo sabe cómo se siente después de que el arrebato se haya mostrado al mundo.",
			Match: "90%"},
		Values: SummaryPercentage{
			Text:  "Como dos representantes del mismo signo con características tan fuertes, valoran cosas similares.\n \nEn general, Leo valora la valentía, la claridad y la fuerza interior de las personas.\n \nEs de suponer que se valorarán mutuamente por estos valores primarios.\n \nLo que ambos valorarán más cuando estén juntos es su tiempo para descansar y su tiempo para jugar.\n \nComo si fueran auténticos leoncitos, estos dos son capaces de disfrutar de verdad de su tiempo libre y cada fin de semana podría parecer el paraíso.",
			Match: "99%"},
		SharedActivities: SummaryPercentage{
			Text:  "Imagine una familia de leones en la sabana africana, tumbados todo el día, luego jugando un rato, después lamiéndose las patas y ronroneando tranquilamente, bien alimentados y felices.\n \nAsí es exactamente como podría ser una relación de dos Leos.\n \nAunque pasarían la mayor parte del tiempo en la cama y jugando, en realidad podrían divertirse tanto haciéndolo que no necesitan a nadie más que les haga compañía.\n \nSon seres sociales pero no les importa mucho pasar el tiempo con gente que no sabe disfrutar de la vida, y en la mayoría de los casos disfrutarán de su tropa.\n \nEl único problema que pueden tener está en su necesidad de mantenerse alejados de las cosas que no encajan con su carácter.\n \nComo signos fijos, ambos estarán volcados en una cierta rutina.\n \nAunque la base de la misma será la misma por tratarse de dos Leos, puede que lo hagan de forma diferente.\n \nPor ejemplo, si a uno de ellos le gusta mostrar su admirada personalidad en un club de la calle, tal vez el otro prefiera ir a un buen restaurante y mostrar sus buenos modales.\n \nEs importante que estén abiertos a las sugerencias del otro, porque sólo así podrán fusionar sus mundos.",
			Match: "85%"},
	},
}
