package compatibilities

var Leopisces = Compatibility{
	Name: Leo + " - " + Pisces,
	Friendship: Friendship{
		Match:   "30%",
		Traits:  []string{CautionRomance, Stormy},
		Summary: "Las diferencias de carácter entre Leo y Piscis, pueden hacer que en este terreno de la amistad no sean tan compatibles.\n \nLa clave del éxito en este tipo de relación entre Leo y Piscis está en la conexión que establezcan desde el principio.\n \nSi conectan bien se abrirán muchos puentes.\n \nSin embargo, si se rechazan de entrada, probablemente no lleguen a ser jamás amigos.\n \nEl poderoso Leo quiere que sus amigos vayan a por todas, lo mismo que él ofrece.\n \nSin embargo, Piscis tiene otro concepto de la amistad, menos rotundo y acaparador.\n \nPiscis estará ahí siempre que se le necesite, incluso sacrificando sus propios intereses, pero lo hará con suma discreción.\n \nEso es lo que Leo no puede llegar a comprender y incluso no llega a apreciar.\n \nEl león es de los que suele llamar a los amigos, mientras que Piscis espera que le llamen.\n \nLeo es extravertido y Piscis, en cambio, tiende a la introspección.\n \nLeo puede ver a Piscis como un personaje un tanto soso, mientras que Piscis puede sentirse molesto con la vanidad de Leo.\n \nSalvado este punto, pueden congeniar bien y ser muy complementarios.\n \nPiscis sentirá admiración por Leo y éste se considerará afortunado por tener la amistad de alguien tan noble y que le comprende tan bien.",
	},
	Love: Love{
		Match:  "14%",
		Traits: []string{LowCommitment, NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "Leo y Piscis parecen haber sido puestos en esta Tierra para difundir tipos de amor totalmente diferentes.\n \nEl problema no está en su elemento o su cualidad, tanto como en su conexión a través de la caída de Neptuno, el regente de Piscis.\n \nSi se sienten atraídos el uno por el otro, correrán el riesgo de sufrir grandes daños en sus creencias, en su fe interior y, por lo general, sucumbirán a la falta de respeto mutuo por una simple falta de comprensión.\n \nLa belleza de su relación podría desarrollarse a través del enfoque de cuento de hadas de Piscis, si construyen la imagen heroica de su pareja Leo hasta el punto en que otras diferencias entre ellos se desvanezcan.",
			Match: "14%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Es increíble cómo dos signos que representan el amor, pueden ser tan equivocados el uno para el otro.\n \nLeo parecerá un bruto, preocupado egoístamente por sus propias necesidades, incapaz de formar una relación íntima con nadie, y mucho menos con Piscis.\n \nAunque esto no es cierto, puede ser la realidad obvia para Piscis si acaban en una relación de pareja con Leo.\n \nA cambio, Leo pensará que Piscis es débil y poco realista, completamente separado de sus propios deseos y de la fuerza de su cuerpo o sus emociones.\n \nLa verdad es que ambos pueden ser amantes increíbles, pero rara vez lo descubrirán juntos.\n \nSus roles y caracteres parecen ser demasiado diferentes como para que encuentren la forma de coexistir en una relación sexual satisfactoria.\n \n La franqueza y franqueza de Leo harán que Piscis se sienta avergonzado y apresurado, y su vida sexual podría retrasarse indefinidamente hasta que la pareja de Piscis se sienta lo suficientemente segura como para desnudarse.\n \nDebido a las diferencias en su enfoque del sexo, Leo parecerá en la mayoría de los casos un bruto insensible, a menos que Piscis empiece a comprender su profundidad emocional aunque sea tan diferente de la suya.",
			Match: "1%"},
		Trust: SummaryPercentage{
			Text:  "Neptuno es el planeta de todo engaño y desconfianza en el mundo, que hace que las cosas que nos rodean parezcan nebulosas, poco claras y falsas.\n \nPiscis es el signo regido por Neptuno, y Leo lo lleva a su caída.\n \nSe trata de una combinación de signos difícil para llegar a un punto de confianza mutua.\n \nAmbos parecerán deshonestos el uno para el otro, no porque mientan, sino porque sus caracteres parecen irreales.\n \nLeo pensará en Piscis como si siempre estuviera drogado, y Piscis sentirá lástima por Leo y su falta de fe.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Los ideales de Piscis podrían quedar destrozados por el acercamiento de Leo si se acercan demasiado el uno al otro.\n \nPodrían compartir muchos intereses debido al poder creativo de ambos signos.\n \nPiscis dará fácilmente inspiración a Leo, pero el problema está en la forma en que Leo podría utilizarla.\n \nLa mejor forma de crear un entorno seguro para ambos es ceñirse al tema que les interesa individualmente.\n \nLeo es un signo cálido, muy apasionado por sus actos y sus deseos.\n \nPiscis rara vez mostrará la misma iniciativa para realizar alguno de sus sueños y ésta es su mayor diferencia.\n \nDado que Leo siempre ilumina nuestras virtudes y defectos, no perderá la oportunidad de mostrar a su pareja Piscis lo poco realista que es.\n \nEsto podría ayudar a Piscis a construir un enfoque más realista, pero también podría afectar a su confianza y perjudicarle con una difícil percepción del mundo.",
			Match: "35%"},
		Emotions: SummaryPercentage{
			Text:  "Estos dos individuos son extremadamente emocionales, cada uno a su manera.\n \nEl elemento Fuego al que pertenece Leo les hace apasionados y les da la necesidad de luchar por su ser amado y por sus emociones.\n \nPiscis es un signo de Agua, y mucho más pasivo, que muestra su pasión a través del flujo de emociones.\n \nRara vez lucharán por algo, convencidos de que no es necesario luchar por la perfección y que los verdaderos tesoros son espontáneos y libres de conflictos.\n \nEl punto medio para estas parejas está en su comprensión de que no todo debe ganarse, tanto como no todo debe ser sin influencia.Aunque se supone que las emociones verdaderas se desarrollan sin dificultad, a veces la vida nos pone a prueba para ver si realmente nos importan.\n \nAún así, esto no es algo que ocurra todo el tiempo, y a veces hay que dejar ir las cosas porque no nos pertenecen, ni nosotros a ellas.",
			Match: "15%"},
		Values: SummaryPercentage{
			Text:  "Es interesante lo mucho que ambos miembros de la pareja valoran la claridad y la honestidad.\n \nLa pareja de Piscis comprende la necesidad de las mentiras, pero aún así vive para la claridad de la mente y la realización de su verdadero Yo interior.\n \nUn gran vínculo entre sus mundos de valores está en la naturaleza heroica de Leo, que parece tener sus raíces en un cuento de hadas de Piscis.\n \nPor mucho que ambos valoren su conjunto individual de creencias, podrán encontrar un término medio en el carácter grandioso de Leo y la naturaleza idealizadora de Piscis.",
			Match: "20%"},
		SharedActivities: SummaryPercentage{
			Text:  "Como signo fijo y mutable, tendrán problemas para sincronizar su necesidad de cambios y nuevas actividades.\n \nAunque Leo es un signo de Fuego, siempre dispuesto a empezar algo nuevo, le gustará ceñirse a su rutina y mostrarse en todos los lugares habituales cada día.\n \nLos Piscis quieren ser invisibles y cambiarán a menudo de escenario para que la gente no los reconozca.\n \nAunque puedan compartir algunos intereses y actividades, rara vez permanecerán juntos en el mismo lugar y realizando las mismas acciones durante mucho tiempo.",
			Match: "10%"},
	},
}
