package compatibilities

var Leosagittarius = Compatibility{
	Name: Leo + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "95%",
		Traits:  []string{FunEnjoyable},
		Summary: "La relación de amistad entre Leo y Sagitario estará repleta de energía y en ella no tendrá cabida el aburrimiento.\n \nEl impetuoso leo basa sus relaciones de amistad en su admiración hacia el otro sigo y la fidelidad, aspectos en los que coincide totalmente con Sagitario.\n \nSi se establece entre ellos una amistad será sólida e indestructible.\n \nLas diferencias con las que tendrán que lidiar Leo y Sagitario consisten en la diferente manera de apreciar el entorno social.\n \nPara Leo desenvolverse socialmente es fácil y eso puede molestar a Sagitario, aunque también con cierta frecuencia, en lugar de irritarse por el protagonismo del león, lo que hará Sagitario es incorporar a su vida los aspectos más positivos de Leo.\n \nUna sabia elección, sin duda.\n \nLeo y Sagitario también son conscientes de que encontrar personas que concuerden tanto con sus respectivos caracteres, no es precisamente fácil.\n \nJuntos proyectarán grandes planes, viajes, encuentros, fiestas y salidas.\n \nEn la amistad de Leo y Sagitario no tendrá cabida el aburrimiento.\n \nLeo es un amigo a toda prueba, que siempre va a estar ahí.\n \nSagitario puede estar seguro de que en Leo encontrará un aliado, un compañero de fatigas y un cómplice incondicional.\n \nLa vida de ambos se enriquecerá con esta amistad.",
	},
	Love: Love{
		Match:  "75%",
		Traits: []string{Harmonious, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Leo y Sagitario son una combinación de signos muy fogosa, y cuando dos personas con estos signos solares se juntan, inevitablemente se enamoran.\n \nEste amor es cálido, apasionado e inspirador, y tendrán la oportunidad de crear, actuar y divertirse juntos mientras se sientan así.\n \nSin embargo, la pareja de Sagitario podría perder interés en Leo porque tiende a alejarse por su naturaleza estática y fija.\n \nLa única forma de que consigan mantener su pasión y sus emociones es que consigan escuchar sus emociones más suaves y sigan siendo tiernos y sensibles el uno con el otro.",
			Match: "75%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Como dos signos de fuego, uno de ellos fijo y el otro mutable, Leo y Sagitario comparten un cálido amor mutuo.\n \nCuando empiecen a salir, su relación sexual podría ser una sorpresa para ambos, ya que se sentirán liberados para ser exactamente quienes son el uno con el otro.\n \nLo mejor que podrían hacer es utilizar el trígono entre sus Soles y fortalecer la autoestima del otro, especialmente si han estado en relaciones exigentes o irrespetuosas antes de la suya.\n \nLo mejor de su vida sexual es la pasión que comparten.\n \nLeo está ahí para aportar fuego interior al acto sexual, y Sagitario para encender la expansión, los lugares, las posiciones y los horizontes.\n \nAmbos disfrutarán de manera fogosa y respetarán sus cuerpos, mentes y personalidades enteras.\n \nSi tropiezan el uno con el otro y nace el amor, su vida sexual podría representar una conexión perfecta para ambos.",
			Match: "99%"},
		Trust: SummaryPercentage{
			Text:  "Puesto que se inspiran mutuamente seguridad y confianza, rara vez mostrarán celos o malinterpretarán las acciones del otro.\n \nA Leo le gusta ser el centro de atención y sentirse atractivo y deseable, pero esto es algo que una pareja Sagitario puede proporcionarle en abundancia.\n \nNo suele haber motivos para que pierdan la confianza con el paso del tiempo, excepto cuando sus emociones empiezan a desvanecerse.\n \nSagitario es un signo mutable, y como tal, pueden enamorarse y desenamorarse con rapidez y frecuencia.\n \nEn caso de que Leo empiece a sentirse excluido y poco querido, la desconfianza aumentará, y qué mejor manera de responder a la desconfianza que volviéndote desconfiado tú mismo, podría pensar Sagitario.\n \nAunque ambos pueden no ser conscientes de la raíz de sus problemas cuando se pierde la confianza, suele tratarse de una simple falta de amor.",
			Match: "80%"},
		Communication: SummaryPercentage{
			Text:  "Tanto Leo como Sagitario están muy centrados en su actividad mental.\n \nLeo porque está regido por el Sol y esto le confiere cierta conciencia racional y Sagitario porque siempre apunta más alto desde la Tierra, filosófico y amplio de opiniones.\n \nEsto es algo que les ayudará a comunicarse sobre casi cualquier cosa, aunque sus intereses puedan diferir y sus orígenes también.\n \nLeo tiene la capacidad de ayudar a Sagitario cuando se pierden, y esto podría suceder a menudo si sus planes son grandiosos.\n \nSagitario le dará a Leo visión y la capacidad de comprender el futuro de sus actuales esfuerzos creativos.\n \nJuntos, forman una parte importante del proceso de creación.\n \nAmbos pueden ser ruidosos, comunicarse mucho, y esto podría hacer que su relación fuera realmente notable, profundizando su intimidad a través de la apertura que comparten para entrar en el mundo del otro.\n \nComo ambos tienen una fuerte personalidad, no se sentirán amenazados por el carácter del otro ni por la fuerza de sus opiniones y convicciones.\n \nLo único que podría faltarles es sensibilidad a las influencias externas y su fogosa relación podría hacerles un poco bruscos entre ellos, y consigo mismos.",
			Match: "85%"},
		Emotions: SummaryPercentage{
			Text:  "Como dos signos de Fuego, Leo y Sagitario tienden a ser muy apasionados y abiertos a la hora de mostrar lo que sienten.\n \nQuerrán demostrar su amor, compartirlo y actuar según sus impulsos tanto como puedan.\n \nEsto a veces puede ser demasiado, ya que no respetarán ninguna emoción o energía pasiva y frágil.\n \nUn poco de equilibrio vendría bien, sobre todo si se pelean a menudo.\n \nLos conflictos entre ellos podrían ser bastante agresivos, no porque ellos mismos lo sean, sino porque dos fuegos crean un fuego aún mayor.\n \nEs casi como si pudieran explotar si ambos van demasiado lejos.\n \nCuando se enamoran, parece el amor más cálido y tierno del planeta Tierra.\n \nEn la mayoría de los casos, esto bastará para superar cualquier dificultad que se interponga en su camino, pero a veces estos dos miembros de la pareja tienden a olvidar su sensibilidad real.\n \nTienen que entender cuándo ha llegado el momento de bajar el ritmo, quedarse en casa, no hablar de nada en absoluto y simplemente callarse.\n \nSi no lo hacen, es probable que recurran de vez en cuando a alguien que les proporcione este tipo de paz.",
			Match: "80%"},
		Values: SummaryPercentage{
			Text:  "Sin duda valorarán la fuerza de carácter y la increíble personalidad del otro, la capacidad de calentarse mutuamente de todas las maneras posibles y la pasión que llevan dentro, cada uno para sus propios fines.\n \nAun así, no es fácil explicarle a un Leo por qué es tan bueno huir del mundo, viajar solo por Groenlandia y comer bichos en algún lugar de Asia, excepto si uno quiere demostrar su valentía.\n \nPor otro lado, Sagitario no entiende muy bien por qué ir a lugares extravagantes y enfrentarse a toda la gente de la que es más fácil huir.\n \nEsto no es consecuencia de una falta de coraje, sino de la falta de sentido que sienten cuando tienen que dedicar su tiempo a personas fastidiosas.\n \nAsí que, aunque valoran lo mismo, el valor, lo ven con ojos distintos.",
			Match: "65%"},
		SharedActivities: SummaryPercentage{
			Text:  "Podríamos pensar que a Leo le gusta viajar tanto como a Sagitario.\n \nTienen la energía y la necesidad de buscar conocimientos y ampliar sus horizontes, pero no les gusta tanto moverse.\n \nEsto se debe a su naturaleza fija, y aunque les gustaría visitar cualquier parte posible del mundo, no lo harían al mismo ritmo que Sagitario, ni elegirían los mismos destinos.\n \nSagitario, por su parte, no entiende muy bien por qué Leo quiere actuar delante de tanta gente cuando hay niños muriéndose de hambre en África.\n \nSon ejemplos simplificados, pero nos sirven bastante bien para entender lo bien que podrían trabajar juntos, viajar juntos, actuar juntos, pero sólo si están lo suficientemente abiertos como para añadir propósito y fuerza a sus planteamientos.",
			Match: "40%"},
	},
}
