package compatibilities

var Leoscorpio = Compatibility{
	Name: Leo + " - " + Scorpio,
	Friendship: Friendship{
		Match:   "65%",
		Traits:  []string{MutualRespect},
		Summary: "Su similitud en algunos rasgos de carácter puede hacer que Leo y Escorpio inicien y mantengan una amistad sólida en la que ambos demostrarán ser fieles y sinceros.\n \nLeo y Escorpio funcionarán mejor como amigos que como pareja, aunque también en este terreno tendrán que lidiar con sus contrastes y su obstinación si quieren que su amistad perdure, algo que conseguirán la mayoría de veces.\n \nTanto Leo como Escorpio poseen personalidades muy marcadas y si están juntos, la diversión, el éxito y la aventura están asegurados.\n \nSus principales inconvenientes es que Leo puede ser demasiado directo y a su vez Escorpio puede resultar difícil de convencer.\n \nSi logran superar restos obstáculos, la energía que les unirá será muy positiva y valiosa.\n \nLos aspectos que unirán a Leo y Escorpio, es que el primero querrá siempre tomar la delantera, algo que a Escorpio, a quien no le gusta destacar y a menudo se muestra complaciente, no le importará demasiado, incluso puede sentirse cómodo, si su amigo Leo toma la iniciativa y se ocupa de todos los detalles de sus proyectos comunes.\n \nPara que todo funcione, sin embargo, Leo tendrá que evitar dar órdenes directas a Escorpio o inmiscuirse en sus asuntos privados, mientras que Escorpio deberá aceptar el liderazgo de Leo.",
	},
	Love: Love{
		Match:  "29%",
		Traits: []string{DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "Cuando Leo y Escorpio empiezan a salir, es posible que no sepan exactamente lo que les espera.\n \nNo se trata en absoluto de una relación fácil, y ambos cónyuges pueden ser obstinados y rígidos en sus opiniones, elecciones de vida y formas de manejar la realidad.\n \nSi quieren seguir manteniendo una relación afectuosa, tienen que entender la forma que tiene el otro de expresar sus emociones y respetar sus necesidades por muy diferentes que sean de las que están acostumbrados.\n \nCuando encuentren la manera de amarse sin condicionamientos, quizá se den cuenta de que buscan lo mismo: la Unidad.",
			Match: "29%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Se trata de una relación complicada entre dos personalidades fuertes con un increíble apetito sexual.\n \nLeo es un amante apasionado, cálido, siempre en busca de acción y pueden ser bastante casuales cuando se trata de sus encuentros sexuales.\n \nEscorpio es el sexo en sí mismo, y la profundidad de las emociones que lo acompañan en su forma más pura.\n \nCuando se juntan, pueden tener verdaderos problemas para encontrar un punto medio entre sus personalidades.\n \nEstas parejas pueden parecer como si hubieran chocado la una con la otra sin ningún plan ni propósito.\n \nSi se sienten atraídos el uno por el otro, esto podría volverlos locos, ya que ninguno de ellos podrá realizar sus deseos de forma deseada.\n \nSimplemente no funcionan de la misma manera y mientras Leo quiere ser respetado, Escorpio entiende que todo respeto muere en el acto sexual.\n \nEs extremadamente difícil para un Leo y un Escorpio llegar a la intimidad, porque tienen una visión diferente de las emociones.\n \nLo que Leo ve como amor, Escorpio lo encuentra superficial e irritante, y lo que Escorpio ve como amor, Leo lo encuentra deprimente e irritante.\n \nAmbos necesitan renunciar por completo al control si quieren encontrar la satisfacción sexual el uno con el otro.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "El lado positivo de esta relación en lo que se refiere a la confianza está en la cualidad fija de ambos signos.\n \nEsto no es tan bueno cuando se trata de su capacidad para adaptarse y ser flexibles el uno para el otro, pero es algo perfecto para la confianza mutua.\n \nSi sientan las bases claras al principio de su relación, Leo transparente como es y Escorpio directo y honesto, podrían confiar el uno en el otro sin excepción durante mucho tiempo.\n \nEso si ambos quieren estar abiertos a este tipo de relación en primer lugar.",
			Match: "65%"},
		Communication: SummaryPercentage{
			Text:  "Es una suerte que estos dos signos puedan comportarse tan bien.\n \nAunque no siempre es así, Leo quiere mostrar la imagen correcta al mundo, y Escorpio entiende el karma mejor que muchos otros signos.\n \nPor eso es probable que se respeten lo suficiente como para comunicarse de forma civilizada.\n \nAmbos son obsesivos en cierto modo.\n \nLeo nunca renunciará a perseguir su pasión, con energía suficiente para encender a todos a su alrededor, y Escorpio se aferrará a las cosas que le importan y luchará obsesivamente por sus objetivos.\n \nSi comparten la misma pasión o los mismos intereses, tendrán de qué hablar, obsesivamente.\n \nLa profundidad típica de Escorpio es algo que Leo se esfuerza por alcanzar en su búsqueda de la Unidad.\n \nSus conversaciones pueden ser muy tensas e irritantes para ambos, pero en el camino pueden darse cuenta de que se dan exactamente lo que ambos necesitan.",
			Match: "30%"},
		Emotions: SummaryPercentage{
			Text:  "Esta es probablemente la relación más difícil de todo el zodíaco en lo que se refiere a las emociones que estos miembros de la pareja sienten el uno por el otro.\n \nEn algunos casos, pueden identificarse con el odio, pero lo importante aquí es recordar que el odio también es amor, en su forma 'negativa', y ambos miembros de la pareja pensarán que cualquier emoción es mejor que ninguna.\n \nSu relación un poco tortuosa puede mantenerlos unidos durante mucho tiempo, aunque sean infelices y conscientes de que podrían ser más felices con otra persona.\n \nEn cierto modo, a Escorpio le gusta estar atado a través de emociones negativas, porque el amor a veces tiene que doler, y Leo se aferra a sus decisiones porque rara vez acepta que podría haberse equivocado.\n \nEsta relación puede convertirse en un círculo de sufrimiento muy difícil para ambos miembros de la pareja, sobre todo si alguno de ellos no tiene su vida independiente, sus amigos y sus finanzas.\n \nCuando lo hacen, pueden encontrar un delicado equilibrio, siempre y cuando ambos tengan libertad para pensar que puede haber mejores opciones para ellos con otras personas.\n \nSi no encuentran ninguna, podrían darse cuenta de que son perfectos el uno para el otro como individuos autosuficientes, mediante un acercamiento sano.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Ambas parejas valorarán la honestidad y la claridad.\n \nAunque entienden la claridad en diferentes direcciones y profundidad, las características principales en las personas con las que desean salir son muy similares.\n \nA menudo, ni siquiera reconocerán su similitud desde una posición emocionalmente inestable u obsesivamente estable, completamente distinta a la de una persona apasionada y creativa.\n \nTienen que lidiar con el valor de la creación frente al valor de la destrucción y esto no es fácil de conciliar.\n \nEl puente entre ambos se encuentra en la honestidad incondicional.",
			Match: "35%"},
		SharedActivities: SummaryPercentage{
			Text:  "Es muy interesante cómo un Leo y un Escorpio pueden organizar su tiempo juntos.\n \nAunque en la mayoría de los casos están interesados en cosas diferentes, Escorpio está regido por Marte, un planeta que Leo comprende bien y con el que coopera bien.\n \nAmbos tendrán la energía necesaria para seguir los deseos del otro y podrían divertirse mucho.\n \nAun así, suelen tropezar con un problema cuando se trata de su comprensión de ciertas circunstancias y de las personas que les rodean.\n \nRara vez hay un compromiso entre el enfoque positivo y constructivo de Leo y el enfoque a menudo negativo y sensible de Escorpio, especialmente cuando ninguno de ellos es exactamente cierto.\n \nLo mejor sería que se mantuvieran fieles a sí mismos y comprendieran que existe un término medio entre sus opiniones y sentimientos, por extraño que pueda parecer.",
			Match: "40%"},
	},
}
