package compatibilities

var Leovirgo = Compatibility{
	Name: Leo + " - " + Virgo,
	Friendship: Friendship{
		Match:   "25%",
		Traits:  []string{Stormy, CautionRomance},
		Summary: "Los vínculos de amistad entre Leo y Virgo están asentados sobre una base de concesiones.\n \nAmbas personalidades se atraen porque cada uno tiene algo de lo que el otro carece.\n \nCuando se establece una relación de amigos entre Leo y Virgo, el primero con toda seguridad probará de llevar siempre la voz cantante y de hecho lo conseguirá en numerosas ocasiones.\n \nVirgo se dejará arrastrar por los planes de Leo si estos le convencen.\n \nEn numerosas ocasiones será así, porque a pesar de sus diferentes personalidades, Leo y Virgo comparten cualidades notables.\n \nAmbos son inteligentes y curiosos por lo que les atraerán muchas actividades de índole intelectual que podrán practicar juntos.\n \nDonde tienen menos probabilidades de coincidir es en el deseo de aventura del impulsivo Leo.\n \nVirgo no estará dispuesto a secundarle, a menos que pueda examinar previamente hasta el último detalle, lo cual restará espontaneidad a la iniciativa, algo que puede disgustar a Leo o le hará perder el interés.\n \nSe complementarán también en el aspecto económico, donde Virgo, más meticuloso, pondrá freno a ciertas aventuras que podrían afectar a sus bolsillos, algo que no parece importar al lanzado Leo.\n \nEsta amistad beneficiará también a la economía de ambos.",
	},
	Love: Love{
		Match:  "35%",
		Traits: []string{Volatile, NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "Leo y Virgo forman una relación constructiva que rara vez sirve a sus naturalezas emocionales.\n \nAmbos tienden a ser demasiado racionales y su fortaleza mental rara vez será una buena base para un amor de cuento de hadas que desean en secreto.\n \nAmbos signos tienen signos opuestos vinculados a Neptuno.\n \nEl signo opuesto de Leo es Acuario, el signo de exaltación de Neptuno, mientras que el signo opuesto de Virgo es el signo de Piscis, regido por Neptuno.\n \nAmbos necesitan a alguien perfecto, alguien hecho sólo para ellos, y si piensan por un segundo que no son el uno para el otro, su búsqueda de la perfección prevalecerá.\n \nEs raro que estas parejas formen un vínculo emocional o sexual fuerte, por muy bien que se lleven en lo que respecta al trabajo y la comunicación.",
			Match: "35%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La naturaleza tímida de Virgo y su cautela a la hora de elegir pareja sexual podrían dificultarles encontrar un lenguaje que ambos entiendan.\n \nLeo quiere estar con una pareja que le haga sentir especial e incluso más seguro de lo que ya es, y esto es difícil de dar para Virgo.\n \nSu relación puede ser todo un reto porque la naturaleza apasionada de Leo no da mucho espacio a Virgo para sentirse protegido y seguro de sus decisiones.\n \nSu racionalidad podría convertirse en una batalla intelectual por el dominio sexual, eso si alguna vez llegan al punto en que ambos quieran tener relaciones sexuales entre sí.\n \nMenos mal que Leo es un signo fijo, por lo que tiene una nota conservadora que le sienta muy bien a Virgo.\n \nAun así, rara vez se conformarán con el enfoque de Virgo sobre las emociones en su vida sexual, y probablemente ambos serán incapaces de establecer una conexión emocional que los mantenga satisfechos.\n \nEn raras ocasiones, cuando la pareja de Virgo no se siente avergonzada o atacada por la pareja de Leo, podrían compartir una relación sexual físicamente satisfactoria, pero ambos podrían seguir siendo demasiado racionales juntos como para encontrar algún tipo de intimidad.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "No hay motivo para que dos personas conscientes no confíen la una en la otra en la mayoría de las situaciones.\n \nEl problema podría surgir cuando la pareja Leo empiece a presumir y a hacerse pasar por 'el rey de la selva'.\n \nEl exceso de atracción que invocará Leo no es algo con lo que Virgo se sienta cómodo, y el problema inicial de Virgo con la confianza florecerá si su comunicación no compensa la confianza perdida.",
			Match: "65%"},
		Communication: SummaryPercentage{
			Text:  "Tanto Leo como Virgo están regidos por planetas racionales y conscientes, por lo que suele ser fácil hablar con ellos.\n \nSin embargo, sus personalidades son muy diferentes debido a la diferencia en el elemento al que pertenecen.\n \nEl signo de virgo pertenece a Tierra, y Leo pertenece a Fuego.\n \nPor eso Leo es muy apasionado y fogoso en sus convicciones, elecciones y todo lo que es importante para él.\n \nPor el contrario, Virgo es muy práctico, tiene los pies en la tierra y suele estar demasiado orgulloso de su intelecto como para dejarse llevar por arrebatos pasionales y emocionales.\n \nEstos signos juntos representan al rey (Leo) y a sus seguidores (Virgo).\n \nDel mismo modo, representa al jefe y a sus empleados o a un marido y su señora de la limpieza.\n \nLo más importante aquí es que ambos se mantengan respetuosos y tolerantes el uno con el otro.\n \nSi Leo se muestra irrespetuoso y empieza a dar órdenes, Virgo saldrá corriendo, pues ésta no es la relación que estaban buscando.\n \nPor otro lado, si la pareja de Virgo no comprende que ha elegido al rey de la selva, su relación no durará mucho porque Leo necesita ser reconocido.",
			Match: "50%"},
		Emotions: SummaryPercentage{
			Text:  "Lo más difícil de encontrar para una pareja Leo-Virgo es la cercanía emocional.\n \nMientras Virgo racionaliza todo lo que sucede en la vida, Leo tiene una respuesta perfectamente racional para todo.\n \nAunque Leo puede ser dolorosamente consciente de su necesidad de intimidad, esto no significa que sea capaz de crearla con facilidad, especialmente con alguien como Virgo.\n \nEsto puede suponer un gran reto para su relación, ya que incluso cuando se sienten fuertemente atraídos el uno por el otro y se comunican bien no parecen despertar las emociones del otro.\n \nAunque ambos pueden ser muy íntimos con otros signos del zodíaco, rara vez encontrarán esto el uno con el otro.\n \nLeo mostrará su afecto a través de un acercamiento apasionado y cálido, lleno de atención y vigor.\n \nVirgo será tímido y le costará entenderlo, mientras que dará amor a través de atenciones que podrían parecer ridículas a un Leo seguro de sí mismo.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Ambos valorarán la inteligencia y la capacidad de utilizar la mente, y lo harán hasta el punto de sentir un respeto indiscutible.\n \nLeo puede quedar prendado de la mente de alguien, y esto es exactamente lo que Virgo tiene para dar, en caso de que no sea demasiado cerrado para demostrarlo.\n \nSi trabajan juntos, pueden crear el ambiente exacto en el que se puede crear cualquier cosa, pero sólo si comparten intereses profesionales similares.\n \nLas diferencias entre ellos suelen ser aún demasiado grandes para ser superadas por una simple mente racional, y mientras Leo valorará todo lo que brilla, las cosas grandiosas y llamativas, Virgo valorará la capacidad de alguien para ser humilde y modesto.",
			Match: "35%"},
		SharedActivities: SummaryPercentage{
			Text:  "Cuando Leo y Virgo trabajen juntos, no tendrán ningún problema en compartir actividades por muy diferentes que parezcan sus naturalezas.\n \nSus papeles en el zodíaco apoyan su cooperación y Virgo no tiene mejor jefe que un Leo, en caso de que ambos no tengan graves problemas de ego.\n \nCon el suficiente respeto mutuo, podrían hacer casi cualquier cosa juntos, siempre que sea a puerta cerrada, si es lo que Virgo desea, y sin exponerse a demasiada gente.\n \nLeo quiere tener la atención de su entorno si no se han magullado y sentido avergonzados demasiadas veces, y Virgo no siente esta necesidad.\n \nPrefieren permanecer en la sombra, detrás de un líder, alguien inteligente, con una gran visión.\n \nLes gusta ocuparse de todos los detalles para que ambos lleguen al punto de éxito deseado.\n \nPuesto que Leo representa nuestro estómago y Virgo nuestros intestinos, metabolizarán juntos diferentes experiencias, guiados por el liderazgo y la pasión de Leo y seguidos por el sentido práctico y la atención al detalle de Virgo.",
			Match: "55%"},
	},
}
