package compatibilities

var Libralibra = Compatibility{
	Name: Libra + " - " + Libra,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{AlmostNothingReally},
		Summary: "En el terreno de la amistad, Libra y Libra compartirán gustos e intereses, por ello su relación será cordial y amable, muy relajada.\n \nLibra siempre guarda para sí algunos secretos que no confía a nadie, pero con otro Libra hará una excepción y le mostrará excepcionalmente este lado escondido.\n \nLibra y Libra formarán un binomio equilibrado y con los mismos intereses y aficiones, que se reconocerán a primera vista y rápidamente se convertirán en grandes amigos.\n \nA Libra le cuesta a veces encontrar a alguien con su elevado sentido humanitario, que lucha contra la injusticia y la desigualdad.\n \nNo siempre es comprendido por otros signos del zodíaco.\n \nSin embargo, no tendrá que dar explicaciones ni justificarse si su amigo o amiga tiene la misma tendencia.\n \nLibra y Libra serán más felices si tienen como compañero de aventuras a alguien que piensa y siente como ellos mismos, que disfrutará también de las mismas actividades sociales.\n \nSu amistad estará llena de diversión, belleza y placer.\n \nLibra y Libra serán muy apreciados socialmente, algo que les llenará de orgullo porque necesitan sentirse queridos y admirados.\n \nEl aspecto más positivo será su sentido de la amistad y su gran sentido del mutuo respeto, que les asegura una verdadera amistad a lo largo de toda su vida.",
	},
	Love: Love{
		Match:  "68%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "El signo de Libra es un signo de relaciones y a menudo tienen la misión de enseñar a los demás a relacionarse.\n \nCuando dos Libra empiezan a salir, puede resultarles difícil encontrar un propósito para su contacto, ya que ambos parecen compartir una misión y un objetivo relacionado con otras personas.\n \nSi encuentran un punto de encuentro, combinando sus actividades y ciñéndose a sus valores compartidos, tenderán a convertirse en una pareja perfectamente equilibrada.\n \nLo único que falta en ambos, muy difícil de desarrollar, es el sentido del respeto mutuo sin juicios ni expectativas pasivas.\n \nAmbos son susceptibles a este problema con su entorno, y cuando estén juntos, estos problemas se multiplicarán fácilmente.\n \nSi se dejaran ser quienes son, podrían convertirse en una inspiración para todos nosotros, enseñándonos lo que es realmente una relación productiva.",
			Match: "68%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Una gran cosa sobre la relación de dos Libras está en su comprensión del comportamiento de buen gusto.\n \nParecen encajar perfectamente cuando se trata de no cruzar la línea y ser lo más moderados posible en su expresión sexual.\n \nEsto les ayudará a construir una relación sólida con el tiempo, si no empiezan a juzgarse mutuamente en cuanto uno de los dos se salga de su estricta rutina sexual.\n \nComo dos parejas regidas por Venus, ambos podrían tener fácilmente problemas de iniciativa y esto podría ser un obstáculo imposible de superar.\n \nCuando uno de los dos empiece a confiar en la naturaleza masculina de su signo, la relación podrá comenzar y el objetivo principal será satisfacer al otro.\n \nSu compatibilidad mental les permitirá comprender las necesidades del otro y hablar de todo lo relacionado con su vida sexual, pero su falta de confianza compartida podría hacerles juzgarse mutuamente de una forma que no juzgarían a otra pareja.",
			Match: "65%"},
		Trust: SummaryPercentage{
			Text:  "Dos Libras ni siquiera saben cuántos problemas de confianza tienen hasta que se juntan.\n \nLa incertidumbre de sus decisiones puede entenderse bien cuando se trata de cosas cotidianas, pero en cuanto la muestren al elegir el uno al otro, todo lo que se hayan dicho será cuestionado.\n \nLa caída del Sol da menos luz a estos individuos, lo que significa que puede ser un reto para ellos ver las cosas con claridad.\n \nEsto no hace que perciban menos las cosas, y sentirán que algo va mal a miles de kilómetros de distancia, sin ser conscientes de lo que es.\n \nLa confianza es un tema muy delicado cuando llegan a este punto, sobre todo si no dicen lo que piensan esperando resoluciones.\n \nEs la pareja más propensa a los malentendidos de todas las del zodiaco.",
			Match: "35%"},
		Communication: SummaryPercentage{
			Text:  "Podemos decir con certeza que su comunicación evolucionará hacia algo que ambos disfrutarán, siempre y cuando no empiecen a alimentar sus egos heridos el uno con el otro.\n \nCuando esto ocurra, uno de los miembros de la pareja se volverá totalmente inconsciente de su comportamiento, actuando como un vampiro que drena la fuerza de voluntad de su pareja, día tras día.\n \nEn el peor de los casos, ambos se sentirán impotentes todo el tiempo, debido a la falta de respeto que sienten el uno por el otro, pero carecerán de iniciativa y parecerán incapaces de resolver la situación que les agobia.\n \nMientras se respeten lo suficiente, como dos signos del Aire, la comunicación entre ellos parecerá interminable.\n \nSiempre tendrán algo que compartir, en la mayoría de los casos hablando excesivamente de otras personas.\n \nCuando empiecen a señalar los defectos del otro, lo mejor será dar marcha atrás y darse cuenta de que no hay nada que cambiar.\n \nSu aceptación mutua es lo único que puede mantener su relación mental en un buen punto y sus conversaciones fluyendo sin juicios ni expectativas poco realistas.",
			Match: "80%"},
		Emotions: SummaryPercentage{
			Text:  "Por un lado, dos signos regidos por Venus parecen estar hechos para el amor, y esto habla de su cercanía física y espiritual que puede darse a través de su contacto emocional.\n \nPor el otro, Libra es un signo que exalta a Saturno, y esto les da a ambos un lado frío, que no les permitirá fácilmente construir una relación íntima.\n \nEl elemento Aire al que pertenecen no ayudará mucho, ya que harán todo lo posible por racionalizar las cosas hasta que pierdan todo valor emocional.\n \nExiste esa terquedad en Libra que no es evidente a primera vista, y si algo podría separar a esta pareja es su necesidad de aferrarse a sus convicciones.\n \nComo si fueran incapaces de ver las cosas en su conjunto, a veces esconden sus emociones bajo la alfombra para aferrarse a lo que saben.\n \nEs extraño lo seguros que pueden estar de sus conocimientos e inteligencia cuando se juntan, como si por fin hubieran encontrado a alguien que les parece más débil.\n \nPara permanecer juntos, dos Libra necesitan apagar sus cerebros y dejarse llevar por sus sentimientos y sus relaciones sexuales.\n \nEsta es la única forma de que construyan intimidad, o ambos podrían resistirse a ello por simple miedo y falta de confianza.",
			Match: "50%"},
		Values: SummaryPercentage{
			Text:  "La combinación del reinado de Venus y la exaltación de Saturno hace que compartan los mismos valores, adquiridos a través de experiencias y relaciones similares.\n \nVenus es un planeta que habla del valor en general, y éste es un fuerte punto de conexión para ellos, especialmente porque ambos carecen de la conciencia del valor real del dinero.\n \nEstas parejas valoran la dedicación, un enfoque espiritual del amor, la delicadeza y las elecciones moderadas, un comportamiento razonable que no sea juzgado por quienes les rodean.\n \nCuando se trata de este aspecto de su relación, dos representantes de Libra parecen encajar a la perfección.",
			Match: "99%"},
		SharedActivities: SummaryPercentage{
			Text:  "A primera vista, podríamos suponer que les gustará presumir, inspirar a los demás por el amor que muestran al mundo y estar en movimiento para crear cierta imagen haciéndolo todo codo con codo.\n \nEl problema surge antes de llegar a este punto, mientras intentan decidir y ponerse de acuerdo sobre dónde ir en primer lugar.\n \nAmbos querrán ceñirse a una cierta rutina segura, raramente dispuestos a conocer a demasiada gente nueva.\n \nPero si sus rutinas no coinciden, tendrán que hacer concesiones para salir de un punto de estancamiento.\n \nCuando encuentren una rutina común y compartan amigos, las actividades compartidas dejarán de ser un problema y se seguirán con mucha más facilidad.",
			Match: "80%"},
	},
}
