package compatibilities

var Libraaquarius = Compatibility{
	Name: Libra + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "95%",
		Traits:  []string{ExcellentAdvisors, GoodRomancePotential},
		Summary: "Lo mejor de todo en una relación de amistad entre Libra y Acuario es que ambos tienen claro como el sol que les alumbra el papel de cada uno dentro de este binomio.\n \nSe ponen de acuerdo siempre en la división de funciones y conviven de forma armoniosa y pacífica.\n \nLibra y Acuario funcionan al cien por cien, su amistad no admite medias tintas.\n \nComparten un espíritu aventurero fuera de lo común y les gusta mantenerse activos, imaginando, planificando y divirtiéndose a su manera.\n \nCuando Libra y Acuario se juntan, no existe el aburrimiento, ni entre ellos ni en el entorno en que se desenvuelvan.\n \nEsta relación fluye de mil maravillas porque tanto Libra como Acuario detestan las imposiciones y respetan las decisiones ajenas.\n \nTienen esto y muchísimo más en común, vibran con la misma energía y no paran de hacer actividades y generar nuevas ideas.\n \nAcuario le gusta la acción y va directo a la práctica, mientras que a Libra le gusta pasar antes por la teoría.\n \nAprenderán el uno del otro estos conceptos.\n \nEl buen gusto de Libra y la energía de Acuario no encontrarán mejor acomodo que relacionándose entre ellos.\n \nSon los amigos perfectos para compartir penas y alegrías, pero también para las reuniones, salidas, encuentros y viajes.",
	},
	Love: Love{
		Match:  "68%",
		Traits: []string{Harmonious, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Existe un gran entendimiento entre Libra y Acuario debido al elemento Aire que comparten.\n \nAún así, puede ser bastante difícil para sus Soles problemáticos llevarse bien y a menudo tendrán dificultades para adaptarse al carácter del otro y encontrar un profundo respeto mutuo.\n \nLa mejor cura para cualquier problema en su relación suele estar en el tiempo, pero con la necesidad de espontaneidad de Acuario a menudo no durarán lo suficiente para que el tiempo repare lo que se rompe.\n \nSea cual sea su historia, tendrán muchas cosas emocionantes que vivir juntos y, si se enamoran, sería una pena que una pareja como ésta no le diera una oportunidad a su relación, acabe como acabe.",
			Match: "68%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Acuario puede ayudar realmente a Libra a expresar su sexualidad.\n \nO bien tendrán miedo a ser juzgados y parecerán demasiado asexuados, o bien tendrán la necesidad de mostrarla 'a pesar' de la opinión de todo el mundo y esto puede resultar bastante repulsivo para su pareja.\n \nCuando se trata de sexualidad, Acuario tiene un enfoque totalmente diferente: simplemente no les importa la opinión de nadie.\n \nViven su vida en una búsqueda constante de la libertad de cualquier tabú o restricciones, y esto ayudará a Libra olvidarse de otras personas, al menos por algún tiempo.\n \nAunque su vida sexual puede ser bastante liberadora para Libra, también puede ser un poco desafiante para Acuario porque será quien tenga que luchar contra la necesidad de Libra de encajar.\n \nSin embargo, como dos signos de Aire, ambos tenderán a ser libres para expresar sus deseos sexuales al otro.\n \nLes gustará experimentar, aprender el uno del otro y de sus propios deseos internos y comunicarse con facilidad.\n \nSus relaciones sexuales deberían ser un pilar fuerte de toda su relación, aunque normalmente pensarán que sus formas verbales de llevarse bien son las más importantes para su vínculo.",
			Match: "90%"},
		Trust: SummaryPercentage{
			Text:  "Debido a su naturaleza recta, podrían confiar el uno en el otro sin excepción, si tan sólo estuvieran tan seguros de sí mismos.\n \nSus inseguridades coinciden muy bien y suelen ayudarse mutuamente a superarlas, pero la confianza entre ellos debe construirse, no es algo implícito.\n \nA ambos signos les gusta ser atractivos para personas diferentes y deben encontrar la forma de comunicar esta necesidad de la manera adecuada.\n \nEl problema puede surgir cuando Libra empieza a encariñarse y se vuelve emocionalmente dependiente de su pareja.\n \nEsto no es algo con lo que Acuario vaya a lidiar fácilmente y podría dañar la confianza de ambos en el otro y en toda su relación.",
			Match: "85%"},
		Communication: SummaryPercentage{
			Text:  "Tanto Libra como Acuario tienen ciertas imágenes que mantener.\n \nLibra quiere parecer agradable y actuar bien ante los demás, mientras que Acuario quiere ir en dirección contraria a todos, a veces incluso aunque no haya motivo para ello.\n \nAmbos son rígidos en sus convicciones y no cambiarán fácilmente de opinión una vez que se hayan decidido.\n \nComo ambos dependen de la comunicación, tendrán mucho de qué hablar y, por lo general, encontrarán un lenguaje para resolver todos sus problemas.\n \nAun así, no les resultará fácil conciliar algunas de las diferencias en su forma de ver las cosas.\n \nLibra es indeciso, pero una vez que toma una decisión, preferirá atenerse a ella antes que salvar su relación, aunque se trate de una simple comida.\n \nAcuario tenderá a alejarse en cuanto se sienta presionado, aunque se trate de la misma comida.\n \nAsí que, básicamente, podrían tener un enorme problema a la hora de comer si hablamos de extremos.\n \nAun así, suelen entenderse bien en las cosas habituales y cotidianas y tienen convicciones similares que les ayudan a manejar bien los grandes cambios de la vida.\n \nCon el tiempo, a medida que se vayan conociendo, sus personalidades se llevarán mejor y podrían darse cuenta de que se respetan hasta un punto inalcanzable con cualquier otra persona.",
			Match: "40%"},
		Emotions: SummaryPercentage{
			Text:  "Libra es un signo regido por Venus y esto les hace ser emocionales en cierto modo, pero debemos recordar que también es un signo de exaltación de Saturno y el desapego es algo que les hace sentir muy bien.\n \nEsto es algo que conseguirán en una relación con Acuario y podría ayudarles a ambos a construir un vínculo emocional muy fuerte.\n \nTienen objetivos extrañamente diferentes en la vida, pero si los armonizan, su vínculo emocional debería ser muy fuerte y desarrollarse mucho más rápido de lo que podríamos anticipar.\n \nEl mayor obstáculo que podría presentarse en su camino es el matrimonio, en algún momento de su relación.\n \nLibra es un signo que representa el matrimonio y lo encuentra muy significativo como la institución que Saturno apoyaría.\n \nAcuario podría considerarlo obsoleto, incluso huir de él y es probable que lo contraiga sólo por razones prácticas.\n \nEs importante no presionar a ninguno de los miembros de la pareja cuando llegue este punto de su relación, o ambos podrían sentir repulsión y enfado, lo que provocaría conflictos innecesarios e incluso el fin de su relación.",
			Match: "80%"},
		Values: SummaryPercentage{
			Text:  "Por mucho que Libra valore la unión, Acuario valorará la soledad.\n \nEsto podría representar un gran problema en su relación, y la pareja de Libra podría parecer pegajosa y nada independiente, mientras que Acuario podría parecer un lunático incontrolable que haría cualquier cosa por destruir todas las relaciones del mundo.\n \nAun así, ambos valoran la comunicación y la fuerza intelectual lo suficiente como para hablar de sus necesidades y deseos, y esto debería ayudarles a superar sus diferencias.",
			Match: "50%"},
		SharedActivities: SummaryPercentage{
			Text:  "Acuario querrá hacer cualquier cosa, en realidad, con tal de que su vida no caiga en una rutina aburrida.\n \nLibra tendrá problemas para decidir lo que quiere hacer y esto podría volver loca a su pareja.\n \nSi algo puede lanzar a Acuario a la órbita es la falta de espontaneidad y Libra a veces puede ser lo contrario de espontáneo.\n \nEstas parejas podrían acabar en una relación en la que sólo Acuario mueve los hilos y Libra le sigue.\n \nEsto no sería realmente una buena solución para ninguno de los miembros de la pareja, y Acuario tendrá que aprender a mostrar algo de paciencia para que el respeto entre ellos permanezca intacto.",
			Match: "65%"},
	},
}
