package compatibilities

var Librasagittarius = Compatibility{
	Name: Libra + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "80%",
		Traits:  []string{FunEnjoyable, CautionRomance},
		Summary: "Libra y Sagitario pueden llegar a ser buenos amigos siempre que haya una buena dosis de condescendencia por ambas partes.\n \nLibra será quien aporte a esta amistad buenas dosis de relajación, armonía y equilibrio.\n \nMantendrá la calma en todas las situaciones que al inquieto Sagitario le pongan de los nervios.\n \nAunque le gusta asumir riesgos, Sagitario no suele tener un buen perder, se agobia y se deprime.\n \nPero ahí encontrará a Libra, dispuesta a mantener la calma hasta que las aguas vuelvan a su cauce.\n \nNo será ésta la única misión de Libra en esta amistad.\n \nPerteneciente al elemento Aire, Libra alimenta el fuego de Sagitario, le ayuda a crecer y desarrollarse.\n \nLa relación entre Libra y Sagitario será muy dinámica porque juntas, las energías de ambos signos resultan altamente estimulantes.\n \nEl inteligente Libra dejará que Sagitario se sienta libre e independiente, le dará margen para que pueda actuar a su modo.\n \nSagitario por su parte, aceptará los a veces frecuentes cambios de ánimo de Libra que suelen afectar a sus planes.\n \nLibra y Sagitario están destinados a entenderse y ser buenos amigos.\n \nA la larga, Libra liderará esta relación y Sagitario se sentirá cómodo con ello.",
	},
	Love: Love{
		Match:  "71%",
		Traits: []string{Harmonious, LowCommitment},
		Summary: SummaryPercentage{
			Text:  "La relación de Libra y Sagitario es, en la mayoría de los casos, un vínculo benéfico que permite a estos compañeros desarrollar sus mundos emocionales e interiores y construir sus vidas sin influencias negativas.\n \nSin embargo, existe una batalla arquetípica entre ellos, ya que Saturno exalta en Libra y no se preocupa mucho por su hijo, Júpiter, el regente de Sagitario.\n \nEsto podría llevar fácilmente a una lucha por la supremacía y a una batalla por alcanzar la posición dominante entre ellos.\n \nEsto viene como una continuación del Sol magullado de Libra y un Sagitario encajará perfectamente con la necesidad de entregar todo sentido de orgullo por algunas convicciones infantiles.\n \nLa única manera de que sean felices juntos, es respetarse plenamente y dejar que cada uno haga lo que debe hacer.\n \nLibra debe ceñirse a su relación y al amor, regido por Venus, mientras que Sagitario debe ceñirse a sus convicciones y a su amplitud, regido por Júpiter, multiplicando el amor que le proporciona Libra.",
			Match: "71%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La intensidad del contacto emocional y la intimidad entre un Libra y un Sagitario dependerá sobre todo de otros factores de las cartas personales, pero sin duda disfrutarán de su relación sexual.\n \nSon una muy buena pareja en lo que respecta a la sexualidad, ya que ningún miembro de la pareja se siente presionado y hay suficiente espacio para que ambos crezcan y se sientan seguros en los brazos del otro.\n \nRegidos por dos planetas benéficos, Venus y Júpiter, su principal objetivo es formar una relación sexual placentera, con la meta primordial de hacer feliz al otro.\n \nPara ello, experimentarán mucho y probarán cosas nuevas, todo ello seguido de una sonrisa y una sensación de ligereza, como si el sexo no fuera realmente un gran problema en primer lugar.\n \nLa seriedad de Libra unida a su exaltación de Saturno dará a toda su relación resistencia y estabilidad, mientras que su regente Venus trabajando junto a Júpiter, da suficiente romanticismo, deseo sexual, ternura y podría llevarles a un final de cuento de hadas.\n \nEsta combinación de planetas forma Neptuno en cierto modo, y habla del crecimiento de la satisfacción que conduce al placer orgásmico, a pesar de que ambos signos pueden no parecer en absoluto sexual a algunos otros miembros del zodiaco.",
			Match: "90%"},
		Trust: SummaryPercentage{
			Text:  "Como ya se ha dicho, los regentes de Libra y Sagitario están estrechamente vinculados a Neptuno y el desafío de la confianza es una de las experiencias más importantes que proporciona esta relación.\n \nAmbos pueden irse a los extremos, ya sea teniendo una fe poco realista en el otro o desconfiando de cada palabra y cada acción que se realice.\n \nLa única manera de mantener la imagen de confianza para estos signos parece ser permanecer siempre en un estado de cuento de hadas, irreal, y esto es algo que un Sagitario nunca querrá hacer.\n \nSi no se vive la verdad, nada en el mundo es hermoso para un Sagitario Sol.\n \nEn cuanto inicien su búsqueda de algo diferente, Libra percibirá el cambio y se sentirá frustrado por su incapacidad de crear unidad con una pareja a la que ama.",
			Match: "5%"},
		Communication: SummaryPercentage{
			Text:  "Es maravilloso observar cómo se ablanda Libra, olvidándose de Saturno y de su propia responsabilidad, mientras la naturaleza infantil de Sagitario derrite su corazón.\n \nAunque no sea algo con un futuro prometedor, ya que nadie puede huir de su verdadera naturaleza, les aportará alegría y felicidad al menos durante un tiempo.\n \nLa pareja Libra podrá relajarse junto a alguien que no juzga, y la pareja Sagitario sentirá que su energía está bien enfocada hacia alguien que necesita un poco de juventud, calor, luz, optimismo y creatividad en su vida.\n \nMientras no rocen los problemas de ego, su comunicación y compatibilidad intelectual son un hecho.\n \nEl principal problema que acabará aflorando y con el que habrá que lidiar, está en las fuerzas de sus Soles.\n \nEl Sol de Libra es débil, y fácilmente cederán el timón a otra persona que tome decisiones y movimientos positivos por ellos.\n \nSagitario tiene demasiada energía ardiente en su Sol, activo, actuando y siempre dispuesto a dar algo de sí aunque nadie se lo haya pedido.\n \nEsto podría llevar a una sutil y oculta imposición de voluntades y a un cambio de carácter que dejará a ambos magullados por respeto cuando por fin se haga la luz sobre el asunto.",
			Match: "85%"},
		Emotions: SummaryPercentage{
			Text:  "Se trata de una de las parejas más compatibles en lo que respecta al aspecto emocional de su relación.\n \nNo es fácil para ninguno de ellos encontrar el amor y compartirlo con alguien.\n \nAl fin y al cabo, son un signo de Aire y otro de Fuego.\n \nAunque Libra está regido por Venus, está vinculado a los procesos mentales, la adaptación social y la comunicación a través de su elemento, mientras que Sagitario tiene sentimientos apasionados, pero utiliza la cabeza, difundiendo su filosofía, más que sentir realmente.\n \nCuando se juntan, parecen capaces de encontrar un equilibrio en el que ambos utilizan la cabeza lo justo y se dan el espacio suficiente para que nazca el amor.\n \nSe trata de un vínculo que brinda a ambos la oportunidad de comprender hasta dónde pueden llegar sus emociones, ya que los regentes benéficos permiten que los sentimientos afloren en una atmósfera de apoyo.\n \nAunque su relación no siempre está destinada a ser la que mantendrán de por vida, podría prepararles para un amor que buscan, dándoles una idea de lo que son capaces de hacer.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Estas parejas valorarán la fuerza de la mente de un modo comprensible sólo para ellos.\n \nLibra no parece una persona creativa para los demás, pero un Sagitario ve su intelecto a través de la comunicación y le motiva a mostrar su calidez.\n \nEsto lleva a compartir el valor de toda su relación y a un entendimiento intelectual que les da espacio para construir su filosofía compartida.\n \nIncluso si no comienzan su relación en el mismo lugar, tendrán la oportunidad de construir valores similares con el tiempo, mostrándose mutuamente lo que es verdaderamente importante.",
			Match: "75%"},
		SharedActivities: SummaryPercentage{
			Text:  "Aunque podríamos suponer fácilmente que un Libra y un Sagitario tendrán muchas cosas que hacer juntos, es muy probable que sus elecciones de actividades no sean tan similares.\n \nLibra quiere ceñirse a su rutina habitual, y hacer excursiones a cosas que le interesen de vez en cuando.\n \nSagitario quiere alejarse de cualquier rutina y vivir una vida viajando por el mundo.\n \nHay excepciones a esta regla, por supuesto, y hay Libras elevados que querrán viajar por el mundo, tanto como hay representantes de Sagitario que quieren seguir un determinado camino, mientras fantasean con su realidad.\n \nSin embargo, en la mayoría de los casos, sus necesidades no encajarán tan bien y probablemente se enfrentarán al desafío de su habitual batalla de egos mientras eligen qué hacer juntos.",
			Match: "70%"},
	},
}
