package compatibilities

var Librapisces = Compatibility{
	Name: Libra + " - " + Pisces,
	Friendship: Friendship{
		Match:   "80%",
		Traits:  []string{MutualRespect},
		Summary: "Libra y Piscis son muy compatibles, tanto por sus aficiones en común como por sus respectivas personalidades, muy similares en el fondo aunque externamente sean totalmente distintas.\n \nCuando Libra y Piscis coinciden sienten fascinación al instante el uno por el otro.\n \nSi entablan una relación en este terreno, ambos se involucrarán con entusiasmo y energía en esta amistad que será sólida y sincera.\n \nTanto Libra como Piscis, son personas soñadoras e idealistas, aunque de forma diferente y su relación será siempre agradable y equilibrada.\n \nSin embargo, ambos tienen una indecisión notable, por lo que a veces no será raro que persigan sus fines comunes desde posturas diferentes.\n \nEn una relación de amistad entre Libra y Piscis los problemas serán escasos o incluso inexistentes.\n \nSi en alguna ocasión llegan a discutir, sus diferencias serán por poco tiempo, se reconciliarán de inmediato.\n \nAdemás, afortunadamente, Libra y Piscis olvidan y perdonan con suma facilidad.\n \nLa modestia es una cualidad que poseen tanto Libra como Piscis, pero Libra necesita sentirse valorado, apreciado, precisa del reconocimiento de los demás.\n \nSin embargo, Piscis prefiere seguir en la sombra.\n \nLo mejor de esta amistad es el interés de ambos signos por ayudar a los demás y colaborar con las cuestiones humanitarias.",
	},
	Love: Love{
		Match:  "29%",
		Traits: []string{DeepMutualUnderstanding, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "Libra y Piscis tienen un punto de encuentro en la belleza de Venus.\n \nSin embargo, la perciben de dos maneras diferentes y a menudo no se respetarán lo suficiente como para encontrar la belleza de Venus en el otro.\n \nPodrían tener verdaderos problemas para adaptarse a la velocidad de su pareja, y la cualidad mutable de Piscis a menudo no les ayudará a abrirse más rápido para construir una relación al ritmo que se adaptaría a su pareja Libra.\n \nTanto Libra como Piscis pueden interesarse desinteresadamente por la satisfacción de su pareja, y esto debería ayudarles a mantenerse en el lado bueno de su relación pase lo que pase entre ellos.\n \nSi dejan atrás la falta de respeto y las expectativas poco realistas de la personalidad del otro, podrían descubrir que comparten un amor verdadero.",
			Match: "29%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Aire y Agua, Libra y Piscis parecen no tener casi nada en común.\n \nSin embargo, no debemos olvidar su conexión a través de Venus, el regente de Libra, exaltado en Piscis.\n \nDado que se tocan a través de este planeta sensual y amoroso, podrían encontrar juntos una verdadera satisfacción sexual.\n \nAmbos pueden ser amantes desinteresados, preocupándose más por la satisfacción de su pareja que por la suya propia.\n \nLa ternura no debería ser un problema, ya que a ninguno de los dos les gusta la agresividad ni la rudeza.\n \nPodrían descubrir muchas preferencias sexuales diferentes de las que antes no eran conscientes, a través de una conexión de naturalezas muy diferentes.\n \nSi no estuvieran conectados por Venus, sería muy difícil para ellos formar una relación de cualquier tipo, ya que su enfoque de la vida y la sexualidad es completamente diferente.\n \nLibra querrá que sus experiencias sexuales sean rápidas y excitantes, y Piscis las querrá lentas y sensuales.\n \nEl principal problema de la velocidad suele superarse gracias a la naturaleza rápidamente cambiante de Piscis, excepto en los casos en que son demasiado tímidos para lanzarse a una relación sexual con alguien tan abiertamente sexual como Libra.",
			Match: "50%"},
		Trust: SummaryPercentage{
			Text:  "No se entenderán lo suficiente como para compartir mucha confianza.\n \nLa necesidad que tiene Libra de ser aceptado y querido por los demás será interpretada erróneamente por Piscis, ya que no entiende cómo alguien puede tener tan poca confianza en sí mismo.\n \nEse carácter chispeante, siempre enamorado, infantil y coqueto de Piscis será una gran desilusión para Libra, que no podrá confiar en alguien que muestra abiertamente su interés por otras personas.\n \nLa única forma de que estos dos miembros de la pareja mantengan una relación de confianza es abordarla de forma casual y construir su entendimiento y confianza desde cero, como si nunca hubieran tenido ninguna relación antes de ésta.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "En muchos casos, Libra apreciará el optimismo y la ingenuidad infantil de su pareja Piscis.\n \nPor desgracia, a menudo querrá ayudarles a crecer y a cambiar su forma de ser para que sean 'más felices'.\n \nEl problema aquí radica en el hecho de que Libra no sabe ni intenta comprender qué haría verdaderamente feliz a Piscis.\n \nEsto es una falta de respeto básica y podría arruinar los cimientos de toda su relación.\n \nEl principal reto aquí es permanecer en un vínculo respetuoso, por muy loco que Piscis pueda parecer a su pareja Libra, o por muy rígido y aburrido que Libra pueda parecer a Piscis.\n \nSu comunicación puede ser inspiradora siempre que no intenten cambiarse mutuamente, explicarse cómo deben pensar o sentir en determinadas situaciones o, peor aún, enseñarse cómo deben comportarse.\n \nLa pareja Piscis puede ser bastante directa y espontánea y esto podría poner en peligro la imagen que Libra intenta mantener a los ojos de los demás.\n \nSi las acciones del otro les resultan inspiradoras de algún modo posible, podrían llegar a un punto en el que realmente se comunicarían sin juzgarse.",
			Match: "5%"},
		Emotions: SummaryPercentage{
			Text:  "Su conexión emocional se presenta sobre todo a través de la adoración de Venus en el signo de Piscis.\n \nSe trata de un amor eterno que está a punto de surgir, y que podría nacer entre estos dos miembros de la pareja en caso de que ambos superen su ego.\n \nSerá un acontecimiento raro y sus racionalidades les pesarán, pues Libra exalta a Saturno y Piscis está regido por Júpiter.\n \nEs probable que sus mentes se llenen de todo tipo de información irrelevante hasta que decidan que simplemente es demasiado difícil para ellos estar juntos.\n \nSi superan el punto de la falta de respeto y establecen límites firmes, alimentando la individualidad y autosuficiencia del otro, podrían llegar al punto de la interacción emocional.\n \nComo si no tuvieran suficientes desafíos, esto sucederá generalmente en otro momento.\n \nLibra se precipitará en un alarde emocional al darse cuenta de que ha encontrado el amor, pero Piscis no sentirá amor hasta que se asiente el polvo y tenga tiempo de cerrar los ojos y sentir.\n \nSi no es el momento adecuado, es probable que la relación termine en buenos términos y que no esperen mucho el uno del otro en el futuro.",
			Match: "15%"},
		Values: SummaryPercentage{
			Text:  "Ambos valorarán el amor y esto es algo que les unirá por encima de todo lo demás.\n \nCon Venus en el foco, ambos necesitarán ser amados y apreciarán a quienes sepan cómo demostrarlo, cómo disfrutar de la vida, la comida y el sexo, y cómo hacer que sus seres queridos queden satisfechos.\n \nEsto podría darles una base sólida para una relación sexual si se sienten atraídos el uno por el otro en primer lugar.\n \nEl resto de sus caracteres diferirán mucho y mientras Libra valorará la coherencia y la estabilidad, Piscis valorará la espontaneidad y la capacidad de cada uno para seguir a su corazón.\n \nSi ambos creen que tienen una misión aquí en la Tierra, y sucede que sus misiones se cruzan, podrían inspirarse mutuamente para luchar por lo que más valoran: sus nombres en las estrellas.",
			Match: "60%"},
		SharedActivities: SummaryPercentage{
			Text:  "El indeciso Libra es exactamente lo que su pareja Piscis no necesita para no sentirse completamente perdido en la vida y en todas las actividades que ha elegido.\n \nEl problema aquí es que para cuando Libra decida si quiere hacer algo o no, Piscis cambiará de opinión cinco veces, sin estar seguro de si es lo mejor para él, para su relación, para el propósito y la misión de su vida, etc.\n \nEl cuestionamiento de Libra levantará sospechas en Piscis con dolorosa facilidad.\n \nSe las arreglarán para encontrar actividades que les gusten a ambos, y si nada funciona siempre pueden recurrir a cualquier tipo de arte.\n \nLa verdadera pregunta es: ¿querrán hacer algo mientras estén juntos? Podrían drenar mucha fuerza y confianza el uno en el otro sólo tratando de hacer un plan para la noche.",
			Match: "40%"},
	},
}
