package compatibilities

var Libracapricorn = Compatibility{
	Name: Libra + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "60%",
		Traits:  []string{CautionRomance, Stormy},
		Summary: "Existe un vínculo invisible entre Libra y Capricornio que desde fuera cuesta un poco de entender pero que les da mucha solidez cuando se relacionan como amigos.\n \nSe necesitan para complementarse y esto lo tienen bien claro.\n \nQuizá de entrada Libra y Capricornio no encuentren muchas afinidades, pero si tienen paciencia para pasar de estos primeros encuentros, se sorprenderán de lo complementarios que pueden llegar a ser.\n \nCapricornio le transmite a Libra la seguridad que a éste le falta, le ayuda a no ser tan indeciso.\n \nAdemás le enseñará que la paciencia es un don muy necesario y que un poco de ambición no le viene mal a nadie.\n \nLibra, por su parte, hará que Capricornio se muestre más optimista y deje de verlo todo blanco o negro, le enseñará que la gama de grises es infinita y muy necesaria para vivir relajado.\n \nLibra y Capricornio tienen en común su amabilidad, aunque su forma de entender las relaciones personales sea distinta.\n \nLibra es extrovertido y capaz de llevarse bien con todo el mundo, mientras que Escorpio es introvertido y conservador.\n \nDifícilmente dejará que alguien penetre en su intimidad.\n \nSu mayor cualidad es la sinceridad, que tanto sabrá valorar Libra si decide convertirse en su amigo.",
	},
	Love: Love{
		Match:  "34%",
		Traits: []string{Volatile, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Si queremos elegir la mejor palabra para describir la relación entre una pareja de Libra y una de Capricornio, tendríamos que decir: dura.\n \nEsto no significa que no disfrutarán de los problemas de estar juntos, o permanecer en una relación durante mucho tiempo, pero esto no es ciertamente un vínculo que muchos otros signos se comprometería.\n \nSu mayor desafío es la falta de respeto por el valor emocional que suele iniciar Capricornio, pero que Libra continúa fácilmente.\n \nSi encuentran la forma de compartir, mostrar y comprender las emociones del otro, todo lo demás parecerá pan comido.",
			Match: "34%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando hablamos de una relación sexual entre un Libra y un Capricornio, lo primero que nos viene a la mente es la espera.\n \nEn cuanto al sexo, esta combinación podría apuntar a una falta de actividad sexual, a pesar de que ambos signos consideran que el sexo es muy importante en sus vidas.\n \nPara empezar, es posible que no sientan atracción alguna, e incluso que inicien una relación sobre una base formada en la amistad, sólo para darse cuenta de que no hay química entre ellos.\n \nSi la falta de atracción no les detiene, normalmente algo más lo hará.\n \nEs una combinación que cede ante circunstancias externas y cosas que están fuera de su control.\n \nAmbos podrían sentirse presionados y su autoestima podría resentirse mucho.\n \nSin embargo, existe un entendimiento entre ellos encendido por la exaltación de Saturno en Libra.\n \nEsto hace que ambos comprendan el buen momento y, por lo general, no les permitirá cometer un error esperando lo que no se debe esperar.\n \nEn caso de que superen todos los obstáculos y formen un fuerte vínculo a través de sus posiciones natales personales, Libra y Capricornio pueden tener relaciones sexuales bastante conservadoras, de acercamiento rutinario y sólo satisfactorias si ambos se desprenden de sus estrictas premisas y condiciones.",
			Match: "15%"},
		Trust: SummaryPercentage{
			Text:  "Algo extraño en una relación de Libra y Capricornio es un nivel realmente alto de confianza entre ellos.\n \nAunque Libra pueda tener a veces motivos cuestionables, una pareja Capricornio hará que se vuelvan completamente hacia Saturno y se sientan culpables al menor atisbo de una posible mentira.\n \nEl único problema posible surge cuando Capricornio es demasiado estricto desde el principio, haciendo que su pareja Libra se sienta inadecuada, juzgada o incluso asustada por las consecuencias de sus actos.\n \nEsto podría convertir su relación en deshonesta, no porque realmente haya algo que ocultar, sino porque la pareja de Libra siente la necesidad de protegerse aferrándose a su intimidad.",
			Match: "80%"},
		Communication: SummaryPercentage{
			Text:  "Los Libra, cuando se encuentran en una relación con un Capricornio, de repente se vuelven testarudos y a veces incluso es imposible hablar con ellos.\n \nAunque Libra ama a Capricornio debido a la exaltación de Saturno, esto se muestra de la forma más inusual, pues parecen sentir la necesidad de hablar por despecho.\n \n Los mayores obstáculos para su entendimiento son los elementos a los que pertenecen.\n \nAire y Tierra están demasiado alejados y no tienen claro cómo entenderse en la vida.\n \nSin embargo, hay una prudencia en ambos que podría darles la suficiente profundidad y comprensión para mantener discusiones muy interesantes y motivarse mutuamente para construir una base mejor para cada próximo debate.\n \nSi mantienen la racionalidad en sus relaciones mentales, podrían divertirse de una forma que otros signos no serían capaces de entender.\n \nLa satisfacción que ambos obtendrán de la resolución seria de problemas podría llevarlos a un punto en el que encuentren juntos una solución, Libra la pone en palabras y Capricornio la pone en acción.\n \nProbablemente no haya nada en el mundo que pueda elevar más sus egos que las situaciones en las que lograron resolver algo con un simple esfuerzo compartido.",
			Match: "35%"},
		Emotions: SummaryPercentage{
			Text:  "Lo más difícil de conciliar en la relación entre un Libra y un Capricornio, son las formas en que abordan sus sentimientos.\n \nLibra es un signo regido por Venus y sus emociones surgen de forma natural, pero normalmente restringidas y contenidas debido a la seriedad de su naturaleza y al juicio de los demás que temen.\n \nCapricornio tiene la misión en la vida de aceptar todas las emociones y, en la mayoría de los casos, a menos que se ilumine, será esa fuerza juzgadora que frena a Libra.\n \nPor si esto fuera poco, toda la situación alimentará el ego de Capricornio y le hará pensar que tiene razón en su enfoque, lo que le alejará aún más de su punto de enfoque.\n \nEsta es una pareja que tiene que esforzarse por encontrar un lenguaje compartido para mostrar cómo se sienten y seguir respetándose.\n \nLa naturaleza emocional de Capricornio les hace distantes para muchos, pero completamente intocables para Libra en cuanto empiezan a desestimar sus sentimientos.\n \nLo único que se puede hacer aquí es encontrar un punto de absoluto respeto y aceptación de todas las emociones y sus manifestaciones.\n \nSi se permiten romper cosas, enfadarse, llorar, montar escenas en público o ceder a la histeria, puede que encuentren la forma de expresar su amor de un modo que se entienda correctamente.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Los valores más importantes que comparten Libra y Capricornio son el valor del tiempo y la asunción de responsabilidades.\n \nEsto puede ayudarles a superar cualquier diferencia y actitudes, valores o convicciones opuestas, ya que cada uno de estos miembros de la pareja estará dispuesto a comprender el conjunto de responsabilidades que tienen el uno hacia el otro.\n \nComo signos de Aire y Tierra, ambos bastante asentados en sus costumbres, Libra y Capricornio diferirán mucho en el valor de las palabras y los hechos.\n \nLibra comunicará y pensará que su mente es su mayor activo, mientras que a Capricornio no le importará realmente si los resultados no se manifiestan a través del mundo material.\n \nEste es un buen entrenamiento para que la pareja de Libra encuentre un punto de apoyo, pero normalmente no será agradable para ninguno de ellos en una relación romántica.",
			Match: "50%"},
		SharedActivities: SummaryPercentage{
			Text:  "Lo mejor que estos dos pueden hacer juntos es ser aburridos para el resto del mundo.\n \nExiste una gran probabilidad de que su relación les arrulle al estado de trabajo duro y descanso perezoso, sin esfuerzo por nada creativo o inspirador.\n \nNecesitan mantener encendidas sus pasiones y crear una rutina semanal que les haga salir de casa y hacer algo divertido.",
			Match: "25%"},
	},
}
