package compatibilities

var Librascorpio = Compatibility{
	Name: Libra + " - " + Scorpio,
	Friendship: Friendship{
		Match:   "45%",
		Traits:  []string{Stormy},
		Summary: "Aunque es cierto que Libra y Escorpio presentan grandes diferencias en sus respectivas personalidades, pueden llegar a ser buenos amigos a poco que se lo propongan porque en el fondo son más parecidos de lo que pueda parecer a simple vista.\n \nUn punto que les une es que Libra y Escorpio detestan discutir y siempre intentarán buscar una solución dialogante a los conflictos.\n \nEsto hace que en el ámbito de la amistad las peleas entre ambos no existan.\n \nAdemás, tanto Libra como Escorpio son signos que tienen la lealtad como un gran valor y que buscan seguridad emocional.\n \nEn este sentido, sus energías son totalmente compatibles.\n \nA Libra le cuesta entender por qué Escorpio es tan desconfiado y posesivo, y a éste le molesta que Libra intente siempre escapar de los problemas en vez de afrontarlos.\n \nPodrán superar estas diferencias fácilmente, puesto que son más interesantes los rasgos que les unen.\n \nLos dos son amables y sociables, y no les cuesta nada ponerse de acuerdo en los planes a realizar.\n \nAunque muchos duden de la posible amistad entre Libra y Escorpio, tendrán que aceptar los hechos, porque a pesar de sus diferencias se entregaran mutuamente su confianza.",
	},
	Love: Love{
		Match:  "29%",
		Traits: []string{Volatile, NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "La relación de Libra y Escorpio no es en absoluto fácil y ligera.\n \nAmbos miembros de la pareja tendrán que enfrentarse a sus lados oscuros a través de este vínculo, y aunque esto puede conducir a una increíble e intensa vida sexual, y a emociones que nadie más puede entender, podría llevar a ambos a un agujero depresivo del que no saldrán fácilmente.\n \nLa única forma de que esta pareja dure en una relación satisfactoria y amable, es que ambos construyan una vida individual fuerte e independiente, o se verán absorbidos por el torbellino de emociones kármicas y expectativas obsesivas y negativas.",
			Match: "29%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Se trata de una pareja intensa en todos los sentidos y su relación sexual es algo realmente excitante y desafiante al mismo tiempo.\n \nEstán unidos por su naturaleza animal, continuándose mutuamente, regidos por planetas que también rigen sus signos opuestos.\n \nSe trata de un contacto sexual complicado, ya que están regidos por Venus y Marte, como si estuvieran hechos el uno para el otro.\n \nSin embargo, parece que les falta el toque del elemento que ambos necesitan, separados por el elemento rápido y superficial del Aire en Libra y emocional y lento del Agua en Escorpio.\n \nAunque no se hagan felices mutuamente en otros aspectos de su relación, cuando la pareja Libra se deja llevar por su lado instintivo y animal, se convierte fácilmente en uno con su pareja Escorpio.\n \nSu vida sexual puede ser increíblemente emocional y exigente, ya que la atracción de sus energías es extremadamente fuerte y hace que ambos sean obsesivos y posesivos el uno con el otro.\n \nA menudo, ambos estarán tan atados que su relación parecerá imposible de romper.\n \nEstos lazos se crean a través del contacto físico, aunque todo lo demás en su relación les produzca una profunda insatisfacción.",
			Match: "45%"},
		Trust: SummaryPercentage{
			Text:  "Si Escorpio no puede confiar en alguien, es en Libra.\n \nCómo podrían hacerlo cuando parece haber una evidente necesidad en su pareja Libra de mostrar lo atractivos y sensuales que son al resto del mundo.\n \nPor si fuera poco, esa posesividad de Escorpio es fácilmente absorbida por Libra, y empezarán a actuar de forma similar, obsesionándose cada vez que su pareja quiera hacer algo a solas.\n \nAunque éste sea el peor de los casos, es probable que esta atmósfera esté presente en cualquier pareja Libra-Escorpio a menor escala.\n \nLa pregunta es: ¿están preparados para vivir así todos los días? Si lo aceptan como una forma de compartir un amor verdadero y profundo, sus problemas de confianza no supondrán un gran problema, por muy extraños que parezcan.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "No hay nada que Escorpio pueda decir que Libra no sea capaz de racionalizar.\n \nSu comunicación es el lugar exacto donde la conexión de Libra con Saturno resulta útil.\n \nEsto le dará a Libra la capacidad de reducir la velocidad, respirar y comprender los actos impulsivos o las palabras de su pareja Escorpio.\n \nHay suficiente profundidad en estos dos signos, aunque Libra es un signo de Aire y bastante distante del planeta Tierra.\n \nEsto permitirá que haya suficiente entendimiento entre ellos en un sentido racional.\n \nEl problema con el que tienen que lidiar es el hecho de que ambos representan un detrimento para los regentes del otro.\n \nEsto llevará fácilmente a descartar la personalidad del otro, sobre todo porque Libra tiene que lidiar con problemas de personalidad por la caída del Sol, y Escorpio no acepta nada que no esté completo.\n \nLibra tendrá problemas para comprender el lado agresivamente claro de Escorpio, tanto como Escorpio no comprenderá el acto deshonesto de su pareja Libra.\n \nSus diferencias podrían ser muy difíciles de conciliar si se acercan demasiado el uno al otro y empiezan a entrometerse en sus vidas y decisiones personales.",
			Match: "55%"},
		Emotions: SummaryPercentage{
			Text:  "Libra busca una pareja activa y fogosa que despierte su fuerza vital y aporte luz a su vida.\n \nEscorpio busca a alguien físico, sensual y práctico, y aunque Libra puede satisfacer estas necesidades hasta cierto punto debido a la exaltación de Saturno y el dominio de Venus, en la mayoría de los casos no es principalmente lo que quieren ser.\n \nCuando existe una chispa entre ellos, es fácil que se convierta en un incendio que queme ciudades enteras, bosques y a todos los que se encuentren en su camino, incluidos ambos.\n \nEsa energía nuclear de Escorpio es encendida por su signo precedente de Libra, porque lleva información sobre todos los asuntos no resueltos en las relaciones y toda la ira que no se ha dejado salir debido a la necesidad forzada de un comportamiento apropiado.\n \nEn otras palabras, Libra acumulará la energía sexual no expresada y estallará en Escorpio, dando lugar a una guerra de por vida si se empuja lo suficiente bajo la alfombra.\n \nEsto se interpretará como amor supremo, haciendo que su relación emocional sea ridículamente intensa.\n \nNecesitan comprender que el amor es ternura tanto como todo lo demás y si no la tienen, quizá no sea amor sino simple atracción física y necesidad de desahogarse de las restricciones.",
			Match: "25%"},
		Values: SummaryPercentage{
			Text:  "Ambos valorarán la coherencia y el compromiso y esto es algo que les unirá en primer lugar.\n \nSin embargo, el resto de sus sistemas de valores no coinciden tanto y diferirán en el comportamiento y las expectativas de otras personas.\n \nMientras Libra frunce el ceño ante el comportamiento indecente, Escorpio tendrá amigos indecentes, honestos sobre su acto y totalmente aceptados y respetados por ello.\n \nA Libra le parece que Escorpio hace todo lo fuera de lo común sólo para parecer especial, mientras que Escorpio ve que Libra hace todo lo ordinario sólo para encajar.\n \nEl principal problema aquí está en el valor que dan a las opiniones de otras personas y esto no será fácil de superar.",
			Match: "10%"},
		SharedActivities: SummaryPercentage{
			Text:  "Si hay una actividad que un Libra y un Escorpio pueden compartir todo el tiempo, debe ser el sexo.\n \nEscorpio despertará el lado animal de su pareja Libra, y su tiempo juntos se centrará sin duda en que ambos sigan sus instintos.\n \nEscorpio es un signo de exaltación de Urano y carecerá de paciencia ante la indecisión de Libra.\n \nPor eso, sus necesidades no encajarán muy bien en otras áreas de su vida y es posible que no puedan satisfacer las expectativas del otro.\n \nUna excepción a esta regla ocurre cuando Libra se pasa al lado oscuro y cede a la necesidad de Escorpio de llevarlos al Inframundo.\n \nNinguna otra pareja encenderá esta necesidad en Escorpio como una pareja Libra.",
			Match: "35%"},
	},
}
