package compatibilities

var Piscespisces = Compatibility{
	Name: Pisces + " - " + Pisces,
	Friendship: Friendship{
		Match:   "80%",
		Traits:  []string{CautionRomance},
		Summary: "Es en este ámbito donde Piscis y Piscis combinarán de maravilla.\n \nEllos se comprenderán al instante y se convertirán en inseparables, pero también mucha otra gente les buscará como amigos por su empatía y su gran poder de comprensión.\n \nTambién a Piscis le gusta tener amigos en todas partes, así que Piscis y Piscis pueden mantener una amistad quizá rodeados de una multitud.\n \nCuriosamente, a Piscis no le interesa destacar o ser el primero en nada, pero siempre está ahí para lo que haga falta y esto tiene un gran valor para muchísimas personas.\n \nPiscis y Piscis formarán un gran dúo, tanto por su capacidad mutua de empatizar con el otro como por su tendencia a conocer la mejor forma de ayudar a los demás.\n \nQuizá no sean los más divertidos del mundo, pero no cabe duda que siempre estarán con su amigo cuando éste lo necesite, pasando incluso por encima de sus propias necesidades.\n \nPiscis y Piscis mantendrán una amistad para toda la vida, aún cuando sus encuentros lleguen a ser esporádicos.\n \nCualquiera de los dos Piscis será capaz de leer en la mente del otro y conectar con su alma con facilidad.\n \nSu amistad será algo indestructible y que ambos sabrá valorar en su justa medida.",
	},
	Love: Love{
		Match:  "73%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "Dos Piscis tendrán problemas para confiar el uno en el otro.\n \nSus naturalezas cambiantes modificarán su relación todo el tiempo, y sólo si comparten suficiente amor, podrán soportar los cambios y permanecer juntos.\n \nEn la mayoría de los casos, no se enamorarán, debido a su necesidad interior de inspirar a su pareja y ayudarla a crecer.\n \nNo lo necesitan el uno del otro, porque ya se inspiran a sí mismos.\n \nCuando el amor romántico surge entre ellos, es posible que vivan una historia de cuento de hadas, de unicornios, arco iris y amor eterno.",
			Match: "73%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "A primera vista, dos representantes de Piscis podrían formar una pareja perfecta, pero cuando rascamos bajo la superficie, vemos que tienen verdaderos problemas para acercarse el uno al otro.\n \nSu vida sexual puede ser mágica, pero en muchos casos ni siquiera llegarán al contacto físico, manteniendo su relación sin sentido de forma platónica.\n \nEsto no es consecuencia de una falta de iniciativa, sino más bien de su propia necesidad de permanecer en la burbuja de la perfección emocional y de su miedo a romper esta burbuja entablando una relación física que requiera enfrentarse a imperfecciones físicas.\n \nCuando inicien una relación física, ambos podrían ser demasiado cautelosos en cuanto a las opciones de actividad sexual que se propondrán mutuamente.\n \nSu relación podría inhibirlos extrañamente, debido a la posibilidad de expectativas poco realistas y al miedo a ser defraudados.\n \nAfortunadamente, sus naturalezas mutables les permitirán en la mayoría de los casos progresar y hacer suficientes adaptaciones y cambios para que su vida sexual funcione.\n \nCuando lo hagan, encontrarán la cantidad exacta de ternura y libertad sexual que ambos necesitan, y comprenderán las necesidades del otro antes de hablar.",
			Match: "75%"},
		Trust: SummaryPercentage{
			Text:  "La confianza es un tema muy difícil cuando dos representantes de Piscis inician una relación romántica.\n \nSu principal problema radica en que se conocen demasiado bien.\n \nAmbos pueden reconocer su propia naturaleza inestable y poco fiable en su pareja, por lo que en lugar de crear confianza y cambiar ambos para mejor, se verán fácilmente atrapados en un círculo de intentos de ser honestos y deshonestos, sin necesidad de que su naturaleza escamosa cambie.\n \nLa mejor forma de crear un ambiente seguro y de confianza para ellos es con mucha comunicación significativa que ambos suelen encontrar obsoleta.",
			Match: "50%"},
		Communication: SummaryPercentage{
			Text:  "Piscis es el signo de la caída de Mercurio y estos individuos estarán a menudo demasiado encerrados o perdidos para tener una buena comunicación práctica.\n \nAunque compartirán sus sueños y probablemente se inspiren mutuamente en muchos aspectos, les resultará difícil mantener conversaciones sobre las cosas corrientes de sus vidas.\n \nAmbos tendrán su propia imagen de lo que es importante que su pareja sepa de ellos.\n \nEs bueno que tengan un sentimiento tan fuerte sobre el punto del otro, porque probablemente nunca se conocerían si no existiera una conexión emocional entre ellos.\n \nTendrán tendencia a no moverse de un punto determinado, ambos intensamente centrados en la idea del amor, más que en las actividades reales.\n \nEsto les llevará fácilmente a un punto en el que realmente no haya nada más que compartir y de lo que hablar, especialmente si no comparten el mismo grupo de amigos, o tienen otras actividades conjuntas de las que puedan hablar a diario.\n \nSi llevan vidas separadas, podrían acabar en una relación en la que simplemente no se conocen y ansían intimar con otra persona.",
			Match: "60%"},
		Emotions: SummaryPercentage{
			Text:  "Piscis es el signo que exalta a Venus, el planeta del amor.\n \nVenus no sólo rige el signo de Libra, que habla de nuestras relaciones, sino que también es el regente de Tauro y representa los placeres físicos y la satisfacción del cuerpo físico.\n \nEl signo de Piscis tiene la gran responsabilidad de exaltar el planeta que está vinculado a todos los aspectos de una relación amorosa.\n \nEl contacto emocional entre dos parejas de Piscis rara vez se materializará, porque ambos buscan a alguien que necesite inspiración, y los dos no la necesitan de su pareja.\n \nCuando se enamoran, se trata de un romance de cuento de hadas y su contacto emocional es algo que ningún otro signo puede alcanzar.\n \nDos de los representantes de la exaltación de Venus en una misma relación, son amor multiplicado.\n \nSu ternura y la forma en que alimentan sus emociones el uno hacia el otro, serán una verdadera inspiración para todos los que les rodean.\n \nNo hay mejor compañero para comprender la naturaleza emocional de una pareja Piscis, que otro Piscis.\n \nSu cualidad mutable se mostrará a través de cambios emocionales y aparente inconsistencia, pero en verdad, sabrán exactamente cuándo separarse y cuándo estar juntos para que su amor siga siendo emocionante y hermoso.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Con su signo exaltando a Venus, es difícil hablar de sus valores mientras mantienen una relación.\n \nAmbos valorarán el talento, la capacidad de mantenerse fiel a uno mismo y la flexibilidad que alguien tenga en el mundo exterior.\n \nSin embargo, dos Piscis pueden darse cuenta de que no comparten los mismos valores cuando están juntos.\n \nEl problema aquí radica en el hecho de que son demasiado parecidos y despertarán las deficiencias del otro con su mera existencia.\n \nEsto dará lugar a malentendidos y a que ambos miembros de la pareja se convenzan de que no valoran las mismas cosas.\n \nNo porque sus valores difieran tanto, sino porque sus prioridades pueden ser distintas.",
			Match: "80%"},
		SharedActivities: SummaryPercentage{
			Text:  "Sin duda, se divertirán mucho.\n \nDos Piscis no pueden aburrirse nunca.\n \nSu relación satisfará todos sus sentidos y pasarán muchas noches románticas, así como días excitantes, abrazados.\n \nSi es que llegan a encontrarse.\n \nMientras que uno de ellos puede aparecer en el momento acordado, el otro se perderá, se equivocará de camino o aparecerá en el punto de encuentro anterior.\n \nCuando por fin consiguen encontrarse, con muchas horas de retraso, es posible que se muevan en direcciones opuestas y no sean conscientes de ello debido a que, para empezar, no se hablaron.\n \nEn general, sus actividades compartidas dependen mucho de su contacto físico, porque si lo tienen, al menos podrían cogerse de la mano para no perderse.",
			Match: "75%"},
	},
}
