package compatibilities

var Sagittariussagittarius = Compatibility{
	Name: Sagittarius + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "60%",
		Traits:  []string{FunEnjoyable, CautionRomance},
		Summary: "Cuando Sagitario y Sagitario entablan una amistad, estará bien equilibrada.\n \nLes encantará pasar tiempo juntos pero sabrán respetar el espacio personal y entender cuando el otro Sagitario desea tomar un poco de distancia.\n \nA Sagitario le gusta vivir sin demasiadas ataduras, así que no harán nada por detener al amigo que de repente quiere salir a respirar aire fresco.\n \nPrecisamente en esta libertad mutua que se otorgan Sagitario y Sagitario, es la base para que su amistad sea sólida y duradera.\n \nDesde que establecen contacto, Sagitario y Sagitario se entenderán a la perfección y respetarán su deseada independencia.\n \nJuntos disfrutarán de proyectos comunes, pero Sagitario sabe que esto no es motivo para dejar de lado otros objetivos más personales e individuales.\n \nSagitario y Sagitario emprenderán juntos numerosas aventuras, explorarán la vida y el único problema es que, siendo ambos tan impetuosos e impulsivos, quizá intenten hacer demasiadas cosas al mismo tiempo porque ninguno de los dos pondrá freno.\n \nNo existirán enfrentamientos entre dos Sagitario, pero si alguna vez tienen ciertas diferencias en su forma de apreciar la vida, harán lo necesario para resolverlas de la mejor manera posible, evitando el resentimiento y el rencor.\n \nPreferirán permanecer atentos a los planes inesperados o proyectando su siguiente hazaña.",
	},
	Love: Love{
		Match:  "74%",
		Traits: []string{LowCommitment, DeepMutualUnderstanding, Harmonious},
		Summary: SummaryPercentage{
			Text:  "Un Sagitario se enamorará fácilmente del otro y su apasionada relación puede cambiar muy rápidamente.\n \nComo dos representantes de un signo mutable, se adaptarán fácilmente, pero cambiarán sus opiniones y sentimientos hacia el otro con una facilidad similar.\n \nEsto no siempre augura una relación duradera, ya que no hay una pareja que sea el pegamento que los mantenga unidos.\n \nEsto no significa que no disfruten de la compañía del otro, que no encuentren muchas cosas que compartir mientras están juntos y que no se rían como niños mientras van por el mismo camino.\n \nSi descubren la verdadera felicidad de dos personas afectadas por Júpiter juntas, puede que pierdan el interés por todos los demás y encuentren ese punto de equilibrio necesario para mantenerse juntos en sus viajes mientras vivan.",
			Match: "74%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando se piensa en dos Sagitario en una relación sexual, es como pensar en dos adolescentes a los que todo les hace gracia.\n \nSe trata de una relación beneficiosa, pero puede ser superficial y muy poco duradera.\n \nEstos dos miembros de la pareja piensan mucho, tienen su propia filosofía liberal y se ven fácilmente arrastrados a una serie de aventuras de una noche o a una actividad sexual casual a la que ningún otro signo se lanzaría.\n \nSagitario es un signo mutable, lo que hace que ambos cambien con el menor atisbo de problema, y aunque están satisfechos con la experiencia desenfrenada y liberadora, seguirán siendo tan íntimos como sus mentes se lo permitan.\n \nEl problema con el que podrían tener que lidiar es la falta de emoción y profundidad en su contacto.\n \nSagitario no suele ser superficial, pero cuando está con otro Sagitario, sus mentes los lanzan en todo tipo de direcciones diferentes y no hay mucho espacio para la emoción genuina.\n \nPueden estar locamente enamorados, pero aún así carecer de consistencia en su contacto emocional.\n \nEsto influirá en su vida sexual y la hará tan cambiante como ambos.\n \nAunque esto no afectará a su satisfacción general, puede truncar su relación y hacerles comprender que necesitan estar con alguien diferente.",
			Match: "65%"},
		Trust: SummaryPercentage{
			Text:  "¿Qué motivo podrían tener dos Sagitario para no confiar el uno en el otro?\n \nEllos se consideran los más honestos de todo el zodíaco, y tendrán la capacidad de entenderse en esta honestidad.\n \nAunque el signo de Sagitario tiene tendencia a mostrar afecto a varias personas a la vez, disfrutando de todo en abundancia, cuando dos de ellos se juntan, simplemente no les importará.\n \nEl único motivo posible de celos y desconfianza en este contacto surge de otros punteros personales, más que de sus Soles en el signo de Sagitario.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "La alegría de este contacto es algo que rara vez alguien tiene la oportunidad de sentir, excepto un Sagitario con otro Sagitario.\n \nCuando encuentran intereses compartidos y descubren sus convicciones similares, no hay nada que les impida entablar conversaciones apasionantes y apasionadas en las que por fin les resulta fácil ser quienes son.\n \nA un Sagitario le encanta hablar con otro y, a menos que haya una batalla oculta de egos entre ellos, rara vez se enfadarán o frustrarán por algo que su pareja tenga que decir.\n \nCada Sagitario suele tener amigos nacidos en el mismo signo solar, porque nadie más puede comprender su naturaleza, apreciarla y despertar su niño interior como su propio reflejo.\n \nCuando estos Soles se juntan, su pasión por las cosas que hacen se multiplica.\n \nMientras no se juzguen ni tengan la necesidad de imponer su voluntad, el tiempo que pasen juntos será increíblemente valioso para ambos.\n \nEsas sonrisas que comparten con todo el mundo en este planeta serán devueltas en la justa medida sólo por otro Sagitario.",
			Match: "99%"},
		Emotions: SummaryPercentage{
			Text:  "Sagitario es un signo que no suele describirse como emocional, pero de hecho su regente, Júpiter, encuentra el lugar de su exaltación en Cáncer, el regente de toda emoción.\n \nPodríamos decir que el verdadero objetivo de todo Sagitario es encontrar esa paz emocional interior, encontrar su hogar, sin huir de las dificultades, de la tristeza y de cualquier emoción con la que deba lidiar.\n \nCada Sagitario quiere estar satisfecho y feliz, sin intenciones ocultas, manipulación, deshonestidad o cualquier impureza.\n \nSus intenciones son siempre buenas y pueden ayudarse mutuamente a alcanzar sus metas utópicas cuando están juntos.\n \nSin embargo, cuando estos dos comienzan su relación, comprenden la positividad y el optimismo que comparten con claridad, pero esto los eleva aún más del suelo.\n \nSi alimentan mutuamente sus incoherencias y necesidades para huir de cualquier seriedad y realidad, podrían perderse realmente en su búsqueda del amor.\n \nEl problema que tienen estas parejas no está en la falta de amor, sino en el apoyo de varias direcciones que pueden alejarles de su corazón.\n \nA menudo parecen necesitar un poco más de constancia para encontrar el amor que buscan.",
			Match: "10%"},
		Values: SummaryPercentage{
			Text:  "Es maravilloso ver a dos secuaces de Júpiter jugar con sus convicciones y compartir valores como si fuera lo más común de la Tierra.\n \nIncluso cuando tropiezan con un desacuerdo, hay muchas posibilidades de que se rían de él y lo olviden en un par de horas.\n \nLa positividad de este choque de Soles ardientes es algo que puede superar cualquier valor previamente establecido, y se adaptarán fácilmente el uno al otro y encontrarán un compromiso perfecto, incluso cuando no estén de acuerdo.\n \nEl valor más importante que comparten es el que ambos otorgan a la libertad de espíritu y a la bondad de la humanidad.\n \nCuando encuentren este punto de utopía compartida, no habrá nada más que realmente importe.",
			Match: "99%"},
		SharedActivities: SummaryPercentage{
			Text:  "Básicamente pueden hacer cualquier cosa juntos, si consiguen encontrarse.\n \nSe distraen fácilmente con diversas cosas de su vida y no son muy fijos en sus acuerdos, buscando la libertad y la comprensión del otro.\n \nCuando se enfrentan a sus propias debilidades, una de las cuales es la falta de responsabilidad y fiabilidad, pueden enfadarse mucho.\n \nEsto no es típico, pero es muy posible en caso de que uno de ellos no se vea a sí mismo en la verdadera luz que se puede esperar de cualquier Sagitario.\n \nLo mejor que podría hacer esta pareja es viajar juntos por el mundo, con una base de un plan que se respete.\n \nNingún otro signo puede comprender su necesidad de viajes, conocimientos, amplitud y distancias, y esto es algo que deberían compartir y multiplicar cuando están juntos.",
			Match: "70%"},
	},
}
