package compatibilities

var Sagittariuspisces = Compatibility{
	Name: Sagittarius + " - " + Pisces,
	Friendship: Friendship{
		Match:   "65%",
		Traits:  []string{CautionRomance, Stormy},
		Summary: "En el plano de la amistad, pese a sus diferencias, Sagitario y Piscis se complementan muchísimo mejor que en las relaciones sentimentales y pueden, incluso, llegar a ser grandes amigos.\n \nNo en vano entre sus aficiones principales hay bastantes coincidencias.\n \nTanto Sagitario como Piscis, disfrutan de los viajes, de las aventuras y les encanta ampliar siempre que pueden sus conocimientos sobre cualquier tema de su interés.\n \nNo será nada raro que Sagitario y Piscis decidan compartir algún viaje a paraísos exóticos.\n \nTal vez surjan discrepancias con los preparativos, con los medios de transporte o en otros planes relacionados con ello, pero sin duda el interés que les crea su objetivo hará que sepan ponerse de acuerdo antes de emprender su aventura.\n \nIgualmente, si comparten alguna actividad lúdica en común, Sagitario y Piscis lograrán llevarse de maravilla y pasarán juntos ratos muy divertidos.\n \nPiscis se sorprende siempre con el punto de locura que imprime Sagitario a sus asuntos y el arquero se siente cautivado la personalidad de Piscis que él considera fuera de lo común.\n \nSu único problema, es que el carácter independiente de Sagitario puede chocar con el sensible Piscis, pero serán trifulcas momentáneas y luego todo volverá a su lugar.",
	},
	Love: Love{
		Match:  "50%",
		Traits: []string{GreatSexualChemistry, LowCommitment},
		Summary: SummaryPercentage{
			Text:  "Se trata de una relación de dos almas gemelas que no suele durar mucho.\n \nAl principio, les costará salir de la zona platónica y empezar a construir una relación física.\n \nUna vez que se acerquen el uno al otro, comenzará su proceso de aprendizaje y ambos miembros de la pareja se sentirán fascinados el uno por el otro, pensando que su relación nunca podría terminar.\n \nSe idealizarán fácilmente, pensarán que su relación es el amor perfecto, pero este enamoramiento no durará mucho debido a sus naturalezas cambiantes.\n \nEl hecho es que su relación representa un momento en el tiempo en el que ambos han merecido sonreír.\n \nMientras dure y sean felices, ambos lo apreciarán.",
			Match: "50%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Si alguna vez consiguen terminar en una relación física, se divertirán mucho.\n \nComo dos signos mutables, su creatividad y sus cambios de posturas, escenarios y niveles de compromiso e intimidad no tendrán fin.\n \nSu vida sexual tendrá altibajos, emociones y decepciones, demasiadas expectativas y muchas sorpresas.\n \nLo mejor de su relación es la positividad que comparten ambos miembros de la pareja, y las muchas risas y diversión que compartirán en su vida sexual.\n \nDesgraciadamente, el nivel de intimidad rara vez será satisfactorio para ninguno de estos miembros de la pareja.\n \nPuesto que ambos están regidos por Júpiter, se enfrentarán a su naturaleza racional y a sus convicciones.\n \nLa razón principal por la que su relación sexual rara vez se hace realidad es el exceso de pensamiento de ambos miembros de la pareja.\n \nSagitario esperará una gran emoción, un gran gesto o cualquier tipo de iniciativa apasionada por parte de Piscis, mientras que Piscis esperará a que todas las piezas del rompecabezas encajen en su posición perfecta.\n \nEn la mayoría de los casos, ninguna de estas cosas sucederá y no pasarán de una relación platónica.",
			Match: "30%"},
		Trust: SummaryPercentage{
			Text:  "A Sagitario y Piscis les resultará muy difícil confiar el uno en el otro, pero probablemente lo aceptarán como algo perfectamente normal.\n \nÉsta es la belleza del reglón de Júpiter: todo tiene sentido en su relación.\n \nLa pareja de Sagitario es demasiado apasionada y le encanta tener muchas opciones a la hora de relacionarse.\n \nRara vez se establecerán con alguien que carezca de una decisión firme para conquistarlos.\n \nPiscis, por otro lado, será demasiado sensible al tratar de mostrar su fuerza imaginaria.\n \nPodrían acabar siguiendo a su pareja Sagitario en aventuras para las que no están preparados, tristes por la falta de comprensión emocional de su pareja y dispuestos a abrirse a otra persona.\n \nIndependientemente del propósito de cada pequeña cosa que hagan, a menudo tendrán expectativas retorcidas el uno del otro y esto les llevará a una deshonestidad involuntaria.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Sagitario está regido por Júpiter, y tradicionalmente también lo está Piscis.\n \nÉste es el planeta más grande del sistema solar y, como tal, tiene una gran influencia en la personalidad de estos signos.\n \nCompartirán el mismo optimismo, la misma visión y prácticamente los mismos delirios.\n \nEstas parejas estarán unidas por influencias extremadamente benéficas y seguramente compartirán el mismo sentido del humor, funcionarán a la misma velocidad y aprenderán mucho el uno del otro durante el tiempo que estén juntos.\n \nJúpiter es el planeta del conocimiento, y les fascinará lo desconocido que puedan compartir el uno con el otro.\n \nCon el tiempo, se darán cuenta de cuáles son sus diferencias de la forma más insólita.\n \nSagitario es un signo de convicciones y será más racional y fiable que su pareja Piscis.\n \nEn algún momento, Sagitario empezará a distanciarse debido a las expectativas que no se han cumplido y al comportamiento irresponsable y desapegado de su pareja Piscis.\n \nA cambio, Piscis tendrá la simple sensación de que ya no es allí donde quiere estar.\n \nPuede que ambos nunca entiendan por qué, pero simplemente se separarán sin malas intenciones y probablemente sin mucha rabia o dolor.\n \nEl comienzo de su separación radica en la falta de respeto a las convicciones y personalidades de cada uno.",
			Match: "85%"},
		Emotions: SummaryPercentage{
			Text:  "Su relación será una montaña rusa emocional para ambos miembros de la pareja, pero rara vez durará mucho.\n \nLa relación que construirán a través de la comunicación y la comprensión del mundo del otro despertará emociones a través de la excitación y lo inesperado.\n \nSe reirán el uno con el otro con el corazón abierto y compartirán emociones maravillosas durante el tiempo que dure su relación.\n \nEn cuanto empiecen a surgir problemas, ambos sentirán que sus emociones se desvanecen, como si toda la relación fuera superficial.\n \nSean cuales sean las circunstancias, es importante que ambos recuerden que este contacto no tiene nada de superficial.\n \nEl proceso de aprendizaje y la belleza de toda su relación no deben olvidarse, sino mantenerse como base para todas sus relaciones futuras.\n \nSe aman de una manera extraña, idealizándose, decepcionándose, eligiendo permanecer separados incluso cuando desean estar juntos.\n \nSe trata de un contacto afectivo complicado porque ambos miembros de la pareja se enamoran con facilidad, y la profundización de su relación puede hacer que ambos se sientan arrastrados.\n \nSi la relación termina de forma irrespetuosa, ambos podrían perder un poco su fe en el amor.",
			Match: "30%"},
		Values: SummaryPercentage{
			Text:  "La mayor diferencia aquí es el valor que la pareja Piscis da a las emociones, ya que Sagitario a menudo no entiende realmente ese enfoque.\n \nSi conectan a través del amor profundo, superarán esto con facilidad y las emociones que compartan harán que Sagitario comprenda a su pareja.\n \nEn general, estarán de acuerdo en muchas cosas.\n \nValorarán las utopías del otro, las personas de buen corazón, los conocimientos, la amplitud de miras y los viajes.\n \nComprenderán el sentimiento de no pertenencia del otro y compartirán el sentido de un poder superior.",
			Match: "65%"},
		SharedActivities: SummaryPercentage{
			Text:  "Mientras se encuentren en la fase de fascinación de su relación, serán inseparables. Ambos tienen la necesidad de agarrar todo lo que se les ofrece y no dejar nada alegre sin usar, sin decir y dejado para mañana. Es como si ambos estuvieran hambrientos de felicidad en un mundo oscuro con el que se han tropezado, y cuando conocen a alguien tan fascinante sería una pena perder la oportunidad de disfrutar. Con el tiempo se darán cuenta de que, aunque comparten la misma necesidad de movimiento y cambios de aires, puede que no necesiten los mismos contenidos en sus vidas y Sagitario se decantará por la actividad física, la filosofía y los viajes, mientras que Piscis suele volver al trabajo creativo y a la búsqueda del amor.",
			Match: "90%"},
	},
}
