package compatibilities

var Sagittariuscapricorn = Compatibility{
	Name: Sagittarius + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{MutualRespect},
		Summary: "Quizá en este terreno donde no interviene la pasión y el enamoramiento, la relación entre Sagitario y Capricornio se vea más comprometida, pero también pueden tener ambos un gran interés en que su amistad prospere y si es así, no cabe la menor duda de que lo conseguirán.\n \nEl Fuego de Sagitario le impregna de dinamismo, mientras que el elemento Tierra de Capricornio le proporciona una gran tranquilidad.\n \nEs muy importante que Sagitario y Capricornio acepten y respeten estas diferencias de temperamento, porque de este modo pueden forjar una amistad que será la envidia de propios y extraños.\n \nEl carácter entusiasta de Sagitario estimulará a Capricornio a aspirar a grandes cosas.\n \nPor su parte, Capricornio le mostrará a su amigo Sagitario que si las cosas marchan sobre seguro, siempre salen mucho mejor.\n \nÉste será el mejor ejemplo de cómo dos personas tan distintas pueden armonizar y mantener una excelente comunicación entre ellos.\n \nAl conocerse, Sagitario y Capricornio quizá desconfíen mutuamente, per sentirán una curiosidad irrefrenable por descubrir más aspectos de la personalidad del otro.\n \nCuando van revelando los aspectos secretos de su carácter, los que intentan que permanezcan más ocultos, Sagitario y Capricornio se atraerán todavía más y establecerán entre ellos una buena amistad.",
	},
	Love: Love{
		Match:  "38%",
		Traits: []string{LowCommitment, DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "No es la relación ideal, y rara vez será la que ambos elijan para el resto de sus vidas.\n \nAun así, su comprensión y aceptación de sus diferencias es refrescante y divertida para ambos miembros de la pareja, y podrían pasarlo bien mientras estén juntos, por el tiempo que sea.\n \nNo podemos predecir demasiada estabilidad a menos que un Capricornio decida hacerla, pero la sonrisa en el rostro de Sagitario y la capacidad que tienen de hacer reír a su pareja, pueden ser el pilar de su vínculo durante el tiempo que ambos lo necesiten.",
			Match: "38%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Las diferencias de carácter pueden resultarles extrañamente fáciles de manejar, simplemente porque un Sagitario lo asimila todo con facilidad, y Capricornio se siente lo bastante responsable como para entender la inmadurez de su pareja como culpa suya, de alguna extraña manera.\n \nCada Capricornio quiere significado y profundidad a sus encuentros físicos, porque son lentos, minuciosos y valoran su realidad física.\n \nSagitario a menudo no entiende el ritmo al que un Capricornio quiere moverse en, ni ven la importancia del mundo físico que Capricornio tiene la responsabilidad de.\n \nAl principio de su relación, si comparten los mismos deseos, es posible que no vean lo incompatibles que son en realidad.\n \nPor desgracia, a medida que pasa el tiempo, se hace bastante evidente que su batalla arquetípica se refleja en sus caracteres de un modo que empaña su vida sexual.\n \nLa única forma de que mantengan una relación sexual sana es que Sagitario respete tanto lo físico como Capricornio se relaje y respete el cambio que supone el Alma regida por Júpiter de su pareja.\n \nSu punto de encuentro está en el canto opuesto a Capricornio, donde el regente de Sagitario está exaltado.\n \nEn otras palabras, su punto de encuentro es la emoción pura.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "Es cierto que Sagitario es uno de los miembros más honestos del zodíaco cuando se trata de su relación con los demás, pero rara vez son del todo honestos consigo mismos.\n \nCapricornio siente esto y reconoce la falta de honestidad interior que no parece cambiar.\n \nEl problema aquí está en el hecho de que Capricornio es el signo de la caída de Júpiter y éste es el regente de Sagitario, así como el regente tradicional de Piscis.\n \nLa magia de la vida y las creencias que conducen en una determinada dirección parecen perderse en Capricornio.\n \nSaben con certeza que lo único que da resultados es su mente racional y el trabajo duro.\n \n¿Cómo puede alguien como Sagitario explicarles que las creencias crean su realidad y que basta con creer en un buen resultado para afectar positivamente a todo el entramado de circunstancias? Esta cuestión se reduce a un problema de confianza, pero en realidad va mucho más allá.",
			Match: "10%"},
		Communication: SummaryPercentage{
			Text:  "Un Sagitario y un Capricornio pueden estar llenos de comprensión mutua, si no se lanzan a una batalla sobre sus sistemas de creencias.\n \nSagitario tiene esa sonrisa optimista que sin duda pondrá una sonrisa en la cara de Capricornio también, y será mucho más fácil para esas ideas ardientes y creativas de Sagitario encontrar su fundamento a través del enfoque práctico de Capricornio.\n \nCon el debido respeto, ésta es una pareja que une a un visionario con un constructor, y realmente no hay nada que no puedan hacer juntos.\n \nSi no esperan cambios el uno del otro, es muy probable que sean extremadamente compatibles desde el punto de vista intelectual.\n \nLo más hermoso de este contacto es que se complementan en sus papeles protectores.\n \nAmbos signos representan la protección, Sagitario regido por el mayor benéfico y Capricornio como nuestro cerco, nuestra coraza frente al mundo exterior.\n \nCuando logran construir un núcleo funcional, son parejas que nunca dejarán que nadie más afecte su relación.\n \nSi buscan a alguien que no permita interferencias, intromisiones ni ningún tipo de falta de respeto por parte de otras personas, esta relación puede ser su mejor elección.",
			Match: "75%"},
		Emotions: SummaryPercentage{
			Text:  "Sagitario y Capricornio pueden encontrar un lenguaje emocional compartido debido al hecho de que Capricornio necesita a alguien como su signo opuesto para completarse, y Sagitario tiende a convertirse en ese signo como lugar de exaltación de Júpiter.\n \nAquí es donde sus corazones se encuentran y si hay suficiente fe en un Sagitario, sin expectativas poco realistas, podrían enamorarse profundamente.\n \nExiste una pequeña posibilidad de que un Sagitario sea esa persona melosa y tierna que necesita un Capricornio, pero esto es algo que puede superarse con suficiente cercanía y comprensión de sus diferencias.",
			Match: "55%"},
		Values: SummaryPercentage{
			Text:  "Hay una cosa importante en la que estas parejas están de acuerdo, y es el valor de la inteligencia.\n \nSagitario es un signo mental, centrado en la filosofía y el aprendizaje, siempre en busca de la unidad, la síntesis y esa verdad universal.\n \nCapricornio es la continuación lógica de Sagitario, como herramienta práctica que utiliza el conocimiento.\n \nSi no se encuentran estúpidos el uno al otro, congeniarán en la misma longitud de onda sin muchos problemas, y descubrirán que comparten cierta profundidad y curiosidad que no es obvia a primera vista.\n \nAun así, la mayoría de sus valores difieren mucho y sus necesidades suelen estar muy alejadas.\n \nMientras uno de ellos valora la libertad, la amplitud y la creatividad, el otro valora el sentido práctico, la responsabilidad y la concentración.",
			Match: "20%"},
		SharedActivities: SummaryPercentage{
			Text:  "Aunque podríamos pensar que un Sagitario se aburrirá y querrá huir de su pareja Capricornio, en la mayoría de los casos esto no sucede.\n \nLa falta de relación entre sus Soles ayuda a que se vinculen con cierta falta de respeto.\n \nEsto los lleva a una situación en la que un Sagitario encuentra a su pareja Capricornio interesante, como un extraterrestre que siempre ha querido conocer.\n \nSon lo suficientemente diferentes como para interesarse el uno por el otro con auténtica curiosidad y un Sagitario siempre está dispuesto a probar algo nuevo.\n \nCapricornio probablemente rechazará muchas de las actividades infantiles que Sagitario sugiere, pero se vuelve divertido convencerlos y hay una nota de risa y alegría en estos intentos.\n \nAmbos son lo suficientemente inteligentes y conscientes de que existen sus diferencias, lo que hace que toda su historia sea tan emocionante y refrescante para ambos.",
			Match: "60%"},
	},
}
