package compatibilities

var Sagittariusaquarius = Compatibility{
	Name: Sagittarius + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "98%",
		Traits:  []string{FunEnjoyable},
		Summary: "Coinciden también Sagitario y Acuario en su forma de enfocar las relaciones sociales.\n \nA ambos les gusta conocer constantemente a gente nueva y de lo más variada.\n \nSuelen coincidir en gimnasios o clubes deportivos y es frecuente que su amistad nazca en este ámbito o en el de otra actividad lúdica de las que ambos comparten.\n \nTambién suelen tener amigos comunes que quizá sean los artífices de que Sagitario y Acuario inicien su amistad.\n \nLos ideales de Acuario y los conocimientos de Sagitario serán decisivos para que su relación prospere.\n \nEntre ambos se establecerá un nivel de comprensión y comunicación notables.\n \nOtro punto que tienen en común Sagitario y Acuario, es que ambos tienen una visión de la vida muy optimista.\n \nLa solidaridad con los menos favorecidos es también las virtudes que poseen Sagitario y Acuario.\n \nEntre ellos no existirán diferencias importantes y mucho menos peleas o discusiones fuertes.\n \nTanto Sagitario como Acuario tienen un sentido del respeto muy grande y una lealtad a prueba de bomba.\n \nEncontrarán el uno en el otro no sólo el mejor amigo, sino también el mejor cómplice, que les cubrirá siempre que lo necesiten.\n \nAunque siempre estén rodeados de otros amigos, Sagitario y Acuario saben que su amistad es más especial e íntima que otras.",
	},
	Love: Love{
		Match:  "83%",
		Traits: []string{DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "Una relación entre un Sagitario y un Acuario pareja puede parecer como una amistad del mismo sexo a otras personas y lo que puedan pensar de esto, este es el tipo de relación tanto de estos socios pueden necesitar.\n \nSe unirán cuando sea el momento para ambos de pasar por un cambio en sus vidas o dejar a una pareja con la que se sienten restringidos.\n \nSu relación suele ser un faro brillante para todos los que les rodean porque da prioridad al futuro y trae la esperanza de un tiempo mejor.\n \nEl principal desafío de Sagitario y Acuario reside en sus naturalezas racionales.\n \nAunque sus mentes tendrán una relación maravillosa, podrían tener problemas para alcanzar una intimidad y cercanía reales.\n \nAmbos necesitan frenarse y preguntarse cómo se sienten antes de acabar en un vínculo sin corazón en el que encuentren consuelo mientras huyen del mundo.",
			Match: "83%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Acuario actúa de una manera Sagitario piensa y esto es todo un activo en su vida sexual.\n \nSu atracción puede ser fuerte, especialmente cuando la pareja de Sagitario se encuentra en una encrucijada en su vida y necesita la confirmación de su libertad y sexualidad.\n \nSu relación sexual será muy divertida, porque a ambos les gusta experimentar y aprender cosas nuevas.\n \nSu comunicación les dará tanta satisfacción que a veces ni siquiera necesitarán el acto sexual para sentirse satisfechos.\n \nAunque su conexión sexual puede ser muy satisfactoria para ambos, podrían tener problemas para crear intimidad.\n \nLa pareja de Sagitario aportará la calidez justa a su relación, pero la cualidad mutable de su signo hará que fácilmente se centre en otra cosa, mientras que la pareja de Acuario seguirá aferrándose a las mismas cosas.\n \nAmbos comprenderán la necesidad del cambio y lo incorporarán a su vida sexual.\n \nAun así, el vínculo emocional y, en consecuencia, la intimidad entre ellos podría debilitarse y fortalecerse, encenderse y apagarse, con demasiada frecuencia como para que ambos se vean como la pareja perfecta.",
			Match: "80%"},
		Trust: SummaryPercentage{
			Text:  "A veces conocerán demasiado bien la mente del otro como para crear confianza a partir de la sensación de libertad absoluta.\n \nSagitario puede ser un signo propenso a la infidelidad y a Acuario le gusta ser libre para estar disponible.\n \nCon ambos sabiendo estas cosas el uno del otro, fácilmente podrían empezar a cuestionarse si deben confiar el uno en el otro o no.\n \nAunque ambos encuentran que sus relaciones dependen mucho del nivel de libertad que tengan, esto es algo que probablemente no podrán darse el uno al otro cuando decidan comprometerse en su relación romántica.\n \nEl mejor remedio para la falta de confianza en cualquiera de los miembros de la pareja es que ambos se den cuenta de que su relación es algo fuera de lo común, casual y libre de cualquier atadura.",
			Match: "60%"},
		Communication: SummaryPercentage{
			Text:  "Cuando Sagitario y Acuario encuentran un interés mutuo, se convierte en la fuente infinita de nuevos temas, información e incluso podría cambiar sus filosofías de vida.\n \nLa pareja de Acuario puede permanecer distante durante mucho tiempo y Sagitario podría sentirse como un niño pequeño, hablando en exceso de temas poco interesantes e intentando establecer una conexión.\n \nCuando por fin apunten en la dirección correcta y decidan hablar de algo que despierte el interés de Acuario, sus conversaciones se volverán increíbles.\n \nAmbos miembros de la pareja son racionales y prestan mucha atención a su cadena de pensamientos.\n \nAmbos son lo suficientemente rápidos para llegar a conclusiones diferentes.\n \nEl contacto entre ellos despertará su necesidad de enfrentarse intelectualmente y podrían acabar en grandes debates.\n \nCuando comparten el amor por algo, hablarán de ello apasionadamente, en exceso y encontrarán nuevas ideas y soluciones que incorporar a su enfoque de este tema.\n \nLa velocidad de Acuario mezclada con el apasionado estado de creencia constante de Sagitario, podría hacer de su relación una de las más productivas de todo el zodíaco.",
			Match: "99%"},
		Emotions: SummaryPercentage{
			Text:  "Es difícil establecer la escala de las emociones en esta relación.\n \nNinguna de estas parejas es tan emocional en la superficie, aunque Sagitario puede enamorarse y desenamorarse con bastante frecuencia.\n \nEs bueno que Sagitario sea tan cambiante, o tendría problemas para seguir el ritmo de su pareja Acuario.\n \nOtra cosa buena en este contacto es la naturaleza racional de ambos signos y su enfoque en los procesos mentales.\n \nEsto les permitirá comunicar sus emociones, sean cuales sean, sin ningún sentimiento de culpa o presión emocional.\n \nCuando sus emociones empiecen a crecer, pasará mucho tiempo antes de que se estabilicen y ambos estén seguros de lo que sienten el uno por el otro.\n \nSagitario cambiará de opinión muchas veces, probablemente yendo de un extremo a otro porque eso es lo que le inspira su pareja Acuario.\n \nPor otro lado, Acuario necesitará formar primero el apego y luego esperar la certeza del amor de su pareja.",
			Match: "85%"},
		Values: SummaryPercentage{
			Text:  "Hay muchas cosas en las que estarán de acuerdo, empezando por lo de siempre:\nel valor de la libertad, y siguiendo por sus propias cualidades y expectativas.\n \nAmbos valorarán la amplitud de miras, el optimismo y la fe detrás del cerebro, la inteligencia y la visión.\n \nComo signo de exaltación de Neptuno, Acuario tiene un enfoque especial de la honestidad, y para un Sagitario la honestidad es una de las cosas que más valoran.",
			Match: "90%"},
		SharedActivities: SummaryPercentage{
			Text:  "Habrá actividades a las que Sagitario querrá comprometerse, mientras que a Acuario le parecerán tontas o incluso estúpidas. Podrían tener problemas para conciliar su acercamiento a la religión y cualquier actividad religiosa podría ser fuente de problemas en su relación, porque todo su sistema de creencias individuales podría estar en juego. Aun así, en la mayoría de las situaciones podrían divertirse mucho dondequiera que vayan. Sagitario sonreirá con facilidad y seguirá cualquier idea de Acuario, siempre que tenga sentido o pueda aprender algo de ella. Probablemente no habrá lugar lo bastante extraño para que estos dos descubran de nuevo sus intereses comunes.",
			Match: "85%"},
	},
}
