package compatibilities

var Scorpiopisces = Compatibility{
	Name: Scorpio + " - " + Pisces,
	Friendship: Friendship{
		Match:   "98%",
		Traits:  []string{GoodRomancePotential, DeepMutualUnderstanding},
		Summary: "Escorpio y Piscis funcionan perfectamente sincronizados.\n \nTambién en la amistad les une ese hilo invisible que les convierte en inseparables.\n \nLa facilidad de ambos para ponerse en el lugar de los demás, sin duda facilita mucho las cosas.\n \nGracias también a ello su amistad puede prevalecer con el paso del tiempo.\n \nA pesar de que Escorpio y Piscis tienen diferentes formas de hacer las cosas y de enfocar la vida, son receptivos para aprender los matices que más les interesen.\n \nEscorpio suele enfocarse en un solo objetivo, mientras que Piscis quiere hacer varias actividades a la vez.\n \nEsto le permite sacar adelante sus proyectos personales y participar también en los de su amigo.\n \nA Piscis, fantasioso y soñador, con una visión amplia de la vida, le sobra empatía.\n \nEscorpio, en cambio, es más introvertido y necesitará más tiempo y esfuerzo para compartir con Piscis sus experiencias más íntimas.\n \nSin embargo, el hilo telepático que une a ambos ya habrá hecho su función y cuando Escorpio hable, Piscis sabrá exactamente de qué le habla.\n \nEn este binomio amistoso, Piscis también podrá brindar las bases emocionales para que esta amistad con Escorpio funcione de forma estable y por encima de sus diferencias.",
	},
	Love: Love{
		Match:  "81%",
		Traits: []string{GreatSexualChemistry, Harmonious},
		Summary: SummaryPercentage{
			Text:  "Cuando Escorpio y Piscis se unan, es probable que esta relación les aporte a ambos nuevas percepciones sobre las posibilidades emocionales.\n \nAmbos se dejarán llevar fácilmente por la imagen de un amor de cuento de hadas, y esta imagen podría mantenerlos juntos durante mucho tiempo, aunque ambos no sean tan felices.\n \nComo dos signos de Agua, confiarán en sus juicios emocionales y comprenderán esto el uno del otro, creando una verdadera intimidad.\n \nEl reto aquí es que la naturaleza de Escorpio no se obsesione y asfixie a su cambiante pareja, y que Piscis deje de huir de las emociones negativas.",
			Match: "81%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Como dos signos de Agua, tanto Escorpio como Piscis consideran muy importante que las emociones sean la parte más intensa de sus experiencias sexuales.\n \nEscorpio es un signo que representa el sexo, así como la represión sexual, y dependiendo de la educación y las experiencias sexuales previas, pueden ser un poco bruscos con su sensible pareja Piscis.\n \nPor otro lado, Piscis es el signo de los orgasmos, las experiencias sexuales extrañas y todas las rarezas sexuales.\n \nSi comprenden la profundidad emocional de Escorpio, podrían ser mucho más resistentes de lo que podríamos suponer.\n \nEl mayor desafío para estas parejas es su relación con Venus, el planeta de la satisfacción física sensual.\n \nEscorpio no cuida mucho a Venus, llevándolo a su detrimento, mientras que Piscis lo adora a través de la exaltación.\n \nEsto puede ser muy desafortunado si Escorpio desprecia esta necesidad emocional de Piscis de ser satisfecho y amado al mismo tiempo.\n \nSi la pareja de Escorpio es consciente de su naturaleza animal y de sus deseos sexuales instintivos, y está en contacto con su lado femenino dispuesto a mostrarlo, Piscis encontrará fácilmente la forma de integrarse en su mundo sexual.",
			Match: "70%"},
		Trust: SummaryPercentage{
			Text:  "El desconfiado Escorpio puede convertirse fácilmente en un obseso del control en una relación con Piscis.\n \nSin embargo, ambos buscarán el amor perfecto y esto debería unirlos con cierta honestidad.\n \nEn cuanto uno de los dos sea engañado o decepcionado, su relación debería terminar, porque ninguno de los dos puede soportar la imagen manchada del amor.\n \nLa confianza entre ellos se mantendrá mientras los Piscis tengan un enfoque idealista, haciendo todo por su único y verdadero amor.\n \nCuando su imagen se aclare y se den cuenta de con quién están y de cómo es su relación, puede que les resulte muy difícil mantenerse en contacto con las expectativas de honestidad de Escorpio.",
			Match: "65%"},
		Communication: SummaryPercentage{
			Text:  "Los posibles problemas en la comunicación entre Escorpio y Piscis son la aspereza de Escorpio o la excesiva sensibilidad de Piscis.\n \nCon estos dos combinados, será casi imposible mantener una conversación sana en la que no haya heridas, distanciamiento ni enfados.\n \nRara vez se pelearán, ya que la pareja Piscis no suele tener motivos para pelearse con nadie, pero podrían tener muchos malentendidos que llevaran a su separación bastante rápido.\n \nSi la pareja Escorpio es lo suficientemente tierna y la pareja Piscis posee los límites necesarios, su comunicación puede ser bastante emocionante y mágica.\n \nAmbos signos están vinculados a diferentes tipos de magia, y a los dos les interesará la visión 'entre bastidores' de todo lo que les rodea.\n \nCuando empiecen a comunicarse y a salir de sus zonas de silencio, podrían dejarse llevar fácilmente por temas que la mayoría de los signos no entenderían.\n \nEl enfoque emocional de todo lo que ocurre en sus vidas les ayudará a entenderse también a la hora de tomar decisiones racionales.\n \nLas experiencias más superficiales se convertirán en algo increíble de lo que hablar, y la verdad detrás de todo en la vida será hipnotizante.\n \nDeberían aferrarse a la fascinación que sienten el uno por el otro, en lugar de ceder a sus debilidades.",
			Match: "90%"},
		Emotions: SummaryPercentage{
			Text:  "Si hay otro signo capaz de comprender a Escorpio, ése es Piscis.\n \nHay una profundidad emocional en Escorpio que no todo el mundo está preparado para afrontar y los Piscis están preparados para enfrentarse a cualquier cosa en el campo de las emociones.\n \nEl signo de Piscis representa nuestros océanos y mares, mientras que Escorpio representa los ríos.\n \nCada río desemboca en el océano o el mar, y esto refleja la conexión emocional entre estos signos de la mejor manera posible.\n \nLa pareja de Piscis tendrá la capacidad de dispersar la intensidad de las emociones de su pareja de Escorpio.\n \nEsto les permitirá a ambos respirar más tranquilos, siempre y cuando no crucen la línea y pongan en peligro la parte de esta profundidad que es amada por Escorpio.\n \nEsta es una conexión especial en la que la pareja Escorpio necesita concentrar sus emociones y la pareja Piscis necesita darles un propósito.\n \nPor muy difíciles y oscuros que se pongan ambos, compartirán una profunda comprensión emocional que deberá seguirse para ver adónde conduce su relación.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Por mucho que Escorpio valore la fuerza de carácter y la profundidad de alguien, Piscis valorará la sensibilidad y la amplitud.\n \nAun así, su amor mutuo por la conexión con las emociones y la profundidad de su conexión emocional, les dará los valores compartidos suficientes para aferrarse a ellos.\n \nEscorpio es un signo regido por Marte y siempre existe cierta admiración por la caballerosidad.\n \nPiscis representa todos los cuentos de hadas en los que un príncipe se convertía en héroe y se casaba con una bella muchacha.\n \nLa pareja de Piscis tiene la misión de enseñar a Escorpio cómo alcanzar su cuento de hadas a través de la caballerosidad, y ambos deben permanecer centrados en la creación de su tierra de ensueño compartida, con realeza o sin ella.",
			Match: "75%"},
		SharedActivities: SummaryPercentage{
			Text:  "Cuando se trata de actividades que podrían compartir, probablemente serán inseparables hagan lo que hagan.\n \nSi Escorpio se ata a su pareja Piscis, esto podría volverse tedioso para ambos, ya que demasiada actividad dispersa de Piscis puede ser irritante para Escorpio centrado y la naturaleza obsesiva de Escorpio podría agobiar a Piscis.\n \nAun así, tendrán suficiente energía para seguirse mutuamente y les resultará fácil encontrar intereses comunes.\n \nEl principal problema del tiempo que pasen juntos podría ser la negatividad inconsciente de la pareja Escorpio.\n \nPodría poner en peligro la imagen positiva y feliz del mundo que Piscis quiere llevar consigo y esto podría alejar a la pareja Piscis si su conexión emocional no es lo bastante fuerte como para mantenerlos juntos.",
			Match: "85%"},
	},
}
