package compatibilities

var Scorpiosagittarius = Compatibility{
	Name: Scorpio + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "35%",
		Traits:  []string{AlmostNothingReally},
		Summary: "Escorpio y Sagitario tendrán su amistad está asegurada si perciben los numerosos intereses comunes que tienen.\n \nCuando se conocen, en el trato superficial, pueden sentir cierta atracción.\n \nSe darán cuenta de que tienen proyectos comunes a realizar, aunque su forma de querer hacerlo sea distinta.\n \nSagitario admira a Escorpio y respeta sus decisiones.\n \nEsto será un punto a favor para establecer una base de amistad entre Escorpio y Sagitario.\n \nPronto se darán cuenta de que juntos podrán dar mucho rendimiento a esta amistad, porque en cierto modo son muy complementarios y aunque no lleguen a la categoría de amigos íntimos, sí que pueden mantener una larguísima amistad basada en las aficiones comunes y la lealtad.\n \nPara contar sus intimidades, tanto Escorpio como Sagitario, buscarán a otros signos.\n \nEl principal obstáculo de esta relación será una comunicación algo deficiente que les impedirá confiar más el uno en el otro.\n \nEscorpio, más discreto y reservado, quizá no expresará todo lo que siente y Sagitario, más claro y directo puede reprochárselo o incluso sentirse mal por ello.\n \nCuando tienen un objetivo deseable en común, se respetarán y pasarán por alto sus diferencias.\n \nSus mayores afinidades son los hobbies creativos y los viajes o las aventuras lejanas.",
	},
	Love: Love{
		Match:  "30%",
		Traits: []string{Volatile, NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "Escorpio y Sagitario hacen una pareja estupenda, siempre y cuando sientan la primera emoción al principio de su relación.\n \nMientras no se conozcan bien y todo parezca nuevo e increíble, Escorpio verá a su pareja Sagitario como un rayo de luz que de repente hace su vida más brillante y mejor, mientras que Sagitario verá que hay mucho que aprender y disfrutará de la profundidad de su pareja Escorpio, a lo que seguirá el apego emocional.\n \nCon el tiempo, es muy probable que poco a poco pierdan el interés el uno por el otro, especialmente el signo mutable de Sagitario por su pareja fija de Escorpio.\n \nAunque su relación podría terminar en malos términos, sería una pena no entregarse a ella y dejar que fascine y enaltezca a ambos durante el tiempo que sea.",
			Match: "30%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Existe un extraño entendimiento entre estos dos signos, como si fueran uno y el mismo, al menos durante un tiempo.\n \nLa fuerza de carácter que comparten es algo que les dará la confianza justa a la hora del sexo, y la creatividad y franqueza de Sagitario serán refrescantes para la naturaleza fija de Escorpio.\n \nSin embargo, esto no suele durar mucho y, con el tiempo, en la mayoría de los casos, Escorpio empieza a considerar a su pareja Sagitario como poco fiable y en quien no se puede confiar, mientras que Sagitario ve a Escorpio como oscuro, prepotente y demasiado controlador.\n \nPara permanecer en una relación sexual sana, estos dos miembros de la pareja tienen que transigir, Escorpio encontrando la forma de dar libertad, mientras Sagitario encuentra la forma de no huir de la seriedad de su pareja.\n \nEn el mejor contacto posible, Escorpio dará a su vida sexual emoción y verdadera intimidad física, mientras que Sagitario estará ahí para dar sentido y sacudir las cosas, representando la luz al final del túnel.\n \nJuntos, pueden construir una relación sexual increíble, ya que ambos tienden a ser desinhibidos en cuanto a lugares, posiciones y situaciones en las que desean hacer el amor.",
			Match: "25%"},
		Trust: SummaryPercentage{
			Text:  "El mayor problema para un Escorpio y un Sagitario en una relación es la confianza.\n \nEscorpio tiene la necesidad de atar a su pareja, aunque tenga esa visión aparentemente liberadora del amor.\n \nNo hay nada que un Sagitario tema más que alguien que intente controlar su vida.\n \nSi alguien puede encender la necesidad de Sagitario de ser infiel, es sin duda Escorpio, lanzándolo cada vez más lejos al intentar acercarse.\n \nUn problema adicional con esta pareja está en la cualidad de sus signos, siendo Escorpio fijo y Sagitario mutable.\n \nEsto hace casi imposible que compartan un ritmo, y para no decepcionarse mutuamente, ambos podrían optar por mentir.\n \nLo más extraño de esta relación está en el hecho de que estos dos signos son, sin duda, los más honestos del zodíaco.\n \nAún así, su relación parece enfrentarles con la otra cara de su personalidad, una que ninguno de ellos quiere ver.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Dos individuos tan fuertes se dan mutuamente exactamente lo que cada uno de ellos necesita cuando se trata de su compatibilidad mental.\n \nEscorpio no sólo se siente más ligero, más optimista sobre la vida y todo lo que hay en ella cuando se comunica con un Sagitario, sino que la profundidad que dan a la mente de Sagitario y a su forma de llegar a conclusiones es imposible para cualquier otro signo.\n \nEscorpio se enfrentará a Sagitario con cualquier punto de vista superficial o anticuado, siendo al mismo tiempo lo suficientemente compasivo como para saber cómo hacerlo sin herirlo, y siendo lo suficientemente fijo como para no cambiar su intención en algún punto del camino cuando Sagitario piense en huir.\n \nDisfrutarán de la compañía del otro mientras las expectativas y los desacuerdos emocionales no estén en el punto de mira, pues tienen algo increíble que compartir: su búsqueda de la verdad.\n \nEl significado que buscan en todas las cosas de la vida, Escorpio yendo a lo profundo y Sagitario viajando a lo ancho, los conectará a través de un fuerte vínculo que ninguna otra combinación de signos puede formar.\n \nSi comparten una misión, pueden lograr cosas increíbles y tener verdaderas epifanías juntos.",
			Match: "80%"},
		Emotions: SummaryPercentage{
			Text:  "Disfrutarán de la compañía del otro mientras las expectativas y los desacuerdos emocionales no estén en el punto de mira, pues tienen algo increíble que compartir: su búsqueda de la verdad.\n \nEl significado que buscan en todas las cosas de la vida, Escorpio yendo a lo profundo y Sagitario viajando a lo ancho, los conectará a través de un fuerte vínculo que ninguna otra combinación de signos puede formar.\n \nSi comparten una misión, pueden lograr cosas increíbles y tener verdaderas epifanías juntos.",
			Match: "10%"},
		Values: SummaryPercentage{
			Text:  "Puesto que Escorpio es el signo de la exaltación de Urano, y Sagitario lo entiende a través de su tercera casa, ambos valoran la libertad y la capacidad de cada uno para luchar por sus creencias.\n \nAmbos pueden sentirse marginados y valoran las decisiones del otro de diferenciarse de los demás por amor propio.\n \nAun así, en la mayoría de los casos se considerarán fácilmente valiosos en cierto modo, ya que no pueden cumplir las expectativas que cada uno de ellos tiene de la personalidad de su pareja.\n \nLa única forma de que se valoren el uno al otro, es centrarse en las características y lados positivos del otro y en todo su contacto.",
			Match: "35%"},
		SharedActivities: SummaryPercentage{
			Text:  "Mientras su comunicación sea inspiradora para ambos miembros de la pareja, no necesitarán mucho para sentirse satisfechos con sus actividades.\n \nSagitario querrá probar cualquier cosa nueva y el enfoque de la vida de Escorpio siempre será nuevo desde su perspectiva, mientras que Escorpio disfrutará del primer impulso de optimismo y diversión.\n \nEs bueno que Escorpio exalte a Urano, pues esto le da suficiente amor por el cambio y las cosas nuevas y excitantes que Sagitario puede aportar a su vida.\n \nSin embargo, la cualidad fija de Escorpio hará que este entusiasmo se desvanezca tan pronto como su relación se vuelva rutinaria, de cualquier forma.\n \nA medida que pasa el tiempo, hay grandes posibilidades de que Sagitario empiece a sentirse presionado, o simplemente se aburra, y esto no da grandes esperanzas de futuro.",
			Match: "30%"},
	},
}
