package compatibilities

var Scorpioscorpio = Compatibility{
	Name: Scorpio + " - " + Scorpio,
	Friendship: Friendship{
		Match:   "80%",
		Traits:  []string{DeepMutualUnderstanding, MutualRespect},
		Summary: "Ser amigo de un Escorpio no es tarea fácil, sin embargo, cuando encuentra a otro Escorpio es como si se viera reflejado en un espejo y le atraerá como un imán.\n \nEsto no quiere decir, sin embargo, que la amistad entre Escorpio y Escorpio sea un mar en calma.\n \nDe hecho podría serlo, pero en este mar puede haber muchas tormentas que sólo lograrán superar por la profunda lealtad que se profesarán desde el mismo momento en que se consideren amigos.\n \nÉste es un rasgo propio de los Escorpio, son siempre muy amigos de sus amigos, aunque llegar a este status cuesta bastante porque no se abren a cualquiera.\n \nConseguir la confianza de Escorpio requiere tiempo, paciencia y honestidad.\n \nEscorpio siempre elige a su gente entre personas tranquilas, discretas y pacientes.\n \nPrefiere las relaciones sociales en petit comité y suele huir de las fiestas multitudinarias y de la gente superficial.\n \nCuando la amistad está establecida, el apoyo la dedicación que brinda Escorpio son incondicionales, aunque esta relación no esté exenta de trifulcas ocasionales.\n \nEscorpio y Escorpio suelen echar mano de la flexibilidad y la tolerancia para resolver sus desacuerdos.\n \nAdemás, suelen profesarse admiración mutua y bastante efusivos en sus muestras de afecto.",
	},
	Love: Love{
		Match:  "66%",
		Traits: []string{GreatSexualChemistry, DeepMutualUnderstanding, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "Escorpio y Escorpio tienen tendencia a sacar lo peor del otro.\n \nAunque pueden compartir el entendimiento más profundo que se conoce en todo el zodíaco, también pueden volverse demasiado oscuros y depresivos juntos, hundiéndose en su piscina de emociones sin resolver.\n \nSu entendimiento emocional es algo que merece la pena valorar, si ambos están abiertos a sus propios sentimientos y aceptan sus propias necesidades internas.",
			Match: "66%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Dos parejas Escorpio pueden ser un sueño hecho realidad cuando se trata de sexo, tanto como pueden ser la peor pesadilla del otro.\n \nSu energía sexual y tensión interior es algo a menudo difícil de manejar individualmente, y cuando se juntan, esto o se multiplica hasta el infinito, o encuentran un entendimiento absoluto.\n \nNormalmente, podemos predecir la primera opción.\n \nEn general, todos los Escorpio necesitan a alguien que los equilibre, ya que llegan a extremos de todo tipo y, cuando están juntos, rara vez tendrán la paciencia o la ternura necesarias para equilibrar nada, y mucho menos el uno al otro.\n \nSu vida sexual es intensa, a menudo asombrosa, aunque todo a su alrededor parezca desmoronarse.\n \nSe pelearán para reconciliarse, manipularán obviamente para enfadar al otro y harán cosas por despecho.\n \nCuando hablamos de condimentar la vida sexual, tenemos que entender que estos dos son especias en sí mismos, y rara vez hay algo aburrido en ellos.\n \nPara que su relación sexual funcione, ambos miembros de la pareja tienen que atenerse a esa ternura interior y cercanía emocional cuando están juntos, o puede que tengan que acabar las cosas como desgarradas por la energía nuclear.\n \nLa clave está en bajar el ritmo, respirar hondo y pasar tiempo abrazados.",
			Match: "65%"},
		Trust: SummaryPercentage{
			Text:  "Qué extraña relación la de dos parejas posesivas, que quieren saberlo todo y que luchan por la libertad.\n \nPor mucho que cada Escorpio quiera involucrarse en la vida de su pareja, ningún Escorpio quiere ser controlado ni dejar que nadie más se involucre en su propia vida.\n \nNinguno de ellos entenderá la falta de confianza que proviene de su pareja, levantando su ego en alto, sabiendo que no hay ninguna razón por la que seguiría compartiendo nada con el otro Escorpio nunca más.\n \nEl problema aquí está en el hecho de que ninguno de los dos parece ser consciente de lo que quiere de su pareja y esto puede convertirse en una verdadera batalla por la supremacía.\n \nAún así, a menudo se verán como verdaderos y honestos, dejando a un lado sus inseguridades, confiando el uno en el otro sin demasiadas palabras.",
			Match: "40%"},
		Communication: SummaryPercentage{
			Text:  "Cuando la carga emocional no forme parte de su comunicación cotidiana, la profundidad mental de ambos será un estímulo increíble para cada conversación que mantengan.\n \nNadie puede entender intelectualmente a un Escorpio tanto como otro Escorpio.\n \nSus temas pueden volverse fácilmente oscuros, no porque ambos quieran hablar de cosas deprimentes, sino porque se entienden en áreas que otras personas no quieren tratar.\n \nEsta es una buena forma de que ambos descubran que no están solos, y puede ser curativo para cada miembro de la pareja siempre que no haya expectativas emocionales de por medio.\n \nCuando empiezan una batalla el uno contra el otro, parece que no puede parar, hasta que uno de los dos está 'muerto' a golpes y ya no hay nada que hacer para que vuelvan al juego.\n \nSi se ven como adversarios, se picarán mutuamente por la victoria, lo que significa que harán lo que haga falta para ganar.\n \nSi se distancian de una situación, podrían darse cuenta de que en realidad ninguno de ellos pone en peligro al otro.\n \nPara llegar a un entendimiento mutuo, tienen que llevar vidas separadas y darse suficiente espacio para ello.",
			Match: "70%"},
		Emotions: SummaryPercentage{
			Text:  "Escorpio es un signo de Agua y representa todas las emociones desechadas con las que no queremos lidiar.\n \nEsto hace que los representantes de este signo se vuelquen a los temas emocionales oscuros y esto es algo que ambos entenderán en el otro.\n \nEl problema con Escorpio está en su batalla con la Luna y en el hecho de que aquí las emociones no son aprobadas.\n \nEsto puede hacer que ambos sean intolerantes a la debilidad, bruscos en su trato y demasiado críticos con las necesidades emocionales del otro, aunque en realidad ambos compartan las mismas necesidades.\n \nAmbos se enfrentarán a emociones con las que no quieren lidiar, simplemente porque ése es su papel individual en la vida de los demás.\n \nEsto podría dar lugar a numerosos conflictos, pero también podría ser la base para una increíble evolución personal de cada miembro de la pareja, y una oportunidad para estar con alguien que realmente comprenda la profundidad de sus corazones.\n \nLa mejor forma de enfocar esta relación es a través de la aceptación emocional más profunda y la tolerancia a la increíble diferencia de caracteres, aunque sean, extrañamente, iguales.",
			Match: "55%"},
		Values: SummaryPercentage{
			Text:  "El problema con las cosas que valoran está en la ilusión de valor que ambos comparten.\n \nValorarán la racionalidad y la madurez emocional, pero son cosas que ninguno de los dos puede ofrecer realmente todo el tiempo.\n \nPertenecen al elemento Agua y son profundamente emocionales, mientras que valoran la falta de emoción del otro, demostrada al principio de su relación.\n \nValoran cosas similares, pero no son del todo racionales o realistas en sus elecciones.\n \nEsto les hace susceptibles de juzgar su propio reflejo en el otro.",
			Match: "90%"},
		SharedActivities: SummaryPercentage{
			Text:  "No les resultará difícil discutir o ponerse de acuerdo sobre adónde ir y qué hacer juntos, pero puede que sus elecciones no les hagan felices.\n \nUna vez más, se trata del equilibrio que ambos buscan, necesitando una pareja de carácter y elecciones opuestas.\n \nSu contacto podría llevarles a todos los lugares oscuros, mientras interpretan situaciones que no podrían interpretar con nadie más.\n \nAunque se sentirán tristes y secos la mayor parte del tiempo, como dos miembros de cualidad fija, podrían aferrarse el uno al otro durante mucho tiempo.\n \nCuanto más tiempo pasen juntos, menos energía tendrán, porque en ambos hay una silenciosa batalla interior que la drena de sus sistemas.",
			Match: "75%"},
	},
}
