package compatibilities

var Scorpiocapricorn = Compatibility{
	Name: Scorpio + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "100%",
		Traits:  []string{GoodRomancePotential, DeepMutualUnderstanding, ExcellentAdvisors},
		Summary: "Al conocerse, Escorpio y Capricornio pueden desconfiar el uno del otro, aunque por suerte sentirán una inexplicable atracción que les llevará a seguir relacionándose hasta en que en este proceso tan largo como discreto surgirá la confianza mutua que les unirá a ambos en una sólida amistad muy duradera.\n \nEscorpio y Capricornio tendrán que aproximarse despacio el uno al otro, porque ambos son algo desconfiados y también les costará ser menos reservados.\n \nPero llegará un momento en que Escorpio y Capricornio se sentirán cómodos en compañía del otro y empezarán a mostrarse tal como son.\n \nEscorpio, tan emotivo, logrará canalizar esta actitud que a veces le perjudica, gracias a que su amigo Capricornio, mucho más sobrio y menos emocional, le mostrará el camino.\n \nA su vez, también Capricornio se dejará influir por las profundas emociones de Escorpio, se humanizará.\n \nSu punto de fricción puede estar originado por la terquedad de ambos, porque si Escorpio y Capricornio discuten, ninguno de los dos querrá dar su brazo a torcer.\n \nSerán tormentas de verano, acabarán sin darse la razón pero olvidando los motivos que los llevaron a discutir.\n \nEn esta amistad, Escorpio y Capricornio aprenderán mucho el uno del otro, crecerán juntos en muchos aspectos y lograrán una relación sólida.",
	},
	Love: Love{
		Match:  "64%",
		Traits: []string{Harmonious, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "La relación de Escorpio y Capricornio puede ser inspiradora para que ambos miembros de la pareja busquen la verdad, escarben bajo su árbol genealógico y se ocupen de cualquier karma y deuda no resueltos.\n \nAmbos son profundos y no se toman las cosas a la ligera, y esto les ayudará a construir una base sólida para una relación que puede durar mucho tiempo.\n \nSin embargo, esto mismo puede fácilmente hacer que su relación sea demasiado oscura y poco emocional, arrastrar a ambos a un estado de tristeza y depresión, o simplemente despertar su necesidad de buscar la luz con otra persona.",
			Match: "64%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Escorpio y Capricornio comparten un vínculo sexual especial como signos en sextil entre sí y debido al hecho de que Capricornio exalta uno de los regentes de Escorpio, Marte.\n \nLa naturaleza física de Capricornio ayudará a Escorpio a satisfacer sus necesidades sexuales con facilidad.\n \nAmbos signos sienten una atracción gravitatoria hacia sus signos opuestos, Tauro y Cáncer, dos de los signos más emocionales del zodíaco.\n \nEsto explica su necesidad de construir una verdadera intimidad.\n \nPara ambos, el placer físico debe alcanzarse a través de la ternura y la emoción, o no estarán realmente satisfechos.\n \nEn general, Escorpio exalta a Urano y puede sentirse un poco frustrado por el enfoque conservador de Capricornio.\n \nEs bueno que puedan esperar y construir lentamente una atmósfera en la que su pareja Capricornio se relaje lo suficiente como para probar cosas nuevas y experimentar.\n \nLa excitación de este contacto sexual es algo que a Capricornio le costará dejar ir.\n \nEscorpio, por otro lado, disfrutará de la sensación de seguridad y paciencia que obtiene de su pareja, aunque exprese abiertamente su sexualidad.",
			Match: "60%"},
		Trust: SummaryPercentage{
			Text:  "Si hay un signo en el que Escorpio puede confiar, ése es el signo de Capricornio.\n \nAunque los representantes de Capricornio no tienen por qué ser tan sinceros, su relación con esta pareja directa y honesta les hará sentir que ellos también deben ser lo más sinceros posible.\n \nCualquier falta de confianza en su relación es consecuencia de la falta de intimidad, ya que parecen carecer de la capacidad de sentirse el uno al otro con la suficiente profundidad como para comprender si confían o no el uno en el otro.\n \nEsto puede solucionarse si cada miembro de la pareja afronta sus propias inseguridades individualmente y con un esfuerzo emocional para construir la intimidad.",
			Match: "90%"},
		Communication: SummaryPercentage{
			Text:  "El fijo, inamovible Escorpio, en estado de constante metamorfosis y evolución en la misma dirección, puede ser un bocado 'demasiado grande para masticar' para su terco, terrenal y duradero en todo Capricornio.\n \nSu ritmo similar y la paciencia que tiene Capricornio, seguida del tacto de Escorpio pueden ayudar mucho a su entendimiento, pero cuando no están de acuerdo en algo, podrían acabar en una pelea silenciosa durante años.\n \nNo hay nada ligero ni fácil en esta interacción, y aunque comprendan la profundidad de mente del otro y una cierta visión de la vida de 'lo que va, vuelve', rara vez reirán, bailarán y se divertirán juntos.\n \nPuede que piensen que ni siquiera es algo que necesiten, pero todo el mundo necesita divertirse y sonreír, o la vida pierde gran parte de su sentido.\n \nEl humor negro podría saborear su situación, día tras día, y si tienen los mismos amigos les será mucho más fácil disfrutar de la vida juntos.\n \nEn general, captan la necesidad de silencio del otro y se acercan pacientemente hasta que cada uno se abre.\n \nEsto puede abrir la puerta a una comunicación respetuosa y a un entendimiento intelectual que dure mucho tiempo, si aprenden a controlar todas las convicciones negativas que afloran cuando están juntos.",
			Match: "70%"},
		Emotions: SummaryPercentage{
			Text:  "El mayor problema en una relación entre un Escorpio y un Capricornio es su contacto emocional, sencillamente porque ambos tienden a tener problemas emocionales, desestimando lo que sienten al desestimar a la Luna.\n \nCuando inician su relación, ambos darán la impresión de ser personas que se mantienen con los pies firmemente sobre la tierra, fuertes y rudos cuando es necesario.\n \nRara vez se darán cuenta de que esto les lleva a esperar ser siempre la persona fuerte que eran al principio, y a forzarse a hacer cosas para las que no están preparados sólo para evitar mostrar cualquier debilidad.\n \nSe necesita mucha comprensión emocional profunda para que no se vean obligados a alejarse aún más de su objetivo vital de encontrar el equilibrio emocional.",
			Match: "35%"},
		Values: SummaryPercentage{
			Text:  "Es realmente interesante observar cómo esta pareja comparte valores con una relación tan difícil con Venus y el término de valor en sí.\n \nEscorpio es el signo de detrimento de Venus y Capricornio le aporta mucha culpa, por lo que su combinación de valores se fundamenta básicamente en sentimientos de culpa y en la sensación de que nada es nunca suficientemente bueno.\n \nAunque esto será una buena motivación para que mejoren día a día, es bastante difícil de manejar en una relación sana y amorosa en la que ambos deberían descubrir que son suficientemente buenos.",
			Match: "30%"},
		SharedActivities: SummaryPercentage{
			Text:  "Juntos, Escorpio y Capricornio lucharán por la grandeza.\n \nCentrarán su energía en cosas constructivas para construir el mundo que desean para sí mismos.\n \nNo siempre es el lugar más feliz y alegre, con arco iris y unicornios, pero es realista, práctico y, sobre todo, bueno para el crecimiento personal.\n \nSi empiezan a escarbar en el pasado, puede que la terapia compartida les resulte reveladora, aunque no la necesiten por razones obvias.\n \nHay una necesidad en ellos de desenterrar la verdad, sea cual sea, y esto les facilitará pasar tiempo de calidad juntos sin muchas dudas sobre lo que quieren hacer.",
			Match: "99%"},
	},
}
