package compatibilities

var Scorpioaquarius = Compatibility{
	Name: Scorpio + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "80%",
		Traits:  []string{MutualRespect},
		Summary: "Es en este terreno, en el que no tienen que convivir, en el que sus diferentes personalidades no chocan tanto.\n \nEscorpio y Acuario saben que cuando se plantean objetivos en grupo o con otra persona, ésos son mucho más fáciles de alcanzar.\n \nComparten, además, que tanto Escorpio como Acuario son dos grandes estrategas y también coinciden en que no les gustan los cambios, se sienten mejor en situaciones que conocen y controlan.\n \nAcuario se muestra siempre comprensivo con el dominante Escorpio, no piensa igual pero le entiende.\n \nCuando Escorpio y Acuario perciben el gran poder que tienen juntos, es cuando otorgan un gran valor a su amistad.\n \nTambién la proverbial terquedad de Escorpio, se suaviza junto a Acuario, que también puede mostrarse terco aunque no en todo momento.\n \nAmbos son muy decididos y por ello cuando se proponen algo, un viaje por ejemplo, se lanzan de cabeza a conseguir realizarlo.\n \nEscorpio vive con profunda pasión e intensidad, mientras que Acuario tiene una visión más idealista e innovadora del mundo, también tiene un carácter más sociable.\n \nEstos aspectos Escorpio y Acuario lograrán complementarlos en beneficio mutuo.\n \nLa voluntad de hierro de ambos signos les facilitará mucho las cosas.",
	},
	Love: Love{
		Match:  "30%",
		Traits: []string{Volatile, DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "Alguien podría decir que se trata de una relación kármica, que estos compañeros fueron enemigos en una de sus vidas anteriores y que podrían luchar hasta que uno de ellos cayera muerto.\n \nSin embargo, esto sería un poco extremo.\n \nLa verdad es que Escorpio es el signo de exaltación de Urano y, como tal, adora en cierto modo a Acuario.\n \nEn la mayoría de los casos, la pareja de Escorpio mostrará su afecto de forma obsesiva, pero esto podría sentarle bien a Acuario.\n \nCuando observamos el signo de Acuario, veremos que exalta a Neptuno, el regente de un signo de Agua de Piscis, y todas nuestras suposiciones sobre su falta de emocionalidad se ahogarán en su amor definitivo.\n \nEl hecho es que ambos son, en cierto modo, marginados y rebeldes.\n \nMientras que Escorpio representa todas las emociones con las que no queremos lidiar, Acuario representa la forma de pensar para la que la mayoría de nosotros no estamos preparados.\n \nLo mejor es verlos como anunciadores del cambio, porque eso es exactamente lo que aportarán a la vida del otro.",
			Match: "30%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "El contacto entre un Escorpio y un Acuario puede ser realmente intenso.\n \nComo signos en cuadratura, deberían tener un contacto muy problemático, pero el signo de Escorpio exalta al regente de Acuario, Urano.\n \nEstos signos combinados representan la máxima libertad sexual, un lugar sin restricciones ni tabúes.\n \nSon una combinación de Agua y Aire, de emoción e información, todo combinado en un fuerte aroma de atracción.\n \nSi se atan el uno al otro y rompen, podrían acabar odiándose y despreciando todo lo que han compartido en su vida sexual.\n \nEs muy difícil para estas parejas encontrar un equilibrio entre pasión, emoción y pensamiento racional.\n \nMientras que la sexualidad de Escorpio es hambrienta, profundamente emocional y penetrante, Acuario quiere estar libre de cualquier límite y emoción, y tendrá verdaderos problemas para estar con una pareja posesiva.\n \nSu vida sexual puede ser como un campo de batalla o como el país de las maravillas, dependiendo de la flexibilidad de ambos y de la profundidad de las emociones que compartan.\n \nAl ser dos signos fijos, seguramente tendrán problemas para cambiar su naturaleza y adaptarse a una pareja demasiado diferente de ellos.",
			Match: "40%"},
		Trust: SummaryPercentage{
			Text:  "¿Cómo es posible que dos personas honestas y directas como Escorpio y Acuario tengan tantos problemas para confiar el uno en el otro?\nEl problema aparece cuando se acercan demasiado.\n \nEn cuanto Escorpio empiece a asumir que Acuario debe ser más dócil y pertenecerle en una relación amorosa, se producirá una rebelión enérgica y el contraataque de su pareja.\n \nLas cosas podrían salirse de control si se produce algún tipo de manipulación, y las tendencias tácitas podrían separarlos en cuestión de minutos.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Ninguno de los dos querrá mantener conversaciones triviales ni hablar de su día en el trabajo.\n \nEs inútil desde su perspectiva, y aunque a Escorpio le gusta tener el control de todo lo que hace su pareja, será refrescante hablar con alguien que dice cosas inusuales.\n \nLa mayor cualidad de su relación es una increíble conexión de profundidad y amplitud en una sola pareja.\n \nA ambos les costará entender nuestra sociedad tal y como es, y tendrán ciertas perspectivas similares sobre cualquier cosa fuera de lo común.\n \nEscorpio exalta al regente de Acuario y por eso su relación es la posibilidad de que ambos crezcan.\n \nEscorpio no sólo adorará la fuerza intelectual de su pareja, sino que también le ayudará a comprender la forma en que sus ideas podrían realizarse a través de un sentimiento de máxima posibilidad.\n \nEl eslabón más débil de su relación es el respeto que sienten el uno por el otro, combinado con sus naturalezas estáticas.\n \nPodríamos pensar que ambos signos están en conexión con el cambio y que no podrían ser estáticos, pero de hecho, son estáticos en su forma de cambiar, y su mayor reto es detenerse un minuto y atesorar lo que han encontrado el uno en el otro.",
			Match: "50%"},
		Emotions: SummaryPercentage{
			Text:  "Si surge el amor entre ellos, lo más típico es que Escorpio caiga en un lío obsesivo de sentimientos hacia su desinteresada pareja Acuario.\n \nLlegar al núcleo emocional de Acuario requiere mucho trabajo y compromiso, y es imposible conseguirlo sin espontaneidad y confianza.\n \nAcuario raramente tolerará o estará con alguien que intente hacerles ser más estables y con los pies en la tierra, o con cualquiera que apague su deseo de ser libres.\n \nEn cuanto se sientan obligados a hacer algo, empezarán a alejarse y cualquier emoción que haya podido desarrollarse quedará de repente cubierta por el miedo al compromiso y la rutina de la vida cotidiana.\n \nSi quieren alcanzar el equilibrio emocional, los Escorpio tienen que desatarse, darse cuenta de que su pareja nunca les pertenecerá y que son libres de marcharse en cualquier momento.\n \nTendrán que entender que esta relación podría terminar mañana y que no hay nada que puedan hacer al respecto más que aceptarlo.\n \nPor otro lado, Acuario tendrá que enfrentarse a su profundidad emocional y estar dispuesto a realizar ciertos cambios en su forma de enfocar las relaciones románticas, para poder sentir de forma constante que comprende la naturaleza emocional de Escorpio.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Ambos valorarán la emoción y el cambio, y éste será un fuerte punto de encuentro para sus caracteres.\n \nPor desgracia, la mayoría de las demás cosas que valorarán en su pareja son completamente diferentes.\n \nMientras que Acuario valora el espíritu libre, la comunicación y la independencia, Escorpio valora el compromiso, el sexo y la conexión emocional profunda.",
			Match: "30%"},
		SharedActivities: SummaryPercentage{
			Text:  "Mientras se mantengan al margen de su batalla de egos, podrían encontrar muchas cosas que hacer juntos.\n \nA ambos les gustará correr riesgos de cualquier tipo y su mejor cita podría ser cualquier cosa, desde saltar en paracaídas hasta una noche en un casino.\n \nLa mejor forma de que pasen un buen rato juntos es en algún tipo de actividades intelectuales y competiciones, porque esto les permitiría manifestar su posible hostilidad de una forma sana.",
			Match: "60%"},
	},
}
