package compatibilities

var Taurusvirgo = Compatibility{
	Name: Taurus + " - " + Virgo,
	Friendship: Friendship{
		Match:   "95%",
		Traits:  []string{GoodRomancePotential, ExcellentAdvisors, DeepMutualUnderstanding},
		Summary: "La amistad entre Tauro y Virgo se asienta sobre la lealtad que ambos signos valoran por igual.\n \nSi llegan a establecer estos lazos, serán amigos para siempre.\n \nLa principal ventaja es que con sólo una mirada Tauro y Virgo son capaces de entenderse.\n \nSu complicidad llega a límites muy elevados y esto les sitúa en posición de pasárselo muy bien juntos.\n \nAlgunas personas encuentran a Tauro demasiado obstinado y conservador, pero esto no sucede con los nativos y nativas de Virgo, sino todo lo contrario, lo que otros consideran defectos para ellos serán virtudes muy apreciadas.\n \nA ambos les gustan las cosas establecidas, las de toda la vida.\n \nUna vez establecidos sus vínculos personales, Tauro y Virgo ampliarán su relación a la de sus parejas, si las tienen, o sus familias, en el plano más tradicional.\n \nAunque pueden surgir diferencias entre ellos, quizá por el carácter un tanto frío de Virgo, que expresará su afecto con gestos útiles y no con palabrería, o por la tozudez de Tauro al que cuesta hacer cambiar de opinión hasta agotar la paciencia de cualquiera.\n \nTodo ello quedará diluido por el sentido de la lealtad y también porque ambos les encanta hacer felices a los amigos.",
	},
	Love: Love{
		Match:  "73%",
		Traits: []string{Harmonious, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "En general, Tauro está ahí para enseñar a Virgo sobre el amor, la ternura y la sexualidad.\n \nVirgo necesita ser lo suficientemente flexible para valorar a su Tauro y darle la visión intelectual de las cosas que podría idealizar.\n \nSu relación podría ser una pareja hecha en el cielo, sólo si no tienen demasiado miedo a que les hagan daño y son demasiado desconfiados.\n \nSi se entregan el uno al otro y se enamoran perdidamente, podrían ser la combinación de un corazón claro, representado por Tauro, y una mente clara, representada por Virgo.\n \n¿Qué más podrían necesitar el uno del otro?",
			Match: "73%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La relación sexual entre un Tauro y un Virgo puede ser bastante conmovedora.\n \nLa pareja de Virgo suele avergonzarse de mostrar su sexualidad o su cuerpo.\n \nEl don de Tauro es su capacidad para relajar a su pareja sexual prestándole suficiente atención y obsesionándose con su satisfacción.\n \nA su pareja Virgo esto le parece casi irreal, ya que esperaría algo rudo y aterrador cuando se trata de sexo.\n \nEsta es una combinación ideal de parejas para las primeras experiencias sexuales, porque Virgo puede entrar en el mundo de la sexualidad de la forma más suave posible.\n \nVirgo es el signo de la virginidad y es el lugar donde cae Venus, que representa toda satisfacción.\n \nEl miedo a ser herido es a veces demasiado grande para manejarlo y con la visión que Virgo tiene de Venus raramente comprenden el lado de la sexualidad que está en relación con la satisfacción y la ternura.\n \nTauro es un signo regido por Venus y su comprensión del sexo es bastante diferente.\n \nParecen tener la misión de explicar qué es la ternura a quienes les rodean, y encuentran en alguien como Virgo un alumno perfecto para sus enseñanzas.\n \nEstarán encantados de explicar a su pareja cuál es el lado hermoso del sexo, sólo si Virgo está dispuesto a escuchar.",
			Match: "85%"},
		Trust: SummaryPercentage{
			Text:  "Virgo no confía en nadie con facilidad.\n \nEsto se debe al hecho de que Piscis es su signo opuesto, y ven a cada compañero de su vida como un atisbo de lo desconocido.\n \nNo es fácil abrirse a un campo tan enorme de posibilidades cuando uno se siente tan pequeño.\n \nTauro es mucho más relajado y da mucha importancia a la belleza del sexo, así que si Virgo no se siente adecuado con su pareja Tauro, no le resultará fácil creer en su honestidad o fidelidad.\n \nEsta desconfianza dolerá mucho a su pareja Tauro, pues no podrá entender qué hizo para merecerla y probablemente culpará a la naturaleza cambiante de Virgo, pensando que tampoco es tan honesto.",
			Match: "75%"},
		Communication: SummaryPercentage{
			Text:  "La fuerza intelectual de Virgo es exactamente lo que Tauro necesita para construir una mejor comprensión del mundo.\n \nA menudo se dice que Tauro puede ser muy terco y difícil de hablar con él, pero es casi seguro que un Virgo utilizará su cualidad mutable para encontrar diferentes enfoques con el fin de explicar su punto de vista.\n \nComo dos signos de Tierra, ambos pueden aferrarse a sus convicciones y ser demasiado rígidos para no aceptar el punto de vista de otro, pero en la mayoría de los casos, el intelecto de Virgo y la ternura de Tauro pueden ayudarles a encontrar un lenguaje que ambos entiendan sea cual sea la situación.",
			Match: "90%"},
		Emotions: SummaryPercentage{
			Text:  "La paciencia que puede tener Tauro cuando se enamora es lo que hace que encaje tan bien con Virgo.\n \nDado que Virgo no reconocerá sus sentimientos de inmediato, necesitará tiempo para establecer una base emocional sólida.\n \nDebido a la falta de confianza y a la decepción para la que Virgo casi siempre está preparado, Tauro necesita quedarse quieto y no defraudarlos nunca para construir la confianza y dejar que evolucionen sus sentimientos mutuos.\n \nSi ambos no son demasiado rígidos y tienen miedo de salir heridos, podrán construir una relación emocional fuerte y profunda con el respeto mutuo intacto.\n \nEs muy importante que no se mantengan a una distancia segura durante demasiado tiempo, porque podrían construir fácilmente una relación sin emociones y permanecer en ella, insatisfechos, durante años, a pesar de que podrían haber tenido potencial para enamorarse perdidamente.",
			Match: "85%"},
		Values: SummaryPercentage{
			Text:  "No valoran exactamente las mismas cosas, pero estarán bien mientras no se falte al respeto al lado femenino de Tauro.\n \nCon el regente de Tauro en otoño en el signo de Virgo, su entendimiento de Tierra a Tierra está un poco dañado.\n \nDado que Venus representa todo el valor, Virgo podría mostrar lo que Tauro reconocería como una falta de comprensión en general.\n \nSin embargo, ambos valorarán la naturaleza del elemento Tierra, estable, seguro y lento, y esto debería darles tiempo suficiente para enmendar las diferencias y encontrar un punto medio.",
			Match: "50%"},
		SharedActivities: SummaryPercentage{
			Text:  "Tauro puede parecer realmente perezoso a su pareja Virgo, especialmente cuando están en una juerga de satisfacción y no salen de la casa, excepto si están en camino a un buen restaurante.\n \nLa intimidad de su naturaleza asusta a Virgo hasta el punto de la agonía y rápidamente necesitarán un cambio de aires para no sentirse como si estuvieran parados en un mismo sitio durante toda la eternidad.\n \nSi Tauro enfoca sus actividades habituales de modo que respete la obsesión ocasional de Virgo por su salud, podrían pensar en varias cosas para hacer juntos y complementarse muy bien.\n \nLa preparación de tentempiés saludables sería sólo una de las posibles sugerencias para satisfacer las necesidades que ambos tienen.\n \nVirgo es un signo regido por Mercurio, y aunque pertenece al elemento Tierra, necesitan moverse.\n \nTauro puede ser realmente estático y es importante que tomen la decisión de seguir a su pareja o realmente no tendrán mucho futuro juntos.\n \nLo bueno es que Tauro suele guiarse por la inercia, así que cuando se acostumbren al movimiento, éste se convertirá en un estado permanente para ambos.\n \nAunque no relacionarías a estos signos con los viajes, cuando estén juntos, podrían sentir y seguir el impulso de recorrer el mundo.",
			Match: "55%"},
	},
}
