package compatibilities

var Taurussagittarius = Compatibility{
	Name: Taurus + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "40%",
		Traits:  []string{CautionRomance, PoorAdvisors},
		Summary: "Tampoco en este apartado la relación de Tauro y Sagitario tiene demasiadas posibilidades de prosperar por sus muy diferentes aficiones y su forma de ver la vida.\n \nMientras Tauro ama disfrutar de su hogar y de los suyos, entre los que se cuentan quienes él considera amigos, Sagitario se divierte más yendo de marcha con la gente más diversa.\n \nY no es ésta la única diferencia notable entre Tauro y Sagitario, porque la capacidad de cambiar de opinión de este último, irrita profundamente al tranquilo Tauro, que necesita solidez a su alrededor.\n \nSi llegan a iniciar una amistad, estará plagada de momentos tensos y de inevitables discusiones con las que ninguno de los dos signos se sentirá cómodo, aunque por distintas razones.\n \nSi Tauro y Sagitario llegan a considerarse verdaderamente amigos, será porque ambos se han esforzado.\n \nTauro en comprender que en la vida hay otras opciones más allá de la seguridad y Sagitario porque quizá descubra que el sentido práctico de Tauro es realmente muy valioso.\n \nSagitario Y Tauro tendrían también que hacer un esfuerzo por mejorar su comunicación, muchas veces deficiente.\n \nSon los que mejor reflejan aquello de “hablando se entiende la gente” y pueden llegar de este modo incluso a ser amigos.",
	},
	Love: Love{
		Match:  "31%",
		Traits: []string{},
		Summary: SummaryPercentage{
			Text:  "Con su belleza interior y la comprensión que comparten en la búsqueda de la verdad de la vida, estos dos podrían parecer una pareja perfecta.\n \nSin embargo, todo positivo necesita un negativo que lo complete, y cuando observamos realmente, podemos darnos cuenta de que a menudo un Tauro y un Sagitario ni siquiera se atraen.\n \nTauro necesita placeres terrenales en sus relaciones y como signo fijo, de Tierra, es el más lento de todos los signos.\n \nNo es precisamente alguien que pueda entender fácilmente al rápido, cambiante y fogoso Sagitario.\n \nEl mejor escenario posible para su relación sería que se conocieran muy bien y construyeran una amistad sin expectativas, durante años.\n \nAl final, esto podría resultar en un entendimiento profundo que les proporcionaría a ambos la paciencia suficiente para comenzar realmente una relación que tenga futuro.\n \nSi no, siempre pueden aferrarse a la belleza del mundo.\n \nImaginen lo maravilloso que podría ser su mundo de creación si unieran sus fuerzas del bien.",
			Match: "31%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando Tauro piensa en sexualidad, Sagitario es probablemente la última persona en la que piensa.\n \nCon su actitud infantil que cambia con el tiempo, parece que no hay lugar para ninguna actividad sexual en su vida.\n \nAunque se trata de una ilusión, estos signos están demasiado alejados en su carácter básico como para entender la sexualidad del otro.\n \nEs interesante, sin embargo, cómo dos personas regidas por dos planetas benéficos como Venus y Júpiter no pueden encontrar satisfacción sexual.\n \nEl hecho es que pueden.\n \nAunque se trata de un escenario poco frecuente, en realidad podrían utilizar sus atributos para aumentar el placer sexual que Venus les ofrecería.\n \nSi se entendieran como dos individuos que merecen respeto, podrían encontrar el eslabón perdido para una vida sexual muy interesante y satisfactoria.\n \nTauro cuidaría de su pareja Sagitario y la mantendría satisfecha.\n \nA cambio, obtendrían un alma alegre que sabe cómo hacer que su relación sea excitante.\n \nAquí hay mucho que aprender sobre el 'lado luminoso' de la sexualidad, y ésta podría ser una experiencia divertida si Tauro se soltara un poco y Sagitario bajara el ritmo.",
			Match: "25%"},
		Trust: SummaryPercentage{
			Text:  "El signo de Sagitario se considera algo así como un sinónimo de honestidad.\n \nEs cierto que los representantes de este signo no tienen ni idea de cómo inventar una mentira, y mucho menos de cómo contarla.\n \nAun así, cuando se trata de relaciones románticas, a menudo sufren el síndrome de Don Juan y no consiguen que su pareja les preste suficiente atención.\n \nTauro encuentra esto repulsivo en el mejor de los casos, y si una relación con una pareja Sagitario comienza y ellos comienzan a actuar de esta manera, hay una gran posibilidad de que sean abandonados.\n \nLa confianza entre estos socios no es algo para ser cuestionado y analizado.\n \nSi confían el uno en el otro pueden tener una relación maravillosa, de confianza por un tiempo, pero todavía no hay garantía de cuánto tiempo podría durar.\n \nSi no lo hacen, no se arreglará intenten lo que intenten.\n \nPor lo general, la pérdida de confianza en este caso simplemente rompe la relación y ambos toman caminos separados sin arrepentirse.",
			Match: "5%"},
		Communication: SummaryPercentage{
			Text:  "Con la Luna exaltada en Tauro y Júpiter exaltado en Cáncer (regido por la Luna), hay un cierto sentimiento, un alma, una ternura que compartir entre ellos.\n \nSus enfoques de la vida son diferentes, sus caracteres incomparables, pero la alegría que pueden sentir hacia algunas cosas es completamente la misma.\n \nSi no encuentran este sentimiento compartido de alegría, ambos podrían aprender lo que es realmente una mala comunicación.En la mayoría de los casos pueden hablar del tiempo y estar bien, pero cuando tienen un problema, esto se convierte en una conversación ridícula que en realidad no es una conversación en absoluto.\n \nSagitario querrá saltar fuera de su piel mientras espera que Tauro termine la frase, tanto como Tauro mirará a su pareja Sagitario como una fuente de toda estupidez.\n \nTauro es su campo y Sagitario es el mundo, por lo que sus problemas podrían incluir fácilmente faltas de respeto por su origen o sus objetivos.\n \nAunque rara vez terminarán en una pelea o usarán palabras feas, a veces puede ser demasiado obvio cuánto no les importan los mundos del otro y cuán alejados están realmente.",
			Match: "50%"},
		Emotions: SummaryPercentage{
			Text:  "Ambos están conectados con la Luna en cierto modo, así que hay algunos sentimientos que compartir. Sin embargo, Sagitario no suele reaccionar con mucha emoción a la estática, desde su perspectiva aburrida naturaleza de Tauro. Si Tauro fuera un poco más propenso a los enamoramientos temporales o a las relaciones platónicas, podría enamorarse de un Sagitario lo suficiente como para superar las diferencias entre ambos. Sagitario, en cambio, suele encapricharse y enamorarse temporalmente. Existe una gran posibilidad de que se enamoren de un Tauro si les gusta su apariencia física, pero no durarán en esos sentimientos lo suficiente como para llevar suavemente a Tauro al amor mutuo. Su ritmo está apagado y rara vez se sincronizan con sus emociones. La mayoría de las relaciones entre un Tauro y una pareja Sagitario que logran durar, son aquellas que comenzaron como una amistad y tuvieron la oportunidad de desarrollarse emocionalmente durante años sin que realmente estuvieran en una relación romántica.",
			Match: "25%"},
		Values: SummaryPercentage{
			Text:  "La combinación de signos de Tauro y Sagitario es un 'niño de las flores' lleno de amor, comprensivo con el mundo y, en última instancia, humano.\n \nPodrían apoyar mutuamente sus mundos utópicos con demasiada pasión, y esto podría llevar a que uno de ellos, o ambos, se hicieran ilusiones sobre lo que es la realidad.\n \nHay demasiado amor y felicidad en el mundo si empiezan a compartir opiniones y esto puede llegar a ser como una droga para ambos.\n \nLa practicidad de Tauro suele romper este patrón y contraatacar con sus comprobaciones de la realidad y cuestiones materiales para que ambos recuerden dónde se separan sus valores: en la seguridad y en la absoluta falta de ella.",
			Match: "60%"},
		SharedActivities: SummaryPercentage{
			Text:  "La comida.\n \nEs lo que más comparten.\n \nPuede que Tauro no comparta la comida con alegría, pero sin duda les gustará compartir la actividad de comer.\n \nTambién les resultará bastante fácil encontrar otras cosas que hacer juntos.\n \nEl problema surgirá en el momento en que Tauro quiera volver a casa y pasar la noche en su cálida cama, mientras que la diversión de Sagitario acaba de empezar.\n \nNo comparten la misma pasión por las mismas cosas y, aunque se diviertan juntos, sus prioridades no son las mismas.\n \nLa energía de Fuego de Sagitario se verá desanimada por la personalidad de Tierra de Tauro y esto será tedioso para ambos.",
			Match: "20%"},
	},
}
