package compatibilities

var Taurusleo = Compatibility{
	Name: Taurus + " - " + Leo,
	Friendship: Friendship{
		Match:   "70%",
		Traits:  []string{MutualRespect},
		Summary: "Los nativos y nativas de Leo atraen la atención en cualquier parte que estén.\n \nTodos se les acercan como moscas a la miel, también el temeroso Tauro, que se siente cautivado por la brillante personalidad de Leo.\n \nDe hecho, Tauro y Leo se complementan muy bien al principio.\n \nA Tauro le gusta la actitud benevolente de Leo, que suele mirar siempre por el bien de los demás.\n \nPero estos inicios tan positivos en una relación de amistad entre Tauro y Leo, pueden acabar en agua de borrajas al cabo de un tiempo y quizá no demasiado.\n \nAmbos deberían poner mucha voluntad de su parte para limar estos aspectos que pueden llevar a separarles.\n \nA Tauro le gusta saber que cuenta con amigos incondicionales, y aunque Leo lo sea, posiblemente no se manifieste así.\n \nDada su facilidad para las relaciones sociales, Leo cuenta con muchos amigos y conocidos, lo cual puede causar cierta inquietud en Tauro.\n \nSi la manifiesta, Leo se sentirá invadido y esto no le va a gustar.\n \nPara que la relación amistosa entre Tauro Leo se prolongue en el tiempo, Tauro deberá aparcar este sentido de propiedad que tiene sobre las personas por quienes siente afecto y Leo tendrá que armarse de paciencia y comprender la bondad innata de Tauro.",
	},
	Love: Love{
		Match:  "29%",
		Traits: []string{DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "La relación de Tauro y Leo podría ser agresivamente desafiante si no fuera por sus cálidas naturalezas regidas por Venus y el Sol.\n \nAunque ambos son signos de cualidad fija con naturalezas totalmente diferentes, si reúnen la suficiente paciencia antes de iniciar su relación, tienen la oportunidad de convertirse en la pareja arquetípica de una chica y un chico.\n \nCuando sus principios masculinos y femeninos están en equilibrio, pueden utilizarlos para arreglar sus circunstancias sexuales, intelectuales y financieras y disfrutar realmente el uno del otro.",
			Match: "29%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La relación sexual entre un Tauro y un Leo puede ser en cierto modo agotadora para ambos.\n \nEsto se debe principalmente al hecho de que ambos pueden ser perezosos.\n \nMientras que a Tauro le gusta tumbarse y disfrutar siendo amado, a Leo le gusta tumbarse y ser servido y atendido.\n \nEstá en la naturaleza de ambos signos pasar el tiempo en posición horizontal y puede resultarles difícil ponerse de acuerdo sobre quién debe estar encima.\n \nCuando están motivados, ambos pueden ser excelentes amantes que ponen mucha energía en sus actividades sexuales, pero el uno con el otro, lo más probable es que su vida sexual se convierta en una batalla por la satisfacción personal y el descanso.\n \nSu mejor posibilidad de una vida sexual sana sería aquella en la que ambos miembros de la pareja ya han construido su identidad sexual y saben cómo satisfacerse a sí mismos.\n \nEn general, son un signo femenino y otro masculino, y comparten una necesidad similar de satisfacción personal.\n \nSi no acaban en una relación en la que ambos tienen expectativas y no se mueven hasta que las cumplen, podrían tener una vida sexual muy gratificante.\n \nAl fin y al cabo, no son más que dos caras diferentes del amor, la alegría y la vida en color.",
			Match: "50%"},
		Trust: SummaryPercentage{
			Text:  "Como dos signos fijos, es muy probable que se valgan por sí mismos a la hora de decir la verdad.\n \nEntienden que la honestidad es la base de cualquier relación que pueda durar y, si se enamoran, ninguno de los dos querrá poner en peligro su futuro juntos.\n \nSin embargo, si uno de los dos tiene el hábito de mentir o engañar que ha desarrollado en sus relaciones anteriores, probablemente continuará con el mismo comportamiento en ésta.\n \nEs muy importante que ambos desarrollen su personalidad y sus límites morales de forma independiente para que puedan funcionar juntos.\n \nSu principal problema podría ser la falta de voluntad de cualquiera de las partes para cambiar los patrones de comportamiento que puedan surgir.\n \nEn caso de que uno de ellos crea que el otro podría cambiar, el tiempo podría consumirlos a través de un sentimiento de desconfianza que se acumula con la decepción porque el cambio no se produce.",
			Match: "60%"},
		Communication: SummaryPercentage{
			Text:  "Están de suerte porque están regidos por Venus y el Sol, ambos cálidos y con tendencia a estar cerca el uno del otro, porque cuando se trata de sus intereses y su entendimiento intelectual, podrían volverse locos el uno al otro.\n \nEs difícil decir quién molestará más a quién.\n \nMientras Tauro se aferra a su perspectiva práctica, Leo se aferra a su ego, y nace un conflicto sin solución.\n \nSus naturalezas fijas les harán aferrarse a su 'bando' por estúpido que sea, sin intención real de reconciliación.\n \nAmbos necesitan a alguien con un enfoque no tan rígido si quieren encontrar el término medio.\n \nTauro encontrará un lenguaje mutuo con Leo a través de su papel habitual, materializador.\n \nCualquier impulso creativo de Leo podría ser seguido por el plan de realización pensado por su pareja Tauro, si tan sólo compartieran suficientes emociones para tener paciencia el uno con el otro.\n \nSu fuerza creativa es la fuerza de un Venus en combinación con el Sol, por lo que podríamos decir con certeza que crearían algo a imagen del amor universal.",
			Match: "5%"},
		Emotions: SummaryPercentage{
			Text:  "Tauro es un signo profundamente emocional, por si no se cierran en banda y viven en su pequeño y seguro mundo material.\n \nLeo es un signo apasionado que representa el amor como poder de creación y todo aquello hacia lo que sentimos gravedad.\n \nAmbos son la personificación del amor, cada uno a su manera.\n \nCuando se junten, rara vez sentirán este amor el uno por el otro.\n \nTal vez podríamos ver esto como su misión de dar amor a los signos zodiacales menos afortunados, o tal vez su naturaleza emocional tiene que dar más y recibir menos.\n \nSea cual sea la razón, en la mayoría de los casos simplemente no se enamoran el uno del otro.\n \nExiste una gran posibilidad de que simplemente se queden en sus propios mundos, sin perspectivas de fusionarse ni siquiera en algo parecido a una amistad.\n \nEsto no se debe a que no se gusten o sientan algún tipo de hostilidad, sino a que son como dos islas en dos océanos diferentes.\n \nCada una tiene su propia naturaleza, su propio mundo con todas sus bellezas, y necesitan a alguien más cercano a ese mundo al que se aferran.\n \nNinguno de ellos tiene el papel de una isla flotante en busca de alguien con quien fusionarse.",
			Match: "20%"},
		Values: SummaryPercentage{
			Text:  "Tauro y Leo tienen puntos de vista diferentes sobre el valor en sí.\n \nMientras Tauro valora la seguridad financiera y la belleza material, Leo valora todo lo brillante, la valentía y el fuego interior de alguien.\n \nHay una paz en Tauro que Leo no quiere entender, pues le parece un lugar aburrido para visitar.\n \nLeo también valora la paz, pero para ellos está escondida en un lugar diferente, mucho más alegre o en público, como la paz entre países y continentes enteros.\n \nA Tauro, Leo puede parecerle alguien que adopta una pose y no tiene profundidad alguna, y aunque la profundidad no es uno de sus valores primordiales, sigue siendo uno muy importante.\n \nNo encuentran nada interesante en las personas sin esencia y Leo tampoco, pensando en Tauro y en cómo no se abren para compartir nada profundo.",
			Match: "1%"},
		SharedActivities: SummaryPercentage{
			Text:  "Las actividades compartidas son muy fáciles de encontrar para ambos.\n \nO bien se tumban, duermen, comen y se abrazan, o bien se separan y hacen cosas el uno sin el otro.\n \nTauro es inerte y le encanta pasar el tiempo en su sofá mientras fuera llueve y no oyen nada más que el sonido de una chimenea.\n \nLeo se guía por su naturaleza, y un león duerme 20 horas al día y juega el resto.\n \nIncluso los leones más feroces esperan a que su leona les sirva la comida.\n \nEl problema surgirá cuando Tauro prepare una imagen romántica y Leo se quede dormido, pero aún así es un escenario que podría funcionar.\n \nSus actividades al aire libre pueden ser divertidas para ambos si salen a restaurantes elegantes.\n \nAquí es donde Leo puede ser visto, y actuar como una persona galante que merece lo mejor, mientras que Tauro podría disfrutar de una comida realmente buena.\n \nAparte de éstas, probablemente no tendrán muchas actividades para compartir, pero si no son testarudos, podrían disfrutar juntos de todo lo que no sea demasiado exigente y físico.",
			Match: "40%"},
	},
}
