package compatibilities

var Tauruscapricorn = Compatibility{
	Name: Taurus + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "98%",
		Traits:  []string{GoodRomancePotential, ExcellentAdvisors, DeepMutualUnderstanding},
		Summary: "Cuando Tauro y Capricornio deciden iniciar una amistad, es bien seguro que ambos ya lo han pensado bien antes de dar el primer paso.\n \nNo será aquello de conocerse y simpatizar y a continuación estar contándose ya la vida entera.\n \nNo, tanto Tauro como Capricornio necesitan más tiempo para abrirse a alguna persona, aunque dicha persona les haya sorprendido por su similitud a ellos mismos en su forma de actuar.\n \nLa primera impresión es buena, la simpatía es mutua, pero necesitan asegurarse de que su intuición no les falla.\n \nTauro y Capricornio serán grandes amigos, de los que siempre encuentras cuando los necesitas.\n \nTauro necesita más que Capricornio esta seguridad y también se sentirá más satisfecho de que sea Capricornio quien en muchas ocasiones lleve la voz cantante cuando se trata de organizar salidas o trazar planes en los que ha de intervenir más gente.\n \nDesde luego Tauro es un buen organizador, pero agradece que en algunas ocasiones alguien le sustituya.\n \nY ese alguien no puede ser cualquiera porque no confiaría en él al cien por cien como lo hace con Capricornio, que se convierte más que en un amigo, una parte de sí mismo.\n \nEsta relación está destinada a durar para siempre.",
	},
	Love: Love{
		Match:  "89%",
		Traits: []string{Harmonious, GreatSexualChemistry, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "Tauro y Capricornio pueden formar una relación tan profunda que su poder creativo en el terreno material podría parecer inalcanzable para otros signos del zodíaco.\n \nCon la capacidad de complementarse mutuamente de forma suave y pausada, son la pareja más aburrida por fuera, con la actividad interior más excitante que permanece oculta al resto del mundo.\n \nSi Tauro motiva a su pareja Capricornio, y Capricornio muestra el camino de los logros a su pareja Tauro, podrían trabajar juntos, criar hijos y compartir una vida con más diversión de la que ambos están acostumbrados, o simplemente formar un vínculo inquebrantable.\n \nCuando sus profundas emociones se entrelazan, quedan unidos el uno al otro para la eternidad.",
			Match: "89%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Tauro y Capricornio pueden ser bastante rígidos en lo que respecta al sexo.\n \nEsto es precisamente lo que podría hacer de ellos una pareja perfecta.\n \nPuede ser difícil para ellos abrirse y sentir la necesidad de experimentar, aunque Capricornio hará todo lo posible para demostrar lo ingeniosos que son cuando se trata de sexo.\n \nCuando estén juntos y se conozcan íntimamente, aprenderán lo que significa relajarse.\n \nEl problema en su relación puede esconderse en su forma de entender la Luna, pues Tauro la exalta y a Capricornio no le gusta demasiado.\n \nPodrían tener problemas para conectar a nivel emocional si Capricornio no se enamora lo suficiente o tiene problemas de confianza.\n \nEsto se multiplicará por la necesidad de Tauro de ser amado incondicionalmente que muestran en un bucle sin fin, ahuyentando a su Capricornio.\n \nSus diferentes aproximaciones a la combinación de instintos sexuales y amor son las que podrían abrir una brecha entre ellos.\n \nTauro tiene un problema con la iniciativa y la agresividad, mientras que Capricornio necesita iniciativa y fuerza física.\n \nEn su vida sexual, esto podría conducir a una falta de emoción de la pareja Capricornio, lo que lleva a la frustración de Tauro, asustado por su libido sin fundamento emocional.",
			Match: "85%"},
		Trust: SummaryPercentage{
			Text:  "A Capricornio no le gusta mentir.\n \nNi siquiera la juzgan, sino que la consideran innecesaria y estúpida.\n \nIncluso cuando dicen una mentira, en la mayoría de los casos se trata de un experimento con otros seres humanos para ver si pueden adivinar dónde está la verdad.\n \nCuando están involucrados íntimamente, les gusta que las cosas entre ellos y su pareja sean limpias y verdaderas.\n \nTauro puede percibirlo fácilmente y se sentirá lo bastante seguro como para no ceder a su necesidad ocasional de ocultar cosas a su pareja.\n \nTauro se rige por Venus, un planeta exaltado en el signo de Piscis, por lo que tienen esta comprensión de la importancia del secreto cuando están en el amor.\n \nCon Capricornio, pueden encontrar la forma de ocultar su intimidad al resto del mundo y mantenerse fieles a su amada durante mucho, mucho tiempo.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Aunque tienen naturalezas diferentes, se entienden muy bien y se motivan mutuamente para crecer, cada uno en la dirección que necesita.\n \nSus diferencias están ahí precisamente para hacer de ellos una pareja perfecta, porque se complementan de una forma más sutil que sus signos opuestos.\n \nLa profunda comprensión de la Luna es algo con lo que Tauro está bendecido y Capricornio carece en su núcleo.\n \nEl miedo a las emociones puede convertirse fácilmente en una rutina diaria de negligencia hacia sus necesidades emocionales personales.\n \nTauro tiene la misión de enseñar a Capricornio el significado de la ternura que uno debe tener siempre consigo mismo.\n \nA cambio, Capricornio ayudará a Tauro a lidiar con la responsabilidad y le enseñará a alcanzar sus metas sin emociones que lo distraigan.\n \nNo siempre les resulta fácil entenderse, pero con la suficiente compasión y apertura para sentir por la otra persona, pueden apoyarse mutuamente como ningún otro par de signos puede hacerlo.\n \nAl fin y al cabo, pertenecen al elemento Tierra y pueden hacer magia en nuestra realidad material cuando concilian sus diferencias.",
			Match: "85%"},
		Emotions: SummaryPercentage{
			Text:  "Es difícil decir con certeza que encontrarán la plenitud emocional el uno con el otro porque ambos son muy cuidadosos en lo que se refiere al amor.\n \nEsto suele ser algo así como un patrón a romper cuando inician una relación, pues tienen suficiente tiempo y paciencia el uno para el otro.\n \nDesde la perspectiva de Tauro, puede que este no sea el mejor contacto emocional que hayan tenido, pero desde la perspectiva de Capricornio, las cosas no pueden ser mucho mejores que ser amado por una pareja Tauro.\n \nSin embargo, hay una dosis de satisfacción casi insoportable que Tauro sentirá cuando su excavación a largo plazo llegue al núcleo emocional de su pareja Capricornio.\n \nCuando se alcanza este contacto, rara vez sentirán la necesidad de volver a separarse de ellos.\n \nA Capricornio esto le parecerá como si alguien le hubiera tocado literalmente el corazón y probablemente nunca querrá dejar marchar a su pareja Tauro.",
			Match: "90%"},
		Values: SummaryPercentage{
			Text:  "Con un sentido compartido del valor del mundo material, estos dos pueden llegar muy lejos juntos.\n \nMientras Tauro crearía y motivaría, Capricornio marcaría el camino hacia el éxito y la seguridad financiera.\n \nCualesquiera que sean sus objetivos, podrían alcanzarlos juntos fácilmente debido al hecho de que, para empezar, comparten los mismos valores materiales.\n \nSin embargo, su relación con las emociones y la familia no es tan agradable.\n \nDeberían observar los diferentes lados de sus personalidades como complementarios en lugar de destructivos y encontrar una forma de coexistir dando valor a la sombra del otro.",
			Match: "90%"},
		SharedActivities: SummaryPercentage{
			Text:  "Se podría decir que Tauro es perezoso y Capricornio no para de trabajar, pero no es exactamente así.\n \nSi algún signo del zodíaco necesita descansar, ése es Capricornio.\n \nSu gran ambición puede llevarles a un estado de baja energía y Tauro está ahí para reparar su alma cansada con buena comida y tiempo para la alegría.\n \nPor otro lado, si el lado creativo y motivador de Tauro es despertado por la naturaleza esforzada de su pareja Capricornio, se convertirán en todo menos perezosos y dejarán espacio para que ambos estén satisfechos y felices con lo que han logrado.\n \nEn resumen, pueden hacer cualquier cosa juntos, siempre que mantengan un delicado equilibrio entre actividad y descanso.",
			Match: "85%"},
	},
}
