package compatibilities

var Taurusgemini = Compatibility{
	Name: Taurus + " - " + Gemini,
	Friendship: Friendship{
		Match:   "30%",
		Traits:  []string{PoorAdvisors},
		Summary: "Tauro pertenece a un signo fijo, que indica estabilidad, mientras que Géminis es un signo mutable, que se relaciona con la flexibilidad.\n \nTauro y Géminis podrán estar de acuerdo en muchas ocasiones y siempre de un modo complementario, no porque tengan las mismas ideas ni la misma forma de realizarlas.\n \nIncluso a la hora de la diversión, Tauro y Géminis mostrarán inclinaciones distintas, aunque casi siempre suela triunfar Géminis con la voluntad de Tauro de seguir sus planes, no porque le apetezcan más, simplemente porque sabe que acabarán resultando más divertidos.\n \nPero en ocasiones, esta dualidad de Géminis le hace parecer frío y distante, y esto desconcierta a Tauro que necesita tanta seguridad en su vida.\n \nTauro está a la expectativa mientras Géminis se mueve y resuelve todos los contratiempos.\n \nEl sentido de la amistad puede lograr que Tauro aprenda a cuestionar su mundo, lo que creía inamovible, y que Géminis aprenda a ralentizar su marcha.\n \nLlegados a este punto, la amistad de Tauro y Géminis, será sólida como el acero.",
	},
	Love: Love{
		Match:  "23%",
		Traits: []string{Volatile, NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "La relación entre Tauro y Géminis no es muy prometedora para empezar.\n \nAún así, la cualidad fija del signo de Tauro puede darles suficiente resistencia y persistencia para durar en su intento de estar con un Géminis, lo suficiente para que realmente lleguen a conocerse bien.\n \nAunque sus posibilidades de reconciliar sus diferencias son escasas, si la pareja de Tauro pone todo su corazón en ello, puede que consiga convertirse en la parte más relevante de la vida de su Géminis como su base y su fiabilidad en todo lo que haga.\n \nEn caso de que se acepten completamente, Tauro le dará a Géminis su conexión con el planeta Tierra, con su cuerpo y su rutina diaria, dándole la base para la salud y el funcionamiento normal.\n \nA cambio, Géminis le dará alas a Tauro y, mejor aún, le enseñará a volar.",
			Match: "23%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Tauro es un signo de Tierra sensual con una profunda necesidad de contacto físico y de disfrutar de todos los sentidos del cuerpo.\n \nGéminis necesita estímulos intelectuales y no le importa tanto pasar tiempo en brazos de alguien.\n \nNo es que no tengan la necesidad de ser tocados, todos la tenemos, pero tienen que saber que son amados y aceptados de muchas maneras diferentes y el tacto es sólo una de ellas.\n \nDespués de todo, son uno de los signos de Aire y en su mundo los pensamientos tienen que preocuparse, mientras que una fuerte comunicación es algo que da la posibilidad de una buena vida sexual.\n \nMientras que Tauro podría quedarse en casa, en la cama, todo el tiempo, acurrucándose con su amorcito y pidiendo comida, a Géminis le gustaría salir e intimar en todos los lugares no tan íntimos.\n \nSu vida sexual podría convertirse en la fuente de la mayoría de sus problemas, en cuanto Géminis se aburra o Tauro se moleste por la falta de esencia emocional.",
			Match: "5%"},
		Trust: SummaryPercentage{
			Text:  "La confianza puede ser un verdadero problema con esta pareja.\n \nGéminis no es muy de fiar cuando alguien intenta atarlo.\n \nTauro, en la mayoría de los casos, vive para el día en que se atarán con alguien simultáneamente.\n \nSi no comienzan su relación sobre una base clara y veraz, en la que lo primero que aprendan el uno del otro sea el nivel de compromiso que cada uno desea, surgirá fácilmente un verdadero problema de confianza.\n \nLa pareja de Géminis empezará a pensar en excusas para librarse de cualquier obligación que le imponga Tauro, sólo para evitar herir sus sentimientos.\n \nEn respuesta, Tauro percibirá que algo va mal y empezará a obsesionarse con el comportamiento de su pareja y las cosas que dice.\n \nEsto puede llegar al punto de la desconfianza absoluta entre ambos, especialmente si Tauro se enfada mucho y se pone 'vengativo' en su habitual actitud pasiva y terca.\n \nLas intenciones de Géminis son a menudo malinterpretadas aquí y esto puede llevar a una serie de siguientes situaciones que los perjudicarán a ambos.\n \nEs muy importante que discutan en detalle lo que ambos desean mientras crece su relación.\n \nDe este modo, podrán evitar malentendidos que podrían conducir a una irreparable falta de confianza.",
			Match: "10%"},
		Communication: SummaryPercentage{
			Text:  "Tauro es un signo que precede a Géminis.\n \nEn el sentido astrológico, esto nos dice que el signo de Géminis no existiría si Tauro no estuviera allí.\n \nBásicamente, esto significa que la pareja de Géminis no haría gran cosa si no se atendieran sus necesidades físicas.\n \nAquí es donde su relación tiene una fuerte conexión, ya que la pareja de Géminis podría necesitar a alguien como Tauro para cuidar de su cuerpo y sus necesidades.\n \nEs muy fácil para un signo de Aire como Géminis olvidarse de comer o dormir un par de horas por la noche.\n \nAquí Tauro podría cocinar una comida sana, ocuparse de sus finanzas e insistir en una rutina diaria que daría a su Géminis una buena base energética para invertir en sus ideas.\n \nEn general, sus intereses no son tan similares, pero pueden encontrar la forma de comunicarse, ya que a ninguno de los dos les falta dulzura y facilidad de palabra.\n \nSi la pareja de Géminis decide bajar un poco el ritmo y Tauro se abre, podrían incluso descubrir que es posible que se diviertan juntos.\n \nAl fin y al cabo, están regidos por Venus y Mercurio, dos planetas interiores que, cuando se combinan, se encargan de la diversión, las palabras dulces y el arte de la conversación.",
			Match: "60%"},
		Emotions: SummaryPercentage{
			Text:  "No es muy probable que compartan sus emociones con facilidad y disfruten el uno del otro como podrían hacerlo con algunos otros representantes del zodíaco.\n \nAun así, Tauro tiene un lado amable que puede derretir hasta el más frío de los corazones.\n \nEn la mayoría de los casos, su mejor oportunidad de tener una relación amorosa está en el amor que siente Tauro.\n \nNo diríamos que Géminis es insensible o poco emocional, pero ciertamente tienen un enfoque diferente de su naturaleza emocional que el signo de Tierra de Tauro, que exalta la Luna.\n \nCuando Tauro se enamora de un Géminis, hará cualquier cosa por comprender su naturaleza.\n \nNo hay nada que la naturaleza amable de Tauro no pueda comprender, por muy diferente que sea de su carácter primario personal.\n \nCuando sus Géminis sienten esta comprensión profunda y estable, podrían responder de forma cálida e infantil, aprendiendo que pueden ser libres incluso cuando están enamorados de alguien como Tauro.",
			Match: "35%"},
		Values: SummaryPercentage{
			Text:  "Mientras que Tauro valora la Tierra, el mundo material, sus emociones y lo que es estable en su vida, Géminis valora el Universo, el mundo de las ideas, su mente racional y el cambio.\n \nAquí es donde sus diferencias y sus naturalezas elementales divergen fuertemente.\n \nDeberían esforzarse por aceptar el verdadero valor de ambos mundos para resolver sus diferencias.",
			Match: "1%"},
		SharedActivities: SummaryPercentage{
			Text:  "Podrían encontrar actividades para disfrutar juntos, pero no al mismo ritmo.\n \nA Géminis le gustan las cosas rápidas, a la vez que emocionantes, y a Tauro le gustaría examinarlo todo de principio a fin, valorar cada actividad y decidir a fondo si querría repetirla o no.\n \nEsto volverá loco a su Géminis.\n \nLo mejor para ambos es caminar, mucho, pues esto puede mantener a Géminis con los pies en la tierra, mientras que Tauro siempre necesita movimiento para no acabar en un estado estático, inerte y horizontal.\n \nPodrían conectar sus naturalezas apasionadas a través de algún tipo de arte, sobre todo si logran encontrar la forma de crear algo juntos.\n \nCon las ideas de Géminis y el sentido práctico de Tauro, combinados con la necesidad de belleza, esto debería ser una verdadera obra de arte.",
			Match: "25%"},
	},
}
