package compatibilities

var Tauruslibra = Compatibility{
	Name: Taurus + " - " + Libra,
	Friendship: Friendship{
		Match:   "55%",
		Traits:  []string{NothingReally},
		Summary: "A los signos de Tierra (Tauro) les cuesta entenderse con los de aire (Libra).\n \nSin embargo, en este caso concreto de Tauro y Libra, las cosas suelen ser mucho más fáciles.\n \nEl planeta regente de ambos es Venus y ahí se produce una conexión especial.\n \nAmbos descubrirán enseguida que tienen muchas aficiones comunes y también comparten su inclinación por la buena vida, el amor por la cultura y el arte, además de buena disposición social.\n \nTambién es compartida su generosidad hacia los demás.\n \nSi superan la primera etapa en la que parece que viven en mundos distintos o incluso opuestos, Tauro y Libra, descubrirán este montón de cosas que les unen y podrán disfrutarlas conjuntamente, estableciendo lazos de amistad sólidos y duraderos.\n \nEsta amistad puede aportar grandes beneficios a amos signos.\n \nLibra transmitirá su flexibilidad a Tauro, le mostrará que hay muchos caminos para cualquier objetivo.\n \nPor su parte, Tauro también impregnará a Libra con su determinación, le ayudará a superar sus indecisiones.\n \nJuntos lograrán disfrutar de la vida a lo grande, que es uno de sus deseos primordiales.\n \nSólo deberán controlar que la tendencia a dominar de ambos no mine esta relación que puede ser muy fructífera.",
	},
	Love: Love{
		Match:  "33%",
		Traits: []string{DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "Cuidado Libras, porque Tauro está aquí para despertar tus miedos internos y hacerlos aflorar.\n \nTauro también debe tener cuidado, pues su necesidad de sentir culpa podría florecer con un Libra.\n \nEsta relación es una lección que ambos nunca olvidarán, especialmente si logran construir suficiente comprensión y ternura entre ellos.\n \nLa única forma en que podrían ser felices sería abrazando lo que no quieren tratar en sus propios mundos interiores.\n \nSi lo hacen, ya se pueden imaginar cómo sería una Venus completa.",
			Match: "33%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Ambos signos están regidos por Venus, pero representan sus características completamente diferentes.\n \nMientras que a Tauro le gusta estar cómodo y confía en su sentido del tacto y del gusto, Libra lo querrá todo bonito y confiará en su vista y en el sentido del olfato.\n \nEn cierto modo conectan, pero en la mayoría de los casos tienen este enfoque diferente de Venus como planeta del placer sexual.\n \nPor su parte, Tauro exalta la Luna y Libra exalta a Saturno.\n \nEs como si adoraran cosas opuestas y mientras Tauro cuidará las emociones y la ternura en una relación sexual, Libra confiará en su profundidad y buen momento.\n \nNo les resultará fácil entender lo que quiere la otra persona y ambos podrían acabar pareciendo necesitados el uno del otro: Tauro de Libra por su necesidad emocional y Libra de Tauro por la física.\n \nPor muy diferentes que sean, siguen siendo dos signos regidos por Venus y pueden sentirse bastante atraídos el uno por el otro.\n \nComo signo femenino y masculino, podrían limar sus diferencias e intentar conocer 'el otro lado de Venus' en lugar de esperar lo imposible el uno del otro.\n \nAmbos son amantes amables a los que les gustan las relaciones sin tensiones ni dramas, así que con la suficiente paciencia podrían encajar muy bien.",
			Match: "35%"},
		Trust: SummaryPercentage{
			Text:  "La confianza de Tauro puede verse dañada con la necesidad de Libra de caer bien a todo el mundo, especialmente si no están seguros de si quieren estar con su pareja Tauro en primer lugar.\n \nSi Libra no puede tomar esta decisión básica, la incertidumbre sería un puñetazo para el ego de Tauro y será muy difícil recuperarse después de que se den cuenta de que no son queridos con certeza.\n \nIncluso si son la primera opción de Libra, todavía hay una cuestión de coquetear con tantas otras personas.\n \nCon ejemplares de Libra realmente inseguros, es casi imposible tener una relación de confianza, pues su necesidad de aceptación puede llegar muy lejos e incluso arrastrarlos a la infidelidad.\n \nSu cualidad, sin embargo, está en su visión de la justicia, y rara vez actuarán de acuerdo con sus inseguridades, pero aun así, quién podría estar seguro cuando la vibración es tan inestable, especialmente cuando alguien tan estable como Tauro intenta mezclarse.",
			Match: "30%"},
		Communication: SummaryPercentage{
			Text:  "Estos dos se volverán locos mutuamente.\n \nPor un lado tendríamos a Tauro, que nunca duda de su carácter, nunca se mueve y es irritantemente inmutable.\n \nPor otro, Libra, indeciso y nunca seguro de lo que quiere.\n \nParece imposible que no se pongan de los nervios a diario.\n \nEl principal desafío es la opinión que tienen el uno del otro.\n \nComo dos caras de Venus, estos signos representan a una campesina (Tauro) y a una mujer de ciudad (Libra).\n \nSi combinamos esto con el hecho de que Libra tiene un Sol caído, su problema de ego les haría alimentarse fácilmente de su imagen refinada y citadina y podrían criticar a la 'campesina' por su falta de estilo y su rusticidad.\n \nSimplemente no entienden que el hecho de que a Tauro le gusten las cosas cómodas no siempre se refleja en su falta de estilo y no pueden aceptar las diferencias en su apariencia.\n \nPodría decirse que esto es bastante superficial, pero en realidad se trata de un problema muy profundo de inseguridad.\n \nLibra no critica a Tauro porque sea una buena persona, sino porque teme no serlo.\n \nTauro se sentirá inseguro fácilmente debido a esta visión crítica y se sumergirá en su sentimiento de culpa, casi como si siempre buscara a alguien que despertara la culpa en él, pero sin la capacidad de cambiar y aceptar las críticas como algo constructivo.",
			Match: "5%"},
		Emotions: SummaryPercentage{
			Text:  "Si se atraen lo suficiente podrían enamorarse perdidamente, pero en la mayoría de los casos, ambos son demasiado precavidos para acabar en una relación amorosa.\n \nAunque tanto Tauro como Libra buscan a alguien que los enamore, rara vez tendrán esto el uno con el otro.\n \nPor lo general, Tauro decidirá no dar suficiente espacio para que Libra los descubra, mientras que Libra pasará demasiado tiempo buscando defectos.\n \nComo signos regidos por Venus, ambos se complementan con signos regidos por Marte y normalmente buscan una pareja con iniciativa, para tener un comienzo rápido y excitante y no tener tiempo suficiente para pensar las cosas.",
			Match: "25%"},
		Values: SummaryPercentage{
			Text:  "Venus, su regente, representa el valor en sí mismo, por lo que podríamos decir que valoran las mismas cosas debido a las similitudes mostradas a través de lo que le gusta o no a su regente, pero de diferentes maneras.\n \nPor supuesto que ambos desean el amor verdadero, mágico y místico con Venus exaltado en Piscis, pero Tauro valora la ternura y el tacto en su camino para conseguirlo, mientras que Libra valora la responsabilidad y la seriedad.\n \nSin embargo, sus objetivos finales son los mismos y, sobre todo, valoran la capacidad de una persona para amarla.\n \nEste podría ser su verdadero punto de conexión si se enamoran el uno del otro.",
			Match: "40%"},
		SharedActivities: SummaryPercentage{
			Text:  "No es difícil encontrar actividades para compartir para esta pareja, siempre que no sean aburridas para uno de los dos.\n \nAunque Tauro no tiene por qué ir a matinés y exposiciones de arte sin alma, podrían pasar un rato agradable en una acogedora galería de arte donde se expongan obras en colores cálidos.\n \nLibra rara vez saldrá a pasear por el barro, pero podrían hacer un recorrido por el centro de la ciudad, donde ambos podrían dejarse ver luciendo sus nuevos atuendos.\n \nCon su amor mutuo por las cosas bellas y el amor en general, encontrarán una forma agradable de pasar el tiempo juntos si están lo bastante abiertos como para hacer algunos cambios en su rutina habitual.",
			Match: "65%"},
	},
}
