package compatibilities

var Tauruscancer = Compatibility{
	Name: Taurus + " - " + Cancer,
	Friendship: Friendship{
		Match:   "98%",
		Traits:  []string{GoodRomancePotential, ExcellentAdvisors, DeepMutualUnderstanding},
		Summary: "El elevado grado de compatibilidad que existe entre Tauro y Cáncer les hace merecedores de unos vínculos amistosos excepcionales, algo difícil de conseguir para el temeroso Cáncer, que no entrega su confianza con demasiada facilidad, exceptuando si en su camino se cruza Tauro, que una vez le ha aceptado como amigo perseverará a lo largo de toda su vida.\n \nTauro y Cáncer son de los que creen a pies juntillas que más vale pocos amigos y buenos que muchos que siembren dudas.\n \nCáncer y Tauro también sienten que si muestran espontaneidad están más expuestos a cometer errores.\n \nSin embargo, esta sensación nunca aparece cuando Tauro conoce a un Cáncer o viceversa.\n \nLa confianza mutua entra de lleno con el primer contacto.\n \nTambién se complementan en algunos aspectos, como por ejemplo, el lado terrenal de Tauro se compensa con la vertiente sentimental de Tauro y en una relación de amigos encuentran el equilibrio necesario que tanto necesitan ambos.\n \nCuando Cáncer y Tauro establecen una conexión, ésta se irá afianzando con el paso del tiempo.\n \nCompartirán muchas confidencias y se apoyarán siempre en los momentos difíciles sin hacer ningún reproche ni soltar aquello tan hiriente de ya te lo dije yo”.",
	},
	Love: Love{
		Match:  "91%",
		Traits: []string{Harmonious, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Tauro y Cáncer forman la pareja más dulce del zodíaco.\n \nCuando se enamoran, rara vez encontrarán el motivo para separarse, debido a sus objetivos emocionales compartidos por el amor, la comprensión, la familia y el sentimiento de hogar.\n \nÉsta es la relación que parece un perpetuum mobile del amor, en caso de que ambos miembros de la pareja no tengan ya demasiada carga emocional que les incapacite para dar y recibir esta profundidad de emociones.\n \nIncluso si la tienen, sin obstáculos en el camino, es probable que aprendan a perdonar y olvidar a medida que el flujo de su relación les lleve a lo que siempre desearon.",
			Match: "91%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Alguien podría pensar que Tauro y Cáncer son dos de los signos más asexuales de todo el zodíaco.\n \nSe trata de una suposición instintiva basada en el hecho de que a ambos signos no les interesa mucho Marte, lo que significa que no les interesa el sexo instintivo.\n \nProbablemente nunca tendrían el impulso de mantener relaciones sexuales porque sí, pero esto no significa en ningún caso que sean asexuales.\n \nTauro es el signo del placer físico.\n \nRegido por Venus, el planeta de la sexualidad femenina, Tauro necesita abordar sus experiencias sexuales con la misma meticulosidad con la que abordaría cualquier otra cosa en su vida.\n \nNecesita ver, tocar, oler, sentir todo lo que hay en el cuerpo de su pareja y disfrutar haciéndola sentir satisfecha.\n \nCon la necesidad de cercanía de Cáncer y la falta de habilidad para hacer que su vida sexual sea ligera y despreocupada, Tauro parece tener el toque perfecto para relajarlos y generar confianza dentro de su relación sexual.\n \nCon la falta de Marte viene la falta de iniciativa, y esto podría ser su problema cuando se trata de sexo.\n \nEn caso de que ambos no tengan un impulso sexual más fuerte que su amor por la comida, podrían acabar en una relación asexual, en la que se pasarían el día tumbados en casa, cocinando, comiendo y engordando.",
			Match: "95%"},
		Trust: SummaryPercentage{
			Text:  "Cuando Tauro y Cáncer se enamoran el uno del otro, basan toda su relación en el tacto de su pareja.\n \nNo hay mucho que se pueda ocultar de este sensible, 'sexto' sentido que estos dos pueden compartir cuando se conectan.\n \nSe necesitaría mucho para romper su confianza y esto sin duda significaría el final de su relación.\n \nEn la mayoría de las situaciones, ninguno de ellos tiene necesidad de traicionar a su pareja, porque su objetivo es el mismo: amor, familia y hogar.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Comparten muchos intereses diferentes y hablarán fácilmente de su relación.\n \nNinguno de estos signos habla mucho, pero son perfectamente capaces de entender el silencio del otro y dan a cada palabra mucho significado.\n \nSus temas más comunes incluirían el amor, el hogar y los hijos, excepto cuando no se sienten preparados o cuando son demasiado jóvenes.\n \nSin embargo, es importante comprender que no son los únicos temas en los que piensan.\n \nSean cuales sean sus intereses actuales, lo comunicarán de forma pausada y sensible, llevando la conversación a un punto de profundo entendimiento mutuo.\n \nAun así, Tauro puede ser realmente testarudo en ocasiones.\n \nEn realidad, no importa si tienen razón o no, ya que simplemente se cierran a cualquier conversación posterior en cuanto se toca una de sus verdaderas convicciones.\n \nCáncer no puede hacer mucho cuando esto sucede.\n \nPueden intentar ser más amables y compasivos.\n \nEn caso de que estén cerca de la iluminación, esto sin duda funcionará.\n \nSi no, se pondrán muy emocionales y descubrirán que su pareja Tauro de hecho los vuelve locos.\n \nComo resultado, Tauro verá a su pareja como un auténtico lunático, agitando las manos sin motivo y sin mostrar ningún tipo de comportamiento racional.",
			Match: "80%"},
		Emotions: SummaryPercentage{
			Text:  "Tauro y Cáncer son los regentes de todo el cálido mundo emocional terrenal.\n \nNo se debe sólo a su sensibilidad, sino que la combinación de su expresión emocional es algo casi inimaginable.\n \nMientras Cáncer siente, percibe y cuida de su pareja Tauro en el terreno emocional, Tauro le devolverá el amor a través de la ternura física, la seguridad material y el suave toque de sentido práctico que Cáncer necesita.\n \nCuando este ciclo se repite varias veces, su amor parece una reacción en cadena que nunca dejará de crecer.\n \nSi se encuentran en circunstancias favorables, cuando no necesitan luchar el uno por el otro o por la posibilidad de su amor, cada emoción debería simplemente acumularse sobre la anterior y las cosas entre ellos deberían ir sobre ruedas.\n \nPero si tropiezan con un obstáculo de cualquier tipo, antes de que se desarrolle su amor mutuo, probablemente se desanimarán y nunca descubrirán lo que podrían haber sentido si sólo hubieran luchado el uno por el otro.\n \nSi se enamoran, no les faltará energía para luchar por su relación, sin importar los obstáculos.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Por encima de todo, ambos valoran la vida y la paz.\n \nComo la Luna rige el signo de Cáncer y está exaltada en Tauro, ambos valoran profundamente todo lo que la Luna representa: la familia, la compasión, la comprensión y la felicidad.\n \nSin embargo, puede haber cierta divergencia en su visión del mundo material.\n \nCáncer es un signo de Agua, mucho más centrado en el valor de las emociones, mientras que Tauro se volcará en la seguridad financiera.\n \nEsto suele reflejar el miedo que siente Tauro cuando se trata de que su existencia material esté en entredicho.\n \nA los ojos de Cáncer, esto puede parecer superficial, ya que tienen tendencia a pensar en la realidad material de forma idealista.\n \nSi tienen una familia juntos, estas cuestiones deberían solucionarse, porque el amor de la pareja Cáncer a sus hijos, combinado con su deseo de darles todo lo que necesitan, cambia fácilmente su perspectiva y les enseña el verdadero valor del dinero.",
			Match: "80%"},
		SharedActivities: SummaryPercentage{
			Text:  "Podríamos decir que comparten todas y cada una de las actividades que se les ocurren, pero esto no suele llamarse 'actividad'.\n \nLa mayoría de las veces, y sobre todo si ambos tienen trabajos exigentes, simplemente compartirán la actividad de dormir, comer o no hacer nada.\n \nNo se trata de pereza, sino más bien de una necesidad exagerada del placer del descanso.\n \nCuando se comparte, parece multiplicarse y crecer más allá de las mentes racionales de ambos.",
			Match: "90%"},
	},
}
