package compatibilities

var Taurustaurus = Compatibility{
	Name: Taurus + " - " + Taurus,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{AlmostNothingReally},
		Summary: "Cuando Tauro y Tauro coinciden, la primera impresión ya es agradable y ambos sienten atracción natural hacia el otro nativo de su mismo signo.\n \nIntuyen que es como si se estuvieran viendo a ellos mismos en un espejo.\n \nSus gustos son parecidos y también su carácter, no se puede pedir más.\n \nHan de luchar también con la tendencia de Tauro de querer controlar o imponer al otro su voluntad.\n \nSu lealtad facilitará las cosas en la relación de amistad entre Tauro y Tauro, pero no se verá libre de algunas rencillas cuando uno quiera que se haga su voluntad a toda costa.\n \nTienen que poner ambos Tauro de su parte para que esto no suceda, ya que su terquedad natural es en este caso peligrosa.\n \nNinguno de los dos querrá dar su brazo a torcer y podría ser causa de un alejamiento puntual o incluso de una ruptura definitiva.\n \nSin embargo, Tauro y Tauro son conscientes del valor de una amistad como la suya, y en casi todas las ocasiones lograrán que la sangre no llegue al río.\n \nAunque le cueste mucho, Tauro acabará cediendo para que las aguas vuelvan a su cauce.\n \nTener un amigo incondicional es algo muy cómodo y esto lo valora Tauro muchísimo.",
	},
	Love: Love{
		Match:  "86%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "La relación entre dos representantes de Tauro es algo que apreciar y a lo que aferrarse, sólo si ambos no son demasiado testarudos en su intención de esperar a que la otra persona dé el primer paso.\n \nDebido a su naturaleza emocional y sensual, pueden ser muy atentos a las necesidades del otro y cuidar el uno del otro cuando sea necesario.\n \nSu problema suele manifestarse sólo a través del doble juego de cuernos, lo que les hace hundirse demasiado en sus diferencias sin motivo aparente.\n \nSi pudieran abrirse el uno al otro, y a su mutua necesidad de cambio, ésta es una relación que ambos encontrarían extraordinaria.",
			Match: "86%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Cuando dos parejas Tauro se juntan, el mundo deja de existir tal y como ambos lo conocían antes.\n \nDescubren un placer del sexo que nunca habían tenido la oportunidad de experimentar, ya que comprenden perfectamente la necesidad que tiene el otro del tacto y de la estimulación de todos los sentidos.\n \nEl signo de Tauro es el más sensual de todo el zodíaco, es decir, cuando no les da pereza descubrir su sexualidad.\n \nSi no les falta el impulso sexual primario, probablemente construirán una relación sexual fuerte y suave, en la que ambos tendrán sus necesidades cubiertas.\n \nEl problema que pueden encontrar es la posibilidad de que ninguno de los dos tenga suficiente iniciativa.\n \nAún así, suelen ser lo suficientemente testarudos como para superar este pequeño obstáculo.\n \nDado que comparten fantasías sexuales e ideas sobre la intimidad, con la suficiente franqueza y comunicación deberían ser capaces de superar cualquier obstáculo con el que tropiecen.\n \nEso si no se obstinan en esperar a que la otra persona dé el primer paso.\n \nEsto podría hacer que ambos esperasen eternamente.",
			Match: "95%"},
		Trust: SummaryPercentage{
			Text:  "El problema de sus problemas de confianza no está en la confianza en sí misma, sino en su incapacidad para cambiar.\n \nSi alguno de los dos tiene un historial de relaciones malsanas en las que se sintieron decepcionados y defraudados, les resultará muy difícil restablecer la confianza con su pareja actual.\n \nAmbos pueden entender la importancia de la honestidad, pero a menudo tienen demasiado miedo de abrirse y dejar que alguien se sumerja en su verdadero mundo emocional.\n \nEsto puede llevar a suposiciones ridículas sobre el comportamiento del otro y a cuestionar cada palabra dicha por ambos.\n \nTendrán la mejor oportunidad posible de formar una relación basada en la confianza si no han tenido tanta experiencia antes de juntarse.\n \nEsto les permitirá la flexibilidad suficiente para sentar unas buenas bases y respetar la necesidad de intimidad del otro sin confundirla con un engaño.",
			Match: "75%"},
		Communication: SummaryPercentage{
			Text:  "Aunque estas parejas comparten muchos intereses y tienen una forma similar de funcionar, cuando se aferran a sus convicciones rara vez deciden dejarlas de lado ni por un segundo.\n \nAl fin y al cabo, ambos tienen cuernos y tendencia a cruzárselos en cuanto uno de los dos se sale del flujo habitual de las cosas.\n \nA Tauro no le resulta fácil aceptar los cambios, así que cuando uno de los dos se encuentra a las puertas de un gran cambio, es fácil que acaben enzarzados en una pelea.\n \nLa pareja que está estancada en un lugar tiene dificultades para entender por qué las cosas no pueden seguir igual, para siempre.\n \nSerá muy difícil explicarles cuánta presión debe haber sentido en primer lugar la persona que está haciendo un cambio para entender que éste es necesario.\n \nPueden ser testarudos y cerrarse a cualquier tipo de contacto emocional, especialmente cuando se enfadan o alguien les hace daño.\n \nEsta es la razón principal por la que su comunicación no es tan buena a veces, ya que a ambos les cuesta abrirse y vivir el momento, sin miedo a que les hagan daño.\n \nEl problema aquí no es el miedo en sí, otros signos también pueden sentirlo, sino la falta de conciencia de que este miedo existe.\n \n",
			Match: "50%"},
		Emotions: SummaryPercentage{
			Text:  "El signo de Tauro es un signo de Tierra en el que la Luna, regente de todas nuestras emociones, está exaltada.\n \nEl propio signo está regido por Venus, que nos informa de su equilibrio y de una contribución a la manifestación material de todas las emociones procedentes de la Luna.\n \nEste es un círculo interminable, como un sistema de la Tierra siendo circundada por la Luna, una y otra vez, mes tras mes.Hay una naturaleza fija e inmutable en este movimiento y esto es algo con lo que el signo de Tauro vive y siente cada día.\n \nCuando dos parejas de Tauro se unen y en caso de que ninguna de ellas tenga el corazón cerrado, existe una profunda comprensión emocional que pueden compartir.\n \nEsto puede ser muy gratificante para ambos, ya que ambos pueden sentir las necesidades de su pareja y ser capaces de cuidar el uno del otro, mientras disfrutan del hecho de que esta vez ellos también son cuidados.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Es curioso hablar del sistema de valores cuando hablamos de Tauro.\n \nEste es un signo que representa todo el valor y retiene en sí mismo el precio de todo en este mundo.\n \nLo que una pareja de Tauro valora es principalmente el respeto de alguien hacia el valor en sí.\n \nYa sea el valor financiero de cualquier objeto en su entorno o el valor de ser amado, la conciencia de que es algo que consideran imperativo para su pareja a tener.\n \nDos Tauro en una relación valoran juntos los valores y sólo puede surgir un conflicto si asignan valores diferentes a cosas diferentes.Aun así, en la mayoría de los casos, se darán suficiente espacio para establecer una lista individual de prioridades y llegar a un compromiso si algunas cosas son más valiosas para uno de ellos que para el otro.",
			Match: "95%"},
		SharedActivities: SummaryPercentage{
			Text:  "No sólo comerán y dormirán juntos, sino que también sentirán mucha alegría por el hecho de tener por fin a alguien con quien hacer estas cosas, sin sentimiento de culpa. El principal problema es que podrían descuidar fácilmente las necesidades de su cuerpo físico para llevar un estilo de vida y una actividad saludables. Se necesita mucho autocontrol para que se mantengan juntos y no adquieran sobrepeso o simplemente se vuelvan demasiado perezosos.",
			Match: "99%"},
	},
}
