package compatibilities

var Tauruspisces = Compatibility{
	Name: Taurus + " - " + Pisces,
	Friendship: Friendship{
		Match:   "85%",
		Traits:  []string{DeepMutualUnderstanding, ExcellentAdvisors},
		Summary: "Tauro y Piscis suelen formar lazos sólidos de amistad.\n \nLa lealtad de ambos signos hace que si inician este recorrido intenten mantenerlo por todos los medios con el paso del tiempo.\n \nPese a las diferencias evidentes de sus signos, Tauro y Piscis están destinados a comprenderse, apoyarse y aprobar siempre cualquier propuesta que haga uno de ellos.\n \nPor supuesto también existen algunas diferencias que se manifiestan más marcadas si la amistad dura muchos años, simplemente por una cuestión de confianza, pero nunca pensarán en serio en alejarse de su amigo.\n \nEl etéreo Piscis, que suele idealizar a las personas que le atraen, también lo hará con Tauro y mucho más si éste manifiesta ya tendencia a querer compartir esta amistad.\n \nLa entrega de Piscis a esta persona, a quien encontrará todas las gracias posibles, sorprenderá agradablemente a Tauro, quien valora mucho el afecto de quienes le rodean.\n \nTauro, por su parte, le ofrecerá a Piscis su solidez y su forma pausada de hacer las cosas, aspectos que cautivarán a Piscis ya que carece de estos aspectos tan positivos.\n \nSerán amigos leales de por vida y sin complicaciones si ponen atención en dominar esos celos bastante absurdos que asaltan a ambos de vez en cuando.",
	},
	Love: Love{
		Match:  "88%",
		Traits: []string{GreatSexualChemistry, Harmonious},
		Summary: SummaryPercentage{
			Text:  "Esta es una relación basada en el amor y llena de él mientras dura.\n \nAmbos anhelan el romance y la belleza en sus vidas, y harán todo lo que sea necesario para mantener la belleza entre ellos.\n \nTauro dará a su pareja Piscis la oportunidad de conectar con el mundo real, mostrándole cómo enraizar su creatividad, mientras que Piscis elevará a Tauro y le hará un poco más suave y flexible.\n \nParece que tienen la misión de convencerles de que el amor verdadero existe.\n \nCuando su relación se acabe, ambos lo sabrán al instante y muy a menudo una conversación sobre la ruptura sería redundante.\n \nSi saborean su confianza y cultivan la belleza del amor que comparten, su relación puede durar y ser tan inspiradora como un sueño hecho realidad.",
			Match: "88%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Tauro y Piscis tienen que ver con el placer.\n \nTauro representa el arte de hacer el amor, la ternura y la sensualidad.\n \nEl signo de Piscis es la culminación de un encuentro sexual: el orgasmo.\n \nEste es un lugar donde Venus está exaltado, mágico, misterioso e increíblemente satisfactorio para el regente de Tauro.\n \nTienen la capacidad de perderse el uno en el otro, hacer realidad sus sueños y satisfacerse mutuamente por pura existencia.\n \nCuando se trata de sexo, Tauro puede acabar fácilmente en la rutina si su pareja no es lo bastante inspiradora o creativa.\n \nLos Piscis, en cambio, se pierden en las experiencias sexuales, e incluso pueden considerarlas tóxicas si sus impresiones sobre otras personas son poco realistas.\n \nCuando conocen a la pareja Tauro adecuada, pueden sentirse intrigados y aliviados por su naturaleza, ya que lo que ven es realmente lo que obtienen.\n \nDebido a la naturaleza emocional del signo de Piscis y a su profundo sentido del propósito, Tauro se sentirá amado hasta el punto de perderse en la sexualidad de su pareja.\n \nAmbos prestarán muy poca atención a su propio placer debido a todos esos sentimientos que los guían.\n \nEsta es casi siempre una relación de entrega en la que ambos miembros de la pareja se sienten igualmente satisfechos en lo que respecta al sexo.",
			Match: "99%"},
		Trust: SummaryPercentage{
			Text:  "Debido a la tendencia de los Piscis a entrar en cada relación con un enfoque idealista, es muy probable que se abran a su pareja Tauro en cuanto se den cuenta de lo estables y seguros que parecen.\n \nLa belleza de su contacto radica en que, cuando están juntos, ambos pierden la necesidad de ocultarse y dejan que sus emociones crezcan con facilidad.\n \nEl signo de Piscis es un signo de cualidad mutable, y pueden cambiar inesperadamente, sin una razón clara.\n \nSi esto ocurre, Tauro sabrá que la confianza se ha perdido, por mucho que su relación pareciera hace tan sólo un par de minutos.\n \nEs una profunda sensación de intimidad rota, perdida en la necesidad de regocijo emocional de Piscis.\n \nBásicamente, cuando la pareja Piscis se aburre, empieza a pensar en excusas y mentiras, antes incluso de darse cuenta de que su relación ha terminado.\n \nCorresponde a Tauro comprender la flaqueza de su pareja.\n \nCuando lo hacen, pueden aceptar la situación y luchar por el amor, o poner fin a la relación y seguir adelante.",
			Match: "80%"},
		Communication: SummaryPercentage{
			Text:  "Tauro y Piscis probablemente no tendrán necesidad de hablar mucho.\n \nEn cambio, se entenderán a través de todo tipo de comunicación no verbal, sintiendo curiosidad por el próximo movimiento del otro.\n \nLa sutileza de Piscis es algo realmente inspirador para Tauro y sentirán la necesidad de conocer cada detalle del comportamiento de su pareja.\n \nEstos dos signos no son muy habladores y Piscis incluso llevó a Mercurio a su caída.\n \nEs por eso que realmente necesitan formar un fuerte vínculo emocional y escucharse a través de muy pocas palabras.\n \nEse campo de talento y energía creativa que lleva Piscis va bien con la necesidad de belleza de Tauro.\n \nPor desgracia, pueden perderse en el mundo de Piscis y perder realmente el control que tienen de la realidad.\n \nAl principio, esto será como una droga, una adicción, algo que han estado esperando toda su vida.\n \nCon el paso del tiempo, la sensación no será tan buena, porque perderán el contacto consigo mismos y tendrán la sensación de que ya no saben quiénes son.\n \nLo más importante para Tauro en una relación con Piscis es mantenerse firme y aferrarse a su sentido común, su sentido práctico y su habitual necesidad de vivir en la realidad.",
			Match: "95%"},
		Emotions: SummaryPercentage{
			Text:  "Tauro y Piscis tienen una conexión emocional mágica.\n \nMientras Piscis no cambie de opinión y se marche nadando, su relación debería estar llena de amor y asombro.\n \nCon Piscis exaltando a Venus, el regente de Tauro, no se trata sólo de amor, sino de adoración.\n \nTauro se sentirá, por mucho tiempo, como el centro del mundo de alguien, amado y apreciado hasta el punto de una belleza insoportable.\n \nSi este sentimiento perdura, podrían permanecer en una hermosa relación durante mucho tiempo.\n \nTan pronto como la pareja Piscis sienta que esta hermosa emoción se apaga, hará una maniobra espontánea para distanciarse de su pareja Tauro.\n \nLo curioso es que en la mayoría de los casos Tauro no se sentirá herido en absoluto.\n \nEse simple sentimiento de inadecuación será suficiente para que ambos dejen que la distancia siga su curso.\n \nAunque Tauro tiene tendencia a atarse emocionalmente a su pareja, su posible separación de Piscis será como una vuelta a la realidad más que un acontecimiento devastador.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Tauro se vuelca en la realidad material y Piscis en la emocional.\n \nSus valores difieren mucho, pero el que comparten es incomparable a los demás: el amor.\n \nNingún otro signo del zodiaco puede entender realmente la forma en que estos dos valoran el amor, especialmente cuando están enamorados el uno del otro.",
			Match: "85%"},
		SharedActivities: SummaryPercentage{
			Text:  "El principal problema con el que se toparán estos signos es que Tauro es un signo fijo y Piscis mutable.\n \nEsto puede llevar a una falta de entendimiento cuando se trata de la forma en que quieren pasar su tiempo juntos.\n \nAl principio, disfrutarán de las mismas cosas, pero la pareja de Piscis se aburrirá muy pronto si el escenario no cambia.\n \nNo es propio de ellos permanecer demasiado tiempo en un mismo lugar.\n \nCuando Tauro se encuentre en una situación hermosa, querrá quedarse en ella para siempre, aferrándose a la primera imagen aunque su belleza se desvanezca.\n \nEsto ralentizará todo movimiento y podría molestar mucho a su pareja Piscis.",
			Match: "70%"},
	},
}
