package compatibilities

var Taurusscorpio = Compatibility{
	Name: Taurus + " - " + Scorpio,
	Friendship: Friendship{
		Match:   "80%",
		Traits:  []string{GoodRomancePotential, ExcellentAdvisors},
		Summary: "Aunque de entrada puede que exista cierta desconfianza entre Tauro y Escorpio, muy pronto ambos percibirán que en la otra persona concuerdan aspectos que les son absolutamente complementarios.\n \nSus lazos de amistad se basan en el conocimiento mutuo, que puede durar algún tiempo.\n \nSu intuición les señalará que aunque parezcan tan distintos, algo intangible los une y pocas veces Tauro y Escorpio dejarán de intentar este conocimiento más profundo de la otra persona.\n \nCuanto más se conocen, más se admiran y no regatean elogios para el otro signo.\n \nEscorpio encuentra en Tauro el aliado perfecto para todas sus incursiones.\n \nEl sociable Tauro jamás tiene un “no” para su amigo, sea cual sea la propuesta.\n \nEl punto más débil de la relación de amistad entre Tauro y Escorpio, es el afán de dominio del primero.\n \nSin embargo, la comprensión de Escorpio puede lograr reconducir estos intentos hasta llegar a un consenso en el que su relación se anteponga a todo lo que podría destruirla.\n \nPor lo demás, ambos son amigos leales y fieles que podrán confiar ciegamente el uno y el otro sin que nunca asome ninguna sombra de traición.",
	},
	Love: Love{
		Match:  "89%",
		Traits: []string{NaturalPartners, GreatSexualChemistry},
		Summary: SummaryPercentage{
			Text:  "Tauro y Escorpio son los dos signos del placer físico más profundo, cada uno a su manera.\n \nEste tiene que ser el centro de su relación, ya que no parecen entender las relaciones platónicas e imaginativas cuando se juntan.\n \nNo existe una experiencia romántica platónica, cuando el objetivo del romance es el placer físico.\n \nEs muy posible que construyan su vida sexual hasta el punto de que ninguna otra pareja pueda satisfacer sus necesidades.\n \nEsto podría llevarles a una relación posesiva sin salida, aunque probablemente no querrían salir aunque pudieran.\n \nToda la experiencia puede resultar demasiado oscura para la pareja de Tauro, sobre todo si su sentido práctico se ve desafiado por el carácter de Escorpio.\n \nEn caso de que ambos sean independientes y estén dispuestos a mezclarse con otra persona, podrían ser la conexión perfecta entre lo sexual y lo emocional, la que todos deseamos.",
			Match: "89%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Como todos los signos opuestos, Tauro y Escorpio pueden sentirse locamente atraídos el uno por el otro.\n \nSu relación es una conexión de emociones profundas y sexualidad que ninguna otra pareja del zodíaco tiene el privilegio de tener.\n \nEscorpio tiene esta necesidad depresiva de morir desnudo y sudoroso en los brazos de un ser querido, mientras que Tauro tiene la necesidad de ser amado tanto.\n \nPuede sonar incluso romántico, pero lleva consigo todos los problemas emocionales no resueltos como equipaje en sus encuentros sexuales.\n \nEsto no significa que su vida sexual vaya a ser mala.\n \nAl contrario, ambos la encontrarán fantástica, porque la llenarán de todo tipo de emociones, buenas o malas.\n \nAl final, la emoción será lo único que quede y el sexo será una forma de conectar más que un medio para la satisfacción personal.\n \n Como signos de cualidad fija, cuando hacen clic es imposible separarlos, y nadie querría hacerlo si se tiene en cuenta la posible venganza de Escorpio.\n \nSignifican una relación profundamente íntima y una vida sexual muy rica, siempre que Escorpio sea lo bastante tierno y Tauro esté dispuesto a experimentar.",
			Match: "95%"},
		Trust: SummaryPercentage{
			Text:  "Escorpio rara vez confía en nadie más que en sí mismo de forma incondicional y en una relación con Tauro necesita reforzar la sensación de seguridad.\n \nNo diríamos exactamente que Escorpio es inseguro, pero su profunda naturaleza emocional les hace cuestionar los motivos de todo el mundo con precaución para no salir heridos.\n \nExiste una delgada línea entre dos posibilidades en una relación de Tauro y Escorpio.\n \nLa primera posibilidad sería aquella en la que la pareja de Tauro es realmente cerrada, inalcanzable y demasiado callada.\n \nEsto podría despertar la naturaleza sospechosa de Escorpio y sus interrogatorios obsesivos dañarán su confianza mutua aún más de lo que carecían en primer lugar.\n \nLa segunda opción sería que la pareja de Tauro se abriera lo suficiente como para compartir lo que Escorpio necesita oír.\n \nSi logran encontrar este delicado equilibrio, no deberían tener ningún problema.\n \nA medida que intimen más y más, Tauro se sentirá lo bastante seguro como para compartir todo lo que Escorpio quiera saber y Escorpio se dará cuenta de que su estable e inmutable Tauro no le decepcionará.",
			Match: "80%"},
		Communication: SummaryPercentage{
			Text:  "Como todos los signos opuestos, parecen completamente diferentes y como si no tuvieran nada en común.\n \nAun así, debemos tener en cuenta que los signos opuestos se complementan a la perfección y su comunicación debería ser emocionante, desafiante y algo de lo que disfrutar si ambos tienen la suficiente confianza.\n \nMientras que Escorpio profundizaría en todas esas cosas que a Tauro no parecen importarle, podría sorprenderse mucho al descubrir que detrás de la naturaleza tierna y viva de Tauro, hay una profunda comprensión de todo lo natural que sucede, por muy oscuro que parezca.\n \nA cambio, Escorpio mostrará a Tauro el valor de la vida desde su perspectiva.\n \nA Tauro le parecerá increíble cómo Escorpio, siendo un signo de muerte y destrucción, puede comprender la profundidad de la vida y las emociones mejor que cualquier otro signo del zodíaco.",
			Match: "75%"},
		Emotions: SummaryPercentage{
			Text:  "Esta conexión emocional es realmente algo que merecer.\n \nEstos dos no sólo representan el eje de las dignidades especiales de Luna, exaltada en Tauro y caída en Escorpio, sino que también tienen a Venus como regente por un lado y al intenso elemento del Agua por el otro.\n \nCuando se enamoran, se convierten en la imagen del amor eterno.\n \nNo hay mejor personificación de Had, el dios del inframundo en la antigua Grecia, y Perséfone: una idea del amor inmortal que nunca puede morir.",
			Match: "99%"},
		Values: SummaryPercentage{
			Text:  "Valoran la vida y el amor como ningún otro signo.\n \nLa profundidad de su sistema de creencias llega hasta el núcleo del planeta Tierra y si comienzan su relación en la misma página, esto podría ser lo que les una durante años.\n \nAunque sus perspectivas difieren en cuanto a valores materiales y emocionales, su núcleo es el mismo y todo lo demás puede ajustarse.",
			Match: "99%"},
		SharedActivities: SummaryPercentage{
			Text:  "Aunque Escorpio es un signo de cambio, esto no significa que no sean muy lentos en su rutina diaria.\n \nComo signo fijo, son, al igual que Tauro, estáticos e inertes.\n \nHay mucha energía en Escorpio, la energía nuclear reside en su signo, pero cuando se trata de la vida cotidiana, tienden a repetir patrones y a mezclarse con lo que la mayoría de los demás consideran 'normal'.\n \nSin embargo, de vez en cuando necesitan experiencias nuevas, emocionantes e impresionantes, pero no les importaría vivirlas a solas si su pareja Tauro no está interesada.\n \nDe todas las actividades posibles, compartirán sobre todo las sexuales y todas las experiencias de placer físico.\n \nAmbos disfrutarán descubriendo hasta dónde puede llevarles su deseo sexual y esto les mantendrá ocupados la mayor parte del tiempo.",
			Match: "85%"},
	},
}
