package compatibilities

var Taurusaquarius = Compatibility{
	Name: Taurus + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "65%",
		Traits:  []string{CautionRomance},
		Summary: "Las relaciones de amistad entre Tauro y Acuario suelen ser también muy complejas, aunque depende mucho de los intereses comunes y de algunas apetencias que compartan, que pueda prosperar.\n \nNo todo van a ser dificultades, entre Tauro y Acuario también hay puntos en común que pueden lograr que ambos compartan ciertas inclinaciones y similar forma de ver las cosas.\n \nAcuario valora mucho la amistad y esto siempre será un aspecto muy positivo, porque Tauro sabrá apreciar el gesto de su amigo, que siendo tan diferente puede llegar a mostrarse tan cercano.\n \nAcuario suele ser también muy sociable y esto abre las puertas a Tauro que no pertenece a sus signos más afines pero que es aceptado como si lo fuera.\n \nUna vez iniciada la amistad, ya se encargarán ambos de encontrar más puntos en común, porque en realidad se van a sentir cómodos y éste es un aspecto muy valorado por Tauro.\n \nLa lealtad de Tauro también impresiona favorablemente a Acuario, que percibe claramente que como amigo podrá contar con él para lo que necesite.\n \nTauro y Acuario podrán ser amigos, incluso íntimos, durante largo tiempo si Tauro cede un poco en su deseo de acaparar los afectos, actitud que haría sentir a Acuario como prisionero de su amistad.",
	},
	Love: Love{
		Match:  "11%",
		Traits: []string{DeepMutualUnderstanding, Volatile},
		Summary: SummaryPercentage{
			Text:  "Tauro y Acuario son personas de dos mundos diferentes.\n \nSin embargo, existe una extraña similitud y conexión entre sus regentes y, aunque muy desafiante, se trata de una relación en la que ambos miembros de la pareja podrían enamorarse el uno del otro, una y otra vez, todos los días.\n \nEstán regidos por Venus y Urano, planetas que giran en dirección opuesta a la de otros planetas.\n \nSon dos marginados, diferentes y que destacan juntos, entienden que Oriente puede estar donde está Occidente, y viceversa.\n \nEntienden la diversidad, el cambio de dirección y la emoción del amor.\n \nSin embargo, rara vez llegarán a entenderse debido a su excesiva necesidad de paz (Tauro) y excitación (Acuario).\n \nQué extraña pareja la de estos signos.\n \nCon una oportunidad tan obvia para el amor eléctrico, le dan la vuelta y buscan otra cosa.",
			Match: "11%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La naturaleza lenta, tierna y suave de Tauro se verá ridículamente molesta por la naturaleza cambiante e inusual de Acuario.\n \nEn la mayoría de los casos, ni siquiera se sienten atraídos el uno por el otro y se consideran aburridos o locos, según la situación.\n \nSin embargo, realmente podrían ayudarse mutuamente a florecer si se abrieran a la posibilidad de encuentros sexuales inusuales.\n \nSi la ternura de Tauro se proyecta en su independiente y distante pareja Acuario, su lado creativo y motivador se despertaría, dando energía y velocidad al productivo lado amable de Tauro.\n \nImagina la vida sexual que podrían tener, diferentes el uno del otro, dos marginados, si sólo compartieran el respeto y la emoción suficientes.\n \nRara vez llegarán tan lejos, pues para empezar parecen buscar cosas distintas en una relación.\n \nA Tauro le gustaría tener una pareja segura e inquebrantable y Acuario quiere estar libre de cualquier atadura a este mundo, y mucho menos a las relaciones emocionales.\n \nNo les resultará fácil limar estas diferencias o mantenerlas al margen de su vida sexual, porque no se sentirían ellos mismos en una relación en la que se desatendieran sus necesidades primarias.",
			Match: "15%"},
		Trust: SummaryPercentage{
			Text:  "Si Tauro no estuviera tan estresado por su pareja Acuario, podría decidirse a ser sincero y honesto.\n \nAcuario no entiende realmente la actitud que tiene Tauro y menos su miedo a no ser lo suficientemente bueno.\n \nLa culpa y la autocrítica es el rasgo más difícil de Tauro, y del que Acuario se libra, encontrándolo obsoleto.\n \nEsta estricta opinión de Acuario asustará a Tauro hasta el punto de que sienta que es imposible decir lo que siente.\n \nEsto terminará en un círculo de mentiras y desconfianza irreparable.\n \nNo parece haber flexibilidad en una pareja Acuario, aunque tienden a mostrar una naturaleza tan abierta a las diferencias de las personas.\n \nCon el fin de construir la confianza sutil, Tauro necesita ser valiente y dejar de pensar en las consecuencias de todo lo que dicen, mientras que Acuario necesita dejar de lado su actitud justiciera y tener cuidado con la forma en que su pareja Tauro se siente en su presencia.",
			Match: "20%"},
		Communication: SummaryPercentage{
			Text:  "Como contacto de los elementos Tierra y Aire, pueden estar tan alejados que no encuentren nada de qué hablar.\n \nEsto no sería un problema per se, pero a veces el estrecho de miras Tauro no ve exactamente las verdaderas posibilidades del mundo material y puede derribar a su pareja Acuario hasta el punto de que no ven cómo cualquiera de sus sueños es posible.\n \nSi Tauro se muestra comprensivo con la necesidad de volar de su pareja, podría ayudarla a materializar sus sueños.\n \nEsto no sucede a menudo, ya que Acuario rara vez encuentra a Tauro como una persona con quien hablar, lento y aburrido con una actitud de 'pueblo pequeño' que inhibe el progreso de nuestra civilización.\n \nSus diferencias son difíciles de conciliar y cuando se enamoran, cualquier nimiedad puede convertirse en un gran problema y en un motivo para que ambos piensen en poner fin a la relación.\n \nSi Tauro quiere ir a pie, Acuario quiere comprar un billete de avión.\n \nEn general, pueden descubrir que no están hechos exactamente el uno para el otro, a menos que ambos tengan la suficiente flexibilidad para comprender la diferencia última de los demás, y la suficiente apertura para hacer cosas que no les importan sólo para ver si al final les gustan.",
			Match: "10%"},
		Emotions: SummaryPercentage{
			Text:  "Tienen suerte de que el signo de Acuario levante los ánimos de Venus, o no tendrían ninguna oportunidad.\n \nTauro rara vez se enamoran de un Acuario debido al hecho de que no reconocen su gobernante en un buen contexto.\n \nAcuario es lo suficientemente distante como es, y sin la emoción que algunos otros signos podrían ofrecer, no sentirán exactamente la electricidad de estar enamorados de un Tauro inamovible.\n \nSin embargo, ambos podrían dejarse engañar por el término medio entre ambos.\n \nSi Tauro ve el lado estable y saturnino de Acuario, y Acuario reconoce al niño interior de su pareja Tauro, podrían descubrir que sí son el uno para el otro, aunque esto vaya contra todo pronóstico.",
			Match: "15%"},
		Values: SummaryPercentage{
			Text:  "Mientras que Tauro valora las cosas materiales y el comportamiento con los pies en la tierra, Acuario valora la libertad en cualquiera de sus formas.\n \nUno quiere estar atado y el otro quiere volar.\n \nRealmente no hay mucho que puedan hacer, sino aceptar las diferencias de sus objetivos y naturalezas, ya que hay verdad y bien en ambos enfoques de la vida.\n \nPueden encontrar ciertas cosas que valorar juntos, si ponen su mente en crearlas a través del campo de ideas de Acuario y las realizaciones prácticas de Tauro.",
			Match: "1%"},
		SharedActivities: SummaryPercentage{
			Text:  "Durante un breve espacio de tiempo podrían hacer muchas cosas bonitas juntos.\n \nUna vez gastados los recursos de Tauro, no habrá mucho más que quieran hacer juntos.\n \nPor 'recursos' no nos referimos necesariamente al dinero, sino a la energía general para la acción.\n \nTauro visitará con gusto un lugar extraño en el que nunca ha estado, pero después querrá volver a casa y disfrutar de una buena cena.\n \nAcuario no tiene esta necesidad y quiere estar siempre en movimiento.\n \nPodrían cuidarse gracias a los esfuerzos de su pareja Tauro, si tuvieran la paciencia suficiente para mantenerlos bien alimentados, vestidos con ropa limpia y se ocuparan de las actividades domésticas.\n \nAún así, este compromiso es raro de encontrar, porque la satisfacción emocional que la pareja Tauro obtendrá a cambio no es suficiente.",
			Match: "5%"},
	},
}
