package compatibilities

var Virgoscorpio = Compatibility{
	Name: Virgo + " - " + Scorpio,
	Friendship: Friendship{
		Match:   "90%",
		Traits:  []string{ExcellentAdvisors, DeepMutualUnderstanding},
		Summary: "Virgo y Escorpio experimentarán un profundo bienestar en su relación mutua y sentarán las bases de una profunda y duradera amistad.\n \nCoinciden en un aspecto básico que será determinante.\n \nNi a Virgo ni a Escorpio les atrae demasiado la idea de formar parte de un grupo de amigos numeroso ni de realizar constantemente fiestas, salidas o viajes.\n \nVirgo y Escorpio no necesitan rodearse de una multitud para divertirse.\n \nSe lo pueden pasar fantásticamente bien sin necesidad de otras personas.\n \nAmbos prefieren un estilo de amistad más sobrio y no necesitarán explicárselo mutuamente con palabras.\n \nLo sabrán por instinto.\n \nAlgunas veces, la timidez de Virgo le impide lanzarse a probar alguna actividad que podría satisfacerle, pero si tiene al lado a Escorpio, puede llegar a objetivos que solo no se atrevería.\n \nLes une también el sentimiento solidario que ambos experimentan.\n \nLes gusta ayudar a los demás y no es poco frecuente verles embarcados en actividades caritativas.\n \nEl talento innato de Virgo para las cuestiones relacionadas con un estilo de vida saludable, encontrarán terreno abonado en Escorpio, a quien le interesa mucho esta temática aunque no llega a dominarla.",
	},
	Love: Love{
		Match:  "76%",
		Traits: []string{Harmonious, GoodWorkCombination},
		Summary: SummaryPercentage{
			Text:  "La naturaleza cambiante de Virgo se verá compensada por la cualidad fija de su pareja Escorpio, que mantendrá su relación excitante durante mucho tiempo.\n \nEn general, estas parejas comparten un problema en relación con Venus, y su relación suele ser un reflejo de estos problemas.\n \nEsto puede dar lugar a todo tipo de chantajes emocionales, a su tendencia a controlar la vida del otro y, si no es esto, a constantes críticas que hacen que ambos se sientan culpables o simplemente tristes.\n \nLo mejor que pueden hacer es decidir que se valorarán y se agradecerán mutuamente en esta relación.\n \nSi desarrollan un fuerte sentido de la gratitud, su relación podría ser extremadamente profunda, emocionante y verdaderamente apreciada por ambos miembros de la pareja.",
			Match: "76%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Aunque Escorpio puede ser demasiado duro con Virgo, haciéndole sentir incómodo e incluso violado en cierto modo, en la mayoría de las relaciones entre representantes de estos dos signos, hay suficiente racionalidad en el enfoque de Virgo para hacer posible este contacto.\n \nLo que a menudo no comprendemos es el hecho de que Escorpio es un signo de Agua y, como tal, profundamente emocional.\n \nVirgo busca a alguien emocional con quien compartir una vida, y si comparten esta emoción de Escorpio a través de sus relaciones sexuales, ambos encontrarán el sexo entre ellos extremadamente satisfactorio.\n \nEl mejor momento para que Virgo y Escorpio creen suficiente seguridad y emoción en sus encuentros sexuales, es en la situación en la que son la primera experiencia verdaderamente emocional del otro.\n \nSi se sorprenden mutuamente con el poder de las emociones bajo la superficie, que ambos parecen llevar consigo, les costará mucho separarse el uno del otro.\n \nEl mayor problema de estas parejas está en su relación con Venus, y esto puede llevar a actos sexuales sin amor con los que ambos no estén realmente satisfechos.\n \nNecesitan mostrar amor y ser lo suficientemente tiernos, disfrutando lo suficiente, o puede que tengan que pasar a otra persona a la que quieran más.",
			Match: "65%"},
		Trust: SummaryPercentage{
			Text:  "La confianza es un tema muy difícil para estos dos signos y es algo de lo que por fin pueden hablar entre ellos.\n \nExiste una gran comprensión entre ellos, ya que uno teme la traición por encima de todo, mientras que el otro la odia y se vuelve vengativo en cuanto ve cualquier signo de deshonestidad.\n \nLo mejor de su conexión es su capacidad para entenderse en silencio, sin querer decepcionarse nunca el uno al otro.",
			Match: "90%"},
		Communication: SummaryPercentage{
			Text:  "Virgo es un signo hablador, regido por Mercurio, el planeta de la comunicación, pero ellos se aferran a un lado de Mercurio mucho más tranquilo e intelectual de lo que podríamos anticipar.\n \nEscorpio representa el silencio profundo de la corriente de un río, y ambos tendrán un fuerte impulso de saltar juntos a las profundidades del silencio.\n \nSu contacto intelectual es estimulante, y a menudo influye mucho en su vida sexual y en sus emociones verdaderamente profundas.\n \nEs casi como si no pudieran formar una relación sin esta capacidad de comunicación no verbal que les hace perfectos el uno para el otro.\n \nAmbos signos están dispuestos a llegar hasta el final: Virgo en su profundidad intelectual y Escorpio en todo en la vida.\n \nEsto inspirará a ambos a buscar juntos todo tipo de respuestas, analizando la psique del otro y determinando el origen de sus problemas con el mundo, o entre ellos.\n \nA través de palabras cuidadosamente elegidas, pueden ayudarse mutuamente a sanar o regenerarse de experiencias difíciles o incluso devastadoras.\n \nEs bueno que estos dos signos se tengan el uno al otro en los momentos de necesidad.",
			Match: "99%"},
		Emotions: SummaryPercentage{
			Text:  "Si alguien puede llegar a las emociones ocultas tras el enfoque extremadamente racional de Virgo, ése es Escorpio.\n \nPodríamos decir que esta capacidad se esconde en ambos y que el desentierro va en ambos sentidos.\n \nEl problema aquí está en el hecho de que se recuerdan mutuamente sus imperfecciones.\n \nEscorpio es un signo en el que cae la Luna y al mismo tiempo el signo del detrimento de Venus.\n \nTodas las emociones se pierden aquí, como si Escorpio fuera un agujero negro que no da abasto.\n \nLa pareja de Virgo ya es sensible y, cuando está enamorada, hace todo lo posible por satisfacer a su pareja de Escorpio.\n \nEsto puede sentirse como invertir en un agujero negro sin ningún tipo de gratitud.\n \nAún así, no hay otro signo que pueda sentir las necesidades de Escorpio mejor que Virgo, ni otro signo que pueda desenterrar las emociones de Virgo mejor que Escorpio.\n \nUna relación emocional entre ellos puede resultar realmente oscura y difícil, pero también increíblemente fuerte e íntima.\n \nLo único que puede llegar a aburrir sus emociones es la crítica a la que ambos son propensos.",
			Match: "75%"},
		Values: SummaryPercentage{
			Text:  "Ambas partes valorarán sobre todo la profundidad intelectual.\n \nNo hay nada en el mundo tan excitante como las conversaciones tan intensas y desafiantes para sus mentes.\n \nLa mayoría de las veces estarán de acuerdo en las cosas que más valoran, aunque podrían tropezar con un gran problema cuando lleguen al punto de tirar la basura.\n \nAunque Escorpio no suele acumular cosas y le encanta tirarlas, aquellas a las que se aferra pueden resultar bastante desagradables para un Virgo.\n \nImagínate que nace su primer hijo y Escorpio quiere enmarcar ese residuo reseco de cordón umbilical.\n \n¿Crees que Virgo querría despertarse con esto en su apartamento cada mañana?",
			Match: "70%"},
		SharedActivities: SummaryPercentage{
			Text:  "Por la misma razón por la que sus valores pueden diferir, su rutina diaria también puede ser diferente.\n \nVirgo limpiará, eso es un hecho, simplemente porque una casa limpia crea una mente clara, y Escorpio no tendrá muchos problemas para encajar, a menos que se cuestionen sus pertenencias personales.\n \nSin embargo, cuando elijan los lugares que quieren visitar, o los clubes a los que quieren ir, sus elecciones diferirán mucho.\n \nNo les resultará difícil comprometerse para mantener la relación, pero puede ser bastante oscuro y exigente para ambos miembros de la pareja.\n \nSi no empiezan a salir de buena gana en algunos cementerios ordenados, puede que se queden sin opciones que realmente mantengan el interés y la felicidad de ambos.",
			Match: "55%"},
	},
}
