package compatibilities

var Virgosagittarius = Compatibility{
	Name: Virgo + " - " + Sagittarius,
	Friendship: Friendship{
		Match:   "55%",
		Traits:  []string{CautionRomance},
		Summary: "En este terreno la relación entre Virgo y Sagitario funciona mejor que en el del amor, aunque también tendrán que salvar notables diferencias.\n \nDe entrada, Virgo se sentirá atraído por el espíritu valiente y atrevido de Sagitario y disfrutará mucho de su compañía, especialmente si viajan juntos.\n \nEl nativo o nativa del signo del arquero, por su parte, disfrutará de la seguridad y estabilidad que siempre desprende Virgo y que le vendrá muy bien para arriesgarse a más aventuras, consciente de que tiene al lado a alguien que le previene del peligro.\n \nTambién el gran sentido del humor que comparten Virgo y Sagitario les proporcionará muchos momentos de diversión.\n \nLo más favorable es que a medida que se vayan conociendo, la confianza mutua irá aumentando y podrán encontrar otras conexiones en sus distintos estilos de vida.\n \nPara que la amistad entre Virgo y Sagitario funciones, el primero tendrá que abstenerse de criticarlo todo y pensar en el fin más que en los medios.\n \nSagitario por su parte, tendrá que contenerse un poco precisamente en el modo de alcanzar el fin.\n \nEl arquero ofrece a su amigo diversión, improvisación, amigos y aventura, mientras que Virgo le aporta protección y organización, que no es poco.",
	},
	Love: Love{
		Match:  "32%",
		Traits: []string{GreatSexualChemistry, Volatile, LowCommitment},
		Summary: SummaryPercentage{
			Text:  "La relación entre un Virgo y un Sagitario no es la típica historia emocional con final feliz.\n \nHay muchos desafíos en su camino, el mayor de los cuales es su falta de comprensión emocional y su posible falta de respeto.\n \nSin embargo, cuando encuentran la manera de mostrar sus emociones y compartirlas al mismo ritmo y de forma comprensible, pueden llegar a divertirse mucho juntos.\n \nSu comunicación suele ser emocionante y ambos tienen mucho que decirse, pero su racionalidad puede distraerles de la búsqueda real del amor.\n \nSi descubren lo bien que se complementan, podrían permanecer juntos durante mucho tiempo.",
			Match: "32%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Como todas las combinaciones de signos mutables, estas parejas pueden divertirse mucho.\n \nAunque Virgo puede ser bastante exigente y crítico, especialmente desde el punto de vista de Sagitario, su vida sexual puede ser satisfactoria para ambos.\n \nLo bueno de su conexión radica en que estos signos están regidos por planetas que también rigen sus signos opuestos.\n \nEsto significa que, en primer lugar, sentirán atracción y necesidad de iniciar una relación sexual.\n \nEl principal problema radica en la diferencia de sus elementos.\n \nVirgo es un signo de Tierra y, como tal, no suele correr demasiados riesgos.\n \nSagitario es un signo de Fuego, y forzará las cosas apasionadamente hasta alcanzar su objetivo.\n \nEsto no funciona bien en sus contactos sexuales, ya que Virgo podría sentirse empujado a hacer cosas que no quiere, y Sagitario podría sentirse apagado por la naturaleza práctica y estática de Virgo.\n \nLo más importante que deben recordar estas parejas es que ambos necesitan espacio para ser quienes son.\n \nCon dos personas tan dadoras, la vida sexual se reduce a quién satisfará mejor a quién, en cuanto se enfrenten a expectativas poco realistas.",
			Match: "30%"},
		Trust: SummaryPercentage{
			Text:  "Si escarbas en busca del mayor problema en la relación de pareja entre un Virgo y un Sagitario, te darás cuenta de que es su falta de confianza, no sólo el uno en el otro, sino en toda su relación.\n \nComo amigos, pueden ser inquebrantables en sus convicciones y aferrarse juntos a algunos valores tradicionales, pero en cuanto inician una relación romántica, ambos parecen empezar a sentirse atrapados.\n \nVirgo no parece un signo del zodíaco que se sienta atrapado con facilidad, pero su cualidad mutable les hace impacientes y siempre en busca del cambio.\n \nNo pueden mantenerse en un mismo lugar durante mucho tiempo, como tampoco puede hacerlo un Sagitario.\n \nLa principal diferencia es el grado de sacrificio que están dispuestos a hacer.\n \nA partir de estas emociones, ambos miembros de la pareja comenzarán a sentir la necesidad de estar con alguien diferente, y ésta es una relación con probablemente el mayor potencial para el adulterio, a menos que una culpa increíble los detenga primero.\n \nLa comunicación, seguida del respeto mutuo, es la única posibilidad de construir un vínculo de confianza.",
			Match: "1%"},
		Communication: SummaryPercentage{
			Text:  "Hay tanto que decir cuando Virgo y Sagitario se juntan, y aunque estos compañeros puedan despertar mutuamente la necesidad de hablar en exceso, todo el tiempo, ambos se sentirán bastante bien al respecto.\n \nSi llegan a la zona de verdadero entendimiento, se entusiasmarán con el uso de sus mentes y las hermosas conclusiones y filosofía que pueden crear juntos.\n \nVirgo aportará todas las pequeñas piezas a su conexión intelectual, mientras que Sagitario tendrá visión y ayudará a crear un panorama más amplio.\n \nAunque no se complementen ni de lejos con sus signos opuestos, la emoción intelectual será igual de importante para ellos desde el principio.\n \nEl hecho más relevante que deben recordar estas parejas es que su respeto es lo más importante a lo que deben aferrarse.\n \nSi se faltan el respeto mutuamente, Virgo observará a su pareja Sagitario como un bicho raro, tan estúpido como para huir de todo lo que tenga profundidad, mientras que Sagitario mirará a su pareja Virgo como un bicho raro, tan estúpido como para aferrarse a cosas irrelevantes.\n \nNecesitan recordar que cada uno de ellos tiene un papel diferente, y que para cada papel, estas características 'estúpidas' representan la mejor base posible.",
			Match: "65%"},
		Emotions: SummaryPercentage{
			Text:  "No es precisamente una pareja que suela acabar en un 'felices para siempre', aunque ambos deseen encontrar a la persona adecuada para ello más que nada.\n \nEn la mayoría de los casos, su visión de un final de cuento de hadas difiere demasiado como para que puedan tenerlo juntos.\n \nAún así, en algunas raras situaciones, sus naturalezas mutables les permiten moverse al mismo ritmo con el suficiente respeto como para mantenerse en un vínculo emocional que satisfaga a ambos.\n \nEstos dos miembros de la pareja se consideran poco emocionales, pero esto se debe sobre todo a su necesidad de racionalizar, analizar y utilizar la mente para explicar todo lo que les ocurre, en lugar de confiar en su corazón o en sus instintos.\n \nEsto a menudo será un problema, ya que Virgo necesita a alguien verdaderamente emocional para poder mostrar sus propios sentimientos profundos.\n \nSagitario parece no interesarse por las necesidades de Virgo o simplemente no ser consciente de ellas porque actúa como si fuera puramente racional.\n \nEl truco aquí es que ambos miembros de la pareja vean detrás de la actuación para encontrar el corazón del otro y comprender lo que pueden esperar el uno del otro.",
			Match: "10%"},
		Values: SummaryPercentage{
			Text:  "Virgo y Sagitario tendrán extrañamente valores similares basados en su cualidad mutable.\n \nPor eso, ambos valorarán a alguien capaz de adaptarse, cambiar y moverse, algo que sin duda encontrarán el uno en el otro al iniciar su relación.\n \nComo signos altamente mentales, también valorarán la claridad mental y la inteligencia en general.\n \nSin embargo, su enfoque del valor intelectual es diferente, y mientras Virgo valora la profundidad y el análisis detallado, Sagitario valorará la amplitud de su mente.\n \nAunque difieren en otras cosas que valoran mucho, ya que Virgo valora el sentido práctico y Sagitario la visión y el enfoque, aquí hay suficientes puntos en común para que ambos se sientan bien cuando están juntos.",
			Match: "50%"},
		SharedActivities: SummaryPercentage{
			Text:  "Virgo y Sagitario tendrán extrañamente valores similares basados en su cualidad mutable.\n \nPor eso, ambos valorarán a alguien capaz de adaptarse, cambiar y moverse, algo que sin duda encontrarán el uno en el otro al iniciar su relación.\n \nComo signos altamente mentales, también valorarán la claridad mental y la inteligencia en general.\n \nSin embargo, su enfoque del valor intelectual es diferente, y mientras Virgo valora la profundidad y el análisis detallado, Sagitario valorará la amplitud de su mente.\n \nAunque difieren en otras cosas que valoran mucho, ya que Virgo valora el sentido práctico y Sagitario la visión y el enfoque, aquí hay suficientes puntos en común para que ambos se sientan bien cuando están juntos.",
			Match: "35%"},
	},
}
