package compatibilities

var Virgolibra = Compatibility{
	Name: Virgo + " - " + Libra,
	Friendship: Friendship{
		Match:   "75%",
		Traits:  []string{CautionRomance, MutualRespect},
		Summary: "En este terreno Virgo y Libra tienen muchos más puntos de coincidencia, por ello lograrán mantener una amistad intuitiva y empática a poco que se lo propongan.\n \nTanto Virgo como Libra son dos signos que se caracterizan por su nobleza y ambos se aceptarán tal cual son, con virtudes y defectos.\n \nEsta amistad, no obstante, se desarrollará lentamente, porque Virgo y Libra son dos signos muy cautelosos y necesitarán asegurarse de que su elección es la correcta, su vínculo pues se afianzará con el tiempo.\n \nVirgo y Libra están destinados a ser amigos y cómplices.\n \nDesearán siempre atender a los deseos del otro y lo harán con éxito.\n \nA menudo será Libra quien tomará la iniciativa en cuanto a las actividades compartidas, pero eso no importará a Virgo, las aceptará de buen grado y se divertirá mucho con ellas.\n \nÉsta es una cualidad de Libra, que sabe dirigir el cotarro sin resultar fastidioso.\n \nTiene muchas estrategias para conseguirlo.\n \nEn la amistad asumirá de alguna manera el papel de líder sin perder la esencia de amigo.\n \nTanto Libra como Virgo intentarán comprender los puntos de vista del otro aunque difiera de los suyos.\n \nAlgunas veces, la amistad entre Virgo y Libra evoluciona hacia una relación sentimental.",
	},
	Love: Love{
		Match:  "30%",
		Traits: []string{DeepMutualUnderstanding},
		Summary: SummaryPercentage{
			Text:  "Virgo y Libra pueden formar un vínculo intelectual muy satisfactorio, siempre que respeten los sentimientos del otro.\n \nEn general, esta relación puede funcionar a veces, y estas parejas pueden sincronizar su ritmo, elegir actividades apropiadas y construir una vida sexual satisfactoria con suficiente paciencia y cuidado.\n \nSin embargo, podrían tener un profundo problema de comprensión emocional, y lo que más les costará conciliar es su frágil ego.\n \nVirgo, deseoso de complacer, asumirá fácilmente las responsabilidades y decisiones que Libra necesita tomar.\n \nEsto provocará un sentimiento de inferioridad en Libra y la pérdida de respeto hacia su pareja Virgo.\n \nSi este problema no se resuelve, su relación podría terminar debido a una falta de respeto que ambos desconocían al principio.",
			Match: "30%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "La relación sexual entre un Virgo y un Libra no parece una buena elección.\n \nProbablemente se volverán locos el uno al otro, uno de ellos tratando obsesivamente de mantener las cosas limpias y pareciendo como si tuviera miedo de cualquier contacto emocional, y el otro estricto en su búsqueda de amor espiritual y de un compañero con el que realmente pueda hablar.\n \nLa mayoría de las veces, ni siquiera se sienten atraídos el uno por el otro, y cuando inician una relación sexual tienen que enfrentarse al reto de la velocidad.\n \nVirgo querrá moverse despacio, y aunque su cualidad mutable les hace bastante adaptables, a menudo no es suficiente para alcanzar la velocidad del Aire de Libra.\n \nSin embargo, pueden encontrar un punto medio cuando Libra se apoya en su exaltación de Saturno y va más despacio, mientras que Virgo se adapta y cambia más rápidamente.\n \nSi encuentran el momento perfecto, ambos miembros de la pareja podrían acabar insatisfechos.\n \nVirgo esperaba una conexión de cuento de hadas al ver la imagen que muestra Libra y encontrará muchos fallos en el enfoque de su pareja.\n \nLa autoestima de Libra no tolera tantas críticas y es probable que vea a Virgo aburrido, rígido e inconsciente de cualquier conexión emocional que quisiera establecer.",
			Match: "1%"},
		Trust: SummaryPercentage{
			Text:  "Menos mal que Libra exalta a Saturno y su necesidad de ser justo es, en muchos casos, más que evidente.\n \nSi no fuera así, Virgo desestimaría cada palabra que dicen para empezar.\n \nHay mucha tensión entre ellos, pues no comprenden la naturaleza primaria del otro.\n \nNo se trata tanto de una cuestión de confianza, pero se reduce a eso cuando el polvo se asienta.\n \nNo hay forma de explicarle a Virgo, tímido e introvertido, por qué Libra tiene que tenerlo todo al descubierto.\n \nY menos aún por qué hay que prestar tanta atención a su relación, o por qué su pareja Libra flirtea con todo el que parece decente.\n \nPor otra parte, Libra no se fía mucho del mal humor de Virgo y piensa en el miedo de su pareja a expresarse como si hubiera algo que quisiera ocultar.",
			Match: "25%"},
		Communication: SummaryPercentage{
			Text:  "Se entenderán perfectamente mientras hablen de asumir responsabilidades y de asuntos serios en la vida, como las elecciones profesionales y sus ingresos.\n \nEsto puede mantenerlos en un buen lugar durante bastante tiempo, especialmente si comparten los mismos intereses profesionales o tienen el objetivo de apoyarse mutuamente en el aprendizaje o en avances de cualquier tipo.\n \nIncluso si tocan el tema del contacto emocional, seguirán coincidiendo durante un tiempo.\n \nAmbos valoran las decisiones racionales y los movimientos inteligentes.\n \nPero entonces, las verdaderas emociones saldrán a la superficie en uno de estos miembros de la pareja, y puede que se den cuenta de que la comunicación entre ellos ya no es posible.\n \nEn cuanto uno de ellos tiene que enfrentarse a un asunto personal, el otro parece congelarse, perdiendo toda capacidad de compasión o cercanía.\n \nEl problema radica en que su relación se basa en su conexión mental, lo que interfiere a la hora de quererse de verdad y de dedicarse una palabra amable en un momento importante.",
			Match: "60%"},
		Emotions: SummaryPercentage{
			Text:  "Su contacto emocional se apoya en el punto de su comunicación ya que se encuentran en una extraña convivencia.\n \nNo hay pareja más propensa a separarse emocionalmente que estos dos, y esto puede llevar a tanta insatisfacción en ambos, sin que los dos miembros de la pareja puedan terminar la relación en la que no se sienten bien.\n \nVirgo es un signo donde cae Venus y éste es el regente de Libra y un planeta que, hombro con hombro con la Luna, representa nuestras emociones.\n \nEl valor y la estabilidad de las emociones que necesita encontrar Libra, parece perder todo su sentido cuando aparece el racional Virgo.\n \nLibra encajará instantáneamente en las expectativas de su pareja, esforzándose por ser esa voz de la razón, más racional de lo que realmente es.\n \nA medida que pasa el tiempo, las emociones que han alejado se acumularán, volviendo en una ola repentina que no se puede detener.\n \nNo hay forma de controlar la naturaleza emocional de Libra, y esto es algo que ambos aprenderán en esta relación.",
			Match: "1%"},
		Values: SummaryPercentage{
			Text:  "Se trata de una pareja que valorará todas las mismas cosas hasta que descubra que, sencillamente, no es así.\n \nEs un extraño engaño lo que se interpone entre ellos, como si ambos fueran capaces de practicar algo totalmente fuera de su alcance.\n \nLa culpa que inconscientemente sentirán por despreciar las emociones del otro (y las suyas propias) acabará con la satisfacción entre ellos y los dejará en un estado de asombro:\n \n¿cómo es posible que dos personas que valoran tantas cosas similares, valoren algo totalmente distinto al final de la relación?",
			Match: "30%"},
		SharedActivities: SummaryPercentage{
			Text:  "Virgo es un signo mutable y se adaptará a cualquier deseo de su pareja con facilidad.\n \nLibra tiene el tacto y la consideración suficientes para que Virgo no se sienta mal por sus decisiones.\n \nRara vez hay algo extremo en su contacto y disfrutarán de las actividades habituales de la relación.\n \nIncluso su ritmo puede sincronizarse bastante bien, ya que Virgo es mucho más rápido que el resto de los signos de Tierra, mientras que la indecisión de Libra los hace bastante lentos.\n \nDeben prestar especial atención cuando Virgo les ayuda en la toma de decisiones, tomando aún más del ya magullado ego de Libra.\n \nEsto puede acarrear serios problemas, no sólo a la hora de decidir sobre futuras actividades, sino en su respeto mutuo.",
			Match: "65%"},
	},
}
