package compatibilities

var Virgovirgo = Compatibility{
	Name: Virgo + " - " + Virgo,
	Friendship: Friendship{
		Match:   "70%",
		Traits:  []string{DeepMutualUnderstanding},
		Summary: "La unión de Virgo y Virgo en la amistad hará que ambos se sientan como en familia.\n \nDos Virgo se reconocerán de inmediato y sabrán intuitivamente que la otra persona es alguien ideal para compartir sus momentos de diversión y de aventura, aunque también percibirán que el otro Virgo será de confianza absoluta, algo muy valioso porque Virgo tiende a desconfiar de todo el mundo.\n \nEn la amistad entre Virgo y Virgo se unirán dos mentes prácticas con un gran corazón.\n \nVirgo y Virgo, pertenecientes al elemento Tierra, conformarán un dúo adaptable, inteligente y bien organizado en el que poquísimas cosas podrán enturbiar su amistad.\n \nTímido y algo introvertido, Virgo suele elegir muy bien a sus amistades, entre otras cosas porque cuando entrega su confianza, se vuelca en sus amigos.\n \nVirgo y Virgo también compartirán un sentido del humor muy agudo, aunque quizá demasiado sutil para ser captado por otros signos.\n \nLa amistad entre Virgo y Virgo estará presidida por la armonía y seguirá avanzando en el tiempo, sin prisa pero sin pausa.\n \nNo se convertirán en amigos íntimos de la noche a la mañana, porque Virgo es muy prudente, pero ambos sabrán que con el tiempo serán como hermanos, que les unirá su complicidad mutua y un profundo afecto.",
	},
	Love: Love{
		Match:  "65%",
		Traits: []string{NothingReally},
		Summary: SummaryPercentage{
			Text:  "Cuando Virgo decide estar con otro Virgo, podemos suponer que su relación es producto de una de dos cosas posibles, la primera es la necesidad de estabilidad y su decisión racional de estar el uno con el otro, y la segunda es la inexplicable fuerza del amor a primera vista.\n \nSea como fuere, ambos miembros de la pareja son bastante racionales y pertenecen al signo de cualidad mutable, por lo que sus emociones pueden cambiar muy rápidamente.\n \nDebido a su tendencia compartida al sacrificio, la falta de fe que tienen en sí mismos y la tendencia a racionalizar todo con valor, podrían acabar fácilmente en una relación en la que ninguno de los miembros de la pareja esté realmente enamorado, o satisfecho.\n \nEs imperativo que actúen de acuerdo con su corazón si quieren que su amor perdure.",
			Match: "65%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Sería gracioso decir que dos Virgo no se entienden cuando se trata de sexo, pero la verdadera atracción y la emoción detrás del acto, parecen faltar.Es bueno que puedan comunicarse y hacer que su vida sexual sea mucho mejor a través del arte de la palabra, pero a menos que estén locamente enamorados para empezar, ambos podrían simplemente pensar que sus relaciones sexuales son inadecuadas. El principal problema con el signo de Virgo es su búsqueda de defectos, y esto puede ser una verdadera ruptura cuando se trata de sexo.Cuando dos miembros de Virgo inician una relación sexual, esta necesidad de crítica se multiplica, y lo que es peor, parecen motivarse mutuamente para hacerla crecer y fortalecerla aún más. Ninguno de estos miembros de la pareja se da cuenta de que esto les quita satisfacción emocional o sexual, y les hace sentirse tensos. En la mayoría de los casos sólo se dan cuenta de que no se sienten relajados el uno con el otro, a menudo sin saber siquiera por qué. Lo bueno en una relación sexual de dos Virgo es su respeto por el pudor del otro y el ritmo al que quieren que avance su relación. Su cualidad mutable les ayudará a hacer los cambios necesarios para que las cosas funcionen, e incluso si su vida sexual no es satisfactoria al principio, podrán adaptarse hasta alcanzar el punto de satisfacción. La creatividad es la clave. Y su entrenamiento para vivir el momento, sin fijarse en cada detalle que no funciona entre ellos.",
			Match: "30%"},
		Trust: SummaryPercentage{
			Text:  "Cuando estas parejas se juntan, se enfrentan cara a cara a sus propios problemas de confianza despertados por el signo de Piscis en su séptima casa.\n \nPuesto que comparten el mismo conjunto de convicciones sobre la confianza que hay que construir, normalmente bastante tradicional, a menudo acaban resolviendo estos problemas juntos.Aun así, ambos deben recordar que en cuanto uno de los dos cuestione al otro, le devolverán el favor, y el círculo de desconfianza puede escalar repentinamente hasta el punto de que ambos empiecen a sentir la necesidad de esconderse.",
			Match: "70%"},
		Communication: SummaryPercentage{
			Text:  "Si hay algo para lo que Virgo es capaz, es para la comunicación.\n \nAl igual que el signo de Géminis, Virgo puede ser bastante elocuente e inteligente, ambos regidos por Mercurio, el maestro de la comunicación.\n \nDado que el signo de Virgo se relaciona con la palabra escrita, mucho más que con la hablada, es probable que estas parejas quieran enviarse mensajes de texto todo el tiempo, siempre y cuando sus charlas no se vuelvan monótonas y aburridas.\n \nAmbos son muy intelectuales, pero también muy rápidos a la hora de descartar los puntos fuertes intelectuales de otra persona si difieren de los suyos.\n \nCuando se trata de evaluar las palabras de alguien, Virgo puede ser extremadamente crítico y centrarse en detalles que la mayoría de los otros signos no verían como importantes en absoluto.\n \nLa belleza de la relación entre dos Virgo reside en su comprensión compartida de la importancia de los detalles.\n \nDesgraciadamente, esto puede ser lo que les distancie del panorama general y les haga preocuparse por cosas que realmente no son importantes.",
			Match: "99%"},
		Emotions: SummaryPercentage{
			Text:  "El amor entre dos Virgo puede ser extrañamente racional.\n \nSuelen ser una pareja que se encuentra en el momento perfecto: cuando ambos están preparados o tienen edad suficiente para formar una familia, o cuando ambos han terminado relaciones que les agotaron durante años.\n \nEl mayor reto para ellos es mantener encendido el amor después de que sus cerebros interfirieran en el proceso que sus corazones deberían haberse guardado para sí mismos.\n \nComo dos representantes de un signo mutable, estas parejas cambian rápidamente y a menudo acaban en una situación en la que el amor a primera vista les une, pero siguen juntos incluso cuando las emociones entre ellos hace tiempo que desaparecieron.\n \nPara que mantengan la llama o rompan, al menos uno de los dos tiene que tener la fe suficiente para creer que tomarán la decisión correcta hagan lo que hagan.\n \nSi ambos empiezan a cuestionarlo todo, probablemente no llegarán a ninguna parte.",
			Match: "25%"},
		Values: SummaryPercentage{
			Text:  "Podríamos decir que sus valores coinciden a la perfección, pero nada con Virgo coincide a la perfección.\n \nSi hay un signo que nos muestre lo diferentes que pueden ser las personas similares, ése es el signo de Virgo.\n \nEstas parejas tienen sus propias opiniones y pensamientos sobre todo.\n \nLes será muy difícil encontrar una pareja, aunque sea otro Virgo, que coincida plenamente con su sistema de valores.\n \nEn la mayoría de las cuestiones generales de la vida, estarán de acuerdo, y ambos valorarán la inteligencia, la capacidad y la atención a los detalles.\n \nAun así, puede que les cueste adaptarse a los valores emocionales o profesionales del otro, sobre todo si sus elecciones profesionales están muy alejadas.",
			Match: "80%"},
		SharedActivities: SummaryPercentage{
			Text:  "Dos Virgo pueden hacer cualquier cosa juntos.\n \nCuando se trata de cosas cotidianas y de la rutina que a ambos les importa, encontrarán emoción y alegría en la mayoría de sus actividades.\n \nSus elecciones les hacen sentirse orgullosos y felices de haber encontrado a alguien que comparte su aprecio por ciertas actividades 'inteligentes', pero el desafío en sus elecciones se esconde en el hecho de que a ninguno de los dos le gusta mucho Venus.\n \nEste hecho podría llevarles a un punto de apatía, en el que ninguno de ellos vive su vida en color, al máximo, amenazando su energía creativa.\n \nNecesitan seguir enamorados, creativos y románticos, o les resultará muy difícil disfrutar de verdad del tiempo que pasan el uno con el otro.",
			Match: "85%"},
	},
}
