package compatibilities

var Virgocapricorn = Compatibility{
	Name: Virgo + " - " + Capricorn,
	Friendship: Friendship{
		Match:   "100%",
		Traits:  []string{DeepMutualUnderstanding, ExcellentAdvisors, GoodRomancePotential},
		Summary: "La amistad entre Virgo y Capricornio será siempre inmediata y duradera, para toda la vida, incluso.\n \nDada su similitud en temas trascendentales, podría decirse que no habrá nunca entre ellos el menor asomo de diferencias importantes.\n \nSe comprenderán a la perfección, incluso en los momentos difíciles en que uno de ellos atraviese una crisis de mal humor.\n \nPodrán expresarse libremente sin el temor de que el otro interprete mal sus palabras o responda de forma airada a sus planteamientos.\n \nLa relación entre Virgo y Capricornio será siempre interesante y satisfactoria.\n \nCapricornio siente una profunda admiración por la lógica y el perfeccionismo de Virgo y éste admira la tenacidad y fortaleza de su amigo.\n \nTanto Virgo como Capricornio tienen un alto concepto del compromiso y ésta será la base de su sólida amistad.\n \nNo temerán que el otro les falle porque desde el principio ambos demostrarán su lealtad a toda prueba.\n \nNi Virgo ni Capricornio se dejan llevar por los impulsos ni las emociones y por ello su amistad será estable y un tanto conservadora.\n \nVirgo y Capricornio aman el confort y la comodidad, por eso a la hora de elegir actividades, siempre coincidirán en sus criterios.\n \nEl éxito en la amistad entre estos dos signos está asegurado.",
	},
	Love: Love{
		Match:  "77%",
		Traits: []string{GoodWorkCombination, GreatSexualChemistry, Harmonious},
		Summary: SummaryPercentage{
			Text:  "Virgo y Capricornio pertenecen al elemento Tierra y siguen perfectamente el ritmo del otro.\n \nAunque todo entre ellos parezca demasiado lento para algunos otros signos del zodíaco, construyen el respeto, la confianza y el amor, sobre la base del análisis mutuo y el examen detallado.\n \nLa búsqueda de la perfección puede terminar en esta relación, ya que se dan el tiempo suficiente y se escuchan lo suficiente como para satisfacer las expectativas que deben cumplirse.\n \nEstos dos miembros de la pareja pueden ser rígidos y perder de vista la importancia del enfoque emocional y meloso de la vida, y esta relación puede volverlos bruscos y demasiado estrictos.\n \nAun así, en la mayoría de los casos, se darán tiempo suficiente para madurar y envejecer juntos.",
			Match: "77%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Una conexión sexual entre un Virgo y un Capricornio podría ser estupenda si ambos no fueran tan rígidos y estrictos en lo que al sexo se refiere.\n \nAunque no les falta paciencia ni comprensión el uno para el otro, siempre parece faltar una pizca de emoción pura en su contacto.\n \nMuy a menudo, estas parejas no llegan a mantener relaciones sexuales, porque tendrán más razones para no hacerlo que para ceder.\n \nLa belleza de su vida sexual, cuando consiguen sincronizarse, está en la profundidad de la que ambos son capaces, que enlaza directamente con la profundidad de las emociones que mostrarán a través del acto sexual.\n \nSu principal objetivo es encontrar a alguien que no se tome el sexo a la ligera, alguien que no sea superficial con ellos y los aprecie como deben ser apreciados.\n \nHay cierta timidez en ambos, y esto es algo que hará que se vuelvan locos el uno por el otro, si tan sólo alcanzan el punto tras la distancia racional que normalmente comparten.\n \nVirgo aportará bastantes cambios a su vida sexual, como signo mutable, dispuesto a experimentar con alguien tan fiable y respetuoso.\n \nEsta es una relación perfecta para que ambos miembros de la pareja se relajen y prueben cosas nuevas, si encuentran la forma de abrirse al principio.",
			Match: "65%"},
		Trust: SummaryPercentage{
			Text:  "Capricornio es un signo en el que se puede confiar, y los signos de Tierra son los que mejor lo entienden.\n \nNo hay nada turbio en ellos, nada poco fiable o que se preste rápidamente al engaño.\n \nVirgo no suele tener motivos para ser infiel, excepto cuando sufre de su propia falta de fe y de emociones que no puede controlar.\n \nAunque éste sea el caso, una pareja Capricornio los inspirará a ser lo mejor que puedan y lo más fieles posible.\n \nNecesitarán algún tiempo para acostumbrarse a los hábitos del otro y construir la confianza que ambos desean.\n \nCuando lo consigan, rara vez la romperán por nada ni por nadie.",
			Match: "99%"},
		Communication: SummaryPercentage{
			Text:  "Cuando alguien del reino del Aire o del Fuego observa a estos dos mientras hablan, esta conversación puede parecer extremadamente aburrida.\n \nEl flujo entre los signos de Tierra en su forma más clara es a veces insoportable para otros signos del zodíaco y esto es algo que Virgo y Capricornio disfrutan de verdad.\n \nLa profundidad mental de ambos signos les fascinará al principio, les entusiasmará y hará que su comunicación sea increíblemente interesante e informativa.\n \nA ambos les gusta un buen debate respetuoso, y en el otro pueden encontrar un adversario perfecto.\n \nSon signos que hacen que un ciclo de comunicación se complete, Virgo decidiendo qué es lo siguiente a discutir y Capricornio decidiendo cuándo el tema está resuelto.\n \nSon como un mecanismo perfecto, como engranajes que encajan entre sí para resolver cualquier ecuación que el mundo tenga que dar.\n \nSu pasión reside en estos roles y cuando encuentran un entendimiento en otras áreas de su relación, la intelectual puede ser estimulante hasta el punto de la felicidad absoluta.\n \nEs una pareja que sabe que cualquier problema está ahí para ser resuelto y cualquier cosa rota está ahí para ser arreglada.",
			Match: "90%"},
		Emotions: SummaryPercentage{
			Text:  "Ambos signos se consideran poco emocionales.\n \nVirgo lleva a Venus a su caída y Capricornio es el signo del detrimento de la Luna.\n \nTienen algunos problemas emocionales, pero no los mismos, y esto les ayuda a encontrar un acercamiento entre ellos que ambos comprendan.\n \nSu relación necesita tiempo, sobre todo, y las emociones entre ellos necesitan construirse, al igual que la confianza.\n \nCon la calma, la práctica y la pasión física surgiendo entre ellos, ambos empiezan a construir su confianza.\n \nCon confianza, se sienten mucho más liberados para experimentar en la vida y en el sexo, y esto da verdadera calidad a todas las áreas de su relación.\n \nLo más increíble que comparte esta pareja es su descubrimiento mutuo.\n \nCon el tiempo, irán pelando capa a capa el corazón del otro, y cada vez se sentirán más fascinados por lo que ninguno de los dos había notado antes.\n \nAl igual que una ecuación matemática, representan una caja misteriosa el uno para el otro, y tienen que abrirla, arco a arco, uno al lado del otro, hasta desentrañar el tesoro que esconde en su interior.",
			Match: "65%"},
		Values: SummaryPercentage{
			Text:  "Tanto Virgo como Capricornio valorarán la calma, el comportamiento y las elecciones racionales, y la capacidad de uno para seguir siendo inteligente por insoportable que sea la situación.\n \nValoran la profundidad y esto es algo que encontrarán increíblemente tranquilizador en el otro, pues ambos sentirán que ya no necesitan fingir ser superficiales.\n \nAmbos valoran la practicidad, el arraigo, el dinero y las inversiones racionales.\n \nLa principal diferencia que tienen que resolver aquí está en el valor de los objetivos de Capricornio, ya que, desde el punto de vista de Virgo, podría estar dispuesto a hacer demasiado para alcanzarlos.\n \nA cambio, Capricornio no comprende la falta de motivación de Virgo y su falta de necesidad de reclamar la posición de liderazgo.",
			Match: "80%"},
		SharedActivities: SummaryPercentage{
			Text:  "Donde Capricornio quiere ir hacia arriba, Virgo quiere ir hacia delante.\n \nAunque ambos son signos de Tierra y esto les permitirá seguirse con la misma energía, no conectan tan bien en la elección de los lugares que quieren visitar.\n \nAmbos querrán ir a un museo de historia y aprender mucha información allí, pero Capricornio a menudo no quiere tratar con médicos, y mucho menos con el recuento de calorías y el té verde.\n \nNo hay otro signo que comprenda mejor que Capricornio la necesidad de sacrificio de Virgo, pero si no se siente responsable de las actividades de su pareja, rara vez la seguirá hasta la depresión.\n \nLo más importante en este caso es aferrarse a actividades positivas y a una rutina que les haga a ambos sanos y felices.",
			Match: "65%"},
	},
}
