package compatibilities

var Virgoaquarius = Compatibility{
	Name: Virgo + " - " + Aquarius,
	Friendship: Friendship{
		Match:   "36%",
		Traits:  []string{Stormy},
		Summary: "Cuando Virgo y Acuario inician una amistad, no pueden llegar a imaginarse todo su potencial.\n \nEs en este terreno donde estos signos opuestos encontrarán mayor complementariedad y sacarán el mejor partido de estar el uno al lado del otro.\n \nDe entrada Virgo se siente atraído por la capacidad social y la vertiente humanitaria de Acuario, aunque siente cierto desánimo por su inclinación para improvisarlo todo.\n \nNo obstante, la nobleza de Acuario será determinante para que Virgo quiera ser su amigo.\n \nLa mayor ventaja de ambos es que se adaptan con facilidad a las todas las situaciones y esto les facilita mucho la vida.\n \nVirgo y Acuario encontrarán apoyo constante el uno en el otro y sobre él forjarán su amistad.\n \nEn el momento en que descubran lo muy provechosa que resulta para ambos esta relación ya no se separarán.\n \nEl imaginativo Acuario y los deseos de Virgo de hacer realidad los proyectos en los que cree, creará entre ellos una potente conexión que se mantendrá con el paso del tiempo.\n \nVirgo será quien guíe a Acuario para que éste saque provecho de su gran potencial, mientras que Acuario le hará recordar a Virgo que puede hacer muchas más cosas que vivir de modo tan estricto, como por ejemplo reservar tiempo para la diversión.",
	},
	Love: Love{
		Match:  "30%",
		Traits: []string{NothingInCommon},
		Summary: SummaryPercentage{
			Text:  "Virgo puede representar todo aquello de lo que huye Acuario: práctico, preocupado por la salud y las cosas terrenales, con los pies en la tierra, maniático obsesionado con la limpieza.\n \nImagina lo increíblemente irresponsable, caótico y poco realista que les parece Acuario.\n \nSu punto de encuentro más fuerte está en la racionalidad y la comunicación, y esto puede servir para superar muchos de los problemas a los que dan lugar sus diferencias.\n \nDesgraciadamente, en la mayoría de los casos no tendrán la química suficiente para iniciar una relación, y mucho menos para mantener una sexualmente satisfactoria durante mucho tiempo.\n \nSi se toman en serio, podrían crear cosas increíbles juntos, al fusionarse sus grandes mentes.",
			Match: "30%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Virgo y Acuario raramente se sentirán atraídos el uno por el otro lo suficiente como para iniciar una relación sexual.\n \nSus naturalezas tienen muchas dificultades para apoyarse mutuamente, ambos son intelectuales pero de maneras completamente diferentes, y probablemente arruinarán cualquier posibilidad de una buena relación sexual dándole demasiadas vueltas a todo, cada uno en su propia dirección.\n \nAcuario realmente se aferra a su espontaneidad, y son racionales cuando se trata de sexo.\n \nLa verdad es que ellos eligen cuándo ser espontáneos y su fuerza intelectual a menudo les da la imagen de espontaneidad porque han visto el resultado más rápido que otras personas 'no tan espontáneas'.\n \nEsto podría arruinar su vida sexual, porque Virgo es una de esas personas y normalmente pensará mucho antes de iniciar una relación sexual.\n \nPensar demasiado es una verdadera desventaja para Acuario, aunque ellos también lo hacen, sólo que a un ritmo más rápido.\n \nLos Virgo tímidos, reflexivos y sensibles tendrán problemas para entender a su pareja Acuario, desnuda, rara y a menudo demasiado rápida.\n \nEs casi seguro que ninguno de ellos tendrá la paciencia suficiente para construir su vida sexual con alguien tan diferente de lo que necesitan.",
			Match: "1%"},
		Trust: SummaryPercentage{
			Text:  "Sus naturalezas racionales suelen unirlos en una relación de confianza, porque a ambos les parece estúpido mentir o no confiar en su pareja.\n \nAunque Virgo puede ser duro con la confianza, con Acuario es obvio incluso para Virgo que la falta de confianza no llevaría a ninguna parte.\n \nAun así, hay muchas posibilidades de que se distancien, incluso cuando su primer contacto sea apasionado y fuerte, porque podrían empezar a sentir que ambos necesitan a alguien diferente.\n \nSi quieren mantener la confianza mutua, deben mantener fresca su relación y aceptarse tal y como son.",
			Match: "50%"},
		Communication: SummaryPercentage{
			Text:  "Virgo está regido por Mercurio y tiene una cualidad mutable, que le confiere esa naturaleza cambiante, móvil y adaptable.\n \nAcuario no tiene problemas para tratar con Mercurio, en la mayoría de las situaciones, y sin duda le gustará esta cualidad adaptable de Virgo.\n \nAcuario suele ser rígido en sus costumbres y esto puede ser difícil de manejar para alguien tan dispuesto a sacrificar su felicidad como Virgo.\n \nCompartirán interés por muchas cosas y suelen entusiasmarse por detalles similares.\n \nSin embargo, pertenecen a los elementos más diferentes de todos: a Tierra y Aire.\n \nComo signo de Tierra, Virgo puede ser muy lento, demasiado minucioso y raramente lo bastante inspirado como para que Acuario sienta siquiera la necesidad de compartir sus ideas con ellos.\n \nPor otro lado, Acuario puede parecer poco realista o incluso loco a su pareja Virgo.\n \nCon la atención al detalle de Virgo, cualquier plan para que la mente brillante de Acuario cobre vida es posible.\n \nSu comunicación puede ser delicada y la falta de compasión que padece Acuario a veces perjudicará a Virgo, pero aún así tienen una gran oportunidad de combinar sus mentes y formar una inteligencia universal capaz de crear cualquier cosa.",
			Match: "40%"},
		Emotions: SummaryPercentage{
			Text:  "La montaña rusa emocional que Acuario ofrece con gusto es algo que Virgo probablemente despreciará.\n \nVirgo es el signo de la salud y de la rutina diaria, y sus representantes a menudo pueden obsesionarse con cada comida o con cada revisión que han tenido con su médico.\n \nEn la mayoría de los casos, Acuario evitará a toda costa a los médicos y el hecho de que exalten a Neptuno hará que se inclinen mayoritariamente por todo tipo de medicina alternativa, en lugar de por cualquier cosa típica a la que Virgo pudiera aferrarse.\n \nTodo el mundo emocional de su relación podría reducirse a que Virgo se preocupe por su irresponsable pareja Acuario, y por la falta de gratitud que podría recibir a cambio.\n \nDe hecho, Acuario no suele necesitar que le cuiden de esta manera.\n \nEsta es una relación emocional complicada porque la preocupación de Virgo degrada la personalidad de Acuario y la mejor de las intenciones podría tener consecuencias perjudiciales.\n \nEl mayor problema en la relación de Virgo y Acuario radica en el hecho de que ambos dependen en gran medida de su mente racional.\n \nEsto no deja espacio para la alegría de la seducción, el amor y la satisfacción, y por lo general ambos necesitan un socio con más calor, la vida o la emoción a ellos para que ambos puedan ser más felices.",
			Match: "35%"},
		Values: SummaryPercentage{
			Text:  "Virgo y Acuario valorarán sobre todo la inteligencia y una mente clara.\n \nEsto no significa que encuentren inteligentes a las mismas personas, acciones o pensamientos, y a menudo podrían tener opiniones opuestas sobre alguien de su entorno.\n \nAún así, podrían motivarse mutuamente para desarrollar sus fortalezas intelectuales y aferrarse a este activo si otras cosas en su relación no son tan buenas.\n \nOtras cosas que valoran no son realmente similares y mientras Virgo siempre elegiría la practicidad, Acuario elegiría lo desconocido y una realidad no tan comprensible.",
			Match: "30%"},
		SharedActivities: SummaryPercentage{
			Text:  "El trabajo de cualquier artista con una gran mente podría conectarlos y fácilmente podrían interesarse por espectáculos, galerías y obras similares.\n \nSus gustos en muchas cosas pueden ser casi los mismos, porque la misma atención al detalle que tanto aprecia Virgo, hace que algunas personas sean geniales en su arte y esto es lo que fascina a Acuario.\n \nSin embargo, Virgo es demasiado cauto y predecible y la mayoría de las veces tendrá problemas para encajar en ese mundo tan excitante e impredecible de Acuario.",
			Match: "25%"},
	},
}
