package compatibilities

var Virgopisces = Compatibility{
	Name: Virgo + " - " + Pisces,
	Friendship: Friendship{
		Match:   "85%",
		Traits:  []string{GoodRomancePotential, ExcellentAdvisors},
		Summary: "Virgo y Piscis son la representación exacta de lo que todo el mundo espera de una buena amistad.\n \nSin duda habrá algunos pros y contras, pero será sólida y equilibrada.\n \nYa desde el principio Virgo y Piscis sentirán atracción mutua como amigos y la intuición de Piscis lo confirmará.\n \nTienen un montón de cualidades comunes, como la lealtad, la sinceridad y su sentido humanitario.\n \nEn cuanto a sus diferencias, saben acomodarse perfectamente y evitar cualquier situación que les incomode o que pueda alterar el buen rollo entre ellos.\n \nVirgo y Piscis se prestarán siempre apoyo y rara vez discutirán, pues los dos poseen un alto nivel de tolerancia y comprensión.\n \nVirgo impulsará a Piscis para que haga realidad sus excelentes ideas, mientras que Piscis sabrá comprender como nadie a Virgo, que necesita siempre ser escuchado.\n \nSon complementarios en algunos rasgos importantes, por ejemplo, Virgo valora la estabilidad económica y las comodidades, mientras que Piscis es un signo muy espiritual, que destaca por su sencillez y se conforma con sentirse bien consigo mismo.\n \nAmbos aprenderán del otro estos valores tan trascendentales.",
	},
	Love: Love{
		Match:  "86%",
		Traits: []string{GreatSexualChemistry, NaturalPartners},
		Summary: SummaryPercentage{
			Text:  "Virgo y Piscis representan el eje de la exaltación y caída tanto de Venus como de Mercurio.\n \nEsto los convierte en los compañeros con mayores retos y el mayor potencial para el amor de todo el zodíaco.\n \nNecesitan encontrar un fino equilibrio de racionalidad y emociones, cada uno individualmente y juntos a través de su relación.\n \nEn muchos casos no se trata de una pareja que vaya a durar mucho tiempo, ya que su cualidad mutable les hace lo suficientemente cambiantes como para desentenderse rápidamente de toda la relación si no están satisfechos.\n \nTienen que darse cuenta de que la perfección que buscan puede no presentarse en la forma que esperan.\n \nSi permanecen juntos el tiempo suficiente para comprender los beneficios de su contacto, podrían descubrir que el amor entre ellos es el único amor verdadero que podrían encontrar en esta vida.",
			Match: "86%"},
		SexualIntimacy: SummaryPercentage{
			Text:  "Virgo y Piscis son signos opuestos y su atracción es muy fuerte.\n \nComo también representan el eje de caída y exaltación de Venus, podemos concluir que su relación siempre tiene una lección sobre Venus que enseñar.\n \nEstas parejas tienen la tarea de encontrar el lugar de intimidad física en el que ambos se sientan relajados para ser exactamente quienes son.\n \nPor lo general, la pareja de Virgo será tímida y tratará de mostrar su sexualidad a través de un comportamiento racional, y Piscis verá a través de esto.\n \nPor otra parte, Piscis temerá la conexión física cercana con otra persona, y esto será prácticamente descartado por Virgo.\n \nA medida que ambos aprendan que no pueden ocultar quiénes son, no tendrán más remedio que liberarse de todo temor y vergüenza, entregándose a la maravillosa experiencia sexual que Venus tiene para ofrecer.\n \nEsta es una pareja que nunca tendrá sexo instintivo, por muy apasionados que se pongan.\n \nLa mente analítica de Virgo no les permitiría actuar 'como animales', y esto es algo que Piscis encontrará tan humano y atractivo.\n \nVirgo se sentirá atraído sobre todo por la pureza del sexo con Piscis, que lo aborda realmente como un acto de amor, libre de prejuicios y siguiendo su sentimiento interior, dondequiera que le lleve.",
			Match: "99%"},
		Trust: SummaryPercentage{
			Text:  "Virgo puede tener serios problemas de confianza que Piscis no le ayudará a superar.\n \nPara tener una relación sana en la que ambos confíen el uno en el otro, los dos tendrán que sentirse lo bastante seguros y confiados como para ser sinceros.\n \nAmbos cederán fácilmente a la deshonestidad, aunque sus convicciones sean opuestas a su comportamiento.\n \nPuede ser una tortura para ambos si alguno de los miembros de la pareja dice una mentira.\n \nAfortunadamente, ambos son conscientes de que un poco de secretismo podría incluso encender su relación y darle más pasión.\n \nPor eso suelen superar pequeños brotes de intimidad para confiar el uno en el otro a un nivel superior.",
			Match: "65%"},
		Communication: SummaryPercentage{
			Text:  "Cuando comiencen su relación, se darán cuenta de lo parecidos que son en realidad, aunque parezcan tan diferentes.\n \nLa cualidad mutable de sus signos les permitirá saltar de un tema a otro, manteniéndose ambos interesados en el flujo y el resultado de sus conversaciones.\n \nLa mejor persona para sacar a Virgo de su análisis obsesivo es Piscis, con su sonrisa y su visión más amplia.\n \nVirgo suele librar una batalla interior en la que nada de lo que sabe, piensa o hace es suficientemente bueno o valioso.\n \nLos Piscis son capaces de inspirar y encontrar valor en todo en la vida, y esas inseguridades y problemas emocionales de Virgo pueden parecer algo innecesario que daña la autoestima de todos los que les rodean.\n \nHarán todo lo posible para ayudar a su pareja a alcanzar el punto de seguridad interior en el que comprenda su valía.\n \nA cambio, Virgo ayudará a Piscis a alcanzar la materialización real de sus increíbles talentos.\n \nAsí como Virgo tiene problemas con Venus, Piscis los tiene con el práctico Mercurio y su mente puede enviarles señales contradictorias que les hacen estar perdidos y confusos.\n \nVirgo les ayudará a construir un sentido interno de seguridad intelectual, a cambio de la emocional.",
			Match: "85%"},
		Emotions: SummaryPercentage{
			Text:  "No hay otro signo en el zodíaco que pueda despertar las profundidades emocionales de Virgo mejor que Piscis.\n \nLa comprensión entre ellos podría alcanzar puntos de perfección y esto es algo que ambos probablemente no podrán encontrar con nadie más.\n \nAun así, es importante que no creen demasiadas expectativas en torno a esta idea de perfección, ya que nadie puede cumplir estos requisitos en la vida real.\n \nSi se desvían del camino, perdiendo el contacto con la verdadera personalidad de su pareja, se decepcionarán fácilmente y tendrán la necesidad de poner fin a su relación.\n \nCon dos signos mutables todo se mueve rápido y los cambios son inevitables.\n \nSi quieren mantener una relación estable, deben encontrar un delicado equilibrio entre racionalidad y emoción, realidad y sueños, y amarse como si fueran perfectos tal y como son.",
			Match: "95%"},
		Values: SummaryPercentage{
			Text:  "Comparten un gran amor por la perfección.\n \nTanto como Virgo valorará una mente perfecta, Piscis valorará una emoción perfecta.\n \nEste es su punto de encuentro y puede hacerles divinos, o que se sientan constantemente insatisfechos con la necesidad de cambiarlo todo de su pareja.\n \nAmbos valorarán la flexibilidad, la capacidad de alguien para adaptarse y cambiar, y sin duda valorarán el amor que reciben de su pareja.\n \nAun así, sus diferencias en cuanto a creencias y convicciones pueden ser enormes, y la aceptación entre ambos debe ser incondicional.",
			Match: "75%"},
		SharedActivities: SummaryPercentage{
			Text:  "Virgo puede ser gruñón a la hora de hacer algo de un cuento de hadas de Piscis, pero lo seguirán por curiosidad.\n \nDespués de todo, están regidos por Mercurio y tienen esa necesidad de ver y sentir todo lo que esta Tierra tiene que ofrecer.\n \nUna vez que se adentren en el mágico mundo de Piscis, podrían descubrir la belleza de la vida que desconocían por completo.\n \nCuando estas parejas están juntas, se hacen sentir mutuamente que todo es posible, ya que Piscis comprende las infinitas posibilidades tanto como Virgo hace que las cosas se hagan realidad, comprendiendo la realidad mejor que muchos otros.",
			Match: "99%"},
	},
}
