name: Prompt getter setter

on:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  generativeAI:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Get Ollama
        run: curl -fsSL https://ollama.com/install.sh | sh
      - name: Run Ollama 3
        run: sudo systemctl start ollama
      - name: Create Ollama model
        run: |
              curl http://localhost:11434/api/create -d '{
                "model": "guru", 
                "modelfile": "FROM llama3\nSYSTEM You are a zodiac guru. You provide only what asked without telling the user anything else",
                "from": "llama3"
              }'
      - name: Get prompts
        run: |
              curl -X POST -H "Content-Type: application/json" -d '{
                "model": "guru",
                "prompt": "give me 7 random prompts to ask you later about what signs are best at. make it sign agnostic, and only enumerate them with no numbering. Please only provide the list only and nothing else",
                "stream": false
              }' http://localhost:11434/api/generate | jq '.response' | jq 'gsub("[\\n\\t]"; "$$")' | jq -Rsc 'split("$$")' | jq -c '.[] | sub("\n"; "") | sub("\""; "") | sub("[^[:alpha:][:space:]]"; "")' | jq -s > data/prompts.json
      - name: Get answers
        run: |
              cat data/prompts.json | jq -r '.[]' | while ((i++)); read -r line; do 
                curl -X POST -H "Content-Type: application/json" -d '{
                  "model": "guru",
                  "prompt": "how good are signs at $line? give me results for each of the signs with a little description of why they have that score. only enumerate them with no overhead,i only want the list. the list should have SignName - Score - Description",
                  "stream": false
                }' http://localhost:11434/api/generate | jq '.response' | jq 'gsub("[\\n\\t]"; "$$")' | jq -Rsc 'split("$$")' | jq -c '.[] | gsub("\n"; "") | gsub("\""; "")' | jq -s > "data/$i.json"
              done
              i=0

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Updated info for the week"
          file_pattern: 'data/*.json'